### ISSUE TITLE
MSI?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/edge-developer#1001]
Where is the MSI package for SCCM distribution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28b35b98-93f6-e1a0-1a30-033641ad4601
* Version Independent ID: d2b4dcc3-9dbd-0a21-4a9f-e0134d85ed3a
* Content: [Microsoft Edge (EdgeHTML) Developer Tools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide)
* Content Source: [microsoft-edge/devtools-guide.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @Bartolomeus-649, the MSI can be downloaded from here: https://www.microsoft.com/en-us/edge/business/download.

Thanks.
