### ISSUE TITLE
A new download API document for Microsoft Edge extensions needed

### ISSUE THREAD

**Issue by yi-Xu-0100** [MicrosoftDocs/edge-developer#1007]
We need a new download API document for Microsoft Edge extensions for fitting the option that **"Ask me what to do with each download"**.

As the extension takes over the download permissions, if this option is selected, the corresponding window for selecting the download location cannot be automatically popped up, and only shows the selection options on the download page(the page cannot be automatically popped up either). 

There is no corresponding API document to guide how to take over this new feature. We need more introduction for this rather than only the Chrome extension API documents. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 814d311d-f0c4-12c3-eab2-ec4c73612de3
* Version Independent ID: 621a1702-2d7c-b9fb-8076-50087e4f5a64
* Content: [Supported APIs for Microsoft Edge extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/api-support)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/api-support.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/api-support.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
@yi-Xu-0100  thank you for posting your query. Will you be able to share a test extension with us to demonstrate the issue? We request you to reach out to us at ext_dev_support@microsoft.com and we'll try our best to help resolve this issue.

**Comment by yi-Xu-0100** [comment]
@gebansal I test many download manager extension for it. They all say no docs for the API to fitting the option.

When there is not an extension to manage download, The download will create a footer for the asking in the Edge.

![image](https://user-images.githubusercontent.com/25523606/105970700-9daab900-60c4-11eb-8840-44fa9baa7d4b.png)

But when we install an extension to manage download, the download asking shows on the download page, not the popup page.

![image](https://user-images.githubusercontent.com/25523606/105971725-d008e600-60c5-11eb-9abb-a482a4255814.png)

But there are no docs for the API about it. We need to open the download page to choose an option otherwise the download will suspend.

I find the new show in the dev version, and which performs like an extension and can solve this issue. But I can not find an extension for this.

![image](https://user-images.githubusercontent.com/25523606/105972671-d5b2fb80-60c6-11eb-989a-56eee5d9963a.png)

Or there is the new API already exist by now?

**Comment by gebansal** [comment]
@yi-Xu-0100 thank you for posting your query. Can you reach out to us at ext_dev_support@microsoft.com to understand and resolve this query in a timely manner?

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.
