### ISSUE TITLE
Remote Edge driver on Linux

### ISSUE THREAD

**Issue by AleckG** [MicrosoftDocs/edge-developer#1014]
Trying to run msedgedriver on Ubuntu 18 selenium node using Selenium hub 4.0-alpha7. 
Microsoft Edge browser and msedgedriver are both version 88.0.692.0.
Every time I get the same error:

>  01:37:44.866 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: Unable to create session for <CreateSessionRequest with Capabilities {browserName: MicrosoftEdge, ms:edgeChromium: true, ms:edgeOptions: {args: [--no-sandbox, --ignore-certificate-errors, --disable-dev-shm-usage, --ignore-urlfetcher-cert-re..., --lang=en-US]}}>
selenium-router         | Build info: version: '4.0.0-alpha-7', revision: 'bd15e4e88a'
selenium-router         | System info: host: '083442badd67', ip: '172.20.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.76-linuxkit', java.version: '1.8.0_265'
selenium-router         | Driver info: driver.version: unknown
selenium-router         | Build info: version: '4.0.0-alpha-7', revision: 'bd15e4e88a'
selenium-router         | System info: host: 'bdf79c3125c6', ip: '172.20.0.7', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.76-linuxkit', java.version: '1.8.0_265'
selenium-router         | Driver info: driver.version: unknown
selenium-router         | org.openqa.selenium.SessionNotCreatedException: Unable to create session for <CreateSessionRequest with Capabilities {browserName: MicrosoftEdge, ms:edgeChromium: true, ms:edgeOptions: {args: [--no-sandbox, --ignore-certificate-errors, --disable-dev-shm-usage, --ignore-urlfetcher-cert-re..., --lang=en-US]}}>
selenium-router         | Build info: version: '4.0.0-alpha-7', revision: 'bd15e4e88a'
selenium-router         | System info: host: '083442badd67', ip: '172.20.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.76-linuxkit', java.version: '1.8.0_265'
selenium-router         | Driver info: driver.version: unknown
selenium-router         | Build info: version: '4.0.0-alpha-7', revision: 'bd15e4e88a'
selenium-router         | System info: host: 'bdf79c3125c6', ip: '172.20.0.7', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.76-linuxkit', java.version: '1.8.0_265'
selenium-router         | Driver info: driver.version: unknown
selenium-router         |       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
selenium-router         |       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
selenium-router         |       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
selenium-router         |       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
selenium-router         |       at org.openqa.selenium.grid.web.ErrorCodec.decode(ErrorCodec.java:141)
selenium-router         |       at org.openqa.selenium.grid.web.Values.get(Values.java:47)
selenium-router         |       at org.openqa.selenium.grid.distributor.remote.RemoteDistributor.newSession(RemoteDistributor.java:83)
selenium-router         |       at org.openqa.selenium.grid.distributor.Distributor.lambda$new$0(Distributor.java:143)
selenium-router         |       at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:183)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
selenium-router         |       at org.openqa.selenium.grid.distributor.Distributor.execute(Distributor.java:293)
selenium-router         |       at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
selenium-router         |       at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
selenium-router         |       at org.openqa.selenium.grid.router.Router.execute(Router.java:85)
selenium-router         |       at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router         |       at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
selenium-router         |       at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
selenium-router         |       at org.openqa.selenium.grid.server.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:30)
selenium-router         |       at org.openqa.selenium.grid.server.WrapExceptions.lambda$apply$0(WrapExceptions.java:36)
selenium-router         |       at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-router         |       at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:46)
selenium-router         |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
selenium-router         |       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
selenium-router         |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
selenium-router         |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
selenium-router         |       at java.lang.Thread.run(Thread.java:748)

**Comment by captainbrosset** [comment]
This unfortunately hasn't been updated in a long time. Marking as stale and planning to close this soon unless this becomes active again.
