### ISSUE TITLE
code line number reference change

### ISSUE THREAD

**Issue by wfleming801** [MicrosoftDocs/edge-developer#1015]
code for get-started.js has been updated since the tutorial. Line number mentioned as 33
![image](https://user-images.githubusercontent.com/855435/99570321-fe17ce80-298e-11eb-9c72-3ec6d9e31efd.png)

, is now showing up as 34. Small minor edit... :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f215748-1d1e-6083-315b-0bf9b7c8f765
* Version Independent ID: 1e372759-3041-11cb-cb6c-5b6f427e9a74
* Content: [Get Started with Debugging JavaScript in Microsoft Edge DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/javascript/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jm-trd-ms** [comment]
@wfleming801 
Thank you for contributing.  Your suggestion initiated a change in the to Microsoft Edge DevTools documentation.  
For all future updates, please follow pull #1083.
