### ISSUE TITLE
Not clear if WebView2 is GA or preview

### ISSUE THREAD

**Issue by PeterSmithRedmond** [MicrosoftDocs/edge-developer#1019]
[Enter feedback here]
This page says both "While WebView2 is a **preview**, the .NET APIs are in the prerelease package." which implies that WebView2 is in preview. But further down the page it says "Announcement: Win32 C/C++ WebView2 is now **Generally Available** (GA)."

I've already been asked about this by a developer partner; they want to use WebView2 but only when it's out of preview and ready for full production use.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728447ae-f77e-e699-61c3-ec6ac9dcfe2f
* Version Independent ID: aa8a2809-de77-8b0a-baf2-45a44d649f77
* Content: [Release Notes for Microsoft Edge WebView2 for Win32, WPF, and WinForms - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes)
* Content Source: [microsoft-edge/webview2/releasenotes.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/releasenotes.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
.Net was released today. Here's the blog post with the announcement: https://blogs.windows.com/msedgedev/2020/11/20/announcing-general-availability-of-microsoft-edge-webview2-for-net-and-fixed-version-distribution-mode/
