### ISSUE TITLE
Missing link in "Distribution of apps using WebView2"

### ISSUE THREAD

**Issue by stephtr** [MicrosoftDocs/edge-developer#1023]
At the end of [Deploying the Evergreen WebView2 Runtime](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#deploying-the-evergreen-webview2-runtime) the GitHub link is messed up:
`Sample code is available in the [Samples repo][GitHubMicrosoftedgeWebView2samplesWebview2Deployment].`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribution of Microsoft Edge WebView2 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jm-trd-ms** [comment]
@stephtr
Thank you for contacted us.  Your suggestion resulted in a change to the content.  For future updates, please follow #1025.
