### ISSUE TITLE
"Download WebView2API Sample" link broken

### ISSUE THREAD

**Issue by MojoDK** [MicrosoftDocs/edge-developer#1026]
"Download WebView2API Sample" link on this page is broken (404):
https://docs.microsoft.com/da-dk/microsoft-edge/webview2/howto/webdriver

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: d3317fb4-5819-7961-ab43-3b0e9d744acf
* Version Independent ID: 0c23b8c3-a6b7-ac17-aad4-da5dd54c80e2
* Content: [Automating and Testing WebView2 with Microsoft Edge Driver - Microsoft Edge Development](https://docs.microsoft.com/da-dk/microsoft-edge/webview2/howto/webdriver)
* Content Source: [microsoft-edge/webview2/howto/webdriver.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/howto/webdriver.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jm-trd-ms** [comment]
@MojoDK 
Thank you for taking the time to contact us.
Your feedback resulted in an update to the documentation.
Please follow PR #1000 for future updates.
