### ISSUE TITLE
Project: Wpf .NET5

### ISSUE THREAD

**Issue by terrytham** [MicrosoftDocs/edge-developer#1029]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9dc9d2-795c-9612-3585-408b4621c080
* Version Independent ID: f73fc16d-d842-4507-9fdb-b42856720355
* Content: [Getting started with WebView2 for WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf)
* Content Source: [microsoft-edge/webview2/gettingstarted/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by terrytham** [comment]
Project Wpf .NET5
Visual Studio Community Version 16.9.0 Preview 1.0
WebView2 version 1.0.664.37

source = new Uri("https://www.microsoft.com");

Output: blank view.

**Comment by Reezaali** [comment]
Hi @terrytham, sorry to hear about this issue. Are you still encountering this issue?
