### ISSUE TITLE
Property author and persistent

### ISSUE THREAD

**Issue by deather** [MicrosoftDocs/edge-developer#103]
I want to alert you on some mistake.

The docs is related about "author is not supported on chrome.", but when I read the Chrome documentation, https://developer.chrome.com/extensions/manifest, it is written "optional property".

The second mistake is about the "persistent" property. This property is supported. There is the migration guide here : https://developer.chrome.com/extensions/background_migration.

Thanks for the complete documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e3b58b7-2f4f-603b-eb83-2f54291cc589
* Version Independent ID: 4bc2670d-bb5a-260d-b0d6-7979a3c0bc65
* Content: [Extensions - Supported manifest keys - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-manifest-keys#feedback)
* Content Source: [microsoft-edge/extensions/api-support/supported-manifest-keys.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/api-support/supported-manifest-keys.md)
* Service: **unspecified**
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by libbymc** [comment]
Hi @deather - thanks for reaching out! I've updated the page to remove the "Not supported in Chrome." line from the `author` row.  

For `persistent`, the existing remark does not indicate that it is not supported in Chrome - just that it is a required field in Microsoft Edge. I don't believe there is a mistake there.
