### ISSUE TITLE
"start" is not a linux/macOS command.  

### ISSUE THREAD

**Issue by timbyu** [MicrosoftDocs/edge-developer#1032]
This document is written for Windows and does not include commands for Linux and MacOS.  For example, "start" is a Windows only command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c648fd42-706c-bb78-2f32-ff6ace125551
* Version Independent ID: 68efb0c6-9a4d-e6f6-4639-c0a9faa4fa39
* Content: [Debug Microsoft Edge (Chromium) from Visual Studio Code - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/debugger-for-edge)
* Content Source: [microsoft-edge/visual-studio-code/debugger-for-edge.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/visual-studio-code/debugger-for-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
I think this page is obsolete now. VS Code comes with a built-in way to connect to Edge, without having to install the extension first.
That being said, you are right, we should also address the part that documents how to attach to Edge and mention how to do it on linux and macOS.

**Comment by captainbrosset** [comment]
@connor4312 would you mind double checking my understanding in the above comment please?

**Comment by connor4312** [comment]
Yea, we have this page on the vscode docs now which covers it -- both for Chrome and Edge: https://code.visualstudio.com/docs/nodejs/browser-debugging

**Comment by captainbrosset** [comment]
Thanks, I'll post a PR with some changes to the Edge docs. I don't think it's worth maintaining our own version of the docs, so I'm thinking of mostly just linking to the vscode docs.

**Comment by codepo8** [comment]
Yes, we should remove this document. It is obsolete.
