### ISSUE TITLE
"Unknown Source" is a confusing

### ISSUE THREAD

**Issue by carmil-ms** [MicrosoftDocs/edge-developer#104]
The source may be known by the user or his/her Administrator. Please consider rephrasing the "Unknown Source". Try using the Subject from the signing certificate instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f10ce7-196b-dffb-cf45-6a2c5d359bde
* Version Independent ID: 14a6d29e-0e8b-cd20-de2d-33081c7cfd29
* Content: [Extensions - Extensions for enterprise - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/extensions-for-enterprise)
* Content Source: [microsoft-edge/extensions/extensions-for-enterprise.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/extensions-for-enterprise.md)
* Service: **unspecified**
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by libbymc** [comment]
Hi @carmil-ms - thanks for reaching out! This sounds like product feedback, not an issue with the doc. Head over to [Uservoice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer) to file your suggestion.
