### ISSUE TITLE
Failed to intall this component in Windows7 32bit and Windows10 32bit OS via bootstrapper

### ISSUE THREAD

**Issue by jimmysheep** [MicrosoftDocs/edge-developer#1040]
I followed the step of **Online-only deployment** in this page (https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution) programmatically. It did work well in Windows10 64bit OS, but for Windows10 32bit and Windows7 32bit OS the installation would fail. Especially in Windows7 32bit system, even if I download the bootstrapper manually and add it to Firewall white list the installation still fail. Could you make some test for different situation?
BTW, standalone installers work well in all system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17f573c0-3c98-2744-e2df-5bf023ee13cb
* Version Independent ID: 9c27ea10-29c8-5310-aa89-c3287d779d50
* Content: [Getting started with WebView2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32)
* Content Source: [microsoft-edge/webview2/gettingstarted/win32.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/win32.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Closing this issue because there's an issue on the engineering feedback repo. Thanks.
