### ISSUE TITLE
Debugging MS Teams Custom Tab on Android device via remote debugging.

### ISSUE THREAD

**Issue by AndreyButyrchik** [MicrosoftDocs/edge-developer#1042]
Element inspector doesn't work. I can select it (ctrl+shift+c) navigate on target element, but on click nothing happens. Also click event on desktop doesn't work at all, but if I try to click on mobile device all works fine.

Environment:

Microsoft Edge version: 87.0.664.57
Microsoft Teams App version: 1416/1.0.0.2020120802
Android version: 10

---
#### Document Details

* ID: 423e15ae-4f85-e6b4-05a0-e1c3a1c2d448
* Version Independent ID: e8d1d135-b095-dbf7-f3b2-28feace8934e
* Content: [Get Started with Remote Debugging Android Devices - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/)
* Content Source: [microsoft-edge/devtools-guide-chromium/remote-debugging/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/remote-debugging/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by zoherghadyali** [comment]
Hi @AndreyButyrchik! Thank you so much for sending the Microsoft Edge DevTools team your feedback. Based on feedback from you and others, we found this bug when remote debugging Android devices and have a fix available in Microsoft Edge version 89. To unblock yourself immediately, try using [Microsoft Edge Beta](https://www.microsoftedgeinsider.com/download) which is currently on version 89. Definitely let us know how that goes for you!

You can also send feedback to the Microsoft Edge DevTools team via the **Feedback** icon in the DevTools.
![image](https://user-images.githubusercontent.com/34316555/107671293-acb36e80-6c61-11eb-9ace-808515b364e1.png)
