### ISSUE TITLE
.NET 5 prerelease not working as indicated in doc

### ISSUE THREAD

**Issue by kennymoto** [MicrosoftDocs/edge-developer#1043]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Microsoft Edge WebView2 Control - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mrsteamfist** [comment]
@kennymoto Thank you for the feedback. Can you file a bug with the Webview team https://github.com/MicrosoftEdge/WebView2Feedback for better tracking?

Are you using multi-targeting or targetting specifically .Net 5? Are there any details you can on your issue?

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.
