### ISSUE TITLE
sequence of navigation events in table not equal 2 webpage description

### ISSUE THREAD

**Issue by amanada** [MicrosoftDocs/edge-developer#1044]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826c31a9-1f9f-4bd4-7389-e9ddb7905fe0
* Version Independent ID: 016e1875-f11d-0ef6-37d4-24851bbffddc
* Content: [Navigation - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/navigation-events)
* Content Source: [microsoft-edge/webview2/concepts/navigation-events.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/concepts/navigation-events.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Closing this issue because an issue was opened on the engineering team's feedback repo. Thanks.
