### ISSUE TITLE
Upload extension error: Files or directories outside directory that contains manifest.json NAME are not allowed

### ISSUE THREAD

**Issue by berthx** [MicrosoftDocs/edge-developer#1051]
Hi! I have few extensions released on chrome store and I wanted to upload them on Edge. However I am getting this error while trying to upload the .zip

The error is kind of hard to understand: "Package acceptance validation error: Files or directories outside directory that contains manifest.json emoji_picker are not allowed: __MACOSX, __MACOSX\._emoji_picker,..."

<img width="1497" alt="Screenshot 2020-12-18 at 11 53 50" src="https://user-images.githubusercontent.com/76207198/102607020-e8c9c780-4127-11eb-90f1-9f7e301419d3.png">

My extension is really basic
<img width="221" alt="Screenshot 2020-12-18 at 11 52 57" src="https://user-images.githubusercontent.com/76207198/102607053-f1220280-4127-11eb-9413-3f1abeb259c4.png">

Everything is inside the directory that contains the manifest.json

Thanks

**Comment by gebansal** [comment]
@berthx The package should not contain any files outside directory with manifest. i.e. zip should not contain any files outside the folder emoji_picker in this case. 
This can be mitigated in two ways:
1. A quick mitigation would be to create the zip from contents and not the parent folder itself.
2. The folder __MACOSX can be removed from within the zip

If you are facing any issue with this or the submission process, send an email to ext_dev_support@microsoft.com. We'd try our best to resolve your issue as soon as possible.
