### ISSUE TITLE
Acccess to Edge Classic

### ISSUE THREAD

**Issue by theking2** [MicrosoftDocs/edge-developer#1055]
Als Webentwickler bin ich vorläufig darauf angewiesen auch mit Edge Classic zu testen.

Wie erlange ich an die Edge Classic Renderung Webseiten?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2c6f6ed7-a789-502b-4c84-e823fa8e58ce
* Version Independent ID: dee3faf2-ef14-c323-6307-ebe204670f59
* Content: [Microsoft Edge (Chromium)-Entwicklungstools - Microsoft Edge Development](https://docs.microsoft.com/de-de/microsoft-edge/devtools-guide-chromium/)
* Content Source: [microsoft-edge/devtools-guide-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jm-trd-ms** [comment]
@theking2 
Danke für Ihre Anfrage.
Gehen Sie zu https://docs.microsoft.com/de-de/microsoft-edge/edgehtml/index.

**Comment by jm-trd-ms** [comment]
@theking2 
Entschuldigung, das die Antwort etwas länger gedauert hat.  
Um einen älteren Microsoft Edge-Browser zu emulieren, gehen Sie zu [https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/device-mode/testing-other-browsers](https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/device-mode/testing-other-browsers).
Um eine VM direkt herunterzuladen, gehen Sie zu [https://developer.microsoft.com/microsoft-edge/tools/vms](https://developer.microsoft.com/microsoft-edge/tools/vms).
