### ISSUE TITLE
webview2 不支持触摸

### ISSUE THREAD

**Issue by CQHO** [MicrosoftDocs/edge-developer#1057]
我下载并在项目里继承了 webview2 sdk 1.0.664.37
可以展示H5 页面，但是不响应任何触摸事件，其余原生页面是响应的。
操作系统：windows 7 已安装webview 2 runtime

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a23e9ad0-bdd1-6bd5-c40b-766b384c8bd4
* Version Independent ID: 2da6244f-4c85-f53c-3c13-080941fda15f
* Content: [在 WebView2 应用中使用 JavaScript - Microsoft Edge Development](https://docs.microsoft.com/zh-cn/microsoft-edge/webview2/howto/js)
* Content Source: [microsoft-edge/webview2/howto/js.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/howto/js.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @CQHO. You can get in touch with the engineering team by opening an issue on this repo: https://github.com/MicrosoftEdge/WebView2Feedback
I'll go ahead and close this issue now. Thank you.
