### ISSUE TITLE
VB.Net Examples?

### ISSUE THREAD

**Issue by AlanBurkhart** [MicrosoftDocs/edge-developer#1058]
Not everyone uses C#. Some VB.Net samples would be helpful. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Getting started with WebView2 for WinForms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms#step-1---create-a-single-window-application)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @AlanBurkhart I've updated the linked issue on the WebView feedback repo with this request. I'll go ahead and close this issue now.
