### ISSUE TITLE
WebView2 documentation - winforms

### ISSUE THREAD

**Issue by bjthomson** [MicrosoftDocs/edge-developer#1059]
The new WebView2 control works nicely, in both a .net framework 4.8 app and a .Net 5 app.

I was just wondering why the doc page details how to handle resize events explicitly rather than using the Dock or Anchor properties, like any other control. Is there something lurking I haven't found yet?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Getting started with WebView2 for WinForms apps - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/WebView2/gettingstarted/winforms)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Closing this issue because an issue was opened on the engineering team's feedback repo. Thanks.
