### ISSUE TITLE
Need more information on IE to Edge redirection feature

### ISSUE THREAD

**Issue by sushruth** [MicrosoftDocs/edge-developer#1061]
I have a few questions about this page -

1. How does this redirect exactly work from IE's perspective?
2. What happens if the user does not have Edge 87+ installed?
3. How backward compatible is this redirection service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe5c21b-2296-8b5c-208a-f41eb967c24e
* Version Independent ID: c3722063-7455-5ba9-a78d-102823dfd474
* Content: [Moving users to Microsoft Edge from Internet Explorer - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#request-an-update-to-the-ie-compatibility-list)
* Content Source: [microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
This unfortunately hasn't been updated in a long time. Marking as stale and planning to close this soon unless this becomes active again.
