### ISSUE TITLE
Is there any way to make a window transparent

### ISSUE THREAD

**Issue by aojianwu** [MicrosoftDocs/edge-developer#1064]
Is there any way to make a window transparent？
I have set the native window to transparent, but the background color of the window is still white.

**Comment by aojianwu** [comment]
Are there attributes to set?
Similar to electron, https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions
transparent: Boolean (optional)-Makes the window transparent. Default is false. On Windows, does not work unless the window is frameless.

**Comment by Reezaali** [comment]
Hi @aojianwu. Are you experiencing this in Microsoft Edge? Can you share a sample of your code please? Thank you.

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now.
