### ISSUE TITLE
User agent string format

### ISSUE THREAD

**Issue by trss** [MicrosoftDocs/edge-developer#1065]
Currently the user agent string format is presented in the form of an example:
```
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.74 Safari/537.36 Edg/79.0.309.43
```

An example definitely helps but a general format similar to https://developer.chrome.com/docs/multidevice/user-agent/ is more useful in that which parts change is made clear:
```
Mozilla/5.0 (Linux; {Android Version}; {Build Tag etc.}) 
AppleWebKit/{WebKit Rev} (KHTML, like Gecko) 
Chrome/{Chrome Rev} Safari/{WebKit Rev}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0130ae-2318-e95c-a77d-669d2c5dc8b8
* Version Independent ID: 3fcc0df5-94ed-6a3d-5c3f-78229329288c
* Content: [Microsoft Edge User Agent String - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string)
* Content Source: [microsoft-edge/web-platform/user-agent-string.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/user-agent-string.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for posting this feedback. This page has since been updated to focus mostly on UA Client Hints rather than UA strings. UA strings are outdated and tend to cause compatibility problems.
That said, the change of format you describe is probably still a good idea, just a low priority one in my opinion given the shift of focus.

**Comment by captainbrosset** [comment]
We have created a task on our backlog to make this documentation change. Thanks for reporting this issue.
