### ISSUE TITLE
Fix the path separators

### ISSUE THREAD

**Issue by sumitchakravarty** [MicrosoftDocs/edge-developer#1081]
This page could use a quick scrub - currently there is a mix of forward-slashes (/), back-slashes (\) and missing slashes (search for libjquery.min.js).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec889040-6707-74fd-9086-d838c15a9172
* Version Independent ID: 73d6355a-b256-c8ab-9889-c51603d3052b
* Content: [Create an extension tutorial Part 2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @sumitchakravarty, thanks for reporting this issue. I've added it to the backlog. I'll go ahead and close this issue now. Thanks.
