### ISSUE TITLE
Request: add a page with information about tracing, debugging etc

### ISSUE THREAD

**Issue by sumitchakravarty** [MicrosoftDocs/edge-developer#1082]
(This feedback is for this section, rather than this page.)

I was expecting to see a page about debugging.  The existing intro sections are good, but the moment one adds any new code, things can break, and the Errors page at edge://extensions tells you very little.

What would be useful:
- where did console.log(...) output go?
- how to set a breakpoint, step in, step over, see variables?
- etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec889040-6707-74fd-9086-d838c15a9172
* Version Independent ID: 73d6355a-b256-c8ab-9889-c51603d3052b
* Content: [Create an extension tutorial Part 2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
Thank you for the feedback. We will work on adding the debugging content to our documentation.

**Comment by pkellner** [comment]
@sumitchakravarty Debugging is pretty straight forward. The process is identical to developing with Google's chrome and they have some docs that will help you.  I believe console.log's will come out in the debugger's output.

https://developer.chrome.com/docs/extensions/mv3/tut_debugging/
