### ISSUE TITLE
Command to extract fixed version does not work

### ISSUE THREAD

**Issue by mungojam** [MicrosoftDocs/edge-developer#1085]
I tried using the command listed in the page for extracting the fixed version and got this error:

`Destination directory required for a multi-file CAB`

I tried various different ways to specify the destination directory, e.g

`expand Microsoft.WebView2.FixedVersionRuntime.88.0.705.56.x64.cab -F:* .\webview2\`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribution of Microsoft Edge WebView2 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Closing this issue because an issue was opened on the engineering feedback repo. Thanks.

**Comment by champnic** [comment]
@mungojam Have you tried using an absolute directory path?

**Comment by cgeier** [comment]
See [this post](https://stackoverflow.com/questions/66500241/webview2-site-not-loading/66501901#66501901).

When using `expand`, the destination must be a folder that already exists and the name must not end with '\'.

```

C:\Users\Test\Downloads> expand Microsoft.WebView2.FixedVersionRuntime.88.0.705.81.x86.cab -F:* "C:\Projects\WpfTestFixedVersion\WpfTestFixedVersion\bin\Debug"
```
