### ISSUE TITLE
Why the Microsoft Webview2 in c# winform works on only the version of beta mircosoft edge?

### ISSUE THREAD

**Issue by LIKESCA** [MicrosoftDocs/edge-developer#1087]
I used  based version of microsoft edge, and I try to used webview2 but It's not working
So I downloaded microsoft edge beta version only then did it work. 
Is this normal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Getting started with WebView2 for WinForms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @LIKESCA, this document should explain the different versions and recommendations: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution
I'll go ahead and close this issue now. Thanks.
