### ISSUE TITLE
PowerShell support

### ISSUE THREAD

**Issue by jflieben** [MicrosoftDocs/edge-developer#1093]
Could you include a sample of WebView2 through PowerShell? E.g. as a WinForm or WPF import? I'm sure that'll be very useful for a lot of admins :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Microsoft Edge WebView2 Control - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @jflieben - I've created an issue to track this request on the WebView feedback repo for the engineering team to review. I'll go ahead and close this issue now. Thanks.
