### ISSUE TITLE
Can't install extension `ClearURLs`

### ISSUE THREAD

**Issue by c2xusnpq6** [MicrosoftDocs/edge-developer#1099]
https://chrome.google.com/webstore/detail/clearurls/lckanjgmijmafbedllaakclkaicjfmnk
https://microsoftedge.microsoft.com/addons/detail/clearurls/mdkdmaickkfdekbjdoojfalpbkgaddei

```
[Variable $LIMIT$ used but not defined.].
```

**Comment by c2xusnpq6** [comment]
https://gitlab.com/KevinRoebert/ClearUrls/-/issues/771

https://gitlab.com/KevinRoebert/ClearUrls

**Comment by Reezaali** [comment]
Thanks for reporting this issue @c2xusnpq6. The extensions engineering team has filed an internal bug and it trying to repro the error. I'll go ahead and close this issue now. Thanks.
