### ISSUE TITLE
How long does it take for the list to be updated with a new entry?

### ISSUE THREAD

**Issue by BenSutcliffeLMK** [MicrosoftDocs/edge-developer#1106]
If I submit my site to the email address provided so it can be added to the compatibility list then roughly how long would this process take? Is it weeks or months? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe5c21b-2296-8b5c-208a-f41eb967c24e
* Version Independent ID: c3722063-7455-5ba9-a78d-102823dfd474
* Content: [Moving users to Microsoft Edge from Internet Explorer - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#request-an-update-to-the-ie-compatibility-list)
* Content Source: [microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Y-Kelly** [comment]
@BenSutcliffeLMK Hello! Rough estimate would be about a week, but it can depend when the request is received.  Normally the Need Microsoft Edge list is updated weekly on Tuesday and then our deployment process can take another day or so.

**Comment by BenSutcliffeLMK** [comment]
Thanks for the quick response
