### ISSUE TITLE
chrome.identity.getAuthToken support in Edge / documentation

### ISSUE THREAD

**Issue by kospl** [MicrosoftDocs/edge-developer#1108]
`chrome.identity.getAuthToken` listed as unsupported here in Edge documentation: https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/api-support#unsupported-extension-apis

but this in not true:

``
![image](https://user-images.githubusercontent.com/26386660/107882852-4db95800-6ef4-11eb-95c5-1915b41619a1.png)

Using this methods gives following error:

> OAuth2 request failed: Connection failed (-2).

Which is also not true, and this is constant error message for `chrome.identity.getAuthToken` in Edge.

Following that, can these requests be considered:

1.  make documentation clarify that `chrome.identity.getAuthToken` API is available and will throw `OAuth2 request failed: Connection failed (-2).` error.
2. OR remove `chrome.identity.getAuthToken` from Edge
3. OR (least real, but hopefully) add support of sign-in with Google for Edge extensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 814d311d-f0c4-12c3-eab2-ec4c73612de3
* Version Independent ID: 621a1702-2d7c-b9fb-8076-50087e4f5a64
* Content: [Supported APIs for Microsoft Edge extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/api-support)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/api-support.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/api-support.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
@kospl We have mentioned "chrome.identity.getAuthToken" in the unsupported list specifically to inform developers that they will not be able to use this API provided by Chromium platform. Can you elaborate on the error or issue here?

**Comment by kospl** [comment]
@gebansal and what developers should add to their code to check if Edge (occasionally) started supporting it - you suggest parsing documentation and use AI library so extension could use logic described there? Funny stuff. I would say functionality of chrome.identity.getAuthToken is `broken internally and documented badly` is more appropriate than `not supported`.

There is not just one usecase: you know extensions can be installed to Edge from Chrome webstore, right? And users won't be able to see any meaningful error in case extension created for Chrome uses chrome.identity.getAuthToken API.

**Comment by gebansal** [comment]
This is a valid concern you have raised. Here is how we plan to take it forward.
We will update our documentation to call out that the API exists and may not work as expected. Meanwhile, we will remove the API from our end so that the users will see a proper error messaging in such cases. 

Thank you for calling this out, will work on improving the documentation and the product.

**Comment by avi12** [comment]
Considering that `chrome.identity.getAuthToken` is unsupported, I believe that the following is a mistake:
https://github.com/MicrosoftDocs/edge-developer/blob/dda3f1d622de58a4722b8c1da69fe5a74f166abc/microsoft-edge/extensions-chromium/getting-started/manifest-format.md?plain=1#L90

**Comment by mikehoffms** [comment]
in 
https://learn.microsoft.com/microsoft-edge/extensions-chromium/getting-started/manifest-format?tabs=v3#format-of-manifestjson-for-extensions
Find:  "oauth2":
but `chrome.identity.getAuthToken` is unsupported
@captainbrosset
