### ISSUE TITLE
Question relating to this page

### ISSUE THREAD

**Issue by colmoflynn** [MicrosoftDocs/edge-developer#1109]
Are these distribution options supported on Windows 10 Enterprise for extensions that are not distributed on the Edge Adds On Store?

I ask this in light of the statement updated (within the last six months) on this other page

https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#extensioninstallforcelist

> "On Microsoft Windows instances, apps and extensions from outside the Microsoft Edge Add-ons website
>  can only be forced installed if the instance is joined to a Microsoft Active Directory domain, and running Windows 10 Pro."

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f290aba-5618-9b79-e3ac-243ec8cc4dd6
* Version Independent ID: 0cda1705-27db-4282-40e1-a2fbbd16ed2e
* Content: [Alternate method to distribute extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @colmoflynn, you can reach the extensions team using any of the following methods: 
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-us
I'll go ahead and close this issue for now. Thank you.
