### ISSUE TITLE
Variable $LIMIT$ used but not defined

### ISSUE THREAD

**Issue by c2xusnpq6** [MicrosoftDocs/edge-developer#1117]
`Variable $LIMIT$ used but not defined.`  https://gitlab.com/KevinRoebert/ClearUrls/-/issues/771

https://gitlab.com/KevinRoebert/ClearUrls

![image](https://user-images.githubusercontent.com/75058881/108698199-d3fe1b80-753e-11eb-9930-8452a45c673e.png)

![image](https://user-images.githubusercontent.com/75058881/108698196-d3658500-753e-11eb-998c-45d5b974c36d.png)

**Comment by Reezaali** [comment]
Hi @c2xusnpq6 - is this a documentation bug, or a bug in Microsoft Edge? If it's a bug in Microsoft Edge, you can submit the bug report using **Help and Feedback** > **Send Feedback** from within Edge. I'll go ahead and close this issue now, but let me know if it's a documentation bug and i'll reopen it. 
Thank you.
