### ISSUE TITLE
The word "gridlines" in the what's new 89 flexbox section is a bit confusing

### ISSUE THREAD

**Issue by captainbrosset** [MicrosoftDocs/edge-developer#1118]
In What's New 89, there's a section about Flexbox:

> Display alignment icons and gridlines when Flexbox layouts change using CSS properties

The word gridlines is a bit confusing. Indeed, there are 2 main CSS layout systems that DevTools has support for: Grid and Flexbox. The word gridlines makes me think of CSS Grids, and in fact, CSS Grids has a notion grid lines, so people familiar with it might be confused as to whether we are talking about Flexbox or Grid.

I would suggest replacing it with the word guides, or something similar, or maybe visual guides:

> Display alignment icons and visual guides when Flexbox layouts change using CSS properties

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff46d439-bddb-b788-2ccd-d5ab89cecc4d
* Version Independent ID: 22a8592b-bb21-47a4-3263-fa98a0e07bf1
* Content: [What's new in DevTools (Microsoft Edge 89) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2021/01/devtools)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2021/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/whats-new/2021/01/devtools.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jm-trd-ms** [comment]
Content updated in #1196.
