### ISSUE TITLE
Great Start

### ISSUE THREAD

**Issue by Javaman2** [MicrosoftDocs/edge-developer#1122]
Just ran the sample code on this page.  On .NET 5.0 and the .NET 5.0 SDK installed.  Instructions went flawlessly.  Great Job!  Been waiting of a 'real' browser experience in WPF for a long time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9dc9d2-795c-9612-3585-408b4621c080
* Version Independent ID: f73fc16d-d842-4507-9fdb-b42856720355
* Content: [Getting started with WebView2 for WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf)
* Content Source: [microsoft-edge/webview2/gettingstarted/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Thank you for your feedback @Javaman2.
