### ISSUE TITLE
EnsureHttps event handler

### ISSUE THREAD

**Issue by itce-torino** [MicrosoftDocs/edge-developer#1128]
FYI : 
La funzione 
"private void EnsureHttps(WebView2 sender, WebView2NavigationStartingEventArgs args)"
segnala  l'errore CS0246; la stesura corretta è:
"private void EnsureHttps(WebView2 sender, CoreWebView2NavigationStartingEventArgs args)"

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 87f61c26-2c48-2ec7-6e18-4aa181702b17
* Version Independent ID: ddd9e9ec-0143-b45b-6e72-225f73d89212
* Content: [Getting started with WebView2 for WinUI apps - Microsoft Edge Development](https://docs.microsoft.com/it-it/microsoft-edge/webview2/gettingstarted/winui)
* Content Source: [microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winui.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for the feedback, and apologies for the delayed reply.
Looking at the docs, it seems like this issue was already fixed. So I'm closing the issue now.
