### ISSUE TITLE
WebView2Loader.dll is left out

### ISSUE THREAD

**Issue by Perka1000** [MicrosoftDocs/edge-developer#1131]
WebView2Loader.dll is left out when publishing an application that have reference to a class library with package reference to Microsoft.Web.WebView2.
Native dll:
WebView2Loader.dll.deploy

Everything works fine when publishing an application with package reference to Microsoft.Web.WebView2.

Step to reproduce issue:
1.	Start VS 2019 and select create a new project.
2.	Select WPF App (.NET Framework) C#, you get a WpfApp1 project.
3.	To solution add New Project, select Class Library (.NET Framework) C#, you get a ClassLibrary1.
4.	To WpfApp1 add reference to ClassLibrary1.
5.	To ClassLibrary1 install NuGet Microsoft.Web.WebView2 (1.0.705.50).
6.	For WpfApp1 select property and select tab Publish and specify a publishing folder on hard drive.
7.	Press Publish Now button and look in publishing folder. The WebView2 assemblies and WebView2Loader.dll is left out.

Thanks
Perka

**Comment by captainbrosset** [comment]
Apologies about the long delay replying.
Unfortunately, this repository is about the documentation of the Edge developer features, not about the features themselves.
If you are still facing the above problem, please get in touch with the WebView2 team by filing an issue on the WebView2Feedback repository here: https://github.com/MicrosoftEdge/WebView2Feedback/issues
