### ISSUE TITLE
User Data Folder

### ISSUE THREAD

**Issue by raggiesoft** [MicrosoftDocs/edge-developer#1140]
There needs to be sample code on this page to show us how to set up the User Data Folder, for when our apps get installed to [PROGRAMFILES] the old fashioned way (I myself still use MSI installers), also remind users to NOT set the Source property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50d81b66-5bfd-17dc-4d56-ee08e1799fc7
* Version Independent ID: af4e49c5-7768-a07c-a4ce-f34b4887474f
* Content: [Manage user data folder in WebView2 applications. - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder)
* Content Source: [microsoft-edge/webview2/concepts/userdatafolder.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/concepts/userdatafolder.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@raggiesoft - I've transferred the issue to the engineering team's repo. I'll go ahead and close this issue now. Thanks.
