### ISSUE TITLE
How to define custom download directory for msedge chromium

### ISSUE THREAD

**Issue by PhilippSelenium** [MicrosoftDocs/edge-developer#1145]
I have tried:
```
{'browserName': 'MicrosoftEdge',
 'version': '',
 'platform': 'ANY',
 'pageLoadStrategy': 'normal',
 'ms:edgeOptions': {'prefs': {'download.default_directory': '/tmp/foo',
   'download.prompt_for_download': False,
   'plugins.always_open_pdf_externally': True,
   'profile.default_content_settings.popups': '0',
   'profile.content_settings.exceptions.automatic_downloads.*.setting': '1',
   'download.directory_upgrade': True},
  'extensions': [],
  'args': ['accept-insecure-certs',
   'ignore-certificate-errors',
   'no-sandbox',
   'disable-dev-shm-usage',
   'disable-gpu'},
 'ms:edgeChromium': True}
```

**Comment by Reezaali** [comment]
Hi @PhilippSelenium - thanks for your question. To ensure it gets routed to the right team, can you submit your question using ... > Help and feedback > Send feedback? I'll go ahead and close this issue now. Thanks.

**Comment by PhilippSelenium** [comment]
@Reezaali Yes, sure, can you tell me where?

**Comment by zoherghadyali** [comment]
Hi @PhilippSelenium! Sorry for the confusion but I think @Reezaali meant the feedback icon shown in the Microsoft Edge DevTools here: 
![image](https://user-images.githubusercontent.com/34316555/112216880-41a17400-8bdf-11eb-8e2b-c19161962e18.png)

If you send your feedback via that icon, we can route it to the right team and the folks on our team who work on Microsoft Edge Driver and Selenium can get back to you. Please be sure to include your email so they can actually send you a response! Thanks!

**Comment by PhilippSelenium** [comment]
Okay thanks, I did that let's see if something happens ...
