### ISSUE TITLE
Newcan

### ISSUE THREAD

**Issue by MYTA1802** [MicrosoftDocs/edge-developer#1150]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff46d439-bddb-b788-2ccd-d5ab89cecc4d
* Version Independent ID: 22a8592b-bb21-47a4-3263-fa98a0e07bf1
* Content: [What's new in DevTools (Microsoft Edge 89) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2021/01/devtools#cookies-updates)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2021/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/whats-new/2021/01/devtools.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by MYTA1802** [comment]
Can you do It?

**Comment by Reezaali** [comment]
Hello @MYTA1802, I'm not familiar with Newcan. Can you provide a link to the documentation please?
