### ISSUE TITLE
Dead links to Mozilla

### ISSUE THREAD

**Issue by bucmic** [MicrosoftDocs/edge-developer#1151]
All links to the Mozilla web sites are dead, please correct.

-> Page not found

Thanx
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55284993-672a-b950-38ec-f3e175dfbf93
* Version Independent ID: 0617203d-5c57-037e-74b9-11c025917d07
* Content: [Progressive Web Apps on Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @bucmic - Sorry to hear about this issue and thanks for opening this issue. 
I'm not able to reproduce the broken links. Can you retry please? All the links opened for me. Thank you.

**Comment by bucmic** [comment]
> Hi @bucmic - Sorry to hear about this issue and thanks for opening this issue.
> I'm not able to reproduce the broken links. Can you retry please? All the links opened for me. Thank you.

Hello Reezaali,

ok, it's the DE version of the pages, EN seems to work. Just try to set DE as system language and you'll see. So it's a redirection issue and I guess I better contact Mozilla.

Regards
Michael

**Comment by Reezaali** [comment]
Thanks for confirming @bucmic.

**Comment by Reezaali** [comment]
@bucmic - I'll also reach out to them to let them know.
