### ISSUE TITLE
How to deploy WebView2 using GPO?

### ISSUE THREAD

**Issue by designchris** [MicrosoftDocs/edge-developer#1152]
We need to deploy WebView2 company-wide using GPO. How can we do that? Repackaging the .exe as .msi any deploying it using GPO did not work (while the msi can be installed fine manually).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribution of Microsoft Edge WebView2 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Created issue on the engineering repo. Will proceed to close this issue.
