### ISSUE TITLE
Failed to find WebView2Loader.dll

### ISSUE THREAD

**Issue by vvx-public** [MicrosoftDocs/edge-developer#1154]
REAL PROBLEM: The BUILD > PLATFORM TARGET was "**Any CPU**"
MY SOLUTION: Changed the BUILD > PLATFORM TARGET to"**x64**"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728447ae-f77e-e699-61c3-ec6ac9dcfe2f
* Version Independent ID: aa8a2809-de77-8b0a-baf2-45a44d649f77
* Content: [Release Notes for Microsoft Edge WebView2 for Win32, WPF, and WinForms - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes)
* Content Source: [microsoft-edge/webview2/releasenotes.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/releasenotes.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Copied the issue to the engineering repo. Proceeding to close this issue.
