### ISSUE TITLE
Support for Chromium Inspect is lovely  but ...

### ISSUE THREAD

**Issue by vvx-public** [MicrosoftDocs/edge-developer#1155]
It shows up in a separate window in unpredictable locations on a multi-monitor system

**Comment by zoherghadyali** [comment]
Hi @vvx-public! Thanks for your feedback. I'm reaching out to let you know that I think docking the Microsoft Edge DevTools could help solve your problem. Select the `...` menu in the top-right corner of the DevTools and select an option to dock the DevTools to the bottom, the left, or the right of the browser. Once you set the dock position you want, DevTools will remember that position and always open there again.

![image](https://user-images.githubusercontent.com/34316555/112228872-35251780-8bef-11eb-989b-454c42c5bd7d.png)

Check out our docs for more info here:
