### ISSUE TITLE
F12 DevTools Elements can't load styles 

### ISSUE THREAD

**Issue by ljt1018168** [MicrosoftDocs/edge-developer#1157]
[在此处输入反馈]
F12 DevTools **Elements** can't load **styles** 
when I open a website like baidu.com ,then click F12 open DevTools Elements ,the Styles option can't load with a loading circle.
like this ->

![snipaste_20210318_152919](https://user-images.githubusercontent.com/19421941/111588998-4214c600-87ff-11eb-9275-7667fed169c8.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2c6f6ed7-a789-502b-4c84-e823fa8e58ce
* Version Independent ID: dee3faf2-ef14-c323-6307-ebe204670f59
* Content: [Microsoft Edge (Chromium) 开发人员工具 - Microsoft Edge Development](https://docs.microsoft.com/zh-cn/microsoft-edge/devtools-guide-chromium/)
* Content Source: [microsoft-edge/devtools-guide-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@ljt1018168 sorry to hear about this error. I'm not able to repro on my end. Can you share what version of Edge you're running?

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.

**Comment by ljt1018168** [comment]
sorry , it doesn't work , so i uninstall Beta version ; after two weeks i download the new version 版本 91.0.864.37;it works.
thanks
