### ISSUE TITLE
Can I have a 2-row toolbar????????????

### ISSUE THREAD

**Issue by c2xusnpq6** [MicrosoftDocs/edge-developer#1170]
![image](https://user-images.githubusercontent.com/75058881/112612072-77ea2800-8e59-11eb-925a-d3cc237dab15.png)

sad..................... or maybe 3-row? **HA!**

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/112612297-b849a600-8e59-11eb-81c1-77a3db90dc78.png)

**Comment by c2xusnpq6** [comment]
and I like to use Google Translate, is there a way................. to.................................... change..................................................... never mind... T.T
![image](https://user-images.githubusercontent.com/75058881/112612486-f050e900-8e59-11eb-88da-1ed496f27567.png)

**Comment by Reezaali** [comment]
Hi @c2xusnpq6, what version of Edge are you using?

**Comment by c2xusnpq6** [comment]
> Hi @c2xusnpq6, what version of Edge are you using?

latest version of course bro?!

**Comment by c2xusnpq6** [comment]
If you install many extensions, `edge` will be difficult to use

(I don't want to collect it in the corner............... =3=)

**Comment by gebansal** [comment]
If you are on Stable version, you can try using the approach mentioned here: https://techcommunity.microsoft.com/t5/discussions/how-to-unhide-vs-disable-enable-my-extensions-in-edge/m-p/2113172/highlight/true#M43247

If you are on Dev or Canary, you'll find an extensions menu available for managing your extensions better on the toolbar.
