### ISSUE TITLE
Does not work, nobody seems to be listening on port specified in launch.json

### ISSUE THREAD

**Issue by pierrecoach** [MicrosoftDocs/edge-developer#1171]
Following the instructions in this page, I tried to debug an html page from vscode - here is the folder contents
[vstest.zip](https://github.com/MicrosoftDocs/edge-developer/files/6217037/vstest.zip)

I only receive a message saying the connection is refused, with no explanation. 
![refused](https://user-images.githubusercontent.com/5269604/112747225-328e3d80-8fb4-11eb-9576-96321fcde352.png)
Could you please provide information about troubleshooting, for example which process should be listening on port specified in launch.json (edge or code or ???), where to find error message if nobody is listening after pressing F5, etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c648fd42-706c-bb78-2f32-ff6ace125551
* Version Independent ID: 68efb0c6-9a4d-e6f6-4639-c0a9faa4fa39
* Content: [Debug Microsoft Edge (Chromium) from Visual Studio Code - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/debugger-for-edge)
* Content Source: [microsoft-edge/visual-studio-code/debugger-for-edge.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/visual-studio-code/debugger-for-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by codepo8** [comment]
Hello there, it seems that your local server isn't running. That's got nothing to do with the code you provided. The extension doesn't start a local server for you, you need to do that by hand. Depending on what platform you use, this could be easier or harder.

If you're already familiar with Node and NPM there are [instructions on the Extension GitHub Repo](https://github.com/microsoft/vscode-edge-devtools#setting-up-your-project-to-show-live-changes-in-the-extension).

**Comment by codepo8** [comment]
Once the server runs (I used `http-server ./` in Node, you also need to change the self-closing script to a closed tag as it is invalid HTML.

![image](https://user-images.githubusercontent.com/13508/112875611-b2a3c880-90c4-11eb-90c7-0a703dad2e6f.png)

**Comment by pierrecoach** [comment]
Yes, I found it out and the issue is fixed for me now.

Let me suggest to add information about “one should ensure an http server running before because the debugger does not start it, not complain that it is not running” – this would have spare me troubleshooting and looking out stupid

Thank you

Pierre

**Comment by codepo8** [comment]
We're working on a solution to start a server in the project folder if there is none running, but it is tough to check automatically as we don't know what port you run your project in. For projects with a launch.json this is an excellent idea though. Will add this to the backlog.

**Comment by Reezaali** [comment]
I'll go ahead and close out this issue now. Thanks.
