### ISSUE TITLE
WebView2 not loading web page in Outlook VSTO Add-in

### ISSUE THREAD

**Issue by kumarkaran** [MicrosoftDocs/edge-developer#1179]
Hi Team,

I am writing new Outlook VSTO Add-in with using Visual Studio 2019 with C#.  Here we are adding TaskPane with using UserControl (Windows Form) which display in right side of Outlook as Pane.

I have installed Microsoft.Web.WebView2 latest stable version as : 1.0.774.44 and I got the new control in Toolbox which I have drag/drop and I can see WebView2 control on my UserControl (Windows Form).  I have also set Source properties with https://www.google.com link.

But when I execute the solution then Task pane with other controls appears, but WebView2 control is blank/grey as it should load https://www.google.com link.

In code side I have checked that CoreWebView2 always null, so I have also implemented the code as suggested in one of the forum as:

string url = "https://www.google.com";
await webView21.EnsureCoreWebView2Async(null);
webView21.CoreWebView2.Navigate(url);

But when debugger reach to "await webView21.EnsureCoreWebView2Async(null);" line then it goes to infinite loop.

Please note when we try to use WebView2 in Windows Application Type project then everything is working fine means I can see web page is loading in WebView2 control, only the problem is in Outlook VSTO Add-in.

So please help on this how we can resolve this.

Thanks.

**Comment by Reezaali** [comment]
@kumarkaran I've opened an issue on the Engineering repo. I'll go ahead and close out this issue now.

**Comment by abhinovpankaj** [comment]
Is any resolution available?
