### ISSUE TITLE
Docs: Cache API link pointing to wrong resource

### ISSUE THREAD

**Issue by ucffool** [MicrosoftDocs/edge-developer#118]
The Cache API link under Current Availability goes to the [wrong place](https://developer.mozilla.org/en-US/docs/Web/API/Push_API). It should point here:
https://developer.mozilla.org/en-US/docs/Web/API/Cache

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31da9c54-4efd-6f71-1ef3-67d796c71cb4
* Version Independent ID: eb5e84cd-b850-fa16-a8b2-5900d6dce2ee
* Content: [Progressive Web Apps on Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps)
* Content Source: [microsoft-edge/progressive-web-apps.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
Thanks again for catching that!
