### ISSUE TITLE
What files exactly need to be included in Fixed Version distribution mode

### ISSUE THREAD

**Issue by bitbonk** [MicrosoftDocs/edge-developer#1180]
For the Fixed Version distribution mode it is not quite clear what files from the decompressed package need to be included. Which files in that package are part of the "Fixed Version binaries".

> 3. Include the decompressed Fixed Version binaries in your project.

Or is it _everything_ (all files) from that package? That would make WebView2 pretty unusable for small-ish simple apps like [in this scenario](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1140).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribution of Microsoft Edge WebView2 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for this issue, and apologies for the very late answer. I have created a task on our backlog to improve this documentation page, and will hopefully address it soon.
Closing this issue now.
