### ISSUE TITLE
Page states that WebView2 on WinUI is in preview

### ISSUE THREAD

**Issue by Marv51** [MicrosoftDocs/edge-developer#1189]
I don't think WebView2 on WinUI is in preview anymore, is it? Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Microsoft Edge WebView2 Control - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
You are correct, thank you for reporting this. WinUI3 is part of Project Reunion which had a 0.5 release. Even though the version is <1.0 it's not technically considered preview anymore. So we should update that page.

**Comment by captainbrosset** [comment]
Addressed in PR #1334.

**Comment by captainbrosset** [comment]
Closing since the PR got merged.
