### ISSUE TITLE
Support latest specification

### ISSUE THREAD

**Issue by vertonghenb** [MicrosoftDocs/edge-developer#119]
Currently Edge does not support the latest [specification](https://notifications.spec.whatwg.org/#dictdef-notificationaction), for example the "Actions" option. Are there plans to do so in the (near) future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b923d493-ec87-0849-5a1b-492d49b63523
* Version Independent ID: d4897fac-40c4-6987-c77f-2e296e3315bf
* Content: [Dev guide - Web Notifications API - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-notifications-api)
* Content Source: [microsoft-edge/dev-guide/windows-integration/web-notifications-api.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/windows-integration/web-notifications-api.md)
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by libbymc** [comment]
Hi @vertonghenb - Yes, support for [NotificatonAction](https://notifications.spec.whatwg.org/#dictdef-notificationaction) is in the latest [Insider Preview](https://insider.windows.com) builds! 

FYI - GitHub issues in this repo are for documentation related issues. Next time, check out the various product feedback channels available here: https://developer.microsoft.com/microsoft-edge/support/.

**Comment by vertonghenb** [comment]
@libbymc , thanks!
