### ISSUE TITLE
Please support importing old data from Chrome and Firefox thx!!

### ISSUE THREAD

**Issue by c2xusnpq6** [MicrosoftDocs/edge-developer#1190]
![image](https://user-images.githubusercontent.com/75058881/113682042-45f88180-96f5-11eb-83eb-e58203273f29.png)
look at firefox, and then look at you................. bruh?

Please support importing old data from Chrome and Firefox, I have used them before.
Data like password, browsing history, cookie… THX!

(I used to use Chrome Beta and Firefox Beta, and I really need this…

https://github.com/MicrosoftDocs/edge-developer/issues/1098

**Comment by captainbrosset** [comment]
Thanks for your feedback. I have forwarded it to the right Edge team. I'll close this issue now as this repository is dedicated to documentation, not new Edge features.
