### ISSUE TITLE
Not up to date

### ISSUE THREAD

**Issue by Marv51** [MicrosoftDocs/edge-developer#1191]
See title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dec166ea-3192-50ac-a930-f2185226801f
* Version Independent ID: a7055048-1b57-b2dc-78ae-6786d8765467
* Content: [Roadmap for Microsoft Edge WebView 2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap)
* Content Source: [microsoft-edge/webview2/roadmap.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/roadmap.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @Marv51 - we pushed an update today. Thanks!
