### ISSUE TITLE
WebView2 does not support .net 5 and core designers?

### ISSUE THREAD

**Issue by PoulBak** [MicrosoftDocs/edge-developer#1192]
[Angiv feedback her]

WebView2 does not support .net 5 and core designers?

Isn't that remark outdated?

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Getting started with WebView2 for WinForms apps - Microsoft Edge Development](https://docs.microsoft.com/da-dk/microsoft-edge/webview2/gettingstarted/winforms)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for filing, and apologies for the delay. Looking at the page, I'm not seeing .net 5 or core designers being mentioned anywhere. So I think this issue has been fixed since you filed it.
@PoulBak can you confirm that the issue you reported has been addressed? If so, I'll close the issue.
