### ISSUE TITLE
Flashing rectangles when interacting with site while devtools window is open.

### ISSUE THREAD

**Issue by asafkaganbezgin** [MicrosoftDocs/edge-developer#1200]
[Enter feedback here]
After opening devtools, every time I click on a button on website and after every single page transition, Microsoft edge shows flashing green and yellow borders. I assume they highlight the newly rendered divs on the website. However, this becomes very annoying while developing and I would like to know if it is possible to disable this behavior.

Versions:
Microsoft Edge:  89.0.774.75 (Official build) (64-bit)
Windows 10: 20H2 19042.867

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d3ec99-16ab-400e-5f1a-aaf1f79ef900
* Version Independent ID: a68ce21e-74ba-b319-a586-355918f499f7
* Content: [Find and fix problems with the Microsoft Edge DevTools Issues tool - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/issues/)
* Content Source: [microsoft-edge/devtools-guide-chromium/issues/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/issues/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @asafkaganbezgin - can you use one of the following methods to ensure this gets routed to the DevTools team to help support you? Thanks.
https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/issues/#getting-in-touch-with-the-microsoft-edge-devtools-team
