### ISSUE TITLE
Click on Links

### ISSUE THREAD

**Issue by harmie11** [MicrosoftDocs/edge-developer#1203]
I use xfinity.com email. Now any message I get that has "Click on Links" won't work. You can set and click on them all day and nothing will happen. Is this due to the last update or an Xfinity problem?
 Whatever the problem is, it sure is an aggravation! The links in some emails are unimportant but others are really helpful. They can take you to sites you don't know the address to for important updates to Apps you have purchased or to sites you really NEED to visit for things like clothing or appliances.
 How do you fix this? I have never had a problem clicking on live links in Xfinity.com email until lately. Comcast/Xfinity almost has no Support anymore so I am asking you if there is a way to set my computer up to get the Links to work or if it's Xfinity's problem?

**Comment by Reezaali** [comment]
Sorry to hear about this problem @harmie11. I recommend starting with xfinity if that's the only place that you've noticed this coming up. Thanks.
