### ISSUE TITLE
How to Open the webview2 in directly to edge browser window in Windows application 

### ISSUE THREAD

**Issue by BalajiSubramanianDhiyashini** [MicrosoftDocs/edge-developer#1205]
Hi Team,

How to use the webview2 control to directly open in edge browser window from Windows application.

Like Target framename  property in WebBrowser control.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Getting started with WebView2 for WinForms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Syul968** [comment]
Hi @BalajiSubramanianDhiyashini,

For questions and bug reports about the WebView2 product itself (as opposed to the documentation in Microsoft Docs) you can open an issue in the [WebView2Feedback repo](https://github.com/MicrosoftEdge/WebView2Feedback).
