### ISSUE TITLE
WebView2/Concepts/Versioning NuGet package kinds

### ISSUE THREAD

**Issue by Syul968** [MicrosoftDocs/edge-developer#1207]
> The WebView2 NuGet package contains both a release and pre-release package.

How accurate is this? We have two different kinds of NuGet packages: release NuGet package and pre-release NuGet package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e7761f-33b7-cdd5-2a03-dbe3ad9fab20
* Version Independent ID: 9ba37c84-78c0-5fb6-5f6a-22d6286add19
* Content: [Understand WebView2 SDK versions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning)
* Content Source: [microsoft-edge/webview2/concepts/versioning.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/concepts/versioning.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
This unfortunately hasn't been updated in a long time. Marking as stale and planning to close this soon unless this becomes active again.
