### ISSUE TITLE
webview2 automation is not working

### ISSUE THREAD

**Issue by deepaklohani1985** [MicrosoftDocs/edge-developer#1208]
[Enter feedback here]

Dear Team,

I was going through the sample app to automate webview2 based wpf applicatin, I followed the same step, but it did not work for me,

i saw below code was mentioned to be tried out, but it is not working as expected.

**ex-**

// EdgeOptions() requires using OpenQA.Selenium.Edge
    // Construct edgeOptions with is_legacy = false and the string "webview2"
    EdgeOptions edgeOptions = new EdgeOptions(false, "webview2");

//Set the BinaryLocation to the filepath of the WebView2API Sample runtime
edgeOptions.BinaryLocation = @"C:\path\to\your\webview2\project.exe";

//Set msedgedriverDir to the filepath of the directory housing msedgedriver.exe
string msedgedriverDir = @"C:\path\to\your\msededriver.exe's\directory";

//Set msedgedriverExe to the name of the Edge Driver. By default it is:
string msedgedriverExe = @"msedgedriver.exe";

// Construct EdgeDriverService with is_legacy = false  
EdgeDriverService service = EdgeDriverService.CreateDefaultService(msedgedriverDir, msedgedriverExe, false);

EdgeDriver e = new EdgeDriver(service, edgeOptions);

1.) EdgeOptions class does not have parametrized constructor, and also it does not have any property with name starting with Binary.

So am not able to run this sample automation code. can you please help me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3317fb4-5819-7961-ab43-3b0e9d744acf
* Version Independent ID: 0c23b8c3-a6b7-ac17-aad4-da5dd54c80e2
* Content: [Automating and Testing WebView2 with Microsoft Edge Driver - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/howto/webdriver)
* Content Source: [microsoft-edge/webview2/howto/webdriver.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/howto/webdriver.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for sending your feedback, and apologies for the long delay replying.
I have created a task on our backlog to fix the docs based on your feedback. We will hopefully be able to get to it soon.
I will therefore close this issue for now.
