### ISSUE TITLE
Font editor, need to encrypt files

### ISSUE THREAD

**Issue by RonnieLew2** [MicrosoftDocs/edge-developer#1213]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da0a7dc-5990-0560-e467-2e849fc8d542
* Version Independent ID: 2a067140-6b45-6d36-f7ab-ca707a482f6d
* Content: [Edit CSS font styles and settings in the Styles pane in DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/inspect-styles/edit-fonts)
* Content Source: [microsoft-edge/devtools-guide-chromium/inspect-styles/edit-fonts.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/inspect-styles/edit-fonts.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
This seems unrelated to the font editor. Maybe this was opened by mistake? I'm going to close this issue for now. 
@RonnieLew2 please do feel free to provide more information as a comment and I'll re-open the issue.
