### ISSUE TITLE
Expand the Application Cache image has an expanded view of Cache Storage

### ISSUE THREAD

**Issue by shettypuneeth** [MicrosoftDocs/edge-developer#1220]
The section covering View Application cache, the _Expand the Application Cache section and choose a cache to view the resources_ has an image of expanded SW Cache Storage instead of Application Cache.

Not sure if this was a miss or intentional.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e647047-d083-63e9-cfad-330a1deff490
* Version Independent ID: 79f40a7c-a89a-dc28-2417-eaa602cf785a
* Content: [View Application Cache Data With Microsoft Edge DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/devtools-guide-chromium/storage/applicationcache)
* Content Source: [microsoft-edge/devtools-guide-chromium/storage/applicationcache.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/storage/applicationcache.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for finding this and reporting it. It is indeed unintentional and should ideally be fixed.

That being said, I would actually vote for removing the feature in DevTools entirely and removing the associated docs page.
The reason being that appcache has been slated for removal from the web for a long time, and it is happening right now:

- https://web.dev/appcache-removal/ mentions that, as of chrome 84, appcache only works with reverse origin trials, and that as of 93, will be removed for everyone (93 is chrome canary right now)
- https://bugzilla.mozilla.org/show_bug.cgi?id=1619673 shows that Firefox has already removed appcache in Firefox 84.
