### ISSUE TITLE
Typo in document

### ISSUE THREAD

**Issue by ericlaw1979** [MicrosoftDocs/edge-developer#1225]
This

```If a user removes the password reveal button, the user must delete the contents of the password field before the password reveal button displays again.```

...doesn't make sense to me. The user can't remove the icon (except by changing the setting, in which case the icon doesn't come back)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5949a483-1a4d-0f77-5576-af0a335fc959
* Version Independent ID: 824cf57c-044d-9dac-085a-8bcfd6f2dc15
* Content: [Customize the password reveal button - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal)
* Content Source: [microsoft-edge/web-platform/password-reveal.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/password-reveal.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Doc has been updated. Thank you!
