### ISSUE TITLE
WebView2 ,WPF ,WIN7,Windowstyle=None,Not Work

### ISSUE THREAD

**Issue by Jabari666** [MicrosoftDocs/edge-developer#1226]
Hi,there is a question。
When Windowstyle（WPF） = none Or FormBorderStyle（Winform） = none.
Webview is Transparent.
Win10 is OK,WIN7 can not work.
webView2 Control Version:1.0.865-prerelease
Microsoft Edge WebView2 Version:89.0.774.54

**Comment by Jabari666** [comment]
I found process manager show the Miccrosoft Edge WebView2 is Suspended

**Comment by captainbrosset** [comment]
Apologies about the late reply. Unfortunately this repository is about the documentation content of WebView2 (and other things), not about WebView2 itself.
If you are still facing the above issue, I suggest getting in touch with the WebView2 team on the WebView2Feedback repository here: https://github.com/MicrosoftEdge/WebView2Feedback/issues
