### ISSUE TITLE
selenium Edge driver Choco package

### ISSUE THREAD

**Issue by richie676** [MicrosoftDocs/edge-developer#1229]
I have seen you also promote chocolaty as source for the Selenium Edge driver but that is still on version 81 (from May 2020). Are there any plans to update the chocolaty package soon?
https://community.chocolatey.org/packages/selenium-chromium-edge-driver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver (Chromium) for test automation - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @richie676 - the advice I got from Engineering was that we don't own the package. It's probably best to reach out to the package owner to get an update.

**Comment by richie676** [comment]
Hi @Reezaali ok I didn't see that its not your package, I guessed it's your package since you are promoting the choco package in  documentation. I will ask for an update on Chocolaty.
But it should be also your interest that you are not promoting a solution that offer an one year old version of your driver! Maybe release your own Choco package and maintain it?
