### ISSUE TITLE
It's missing "management" API. Is this under consideration, planned, rejected, or is it in the works?

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/edge-developer#123]
Hello,

On this page, the API, "management", is left out in the roadmap. Does this mean this API is explicitly under consideration, planned, rejected, or it's under construction?

I would like to report that this needs to be explicitly explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0570b6f-559c-e512-49b4-8c78341407d1
* Version Independent ID: 85c8aa17-9d5e-ce7d-be50-0e1e9cb85e88
* Content: [Extensions - Extension API roadmap - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/extension-api-roadmap)
* Content Source: [microsoft-edge/extensions/api-support/extension-api-roadmap.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/api-support/extension-api-roadmap.md)
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by libbymc** [comment]
Thanks @tommai78101! The management API is under consideration. I've updated the roadmap to reflect this.
