### ISSUE TITLE
Document how this information will be used.

### ISSUE THREAD

**Issue by bbarry** [MicrosoftDocs/edge-developer#1235]
There should be a paragraph about how this email is used and a link to data retention and disposal policies. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe5c21b-2296-8b5c-208a-f41eb967c24e
* Version Independent ID: c3722063-7455-5ba9-a78d-102823dfd474
* Content: [Moving users to Microsoft Edge from Internet Explorer - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#request-an-update-to-the-ie-compatibility-list)
* Content Source: [microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for submitting this feedback. We have created a task on our backlog to make the suggested doc change. Hoping we can do it soon. I'm closing the issue for now as this is tracked somewhere else.

**Comment by captainbrosset** [comment]
Circling back on this. The email is only used for conversations with the IE compat list change requestor, which use the normal Microsoft retention policies.
I will make sure the page gets updated with this information.
