### ISSUE TITLE
Url matching semantics / wildcard support?

### ISSUE THREAD

**Issue by bbarry** [MicrosoftDocs/edge-developer#1236]
When determining if a url is in the list, does IE match the url exactly or will it match on all subdomains?

eg if `example.com` is in the list which of these would match:

* `https://example.com`
* `https://www.example.com`
* `https://extra.example.com`

Would the person sending the email specify a wildcard to match or every subdomain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe5c21b-2296-8b5c-208a-f41eb967c24e
* Version Independent ID: c3722063-7455-5ba9-a78d-102823dfd474
* Content: [Moving users to Microsoft Edge from Internet Explorer - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#request-an-update-to-the-ie-compatibility-list)
* Content Source: [microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jenny-microsoft** [comment]
Hi @bbarry, a rule will apply to all subdomains unless it's for a specific subdomain - in that case we will use the specified subdomain instead of the parent domain.
