### ISSUE TITLE
DOM7011 Documentation 

### ISSUE THREAD

**Issue by JonathanYiv** [MicrosoftDocs/edge-developer#124]
I am trying to get a website working in IE11 and came across DOM7011 - which stated "The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337"
This redirected to a page without the DOM7011 code documented. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e413c6-445b-30c6-b2f8-7959c9c4a759
* Version Independent ID: 57c3967d-f4b1-7ede-11fc-56772cf616ae
* Content: [Microsoft Edge DevTools - Console error and status codes - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console/error-and-status-codes?source=errorcode)
* Content Source: [microsoft-edge/devtools-guide/console/error-and-status-codes.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/console/error-and-status-codes.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
Thanks for reporting, @JonathanYiv! We'll get that updated. In the meantime, here's the page it should've pointed to: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/dn265017(v%3dvs.85)

**Comment by JonathanYiv** [comment]
Thank you!

**Comment by mattwojo** [comment]
Updated that redirect link.  Closing this out. :)
