### ISSUE TITLE
Issue with the web browser

### ISSUE THREAD

**Issue by SirnWilliam** [MicrosoftDocs/edge-developer#1249]
Hello Team,
Thanks for all the hard work and progress you guys are making.  When I use web browser  in windows form app, it works fine and display the page. The issue I am having is when I make a change to a specific page and reload the page, the new changes don't get shown on the page. I think this is related to cache. Is there way we can control this issue in the app itself?
Many thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Microsoft Edge WebView2 Control - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Apologies about the long delay replying. Have you found a solution to your problem? If not, I encourage you to go and ask on the WebView2Feedback repository here instead: https://github.com/MicrosoftEdge/WebView2Feedback
The current repository is for tracking the documentation content.
