### ISSUE TITLE
Cannot automate Application Guard Windows using webdriver or selenium related technologies.

### ISSUE THREAD

**Issue by Fangchao-Li** [MicrosoftDocs/edge-developer#1250]
[Enter feedback here]
Hi all seniors.
I am from Dell technology, shanghai, China.
We are working on the validation of microsoft edge, and application guard mode is included in our scope.
also we have finished automation for normal mode and inprivate mode for edge.
but when facing application guard mode, I find the edge process is included in windows defender application guard suite,
I cannot find a way to manipulate this application guard window using selenium and webdriver, so I am wondering how can I finish this job, maybe some configurations or some other work to make this happen.

You can also contact me through my enterprise email accout: Brian_Li@dell.com

Thanks,
Brian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver (Chromium) for test automation - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @Fangchao-Li , sorry to hear about this issue. I've checked with Engineering and they said that this scenario isn't supported today. Thank you.
