### ISSUE TITLE
Both Release and preview versions should be able to work on the same machine.

### ISSUE THREAD

**Issue by PoulBak** [MicrosoftDocs/edge-developer#1251]
[Angiv feedback her]
I have several STABLE programs on my computer using the STABLE version WebView2 runtime - all fine.
Now I want to experiment with new features of VebWiew2 released in the PRE-RELEASE version. So I download the newest pre-release version of WebView2 and install that in my new program.
To make that work, I download and install the CANARY build of Microsoft Edge.
However, when I run my program, it still tries to use the STABLE WebView2 runtime, which fails because it misses the new features.
I have to uninstall WebView2 runtime to make my new program work. THAT IS BAD in case of breaking changes - then the old programs won't work.

The solution is simple logic: The stable versions of WebView2 should prioritize the WebView2 runtime (as they do today), but the PRE-RELEASE version of WebView2 should prioritize Microsoft Edge CANARY, even when the runtime is installed.
(You can easily make this work by having a compiler directive in your code, that you change when releasing a stable version).

Now you can have stable programs on your machine while still being able to experiment with new features from the pre-release version of WbView2.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: e4e7761f-33b7-cdd5-2a03-dbe3ad9fab20
* Version Independent ID: 9ba37c84-78c0-5fb6-5f6a-22d6286add19
* Content: [Understand WebView2 SDK versions - Microsoft Edge Development](https://docs.microsoft.com/da-dk/microsoft-edge/webview2/concepts/versioning)
* Content Source: [microsoft-edge/webview2/concepts/versioning.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/concepts/versioning.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Sorry about the (very long) delay replying here. This repository is about the documentation of WebView2, not about WebView2 itself.
You will get more luck getting in touch with the team to investigate this issue by posting a new issue on the WebView2Feedback repository here: https://github.com/MicrosoftEdge/WebView2Feedback/issues
