### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/edge-developer#1259]
I go to https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
 and choose IE8 on Win7(x86) for VirtualBox and get 
 
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:d7abbb19-901e-0041-0b08-53a97e000000 Time:2021-05-27T14:58:30.3074248Z</Message>
</Error>

**Comment by DSPatrick** [comment]
Not sure why it would be closed? How will I know any status on this issue?

**Comment by Reezaali** [comment]
@DSPatrick - ok I'll reopen it. Thanks.

**Comment by DSPatrick** [comment]
Thank you, much appreciated.

**Comment by Reezaali** [comment]
Hi @DSPatrick - the error has been fixed. Thanks.

**Comment by DSPatrick** [comment]
Thank you
