### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by RezaT1994** [MicrosoftDocs/edge-developer#126]
App Image Generator is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcef5936-232e-1ab0-c1c4-77026c79e277
* Version Independent ID: b6ec450d-ead9-ffcf-0d5b-7a408bf0e13d
* Content: [Get started with Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/get-started)
* Content Source: [microsoft-edge/progressive-web-apps/get-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/get-started.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
Ack! Looks like the link changed--here's the correct destination: https://www.pwabuilder.com/imageGenerator

I'll update the doc now...

**Comment by erikadoyle** [comment]
Fixed now. Thanks @RezaT1994 !
