### ISSUE TITLE
Code samples for javascript with selenium 4 don't make sense.

### ISSUE THREAD

**Issue by chrisfcarroll** [MicrosoftDocs/edge-developer#1266]
using: "selenium-webdriver": "^4.0.0-beta.3"

The code sample starts with
```
let driver = edge.Driver.createSession(options);
```
but `edge` is not defined in selenium-webdriver and whilst selenium webdriver supports edge, it does not export any such symbol.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver (Chromium) for test automation - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @chrisfcarroll - sorry to hear about this issue. I contacted our Engineering team and they will put together a code sample and reply on this issue when it's ready.

**Comment by zoherghadyali** [comment]
Hi @chrisfcarroll! Thanks for the feedback! With Selenium 4, you should be able to access the `edge` object by adding this `require` statement at the top of your test script:

```javascript
const edge = require('selenium-webdriver/edge');

let options = new edge.Options();
//example way you may use the edge.Options object
options.setBinaryPath("C:\\Program Files (x86)\\Microsoft\\Edge Dev\\Application\\msedge.exe");

let driver = edge.Driver.createSession(options);
```
Please give that a try and let us know how that goes for you! Currently, we use the same set of code samples across both Selenium 3 and Selenium 4 but Selenium 3 requires additional imports to support the Chromium-based Microsoft Edge so we didn't include the `require` statements in our JavaScript samples.
