### ISSUE TITLE
In MS Edge IE Mode, Selenium webdriver always shows WindowHandles.Count as '0'

### ISSUE THREAD

**Issue by csharsha** [MicrosoftDocs/edge-developer#1270]
When using IEDriverServer.exe with C# to launch MS Edge in IE Mode, when clicking on a button in my application which closes the current window and opens a new window, I noticed that when we tried get driver.windowhandles.count it is returning always 0.

**To Reproduce**
Detailed steps to reproduce the behavior:

I have used the following code to open MS Edge in IE Mode.

``var ieService = InternetExplorerDriverService.CreateDefaultService(requiredDirPath, iedriverexefilename);``
`var ieOptions = new InternetExplorerOptions();`
`ieOptions.AddAdditionalCapability("ie.edgechromium", true);`
`ieOptions.AddAdditionalCapability("ie.edgepath", @"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe");`

`driver = new InternetExplorerDriver(ieService, ieOptions, TimeSpan.FromSeconds(30));`

`driver.Navigate().GoToUrl(APP_URL);`
`driver.FindElement(By.XPath("//input[@dikey='txtUserName']")).SendKeys(strUsername);`
`driver.FindElement(By.XPath("//input[@dikey='txtPassword']")).SendKeys(strPassword);`

`//Click on Login button`
`driver.FindElement(By.Id("iC_C_C8").Click`

`WebDriverWait waitForIE = new WebDriverWait(driver, TimeSpan.FromSeconds(10));`
`waitForIE.Until((d) => d.WindowHandles.Count > 0);`
`int count = driver.WindowHandles.Count;`

**Expected behavior**
driver.WindowHandles.Count always returns '0' after login button is clicked

**Test script or set of commands reproducing this issue**
I have attached the page source code. After clicking on login button, the page is submitted using javascript "document.Logon.Submit();" which closes the login window and opens a home page.

**Environment**
OS: Windows 10 2019 (version 1909)
Browser: MS Chromium Edge
Browser version: 88.0.705.74
Browser Driver version: IEDriverServer.exe 3.150.1.0
Language Bindings version: C#

An issue is raised in Selenium GitHub, is there any chance we can get solution for this? [#8868](https://github.com/SeleniumHQ/selenium/issues/8868)

[HTMLContent_LogonPage.txt](https://github.com/MicrosoftDocs/edge-developer/files/6591773/HTMLContent_LogonPage.txt)

**Comment by objectpython** [comment]
Guys, any updates on this? I am also getting same issue. Due to this, selenium is unable to work with child windows as it is unable to detect it.

**Comment by captainbrosset** [comment]
This does not appear to be an issue with the docs content (which this repo is about), but rather an issue with the driver. So let me ping @bwalderman as he may be able to help solve this, and if not at least redirect the issue to the right place.

**Comment by captainbrosset** [comment]
Closing as this isn't a docs problem, but this can still be used to discuss the particular problem that was reported.
