### ISSUE TITLE
Link to "Microsoft Edge Driver" is bad

### ISSUE THREAD

**Issue by LarsLiden** [MicrosoftDocs/edge-developer#1271]
Documentation page:
https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp

Bad Link URL:
https://developer.microsoft.com/microsoft-edge/tools/webdriver

Leads to:
Sorry, something went wrong. Please try again later.
CorrelationID: 30c12654-123d-4a8e-b830-0563059ddf67
Correlation Vector: u8bs4lsGMUSjXOlt.0
App Server: 
Date: 03 Jun 2021 20:01:53 +00:00

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver (Chromium) for test automation - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@LarsLiden - sorry to hear about this issue. Looks like the error got resolved. I'll go ahead and close this issue now. Thanks.
