### ISSUE TITLE
Export as HAR not available

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/edge-developer#128]
As per https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/network#toolbar
Item 2 Export as HAR
on my Edeg v 42.17134.1.0
Export as HAR , even via ctrl-S
is not available in Developer Tools.
URL testing with is: https://docs.microsoft.com/en-us/search/index?search=nvarchar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5159b00-45b5-2f33-6d5c-32f3d4aaab4b
* Version Independent ID: 212d758e-af0c-6058-873d-1393ddc1212d
* Content: [Microsoft Edge DevTools - Network - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/network)
* Content Source: [microsoft-edge/devtools-guide/network.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/network.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by libbymc** [comment]
Hi @OzBob - I'm not able to repro this issue on the same build. Would you mind filing a product bug (click on the smiley face in the DevTools to open Windows Feedback Hub) with your exact repro steps and a screenshot? Thanks!

**Comment by OzBob** [comment]
Restarted and tried to replicate myself.  Can't replicate now.
