### ISSUE TITLE
Opening PDF file in  webview2 control

### ISSUE THREAD

**Issue by TimKadyrov** [MicrosoftDocs/edge-developer#1285]
When I pass URL to PDF file, wv2 first downloads it and then user need to select what to do with it. 
If selection is made to open it in viewer - it will be opened in a new wv2 window, and not in the one embedded in application.

Is it possible to control somehow that downloaded PDF is automatically opened in wv2 control which received this download link?

Very much appreciated.

**Comment by Reezaali** [comment]
Hi @TimKadyrov, can you ask your question about WebView2 on the WebView feedback repo at the following link? The Engineering team responds to customer questions on that repo.

https://github.com/MicrosoftEdge/WebView2Feedback

**Comment by TimKadyrov** [comment]
ok, thanks
