### ISSUE TITLE
NavigationCompleted event not getting triggered in WebView2 control

### ISSUE THREAD

**Issue by 611970846** [MicrosoftDocs/edge-developer#1288]
Our application is a windows forms application where we use webBrowser control to load a third party website.

We are in the process of migrating webBrowser control to WebView2 control.

For a specific scenario, the 3rd party website appends few query string parameters to the existing url without reloading the page, which is triggering DocumentCompleted Event in case of WebBrowser control. But in WebView2 control, NavigationCompleted Event is not getting triggered for this scenario.

Can you let us know how to resolve this issue.

**Comment by Reezaali** [comment]
Hi @611970846 - can you post your issue on the Engineering repo located at the link below, where they answer these types of questions?

https://github.com/MicrosoftEdge/WebView2Feedback
