### ISSUE TITLE
PWA support on Windows 8.1

### ISSUE THREAD

**Issue by taisino** [MicrosoftDocs/edge-developer#1292]
According to the following context, PWA isn't supported on Windows 8.1. But PWA is working on Windows 8.1. Is PWA really unsupported on Windows 8.1?
----------
Desktop PWAs are supported on any of the platforms Microsoft Edge (Chromium) is available. Microsoft Edge (Chromium) is available on Windows 7, Windows 10, and macOS. The following benefits are included.
----------
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55284993-672a-b950-38ec-f3e175dfbf93
* Version Independent ID: 0617203d-5c57-037e-74b9-11c025917d07
* Content: [Progressive Web Apps on Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by vchapel** [comment]
Resolved with new content: "Desktop PWAs are supported on any of the platforms Microsoft Edge (Chromium) is [available](https://www.microsoft.com/edge)." On page [https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/)
