### ISSUE TITLE
How to integrate the Blazor webassembly in WPF (webview2)

### ISSUE THREAD

**Issue by venkakat83** [MicrosoftDocs/edge-developer#1302]
Currently we have web application running on Angular. And we would like to integrate angular based web component into existing windows based desktop application.

Our main functionality:-

1) Angular Component and Desktop app should communicate each other.

Can some one provide some insights to work on? will this can be achieved with integrating the Blazor webassmebly into webview2 ? If yes, please guide and kindly share if we have any demo project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Microsoft Edge WebView2 Control - Microsoft Edge Development](https://docs.microsoft.com/en-in/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @venkakat83 - can you open an issue on the following webview 2 feedback repo where the engineering team responds to these types of questions: 
https://github.com/MicrosoftEdge/WebView2Feedback
Thanks.

**Comment by venkakat83** [comment]
@Reezaali Thanks requested at https://github.com/MicrosoftEdge/WebView2Feedback
