### ISSUE TITLE
Documentation grammatical error

### ISSUE THREAD

**Issue by jd3nn1s** [MicrosoftDocs/edge-developer#1308]
Sentence structure incorrect: "The script injection APIs (and some other WebView2 APIs) are asynchronous, you should use callbacks **if code is must be** run in a specific order."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0f291fb-5bcf-0319-da09-ca1a2dc9b023
* Version Independent ID: d96ef94e-4a68-0671-bb38-47bde4035be9
* Content: [Get started with WebView2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32)
* Content Source: [microsoft-edge/webview2/get-started/win32.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/get-started/win32.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by ericlaw1979** [comment]
Drop "is"

**Comment by Reezaali** [comment]
Thanks, we updated the doc.
