### ISSUE TITLE
haw registration my console xbox one x for devolaper

### ISSUE THREAD

**Issue by Sleeplikelion** [MicrosoftDocs/edge-developer#131]
i can't 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7708ebf-b89b-168e-de02-bb00e9223318
* Version Independent ID: 48a20484-21fe-cbd3-7b84-f1992002eb63
* Content: [Microsoft Edge Developer Tools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide)
* Content Source: [microsoft-edge/devtools-guide.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
Sounds like you might be looking for the Xbox developer center: https://www.xbox.com/en-US/developers/

Hope that helps.
