### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jviseur** [MicrosoftDocs/edge-developer#1316]
Hi,

I have spent a large amount of time in seeing if there is a solution to my problem and have not been able to do so

Set up the event webView21.NavigationCompleted += WebView21_NavigationCompleted;

The method private void WebView21_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
{} works but if I use the method private async void WebView21_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e){} the event is no longer executed

Are you able to give me a pointer on how I can solve that issue

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Microsoft Edge WebView2 Control - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/webview2/#getting-in-touch-with-the-microsoft-edge-webview-team)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Apologies for the long delay in answering.

Note that this repository is for the Edge developer documentation. Not for the products themselves.
So you will get more traction by posting your question on the dedicated WebView2 feedback repository here: https://github.com/MicrosoftEdge/WebView2Feedback/issues

So, I'm closing this issue now. But please feel free to re-open one if there is an issue with the documentation.
