### ISSUE TITLE
7 business days for extension review!!!

### ISSUE THREAD

**Issue by gitgitwhat** [MicrosoftDocs/edge-developer#1319]
Firefox approves new extensions in minutes.  Google may take up to a day or so.  What the *@!k takes seven business days to approve?  Do better Microsoft.  The signup process to the Edge store is painful enough.  Don't turn devs away by a slow and opaque review process.

**Comment by Reezaali** [comment]
Hi @gitgitwhat - thanks for the feedback. Can you send this feedback using Edge by selecting the following menu items?
... > Help and Feedback > Send Feedback 
Thanks.
