### ISSUE TITLE
Debugging IE mode after IE app EOL

### ISSUE THREAD

**Issue by mgol** [MicrosoftDocs/edge-developer#1320]
After the [recent announcement of the IE 11 EOL](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/) it's not clear how to debug issues occurring only in the legacy Trident engine. The [IE mode page](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/ie-mode/) mentions DevTools don't work in IE mode and the full IE app needs to be open.

Those two messages seem to suggest there will be no way to debug pages opening in IE mode once IE is removed from Windows. Is that the case?

I'd expect this page to address these questions, I'm sure I'm not the only one wandering what will happen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7754210-02b0-6d3b-0405-e84b8b926c52
* Version Independent ID: 51551106-f219-09b0-5d6e-755115705f33
* Content: [Internet Explorer mode and the DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/ie-mode/)
* Content Source: [microsoft-edge/devtools-guide-chromium/ie-mode/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/ie-mode/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for opening this issue. You are correct, the instructions to use IE don't make sense anymore in light of the recent announcements.
The page has been updated with new instructions to use IEChooser as a way to debug issues with IE Mode pages:

> If Internet Explorer 11 is not available, such as on Windows 11, you can use IEChooser to launch the Internet Explorer DevTools to debug the content of your IE mode tabs. To use IEChooser, perform the following steps.
> Open IEChooser.
> Open the Run dialog box. For example, press the Windows logo key + R.
> Enter %systemroot%\system32\f12\IEChooser.exe, and then select Ok.
> In IEChooser, select the entry for the IE mode tab.

Closing this issue now as I think this addresses what you were asking. Please feel free to let me know if not.

**Comment by mgol** [comment]
That's clear to me now, thanks! I didn't know about IEChooser before.
