### ISSUE TITLE
Only absolute URI is allowed

### ISSUE THREAD

**Issue by GarryLowther** [MicrosoftDocs/edge-developer#1321]
This control does not work in VB.Net WinForms

Even setting the Source at design-time does not work.
Trying to set it to blank results in this design-time error:

Only absolute URI is allowed
Parameter name: Source

A rather poorly implemented control not worthy of a place amongst the decades-old tried and tested WinForms controls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ba6a76-eb0b-e8f2-dfc9-d2c0df6261a4
* Version Independent ID: 8d62fdee-f44a-3d40-6800-04d7bd6193f8
* Content: [Get started with WebView2 for WinForms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms)
* Content Source: [microsoft-edge/webview2/get-started/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/get-started/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by TriSysBusinessSoftware** [comment]
![webview-2-fail-2](https://user-images.githubusercontent.com/5684253/124743874-15073300-df16-11eb-80dd-d86a66d99504.png)

**Comment by captainbrosset** [comment]
After re-reading this issue, it does not seem to be about the documentation of WebView2 (which this repository is about), so closing this issue now. You can send your feedback to the WebView2 team via this repository: https://github.com/MicrosoftEdge/WebView2Feedback
