### ISSUE TITLE
I'm not noticing the password visibility toggle for inputs in Edge for MAC 

### ISSUE THREAD

**Issue by spacejamjim** [MicrosoftDocs/edge-developer#1335]
I think this documentation should specify (verify if I'm wrong here) that this is only displaying for windows. 
Version 91.0.864.67 (Official build) (x86_64)
catalina: 10.15.7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5949a483-1a4d-0f77-5576-af0a335fc959
* Version Independent ID: 824cf57c-044d-9dac-085a-8bcfd6f2dc15
* Content: [Customize the password reveal button - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal)
* Content Source: [microsoft-edge/web-platform/password-reveal.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/password-reveal.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
You are right, I didn't know this myself, but indeed I'm not seeing the password reveal button on Mac.
@melanierichards could you please confirm that this is the case?

**Comment by melanierichards** [comment]
Hi @spacejamjim and @captainbrosset, the password reveal button is supported in Edge on MacOS. If you're not able to view the button by typing some text into the password field [on this MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password), would you mind filing a bug from the browser using the "Settings and more" menu > Help and Feedback > Send Feedback tool? I'm not able to repro this issue but having a report in the system will help us investigate further.

You may also want to first validate that edge://settings/passwords => "Show the 'reveal password' button in password fields" setting is toggled ON.

**Comment by captainbrosset** [comment]
Thanks @melanierichards. I am able to see the button on this page. I was previously testing on the login page for twitter, and I'm guessing they are hiding it on this page.

**Comment by captainbrosset** [comment]
I will close the issue now, since it's been inactive for a while. @spacejamjim feel free to follow Melanie's instructions to send feedback to us via the Feedback tool in the browser if this still happens to you.
