### ISSUE TITLE
“To do this you can use the MakePRI tool which is included with the Windows 10 SDK.”

### ISSUE THREAD

**Issue by PoziWorld** [MicrosoftDocs/edge-developer#134]
Hi there, 

It will be a welcome addition if you specify where to get the SDK and what SDK components are required to be installed to get the tool.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d0abd6-37a3-3f4c-066f-4018f432919c
* Version Independent ID: 310108f1-d468-6634-238b-e9d75a305a6e
* Content: [Extensions - Localizing extension packages - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/packaging/localizing-extension-packages#creating-the-resources-file)
* Content Source: [microsoft-edge/extensions/guides/packaging/localizing-extension-packages.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/packaging/localizing-extension-packages.md)
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by erikadoyle** [comment]
Thank you @PoziWorld, great suggestion! Working on that now....in the meantime, here's where to get the Windows SDK: https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk . Once downloaded, you can find the makepri utility here: 

%ProgramFiles(x86)%\Windows Kits\10\bin\<target Win10 version>\<target architecture>\makepri.exe

**Comment by PoziWorld** [comment]
@erikadoyle, thank you for your quick reply.

> what SDK components are required to be installed to get the tool

I was referring to the step during installation where one is supposed to choose the features of the SDK:
<img src="https://user-images.githubusercontent.com/5961162/43115674-7c72c17c-8eb9-11e8-9b4d-b1d44770b277.png" width="250" height="188" alt="Windows SDK: Select features you want to download">

It'd be good to know which one(s) contains MakePRI, so that there is no need to download and install the whole thing.

**Comment by mattwojo** [comment]
Hi @PoziWorld -- Yes, you should just need the "**Windows SDK for UWP Managed Apps**" feature.  

We think that the "WIndows SDK for UWP Apps Localization" is the multi-lingual toolkit helpers and not needed for this use-case, but I'll try to dig into it deeper to make sure... or if you try just downloading that single SDK feature and have any trouble, please let us know!

**Comment by mattwojo** [comment]
Of course -- I'll be sure to add this specification to the doc. Thanks for the contribution!

**Comment by mattwojo** [comment]
Updated: https://github.com/MicrosoftDocs/edge-developer/commit/71266b1db5703e6326448088052a4c832e4d7cbf 
Closing this issue.
