### ISSUE TITLE
Code is missing

### ISSUE THREAD

**Issue by lukacat10** [MicrosoftDocs/edge-developer#1341]
This page is giving only part of a code, understanding what's going on is extremely difficult.

My only clue was this: [https://github.com/arsher/WebView2GettingStarted/blob/master/WebView2Sample/HelloWebView.cpp](url)

And even this code is missing key features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0f291fb-5bcf-0319-da09-ca1a2dc9b023
* Version Independent ID: d96ef94e-4a68-0671-bb38-47bde4035be9
* Content: [Get started with WebView2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32)
* Content Source: [microsoft-edge/webview2/get-started/win32.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/get-started/win32.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for the feedback!
@jasonstephen15 do you think the whole code could be made available as a download link on the page?

**Comment by jasonstephen15** [comment]
Yes, the full demo app code lives here: https://github.com/MicrosoftEdge/WebView2Samples/tree/master/GettingStartedGuides/Win32_GettingStarted

I agree we should make this more apparent in the document. Will create a PR for that!

**Comment by lukacat10** [comment]
Thank you for taking documentation seriously. Much appreciated.

**Comment by captainbrosset** [comment]
@vchapel you mentioned this issue in your PR #1442, does that mean this PR fixes this issue? 
Please let me know and if so, I'll close this.

**Comment by vchapel** [comment]
Yes, 1442 fixed this issue, thanks!
