### ISSUE TITLE
Please fix spelling...

### ISSUE THREAD

**Issue by AlanR2** [MicrosoftDocs/edge-developer#1343]
Please fix the spelling error in "Add a declaration to an existing rulest in DevTools" - it should be "ruleset", not "rulest".

- It is an excellent tutorial, thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d236a87-dbb2-6330-23a8-c88eb641c12a
* Version Independent ID: 514f72b6-b104-ee3e-a982-98510467422e
* Content: [DevTools for beginners: Get started with CSS - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/beginners/css)
* Content Source: [microsoft-edge/devtools-guide-chromium/beginners/css.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/beginners/css.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for the feedback. I will fix the typo.
