### ISSUE TITLE
input type password and the auto-reveal

### ISSUE THREAD

**Issue by astigmatik** [MicrosoftDocs/edge-developer#1345]
While this is a great idea, it is also quite annoying. It is not easy to spot especially when you start developing in another browser, and when you test your pages on MS Edge, you wonder why there's an extra eye in there and you'd think that the bug is on your code (or MY code). So, I had to sift through my Javascript files and wonder what went wrong. Luckily, it only took me a short while to figure it out. But, still an annoying feature for devs whose default browsers are not MS Edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5949a483-1a4d-0f77-5576-af0a335fc959
* Version Independent ID: 824cf57c-044d-9dac-085a-8bcfd6f2dc15
* Content: [Customize the password reveal button - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal)
* Content Source: [microsoft-edge/web-platform/password-reveal.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/password-reveal.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for the feedback @astigmatik.
This feedback is interesting for the browser implementation team. This repository is just for documentation. So I'll forward it to the right people.
If you do get a change though, I'd love to hear more from you about what experience you'd prefer. You did say that this was a great idea, so I'm guessing you still welcome the feature. What would help make it less annoying?
