### ISSUE TITLE
NO

### ISSUE THREAD

**Issue by stijnhommes** [MicrosoftDocs/edge-developer#1346]
Stop this incessant spam and tell us how to block PWAs from accessing our system.
Since you don't bother requiring PWAs to be properly named in app stores, there is no way to properly boycott this crap without switching to Linux and Firefox.

Give people an option to avoid this PWA crap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55284993-672a-b950-38ec-f3e175dfbf93
* Version Independent ID: 0617203d-5c57-037e-74b9-11c025917d07
* Content: [Progressive Web Apps on Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Hello @stijnhommes. This kind of tone is not going to help move your request forward at all. Please bring constructive feedback and be accepting of other points of view. Please do go through our [code of conduct](https://opensource.microsoft.com/codeofconduct).
I will be closing this issue for the time being. Feel free to open a new one with a more specific description of what documentation changes you are requesting, and utilizing a more professional, kind, and respectful tone.
