### ISSUE TITLE
Please offer an option to block PWAs and remove the icons related to 

### ISSUE THREAD

**Issue by stijnhommes** [MicrosoftDocs/edge-developer#1348]
1. I'm looking for the options to remove the install PWA icon from the address bar and the browser menu in Edge.
2. I'm also looking for a way to recognize PWAs on the app stores (Google, Microsoft, etc) to avoid accidentally installing one.

**Comment by captainbrosset** [comment]
Thank you for your feedback. I just forwarded it to the Edge team so they can take it into consideration.
I'll close this issue since this repository is about documentation of Edge and related technologies.
