### ISSUE TITLE
Certutil -addStore TrustedPeople MyKey.cer

### ISSUE THREAD

**Issue by PoziWorld** [MicrosoftDocs/edge-developer#135]
Hi there,

This article links to https://docs.microsoft.com/en-us/windows/desktop/appxpkg/how-to-create-a-package-signing-certificate, which says “MakeCert.exe is deprecated. For current guidance on creating a certificate, see Create a certificate for package signing” and links to https://docs.microsoft.com/en-us/windows/uwp/packaging/create-certificate-package-signing, which doesn't have any info about the MyKey.cer file that you reference in “Certutil -addStore TrustedPeople MyKey.cer”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d5f8503-00e3-1b62-0912-0789ae732d38
* Version Independent ID: 8e273172-c25a-0fdf-0d10-3cd9aa3f542c
* Content: [Extensions - Creating and testing extension packages - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages#testing-an-appx-package)
* Content Source: [microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages.md)
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by mattwojo** [comment]
Thanks @PoziWorld. I just took a look through and agree that this is a bit confusing. Getting some help and digging in a bit deeper... I'll replying again once I have a better handle on what's happening.

**Comment by gebansal** [comment]
@PoziWorld, @mattwojo Considering its an old thread and we have rolled out a new Chromium-based Edge browser, I'll go ahead and close it. If you still are facing any issues, please feel free to reopen this issue or file a new one.
