### ISSUE TITLE
What VS project template is the one used here?  

### ISSUE THREAD

**Issue by wildough57** [MicrosoftDocs/edge-developer#1350]
As far as I can tell, there is no project template that magically gives you the project used to illustrate this article.  

The one shown in the article is described as including pretty much every possible variation.  Meanwhile, the actual templates provided (VS 2019 Enterprise 16.10.3) are specific to a particular target i.e. React, Angular, MVC, Web API.

So this ends up being another 'all you have to do' that turns into a major time suck.  It's really annoying trying to get my example to match your example.  Maybe provide your Project for download because I see nothing that doesn't involve an hour or two of messing around. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4538b351-b450-e104-3f5c-76bd9c5233e9
* Version Independent ID: 700de4b5-e02b-8914-c0a6-0ab604025e1f
* Content: [Visual Studio - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/visual-studio/)
* Content Source: [microsoft-edge/visual-studio/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/visual-studio/index.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
You are right, sorry about the bad experience. It looks like the templates are now divided per framework. We need to update this documentation page accordingly. I'll give it a shot.
