### ISSUE TITLE
There are no constructor takes 2 arguments

### ISSUE THREAD

**Issue by superbull** [MicrosoftDocs/edge-developer#1352]
EdgeOptions edgeOptions = new EdgeOptions(false, "webview2");

![image](https://user-images.githubusercontent.com/455630/126579370-c603edf1-1a02-4a93-a55e-b834bd29df52.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 758ec47a-0630-ed93-b312-66cc2c6f48d5
* Version Independent ID: 6b666839-119d-433e-8756-0089378b5269
* Content: [Automating and Testing WebView2 with Microsoft Edge Driver - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver)
* Content Source: [microsoft-edge/webview2/how-to/webdriver.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/how-to/webdriver.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jasonstephen15** [comment]
Hi @superbull - in the sample code we suggest to instantiate EdgeOptions like this:
![image](https://user-images.githubusercontent.com/22718545/127404381-0820c0db-517f-4028-95d3-45c9b5d10e7c.png)

I think we might have made this doc update after you created the PR, but let me know if this is still a current problem with the doc.
