### ISSUE TITLE
Documentation for command line switches

### ISSUE THREAD

**Issue by mikernet** [MicrosoftDocs/edge-developer#1354]
Not sure if I'm just blind but I looked everywhere and I can't find documentation for Edge command-line switches. Am I missing something or have they not been documented yet?

**Comment by captainbrosset** [comment]
Oh, interesting. Indeed there does not seem to be a page that references *all* possible command line switches.
There appears to be a number of pages that document specific switches like:

* https://docs.microsoft.com/en-us/deployedge/edge-learnmore-cmdline-options-proxy-settings
* https://docs.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode
* https://docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/debugger-for-edge

So depending on what you want to do, there might be a page that has documentation about it.
Is there a specific thing you'd want to do with a command line switch? Or are you looking for a page that documents them all?

**Comment by mikernet** [comment]
I was looking for a list of all possible switches so I could explore the options available.

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thank you.
