### ISSUE TITLE
Not able to download service worker files. the URL is a blank page

### ISSUE THREAD

**Issue by zeshhaan** [MicrosoftDocs/edge-developer#1357]
[Enter feedback here]

To install service worker, the docs asks to go to this [URL](https://www.pwabuilder.com/serviceworker) and download couple files but the page is blank
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18b321d1-e8fa-e95a-3345-1407b585cc63
* Version Independent ID: def7c23d-f888-3ab6-60a3-95ebb27cc807
* Content: [Get started with Progressive Web Apps (Chromium) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/get-started)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/get-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-chromium/get-started.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**
https://www.loom.com/share/976bc48d9a93482e8ee2197ce6f926ba

**Comment by captainbrosset** [comment]
Thanks for the feedback. Indeed the link is broken. I filed an issue about it a few days ago, so I will close this one since it's a duplicate. See #1351.

**Comment by zeshhaan** [comment]
Thank you! And my bad that i didn't check the existing issue before making one. Thanks again for looking into it.
