### ISSUE TITLE
Is there any way to use developer tools in IE mode?

### ISSUE THREAD

**Issue by moong78** [MicrosoftDocs/edge-developer#1361]
I still need to use the EdgeBrowser in IE mode for old website management.
IE mode is not able to use developer tools, so I am uncomfortable debugging.
Is there any way to use developer tools in IE mode?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7754210-02b0-6d3b-0405-e84b8b926c52
* Version Independent ID: 51551106-f219-09b0-5d6e-755115705f33
* Content: [Internet Explorer mode and the DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/ie-mode/#remote-debugging-and-ie-mode)
* Content Source: [microsoft-edge/devtools-guide-chromium/ie-mode/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/ie-mode/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
IE mode-rendered websites use an older rendering engine that the new developer tools don't work with. There are 2 ways available to you to debug your website:

* either use Internet Explorer to open this site and use the IE built-in tools,
* or use Edge in IE mode and then use the IEChooser app to debug the site as described on this page: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/ie-mode/#launching-the-devtools-on-a-tab-in-ie-mode

> If Internet Explorer 11 is not available, such as on Windows 11, you can use IEChooser to launch the Internet Explorer DevTools to debug the content of your IE mode tabs. To use IEChooser, perform the following steps.
> Open IEChooser.
> Open the Run dialog box. For example, press the Windows logo key + R.
> Enter %systemroot%\system32\f12\IEChooser.exe, and then select Ok.
> In IEChooser, select the entry for the IE mode tab.

Let me know if this works for you. Closing this issue for now.

**Comment by moong78** [comment]
Thank you sooooooo~~~ much.
It was a great help to me.
