### ISSUE TITLE
Web driver page broken link

### ISSUE THREAD

**Issue by kvallecillog** [MicrosoftDocs/edge-developer#1369]
[Web driver page not accessible in the following link https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver (Chromium) for test automation - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@kvallecillog - thanks for reporting this. I've forwarded to the Engineering team.

**Comment by Reezaali** [comment]
@kvallecillog - Looks like it's working again. Can you try again? Thanks!
