### ISSUE TITLE
Add Info on Opening Console ; Address Messy "Shortcuts" Table

### ISSUE THREAD

**Issue by sirredbeard** [MicrosoftDocs/edge-developer#137]
This is the first result for most searches on how to launch the console in Edge and yet it does not actually tell you how to do that. That should be added.

Also the "Shortcuts" section is a bit of a mess. A markdown mistake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462f093f-9486-8086-da81-c689b7ef7d9e
* Version Independent ID: 0424a5af-15a6-1ccd-5732-12edb757838a
* Content: [Microsoft Edge DevTools - Console - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console)
* Content Source: [microsoft-edge/devtools-guide/console.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/console.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by mattwojo** [comment]
Thanks @sirredbeard! Corrected these issues. :) 
https://github.com/MicrosoftDocs/edge-developer/pull/140
