### ISSUE TITLE
Tab control is broken  (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/edge-developer#1376]
ja-jp:"https://docs.microsoft.com/ja-jp/microsoft-edge/webview2/how-to/debug?tabs=devtools"
![how-to_debug_j](https://user-images.githubusercontent.com/40815708/128452704-eabbd1a5-8efd-41ff-9226-7b80adc9e483.png)

en-us:"https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug?tabs=devtools"
![how-to_debug_e](https://user-images.githubusercontent.com/40815708/128452708-6b9b3e48-a4d1-40b1-9e0d-56bb5f611e13.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89a5d7-546f-70dc-d4c5-708071cf45bb
* Version Independent ID: f5da9a41-3346-d7a2-3355-e25cc1e846fc
* Content: [Get started debugging WebView2 applications - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug?tabs=devtools)
* Content Source: [microsoft-edge/webview2/how-to/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/how-to/debug.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for filing. I will investigate the issue.

**Comment by captainbrosset** [comment]
The DOM structure is incorrect in ja-jp:

![image](https://user-images.githubusercontent.com/1152698/128496495-4edf8f3f-2071-4043-8384-4a017af5cdfa.png)

Compared to the DOM in en-us:

![image](https://user-images.githubusercontent.com/1152698/128496552-85de9cea-39f8-4db7-83e4-0f044a045b12.png)

**Comment by captainbrosset** [comment]
@mikehoffms do you know where the code for the docs website is? I think we should open an issue there.

**Comment by hyoshioka0128** [comment]
@captainbrosset  - Thanks. zh-cn is also broken.
zh-cn:"https://docs.microsoft.com/zh-cn/microsoft-edge/webview2/how-to/debug?tabs=devtools"
![how-to_debug_z](https://user-images.githubusercontent.com/40815708/128500571-f3bc2a48-756c-47ca-89b0-bd520be4085b.png)

**Comment by mikehoffms** [comment]
4 .md files in the repo contain the tagging "](#tab/"   They are all broken, in ja-jp.

A "workaround" to switch tabs in ja-jp (useful for troubleshooting):
1. Go to the ja-jp URL.  Note end of url, which is for a particular tab.
2. Change url to en-us.
3. Click the desired tab.  Note end of url, which is for a particular tab.
4. Change url to ja-jp.

"Open Microsoft Edge DevTools"
https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/open/?tabs=cmd-Windows 
https://docs.microsoft.com/ja-jp/microsoft-edge/devtools-guide-chromium/open/?tabs=cmd-Windows 

"Native messaging"
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging?tabs=windows
https://docs.microsoft.com/ja-jp/microsoft-edge/extensions-chromium/developer-guide/native-messaging?tabs=windows 

"Use WebDriver (Chromium) for test automation"
https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp 
https://docs.microsoft.com/ja-jp/microsoft-edge/webdriver-chromium/?tabs=c-sharp 

"Get started debugging WebView2 apps"
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug?tabs=devtools 
https://docs.microsoft.com/ja-jp/microsoft-edge/webview2/how-to/debug?tabs=devtools 
The PR's file.

**Comment by mikehoffms** [comment]
@captainbrosset - Please see this bug I logged.  I went to the Doc Contributor Guide, signed in, clicked Edit, clicked Issues, Create New Issue.   
https://github.com/MicrosoftDocs/docs-help-pr/issues/5121
