### ISSUE TITLE
Broken PWA Builder link

### ISSUE THREAD

**Issue by IAmHopp** [MicrosoftDocs/edge-developer#138]
The first line on the Current availability table is pointing to a broken page on the PWA Builder website. It's probably from an old version of the website, specially judging by the styling, since it's almost impossible to spot the white links in the light gray background of that error page.

The right link is probably just the main page of the website.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31da9c54-4efd-6f71-1ef3-67d796c71cb4
* Version Independent ID: eb5e84cd-b850-fa16-a8b2-5900d6dce2ee
* Content: [Progressive Web Apps on Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps)
* Content Source: [microsoft-edge/progressive-web-apps.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by mattwojo** [comment]
Thanks for pointing this out @IAmHopp! I've corrected the link.
