### ISSUE TITLE
WebView2 currently *does* support the .NET 5

### ISSUE THREAD

**Issue by Arkarr** [MicrosoftDocs/edge-developer#1381]
This doc (https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms) indicated that WebView2 is not supported by designer, but I just managed to drag-n-drop the component on the designer and was able to set a few properties.

What isn't supposed to work, exactly ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ba6a76-eb0b-e8f2-dfc9-d2c0df6261a4
* Version Independent ID: 8d62fdee-f44a-3d40-6800-04d7bd6193f8
* Content: [Get started with WebView2 for WinForms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms)
* Content Source: [microsoft-edge/webview2/get-started/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/get-started/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Apologies about the late reply. It seems like this page was updated in the meantime, and no longer mentions that designer isn't supported. So I will close this issue.
