### ISSUE TITLE
[Add-ons API] Test of feedback about the proposed API endpoints

### ISSUE THREAD

**Issue by mikehoffms** [MicrosoftDocs/edge-developer#1387]
This is a test/mock Issue, regarding the proposed Add-ons API which is open for review.  To arrive here, I went to https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api, then I clicked "Please submit your feedback as an Issue about the Add-ons API."

An actual question about this repo's Issues UI/template:
First I had to clear the following, which appears in the Issues template.  Is this normal?:
"The following references to versions older than the current Edge release version were detected: {{ env.CONTENT }}"

Regarding this endpoint, the overview section is:
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api#checking-the-status-of-a-package-upload
and the reference docs are at:
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#check-the-status-of-a-package-upload
It says _blah_ but should say _blah_ instead.
Should this endpoint be renamed as blah?

Some JSON, without triple backticks:
{
    "id": "{operationID}",
    "status": "FAILED",
    "message": "The package upload failed. Please fix the errors and make the request again.",
    "errors": [
       {
           "id": "MANIFEST_FILE_MISSING",
           "message": "Zip file must contain a manifest.json file."
       },
       {
           "id": "SIZE_LIMIT_EXCEEDED",
           "message": "Zip file size must not exceed 500MB."
       }
    ]
}

JSON with backticks:
```json
{
    "id": "{operationID}",
    "status": "FAILED",
    "message": "The package upload failed. Please fix the errors and make the request again.",
    "errors": [
       {
           "id": "MANIFEST_FILE_MISSING",
           "message": "Zip file must contain a manifest.json file."
       },
       {
           "id": "SIZE_LIMIT_EXCEEDED",
           "message": "Zip file size must not exceed 500MB."
       }
    ]
}
```

-- end of test mockup Issue.

**Comment by mikehoffms** [comment]
This is a test reply Comment.

**Comment by mikehoffms** [comment]
I assigned this Issue to Ashish.

**Comment by mikehoffms** [comment]
I added some existing Labels to this Issue.

**Comment by ashishnirvana1** [comment]
Shall i close this isseu?

**Comment by mikehoffms** [comment]
Yes, thanks.
