### ISSUE TITLE
"Issues: New issue" contains "The following references to versions older than the current Edge release version were detected: env.CONTENT"

### ISSUE THREAD

**Issue by mikehoffms** [MicrosoftDocs/edge-developer#1395]
Repro steps: 

1. In Stable or Canary channel of Microsoft Edge, go to: https://github.com/MicrosoftDocs/edge-developer
2. Click the **Issues** tab.
3. Click **New issue**.

Actual result:  Text appears in the text edit box: "The following references to versions older than the current Edge release version were detected: {{ env.CONTENT }}"

Expected result: No text should be in the new Issue.

**Comment by captainbrosset** [comment]
This will be fixed by PR #1586.
