### ISSUE TITLE
Webview2 is unable to navigate to secure Google sites. Tried changing user agent string to no avail.

### ISSUE THREAD

**Issue by joedean3** [MicrosoftDocs/edge-developer#1396]
https://veamcast.com/veam.aspx?userid=cedf76f6ca144855b8e3c7b67b68e3c2&packageid=55c211596d8949c5abdf1a8d658f63c8&viewer=online+view&embed=true

Link above is video describing and demonstrating the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Microsoft Edge WebView2 Control - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Apologies about the very late reply. This repository is about the documentation of WebView2, not about the control itself. So I would suggest posting your question over on the WebView2Feedback repository, where you will find people that can help you with this particular issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues
