### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by freda-msft** [MicrosoftDocs/edge-developer#1400]
Both links to "WebView2 Windows Forms Browser - Code Samples" and "WebView2 API Sample - Code Samples" are giving 404 errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ba6a76-eb0b-e8f2-dfc9-d2c0df6261a4
* Version Independent ID: 8d62fdee-f44a-3d40-6800-04d7bd6193f8
* Content: [Get started with WebView2 for WinForms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms#getting-in-touch-with-the-microsoft-edge-webview-team)
* Content Source: [microsoft-edge/webview2/get-started/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/get-started/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
I cannot find these links anymore. It seems like the recommended content section got updated and those links were removed.
Closing the issue based on this. Feel free to re-open an issue if the problem persists.
