### ISSUE TITLE
Can you please add a new domain from Nvidia to user agent overrides? 

### ISSUE THREAD

**Issue by titooo7** [MicrosoftDocs/edge-developer#1407]
It would be great if you could add user agent overrides for https://play.geforcenow.com inside edge://compat/useragent

That would allow me to play GeForce Now using Edge browser on my Series X. Otherwise I have to shut it down and switch to a different device

**Comment by captainbrosset** [comment]
I don't know of a process to do this, but I will do some research and comment back here once I know.

In the meantime, you can always try to spoof the user agent string on this particular site by:
* either using an extension such as [user-agent switcher](https://microsoftedge.microsoft.com/addons/detail/useragent-switcher/npjnioaeoicmjokbdpfiecnbildopjad?hl=en-US)
* or using the Edge Developer Tools as [documented here](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/override-user-agent).

**Comment by titooo7** [comment]
thanks @captainbrosset 

Currently edge://compat/useragent  includes **geforcenow.com** on "User agent overrides" but that ignores **play.geforcenow.com**

Based on the testing I made with user-agent switcher extension on Windows 10, I came to the conclusion that if play.geforcenow.com was added to "User agent overrides" then the issue would fixed on Xbox Series X 

PS: unfortunately Edge on Series S/X doesn't support the extensions that's why I'm proposing this solution :)

**Comment by titooo7** [comment]
Resolved
