### ISSUE TITLE
“Open Microsoft Edge and verify that the strings defined for the locale appear as expected”

### ISSUE THREAD

**Issue by PoziWorld** [MicrosoftDocs/edge-developer#141]
Hi there,

Is it me or there seems to be a bug that prevents the strings defined for the locale to appear as expected?

I add a language, set it as default, log out, log back in, the locale is applied across the system, including Edge.
However, the locale is not applied to the extension. 

Tried disabling and enabling the extension, restarting the browser – it doesn't help.
However, uninstalling and installing extension fixes it.

The extension preserves the locale it was installed in. 
Tried both, loading extension from a folder and sideloading the appx.

And even if I change the locale a few times, log out and log back each time, the original locale is still preserved.

Microsoft Edge 42.17134.1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38d01093-c84f-f986-774b-33fccccf4eb8
* Version Independent ID: 2505d179-2f4b-92f6-2acf-d89f34ace911
* Content: [Extensions - Internationalization - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/internationalization)
* Content Source: [microsoft-edge/extensions/guides/internationalization.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/internationalization.md)
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by mattwojo** [comment]
Hmm... thanks @PoziWorld, did you check to ensure that there aren't any hardcoded URLs in the extension code?  I'm not sure of the answer to this... @balajikris can you help?

**Comment by PoziWorld** [comment]
@mattwojo, there are no hardcoded URLs.
It works fine in Chrome, Firefox, Opera, and Yandex.Browser.

**Comment by erikadoyle** [comment]
Update from @balajikris -- we were able to repro the issue and logged a bug to fix it. Closing the thread here, as this is a confirmed product (not documentation) bug.
