### ISSUE TITLE
Details about the Fixed Version runtime distribution mode

### ISSUE THREAD

**Issue by JaseRandall** [MicrosoftDocs/edge-developer#1413]
I've followed the Details about the Fixed Version runtime distribution mode instructions and get an error: Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews. ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

Can you please update the instructions to include a code example.  I need to deploy the WebView2 binaries onto a system for which I don't have administrator privileges so I don't have the option to use the non Fixed Version runtime approaches. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute a WebView2 app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Let's take the discussion over to the WebView2Feedback repo MicrosoftEdge/WebView2Feedback#1995.
Thanks!
