### ISSUE TITLE
TPM Attestation and Hardware Authenticator

### ISSUE THREAD

**Issue by pkuntal** [MicrosoftDocs/edge-developer#142]
Hi Guys,
Thanks for detailed write up about Microsoft support for FIDO.
I have been testing FIDO support in Windows 10 RS5 releases, currently using RS5 17713 for test setup (TPM2.0 supported device). I am unable to establish the fact whether "TPM' is being used while FIDO Registration/ Authentication or not.
I am setting 'attestation : "direct"' while calling create()  method for Registration, but when I checked WebAuthn Events for 'Ngc MakeCredential Response', AttestationFormatType comes as "none". Does it mean Windows Hello is not using TPM as Cryptographic engine?
I noted AAGUID as "08987058-CADC-4B81-B6E1-30DE50DCBE96" in MakeCredential Response which belongs to Hardware authenticator.  What does Hardware Autheticator mean if it is not using TPM? does it mean that it is using Match-in-sensor for biometrics verification?

Thanks,
Pooja

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cabf96-7b2b-9eb6-c428-ff4b44a97312
* Version Independent ID: 922d390b-52b6-db2a-0aab-f338e8c21b85
* Content: [Dev guide - Web Authentication - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication)
* Content Source: [microsoft-edge/dev-guide/windows-integration/web-authentication.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/windows-integration/web-authentication.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
@idamlaj, would you mind helping @pkuntal with these questions?

**Comment by idamlaj** [comment]
>> I am setting 'attestation : "direct"' while calling create() method for Registration, but when I checked WebAuthn Events for 'Ngc MakeCredential Response', AttestationFormatType comes as "none". Does it mean Windows Hello is not using TPM as Cryptographic engine?

TPM attestation may fail for a variety of reasons, but you can check AAGUID to see where the credential was stored. I created a pull request to update the documentation to make TPM vs non-TPM clearer. 

There is currently no way to determine where a biometric match is happening.
