### ISSUE TITLE
WebView Docs Do Not Explain How To View Local Content

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/edge-developer#1421]
The current WebView documentation does not explain how to load content from the local filesystem beyond single HTML files.

For example, if I build a React application, the builder outputs a directory with HTML, javascript, and other required assets. The current webview documentation does not cover navigating to the local directory in such a way where referenced assets (css, js, images, etc) are correctly loaded.

The `SetVirtualHostNameToFolder` helps with this, but the only way to find that it exists it to browse the CoreWebView2 .NET API. It also has significant limitations on addressing (for example, a single page application may assume it is loaded from '/', not '/index.html', causing the internal router to break). 

Most critically, there's no guidance provided on how to handle this scenario at all - how to adapt basic web apps working in Electron for WebView. This is strange, considering the documentation explicitly lists WebView as filling the same role as Electron. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99f63e2b-08f3-0123-0290-81ed8e9007a8
* Version Independent ID: ddea56f8-1ea4-ac98-1a18-00b107f46a3e
* Content: [Get started with WebView2 for WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/wpf)
* Content Source: [microsoft-edge/webview2/get-started/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/get-started/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Let's take the discussion over to the WebView2Feedback repo here MicrosoftEdge/WebView2Feedback#1996.
Thanks!
