### ISSUE TITLE
Integrate Progressive Web App into the Operating System

### ISSUE THREAD

**Issue by jirkapinus** [MicrosoftDocs/edge-developer#1422]
[Enter feedback here]
Hello,

I send my current experiences with integrating Progressive Web App into the Operating System used on our company website https://www.slunecno.cz

Edge Browser integrates PWA into Start Menu but not makes shurtcut on desktop
Chrome Browser makes shurtcut on desktop but doesn't integrate PWA into Start Menu 
and integrated PWA is between Programs and Features list named as Microsoft Edge WebView2 Runtime

I would like add some function as  ,,Welcome page" after PWA is installed and first run.

Best Regards,
Jiri Kapinus
Slunecno.cz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1af9f708-54ab-9084-41b8-73a9e4048a91
* Version Independent ID: ad5d0185-fb2b-7413-ca5f-a1085dc71432
* Content: [Use the Web App Manifest to integrate your Progressive Web App into the Operating System - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/webappmanifests#feedback)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/webappmanifests.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-chromium/webappmanifests.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for your feedback, I will pass it on to the right team (closing this issue now since this repo is about docs).
