### ISSUE TITLE
Detecting Microsoft Edge  Javascirpt Sample Code Error

### ISSUE THREAD

**Issue by liudikang** [MicrosoftDocs/edge-developer#1425]
This sample code is wrong,  navigator.userAgentData.brands is an array in my browser(Edge 92.0.902.84 ).  

The loop should be` for (brand_version_pair of navigator.userAgentData.brands)`

```
function isChromium() {
    for (brand_version_pair in navigator.userAgentData.brands) {
        if (brand_version_pair.brand == "Chromium"){
            return true;
        }
    }
    return false;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e7cee1-a4cc-cb21-abf9-19e7eb1333ed
* Version Independent ID: 67677a5d-e51c-5aff-d5fc-b2effddb8fe2
* Content: [Detecting Microsoft Edge from your website - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-guidance#feedback)
* Content Source: [microsoft-edge/web-platform/user-agent-guidance.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/user-agent-guidance.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for catching this and reporting the issue! I'll put up a PR to address this shortly.
