### ISSUE TITLE
Service Worker Linking Issue

### ISSUE THREAD

**Issue by Plaban9** [MicrosoftDocs/edge-developer#143]
In Service Worker Section, we were told to get 2 file - "pwabuilder-sw-register.js" and "pwabuilder-sw.js".

As per my understanding, "pwabuilder-sw-register.js" is registering "pwabuilder-sw.js" but it will not link and Node.js console will say 404 - "GET /pwabuider-sw.js 404 12.204 ms - 1477"

On further inspection, I found that there is a typo in ""pwabuilder-sw-register.js" in line "navigator.serviceWorker.register('pwabuider-sw.js'...". I changed it pwabuilder-sw.js and it is working fine now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcef5936-232e-1ab0-c1c4-77026c79e277
* Version Independent ID: b6ec450d-ead9-ffcf-0d5b-7a408bf0e13d
* Content: [Get started with Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/get-started)
* Content Source: [microsoft-edge/progressive-web-apps/get-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/get-started.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by ricardoserradas** [comment]
Yes, @Plaban9. Thanks for the comment, by the way.

I opened an issue on its repository to report it.

https://github.com/pwa-builder/serviceworkers/issues/26

It seems to be already fixed but not published.

https://github.com/pwa-builder/serviceworkers/blob/master/serviceWorker1/pwabuilder-sw-register.js

**Comment by TLWard** [comment]
Good catch @Plaban9.  This has still not been updated but I noticed your comment and was able to get this going. Thanks.

**Comment by CirkDunhaim** [comment]
I'm browsing information about this on the Internet. There are some more interesting articles, such as https://axisbits.com/blog/PWA-Development-A-Step-by-Step-Tutorial-To-Starting-Your-Business-With-Progressive-Web-Applications https://medium.com/samsung-internet-dev/a-beginners-guide-to-making-progressive-web-apps-beb56224948e ,, I will add to my list and your

**Comment by mattwojo** [comment]
It looks like this issue is being handled on the PWA Builder repo: https://github.com/pwa-builder/serviceworkers/issues/26 
@Plaban9 Do you feel alright about me closing this issue and tracking there?   (I'm adding a ping to that team on the issue as well).

**Comment by Plaban9** [comment]
Sounds good.

**Comment by Plaban9** [comment]
> 
> 
> It looks like this issue is being handled on the PWA Builder repo: [pwa-builder/serviceworkers#26](https://github.com/pwa-builder/serviceworkers/issues/26)
> @Plaban9 Do you feel alright about me closing this issue and tracking there? (I'm adding a ping to that team on the issue as well).

Sounds Good.

**Comment by mattwojo** [comment]
Thanks closing.  Track here: https://github.com/pwa-builder/serviceworkers/issues/26

**Comment by tatted001** [comment]
FUCK YOU!
