### ISSUE TITLE
Sensors - Change location by editing lat and long is not working

### ISSUE THREAD

**Issue by VisalVa** [MicrosoftDocs/edge-developer#1434]
Dear Team,

I'm not sure if I'm using the Sensors feature from Dev Tools correctly. But I couldn't see the location change once I changed the location to another country (e.g. Tokyo).

Location: Tokyo (35.689487, 139.691706)

From Google Maps, it still shows this location: https://www.google.com/maps/@11.5332067,104.9038455,15z

Can you please help me?

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8adbf0ab-a03d-f7ed-76a4-20ad3127ade9
* Version Independent ID: 79112442-6921-c286-8f39-c079fc2d526b
* Content: [Override geolocation with Microsoft Edge DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/geolocation)
* Content Source: [microsoft-edge/devtools-guide-chromium/device-mode/geolocation.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/device-mode/geolocation.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
I don't know how google map detects your position, but it doesn't seem to be by using the [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API#examples), which the Sensors panel lets you play with.

Can you try with this website instead: https://www.where-am-i.co/
it seems to be using the Geolocation API, and I was able to successfully simulate other locations like Tokyo.

**Comment by captainbrosset** [comment]
Closing issue for now, based on my last comment. Let's re-open it once @VisalVa replies and if the problem does persist.
