### ISSUE TITLE
Not getting any reply when trying to Upload a extension.

### ISSUE THREAD

**Issue by AdityaSaurabhbxr** [MicrosoftDocs/edge-developer#144]
I have tried too many times to upload a extension in my developer account, i have field the form which has to be field before upload of extension for permission, Its been more than 5 Months I am trying but i am not getting the proper support Please help me with this, This page is not help full for that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1037a28d-7cd5-66dc-9826-1e626fa6e74b
* Version Independent ID: f90b56a3-db51-eeea-707c-0c30e81b4749
* Content: [Extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions)
* Content Source: [microsoft-edge/extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions.md)
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by erikadoyle** [comment]
@AdityaSaurabhbxr, is the upload itself failing? Or were you able to successfully submit it to the store and still waiting to see if it was accepted?

**Comment by AdityaSaurabhbxr** [comment]
@erikadoyle Thanks For the reply,
 upload itself failing. I am not able to upload I have followed the entire process listed on the web.

**Comment by erikadoyle** [comment]
[Windows developer support](https://developer.microsoft.com/en-us/windows/support) should be able to help. You might find an answer in the community forums, and if not, you can file a ticket from the **Contact Us** link.
