### ISSUE TITLE
The sample in this page fails with : Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist

### ISSUE THREAD

**Issue by fuzzychild** [MicrosoftDocs/edge-developer#1446]
Tried the steps mentioned here in this page (Create an extension tutorial Part 2) on Microsoft Edge
Version 93.0.961.47 (Official build) (64-bit)  WIn 10 2004.
It keeps failing with the following error:
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec889040-6707-74fd-9086-d838c15a9172
* Version Independent ID: 73d6355a-b256-c8ab-9889-c51603d3052b
* Content: [Create an extension tutorial Part 2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @fuzzychild, sorry to hear about the errors. We can't reproduce the error on our side. Here's a link to the sample extension:

[https://github.com/MicrosoftEdge/MicrosoftEdge-Extensions-Demos/tree/master/extension-getting-started-part2/extension-getting-started-part2](https://github.com/MicrosoftEdge/MicrosoftEdge-Extensions-Demos/tree/master/extension-getting-started-part2/extension-getting-started-part2)

Can you tell us if it works for you?
