### ISSUE TITLE
Need an easy to delete the db as well

### ISSUE THREAD

**Issue by kakugiki** [MicrosoftDocs/edge-developer#145]
Need an easy to delete the db as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b080df7-306f-3ebd-6b46-49ecc02cb932
* Version Independent ID: 3e717fd4-9cde-8fa0-9dcc-ef5ed4d0f145
* Content: [Microsoft Edge DevTools - Debugger - IndexedDB manager - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/debugger/indexeddb)
* Content Source: [microsoft-edge/devtools-guide/debugger/indexeddb.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/debugger/indexeddb.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
Good idea! Could you please file a feature request on the Edge UserVoice channel: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer?category_id=84475
