### ISSUE TITLE
Now that we've sideloaded how do we see the result of the extension?

### ISSUE THREAD

**Issue by Javaman2** [MicrosoftDocs/edge-developer#1466]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd37dada-0845-5f1a-7f99-495fe06882cd
* Version Independent ID: 1bbb4d2e-dabb-3d68-de2b-12fb808f86ca
* Content: [Sideload your extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/extension-sideloading)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/extension-sideloading.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/getting-started/extension-sideloading.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
@Javaman2 sideloading an extension does the same thing as installing it from the store. Once you've loaded the unpacked extension, you can use it the same way as you would when installing it from the store.
Does this help? If not, can you please elaborate on what's not working for you?

**Comment by captainbrosset** [comment]
I'm going to close this issue now since it has become inactive and it isn't clear what the issue is.
