### ISSUE TITLE
Missing APIs for bookmarks

### ISSUE THREAD

**Issue by SciFreakholic** [MicrosoftDocs/edge-developer#148]
Hello, are you planning to support the following bookmarks APIs?

- bookmarks.onCreated
- bookmarks.onRemoved
- bookmarks.onChanged
- bookmarks.onMoved

Please visit this link for reference: https://developer.chrome.com/extensions/bookmarks

Thanks in advance.

**Comment by erikadoyle** [comment]
Hi @SciFreakholic, our [UserVoice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer?category_id=87962) channel is the place for Edge platform requests. Please do file that!
