### ISSUE TITLE
missing words in phrase

### ISSUE THREAD

**Issue by marypcbuk** [MicrosoftDocs/edge-developer#150]
"or by taking action an external FIDO2 device" doesn't make sense; perhaps "or by taking an action like inserting an external FIDO2 device"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cabf96-7b2b-9eb6-c428-ff4b44a97312
* Version Independent ID: 922d390b-52b6-db2a-0aab-f338e8c21b85
* Content: [Dev guide - Web Authentication - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication)
* Content Source: [microsoft-edge/dev-guide/windows-integration/web-authentication.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/windows-integration/web-authentication.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by idamlaj** [comment]
I agree it could be clearer. 

What I was trying to convey: Even if the FIDO device is already inserted, the user will need to take action on the device (like touch the button or scan their finger on the device) to confirm they are present. This behavior is to prevent malware from silently using your FIDO device.

**Comment by erikadoyle** [comment]
How about "or by taking action [on] an external FIDO2 device"? I'll update it. Thanks @marypcbuk and @idamlaj !
