### ISSUE TITLE
Merge Preview and Response Tab in Dev tools

### ISSUE THREAD

**Issue by chaurasiagovind** [MicrosoftDocs/edge-developer#1503]
Hi, I am wondering if what is the use of **Response** Tab in Dev tools. We mostly use the raw response to copy it or search for an item there. 

We also have **Preview** tab to explore the response.  I understand that we can manually remove it. Can we just merge all these features in one tab?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee20453a-60c5-91b0-0e1c-4c0fd48de570
* Version Independent ID: e61856a8-ad86-bed6-601f-69b69128f06c
* Content: [What's new in DevTools (Microsoft Edge 94) - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/devtools-guide-chromium/whats-new/2021/09/devtools)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2021/09/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/whats-new/2021/09/devtools.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@chaurasiagovind - thanks for your suggestion. To ensure this gets routed to the Engineering team, can you use the following link to submit your feedback: 
https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/contact#use-the-send-feedback-window

Thanks again.
