### ISSUE TITLE
UseChromium no longer exists in Selenium v4

### ISSUE THREAD

**Issue by Sebazzz** [MicrosoftDocs/edge-developer#1507]
In the document several times the `UseChromium` property is referenced - however it is no longer present in Selenium v4 final and never was for Selenium v3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver to automate Microsoft Edge - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Sorry to hear about this @Sebazzz. I've reached out to Engineering for more information on this issue.

**Comment by Sebazzz** [comment]
It is no problem - legacy Edge is legacy. Just the references to UseChromium need to be removed from the docs.

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Reezaali ***@***.***>
Verzonden: Friday, October 15, 2021 6:56:33 PM
Aan: MicrosoftDocs/edge-developer ***@***.***>
CC: Sebastiaan Dammann ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [MicrosoftDocs/edge-developer] UseChromium no longer exists in Selenium v4 (#1507)


Sorry to hear about this @Sebazzz<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSebazzz&data=04%7C01%7C%7C100b2e670bb74867eea808d98ffcbee2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637699137957567857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NI6GAN3%2B2uTq%2BzAw0vC%2FyDH8EfyVA28G5abc3wFpbus%3D&reserved=0>. I've reached out to Engineering for more information on this issue.

**Comment by captainbrosset** [comment]
Thank you for reporting this issue. We have created a task on our backlog, and we will provide a fix soon. Closing this issue for now.
