### ISSUE TITLE
about pdf extension

### ISSUE THREAD

**Issue by kfyidrig** [MicrosoftDocs/edge-developer#1509]
Is the PDF extension of edge browser an open source project? I feel that it is very smooth to use, compared with pdf.js. I want to make some modifications based on PDF extension, or learn how you draw smooth curves on PDF and save curves in PDF, but I can only understand that you seem to be manipulating HTML < embed > tag.

**Comment by Reezaali** [comment]
@kfyidrig - thanks for the question. You can use the following method to submit feedback and include an email address for someone to reply to your question. 

https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/contact#use-the-send-feedback-window
