### ISSUE TITLE
issue how to get HTML content from webview2 to detect malicious code (chromium edge)

### ISSUE THREAD

**Issue by spidemen** [MicrosoftDocs/edge-developer#1523]
when I load a web page, I want to get the HTML of this web page and to check is there any malicious code ??  like javascript code or HTML content

I check to  https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2webresourcerequest?view=webview2-1.0.992.28#get_content.  Cannot find any useful method that can do this job.  

I use win32 to doing window coding. 
browser: chromium edge

**Comment by Reezaali** [comment]
Hi @spidemen - can you post your question on the following Engineering repo to get an answer to your question? Thanks!
https://github.com/MicrosoftEdge/WebView2Feedback
