### ISSUE TITLE
Cannot Find the indexedDB manager. 

### ISSUE THREAD

**Issue by theeGwandaru** [MicrosoftDocs/edge-developer#154]
My edge version is 41.16299.402.0 and I cannot find this IndexedDB manager as described here.  I can see Local Storage, Session Storage, cookies and some some other folders but no IndexedDB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b080df7-306f-3ebd-6b46-49ecc02cb932
* Version Independent ID: 3e717fd4-9cde-8fa0-9dcc-ef5ed4d0f145
* Content: [Microsoft Edge DevTools - Debugger - IndexedDB manager - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/debugger/indexeddb)
* Content Source: [microsoft-edge/devtools-guide/debugger/indexeddb.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/debugger/indexeddb.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
Hi @theeGwandaru, I[ndexedDB manager is available starting EdgeHTML 17](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/whats-new#indexeddb-inspection) / Windows 10 April 2018 Update (build 17134), which is the latest public release after your build (16299 shipped starting October 2017 with EdgeHTML 16).
