### ISSUE TITLE
Is Commands API support planned?

### ISSUE THREAD

**Issue by rensa** [MicrosoftDocs/edge-developer#155]
Hi there,

I'm getting into Edge extension development, and I was wondering if the [Commands](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands) manifest key and associated API were on the development roadmap. As far as I can see, it doesn't appear to be supported as of Edge v42.17134.1.0 and isn't on the [roadmap](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/extension-api-roadmap).

The utility of the extension I'm interested in building is fairly contingent on it being accessible via a keyboard shortcut, so I'm pretty keen to see it (or a similar API) implemented!

Thanks very much,

James

**Comment by erikadoyle** [comment]
Good question @rensa -- I checked with the Edge team, and its "Under Consideration". I'll add that to the roadmap. In the meantime, please do [upvote the UserVoice entry](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/18970390-add-support-for-the-commands-api) so we can track requests for it. Thanks!

**Comment by rensa** [comment]
Shall do, Erika. Thanks very much!
