### ISSUE TITLE
Premature to use UACH

### ISSUE THREAD

**Issue by jwrosewell** [MicrosoftDocs/edge-developer#1551]
The [User-Agent Client Hints (UACH) draft report](https://wicg.github.io/ua-client-hints/) on which this documentation relies is not yet on a standards track. It seems premature of Microsoft to advise developers to use a proposal that has not commenced the standards track work and does not enjoy consensus at W3C. Some specific issues include:

1. Microsoft have not been involved in the draft report and in any case the proposers from Google do not believe the proposal is ready to [move into the W3C](https://github.com/WICG/ua-client-hints/issues/176) to commence standards work. If Microsoft feel differently then they might wish to commence the creation of a Working Group at W3C.
2. There is [no evidence](https://github.com/WICG/ua-client-hints/issues/215) associated with the core problem being solved. The document relies on a self-evident justification. Given the information contained in facts contained in the [Google Digital Advertising Antitrust Litigation](https://storage.courtlistener.com/recap/gov.uscourts.nysd.564903/gov.uscourts.nysd.564903.152.0_1.pdf) filing there are legitimate and serious questions concerning the information asymmetries that UACH would generate between browser vendors collaborating on such a change and the rest of the web eco-system. Consensus across the web eco-system rather than a few browser vendors is more important than ever.
3. The web eco-system has been conditioned to expect a [Q2 2022](https://privacysandbox.com/timeline/) timeline for earliest deployment. In this documentation Microsoft seem to be suggesting they intend to commence deployment to a different timeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da54f17-9c2a-65dd-6a46-afca9ccb567d
* Version Independent ID: 8da54f17-9c2a-65dd-6a46-afca9ccb567d
* Content: [Detecting Windows 11 using User-Agent Client Hints - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11)
* Content Source: [microsoft-edge/web-platform/how-to-detect-win11.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/how-to-detect-win11.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jenny-microsoft** [comment]
Hi James, thanks for your comment. Edge is shipping UA Client Hints to all Edge Stable clients. This is our current guidance to web developers. As with all web APIs, we will continue to evolve our implementation as the standardization process progresses. If you have feedback about progress in the W3C, we recommend having that conversation within the W3C.
