### ISSUE TITLE
Possible to enable remote debugging port on built application with Webview2?

### ISSUE THREAD

**Issue by omegadash** [MicrosoftDocs/edge-developer#1555]
Hi, I have an application that I need to attach to for automation. The application has a login screen which is written as a UWP app but once you are logged in it switches over to Webview2. I need to attach to the Webview2 session after the login has completed.

I wanted to know if it is possible to enable remote-debugging on this application if not, is it possible to check if a remote-debugging port is enabled on the application without having access to the code?

**Comment by Reezaali** [comment]
Hi @omegadash - thanks for your question. Can you post your question on the following repo where the engineering team will respond?
https://github.com/MicrosoftEdge/WebView2Feedback
