### ISSUE TITLE
Web Share text is incorrect 

### ISSUE THREAD

**Issue by tomayac** [MicrosoftDocs/edge-developer#1571]
The web share message of this page is: “Synchronize and update a Programmable Web App (PWA) in the background. - Microsoft Edge Development | Microsoft Docs”, but PWA means Progressive Web App, not Programmable Web App. 
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eeeb1dc-e96f-3562-3c6c-71426aa2014c
* Version Independent ID: 1b62360e-26b4-db3a-1b7b-5dc15cad924e
* Content: [Synchronize and update a Programmable Web App (PWA) in the background. - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/background-syncs)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/background-syncs.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-chromium/how-to/background-syncs.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikehoffms** [comment]
FTS shows 1 other hit to fix: in demo-pwas.md
