### ISSUE TITLE
Extension tutorial doesn't work

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/edge-developer#158]
It looks like the extension tutorial relies on the docs pages having the .c-uhfh and .brand-neutral classes, which they don't anymore. So the extension, in the end, doesn't work as expected. Maybe, we can just change the body color instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e322d0db-8a91-6fff-7510-a5ec18fa4a65
* Version Independent ID: 0c60d518-08f5-3b4e-0f4b-b7cd71455951
* Content: [Extensions - Creating an extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/creating-an-extension)
* Content Source: [microsoft-edge/extensions/guides/creating-an-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/creating-an-extension.md)
* Product: **microsoft-edge**
* GitHub Login: @libbymc
* Microsoft Alias: **libbymc**

**Comment by mattwojo** [comment]
This Extension tutorial needs a re-write! Thanks for pointing out these errors @damienestewart. I'm working on getting this rewrite work scheduled and will get this content updated ASAP.

**Comment by erikadoyle** [comment]
Good call @damienestewart --toggling the document body color is simpler and more reliable. Thanks!
