### ISSUE TITLE
Mikey

### ISSUE THREAD

**Issue by mikey77777** [MicrosoftDocs/edge-developer#1580]
[IEnter feedback here]I am totally in love with the science of code, the internet & more. I plan to devote my life to this and learn every little byte that I can.  I know I am behind in the game, but I will be catching up as much as I can. And I want to Thank Microsoft & Github & all the great People that have been helping me out. Some of them know that they have to step aside so that you can make your decisions in what direction that you want to go so that you can be happy with your life. Thanks to All, Mikey Yarbrough

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c229daf5-92cb-dd84-1d48-be8672a6dae5
* Version Independent ID: 7f9a1c80-26b8-b222-3842-c1dfb5f11e1d
* Content: [Get started with viewing and changing CSS - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/css/)
* Content Source: [microsoft-edge/devtools-guide-chromium/css/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/css/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Thanks for the feedback @mikey77777.
