### ISSUE TITLE
Can't edit files with workspaces

### ISSUE THREAD

**Issue by MarkPuchalaII** [MicrosoftDocs/edge-developer#1585]
[Enter feedback here]
There seems to be something missing from this guide, because no matter WHAT I do, I cannot get the workspaces to sync up for me to edit from devtools.

The issue happens specifically at 6. "A green dot indicates..."
There is no green dot for me. I've even confirmed it's disconnected.
Nothing is working. Something in the guide needs to be amended to address this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6fb311-8bae-b4cb-e395-8e4e084a32ef
* Version Independent ID: ecf93d87-c4c4-0678-a09c-6d920021a090
* Content: [Edit files with Workspaces - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/workspaces/)
* Content Source: [microsoft-edge/devtools-guide-chromium/workspaces/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/workspaces/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for your feedback. I tested on my side again and it did work for me. So I don't think it's a problem with the guide. It could be a bug with DevTools.
Would you mind sharing more information please? Like whether you are using a PC or Mac. Which version of Edge you have?

**Comment by MarkPuchalaII** [comment]
Windows 11 (upgraded, not fresh install), Custom-built PC. 
Edge 96.0.1054.34, 64-bit
  — Mark Puchala 2/

**Comment by captainbrosset** [comment]
Thanks for coming back with details. My understanding is that this is a DevTools bug. So I forwarded this to the right team for investigation. In the meantime, I will close this issue as I think this isn't a documentation problem. We can still re-open it later if it turns out something was missing.
Thanks for your understanding.
