### ISSUE TITLE
Show final manifest.json

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/edge-developer#159]
It would be helpful to see the final manifest.json on the tutorial page. This would ensure that a user did all of the updates correctly, without needing to come to GitHub and check the repository. For example: 'Update "manifest.json" to include the icons.' doesn't indicate where in the "icons" key should be added in the manifest.json file. Is it a top-level key, or is it a sub-key of another key? Showing what the manifest.json should look like after updates would solve the potential ambiguity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e322d0db-8a91-6fff-7510-a5ec18fa4a65
* Version Independent ID: 0c60d518-08f5-3b4e-0f4b-b7cd71455951
* Content: [Extensions - Creating an extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/creating-an-extension)
* Content Source: [microsoft-edge/extensions/guides/creating-an-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/creating-an-extension.md)
* Product: **microsoft-edge**
* GitHub Login: @libbymc
* Microsoft Alias: **libbymc**

**Comment by mattwojo** [comment]
Adding that a final manifest.json file has been requested as a part of this tutorial re-write. Thanks Damien.

**Comment by erikadoyle** [comment]
Great suggestion @damienestewart , thank you.
