### ISSUE TITLE
Is there any feature detection for password reveal?

### ISSUE THREAD

**Issue by karladler** [MicrosoftDocs/edge-developer#1592]
I just found this page about how to [style the password reveal,](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal#visibility-of-the-control) but how is it possible to detect if that is even enabled by the user?

**Comment by captainbrosset** [comment]
Thanks for filing this issue. Could you elaborate what you mean by "enabled by the user". The password reveal button appears no matter what (except in the 2 cases listed at the bottom of the documentation, but those are chosen by the browser, not the user).
