### ISSUE TITLE
Switch back to window does not bring it to foreground

### ISSUE THREAD

**Issue by bswhb** [MicrosoftDocs/edge-developer#1596]
Regarding the active tab handling, as far as I know previously in IE the switchTo.window() command will automatically bring the specific window to foreground, while currently in Edge we have to do this manually. Is such tab activation process able to be done with webdriver, or we have to reach other automation mechanism?

Similarly, we also came across the screenshot issue when we did the following commands:
* open new window in a tab
* switch back to the old window, by switchTo.window() command (old window not brought to foreground)
* take screenshot of old window, ends up with black screen

**Comment by captainbrosset** [comment]
Thanks for your feedback @bswhb. Unfortunately, this repository is here to track the code and issues related to the documentation of various Edge developer products. It doesn't track issues related to the products themselves. So I would encourage you to reach out for help on the Microsoft Q&A website. In particular, this question seems related: https://docs.microsoft.com/en-us/answers/questions/181974/selenium-switch-to-new-window-is-not-working-in-ed.html

Thanks for your understanding.
