### ISSUE TITLE
WebSocket doesn't work in MicroSoft Edge

### ISSUE THREAD

**Issue by dlyltm** [MicrosoftDocs/edge-developer#1610]
My relevant js code is as follows:

var scheme = document.location.protocol == "https:" ? "wss" : "ws";
    var port = document.location.port ? (":" + document.location.port) : "";
    var connectionUrl = scheme + "://" + document.location.hostname + port + "/" + scheme;  
    var socket = new WebSocket(connectionUrl);
    socket.onmessage = function (msg) {
          ......
    }

But it doesn't work in Edge.The "socket.onmessage" was not entered at all.
My Edge's version is 96.0.1054.43.To solve this problem, I have done the following work:
1.The following settings are made on the  Edge's about:flags page:
![6@$_C(11~TX~@` 1JZ%9 EH](https://user-images.githubusercontent.com/33916145/144775678-934fc73d-9e16-4fb3-906f-7932c85f6388.png)
2.Run the command Get-AppxPackage in PowerShell to get the Edge's PackageFamilyName,then use CheckNetIsolation LoopbackExempt -a -n= PackageFamilyName in cmd.
3,The following settings are made in the registry:
![IU1BATG99 QS$R%MK AV}O4](https://user-images.githubusercontent.com/33916145/144777130-1714402f-9ad2-4eb6-96dc-9874ef2d0e3c.png)

But none of the above works.What's going on?What should I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4538b351-b450-e104-3f5c-76bd9c5233e9
* Version Independent ID: 700de4b5-e02b-8914-c0a6-0ab604025e1f
* Content: [Visual Studio for web development - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/visual-studio/)
* Content Source: [microsoft-edge/visual-studio/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/visual-studio/index.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. Unfortunately this repository is only for the documentation of Microsoft Edge's developer products. So this isn't really the right place for this technical question. I can suggest posting your question on [the Edge Q&A site](https://docs.microsoft.com/en-us/answers/topics/ms-edge.html). You will have better luck there.
Thank you for your understanding.

**Comment by dlyltm** [comment]
I posted my question on the Edge Q&A site,but it refused:
![15XUBTSDBOS36HW7%~ )8O](https://user-images.githubusercontent.com/33916145/144949955-ca4d2a7f-1b33-4879-9dfa-80672951cfb5.png)
What's going on?
