### ISSUE TITLE
Instructions to install WebView2 literally don't work with VS 2022

### ISSUE THREAD

**Issue by gwickman-dev** [MicrosoftDocs/edge-developer#1618]
> Using VS2022 and wanted to try new WebView2 control to determine if it can be used in our future releases.  
> Followed the step-by-step instructions for installation at: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32#step-2---install-webview2-sdk
> BUG: Fails to acknowledge control even exists so instructions are completely wrong and I've not figured out a workaround to get this updated control.

Best case: The instructions are faulty and need to be updated.
Worst case: The product isn't actually available and is sending developers that want to continue modern support of MS products on a wild goose chase for no reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ba6a76-eb0b-e8f2-dfc9-d2c0df6261a4
* Version Independent ID: 8d62fdee-f44a-3d40-6800-04d7bd6193f8
* Content: [Get started with WebView2 in WinForms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms)
* Content Source: [microsoft-edge/webview2/get-started/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/get-started/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jasonstephen15** [comment]
Hi @gwickman-dev, could you please ensure you are in the 'Browse' tab of the visual studio nuget installation window?

**Comment by gwickman-dev** [comment]
Yes, I was in Browse.  

I think I figured out the bug.  VS2022 doesn't install with the proper NuGet package source locations listed in the **Options->NuGet Package Manager->Package Sources**.  I manually created a source pointing to **https://api.nuget.org/v3/index.json** and then the Browse list populates.  Apparently this was already reported previously but still hasn't been addressed.  See: [https://developercommunity.visualstudio.com/t/missing-default-nuget-package-source/1453751](https://developercommunity.visualstudio.com/t/missing-default-nuget-package-source/1453751)

Without the critical step of ensuring the proper NuGet Sources are available or instructions to manually enter them, these instructions would not work.  For what it's worth, this was a plain vanilla VS2022 installation so I'm surprised it was missing the default package source locations.

**Comment by jasonstephen15** [comment]
@gwickman-dev - Glad you were able to get it working, I will make an update to the doc to call this out and reach out to the VS team to make sure they are aware of this. Thanks for raising this question, and please let me know if you have any other questions!

**Comment by kyle-thdi** [comment]
Thank you! @gwickman-dev ... I was pulling my hair out trying to figure out why I couldn't see any reference to WebView2 in the NuGet Package Manger.  Manually creating the source to point to https://api.nuget.org/v3/index.json finally worked!
