### ISSUE TITLE
This doc is not good for local file path after Chrome M33

### ISSUE THREAD

**Issue by AlexChongMicrosoft** [MicrosoftDocs/edge-developer#1619]
[Enter feedback here]
This doc is not good for local file path after Chrome M33. I think it's also no longer available for Edge v96. Please check the local path part and verify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f290aba-5618-9b79-e3ac-243ec8cc4dd6
* Version Independent ID: 0cda1705-27db-4282-40e1-a2fbbd16ed2e
* Content: [Alternate method to distribute extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by khaleefa222** [comment]
leave comments

**Comment by captainbrosset** [comment]
This issue has unfortunately gotten stale. I'm going to assume it no longer applies and will close it now. If there is still a documentation issue here, please feel free to comment.
