### ISSUE TITLE
The Windows Registry key method seems unavailable now

### ISSUE THREAD

**Issue by AlexChongMicrosoft** [MicrosoftDocs/edge-developer#1620]
[Enter feedback here]
The Windows Registry key method seems unavailable now. If so, it's good to modify this doc more clearly.
![image](https://user-images.githubusercontent.com/45751478/145155055-8adbbf44-3373-4b4e-9aa2-cc7930553d0c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f290aba-5618-9b79-e3ac-243ec8cc4dd6
* Version Independent ID: 0cda1705-27db-4282-40e1-a2fbbd16ed2e
* Content: [Alternate method to distribute extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
This issue has gotten stale. Closing now, assuming it no longer is a problem. Please feel free to re-open if it is.
