### ISSUE TITLE
Add note about `Shift` modifier when selecting an element

### ISSUE THREAD

**Issue by dwelle** [MicrosoftDocs/edge-developer#1625]
We should list that holding `Shift` while inspecting an element will enable selecting elements with `pointer-events: none` (see https://devtoolstips.org/tips/en/select-pointer-events-none-elements/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f4e719c-edd9-95fc-6b62-66f1a172f21d
* Version Independent ID: 0b55c280-1b8b-a84a-49a1-9f86c4aa85ed
* Content: [CSS features reference - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/css/reference#select-an-element)
* Content Source: [microsoft-edge/devtools-guide-chromium/css/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/css/reference.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for filing this. I agree. 
@codepo8, I believe this is on your radar to add, right?

**Comment by codepo8** [comment]
I can write something next week when I'm back. I really think inspector
should get it's own page.

**Comment by mikehoffms** [comment]
Related:
Use the Inspect tool to detect accessibility issues by hovering over the webpage
https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/accessibility/test-inspect-tool

**Comment by codepo8** [comment]
Yes but specific. I find it odd that there is no landing page for inspect

**Comment by captainbrosset** [comment]
Doc is now live: https://docs.microsoft.com/fr-fr/microsoft-edge/devtools-guide-chromium/css/inspect
Leaving this open as I think there's a bit of follow-up work needed for the table of content.

**Comment by captainbrosset** [comment]
I believe the page has now been integrated in the table of content. Closing as done.

**Comment by mikehoffms** [comment]
Confirmed:
"Shift" has been added in section:
https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/css/inspect#inspecting-non-accessible-elements

Inspect tool is now mentioned in the TOC:
https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/accessibility/test-inspect-tool
