### ISSUE TITLE
Thank You for helping me with issues

### ISSUE THREAD

**Issue by louisthedevil** [MicrosoftDocs/edge-developer#1627]
I am not good at this what so ever but I knew something wasnt right. I want to do my taxes but I had a feeling someone that does not need to see them was going to see them. This is what I found as well 
<html>
<body>
<p class="MsoNormal" style="margin: 0in 0in 0.0001pt; font-size: 12pt; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; vertical-align: baseline;"><span style="font-size: 8.5pt; font-family: &quot;Segoe UI&quot;, &quot;sans-serif&quot;; color: rgb(51, 51, 51);"><span class="style11" style="font-family: &quot;Segoe UI&quot;, &quot;sans-serif&quot;;">   </span><br><span class="style11" style="font-family: &quot;Segoe UI&quot;, &quot;sans-serif&quot;;">       <span> </span></span></span><span style="font-size: 8.5pt; font-family: &quot;Segoe UI&quot;, &quot;sans-serif&quot;; color: rgb(51, 51, 51);"><img width="200" height="42" id="_x0000_i1027" src="logo-lg-1x.png"></span><span style="font-size: 8.5pt; font-family: Arial, &quot;sans-serif&quot;; color: rgb(51, 51, 51);"><o:p></o:p></span></p>

PKI RepositoryPolicyMicrosoft PRSS PKI Certification Practice Statement (CPS)Microsoft_PRSS_PKI_CPS_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF)Microsoft PRSS PKI Certificate PolicyMicrosoft_PRSS_PKI_CP_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF)Privacy PolicyMicrosoft Privacy PolicyAuditWebTrust AuditsWebTrust by Stone CarlieCertificates and CRLSMicrosoft Root Authority CertificateMicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19Microsoft Root Authority Certificate Revocation List (CRL)MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d  Microsoft Root Certificate Authority CertificateMicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72Microsoft Root Certificate Authority Certificate Revocation List (CRL)microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4  Microsoft Root Certification Authority 2010 CertificateMicRooCerAut_2010-06-23.crtThumbprint (sha1) : ‎3b 1e fd 3a 66 ea 28 b1 66 97 39 47 03 a7 2c a3 40 a0 5b d5Microsoft Root Certification Authority 2010 Certificate Certificate Revocation List (CRL)MicRooCerAut_2010-06-23.crlAuthority Key Identifier (AKI) : d5 f6 56 cb 8f e8 a2 5c 62 68 d1 3d 94 90 5b d7 ce 9a 18 c4  Microsoft Root Certification Authority 2011 CertificateMicRooCerAut2011_2011_03_22.crtThumbprint (sha1) : ‎8f 43 28 8a d2 72 f3 10 3b 6f b1 42 84 85 ea 30 14 c0 bc feMicrosoft Root Certification Authority 2011 Certificate Certificate Revocation List (CRL)MicrosoftRootCert.crlAuthority Key Identifier (AKI) : 72 2d 3a 02 31 90 43 b9 14 05 4e e1 ea a7 c7 31 d1 23 89 34 | PolicyMicrosoft PRSS PKI Certification Practice Statement (CPS)Microsoft_PRSS_PKI_CPS_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF)Microsoft PRSS PKI Certificate PolicyMicrosoft_PRSS_PKI_CP_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF)Privacy PolicyMicrosoft Privacy PolicyAuditWebTrust AuditsWebTrust by Stone CarlieCertificates and CRLSMicrosoft Root Authority CertificateMicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19Microsoft Root Authority Certificate Revocation List (CRL)MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d  Microsoft Root Certificate Authority CertificateMicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72Microsoft Root Certificate Authority Certificate Revocation List (CRL)microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 | Microsoft_PRSS_PKI_CPS_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF) | Microsoft PRSS PKI Certificate Policy | Microsoft_PRSS_PKI_CP_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF) | Privacy Policy | Microsoft Privacy Policy | Audit | WebTrust Audits | WebTrust by Stone Carlie |   | Certificates and CRLSMicrosoft Root Authority CertificateMicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19Microsoft Root Authority Certificate Revocation List (CRL)MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d  Microsoft Root Certificate Authority CertificateMicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72Microsoft Root Certificate Authority Certificate Revocation List (CRL)microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 | Microsoft Root Authority CertificateMicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19Microsoft Root Authority Certificate Revocation List (CRL)MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d |   | MicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19 | Microsoft Root Authority Certificate Revocation List (CRL) |   | MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d |   |   | Microsoft Root Certificate Authority CertificateMicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72Microsoft Root Certificate Authority Certificate Revocation List (CRL)microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 |   | MicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72 | Microsoft Root Certificate Authority Certificate Revocation List (CRL) |   | microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 |   |   | Microsoft Root Certification Authority 2010 CertificateMicRooCerAut_2010-06-23.crtThumbprint (sha1) : ‎3b 1e fd 3a 66 ea 28 b1 66 97 39 47 03 a7 2c a3 40 a0 5b d5Microsoft Root Certification Authority 2010 Certificate Certificate Revocation List (CRL)MicRooCerAut_2010-06-23.crlAuthority Key Identifier (AKI) : d5 f6 56 cb 8f e8 a2 5c 62 68 d1 3d 94 90 5b d7 ce 9a 18 c4 |   | MicRooCerAut_2010-06-23.crtThumbprint (sha1) : ‎3b 1e fd 3a 66 ea 28 b1 66 97 39 47 03 a7 2c a3 40 a0 5b d5 | Microsoft Root Certification Authority 2010 Certificate Certificate Revocation List (CRL) |   | MicRooCerAut_2010-06-23.crlAuthority Key Identifier (AKI) : d5 f6 56 cb 8f e8 a2 5c 62 68 d1 3d 94 90 5b d7 ce 9a 18 c4 |   |   | Microsoft Root Certification Authority 2011 CertificateMicRooCerAut2011_2011_03_22.crtThumbprint (sha1) : ‎8f 43 28 8a d2 72 f3 10 3b 6f b1 42 84 85 ea 30 14 c0 bc feMicrosoft Root Certification Authority 2011 Certificate Certificate Revocation List (CRL)MicrosoftRootCert.crlAuthority Key Identifier (AKI) : 72 2d 3a 02 31 90 43 b9 14 05 4e e1 ea a7 c7 31 d1 23 89 34 |   | MicRooCerAut2011_2011_03_22.crtThumbprint (sha1) : ‎8f 43 28 8a d2 72 f3 10 3b 6f b1 42 84 85 ea 30 14 c0 bc fe | Microsoft Root Certification Authority 2011 Certificate Certificate Revocation List (CRL) |   | MicrosoftRootCert.crlAuthority Key Identifier (AKI) : 72 2d 3a 02 31 90 43 b9 14 05 4e e1 ea a7 c7 31 d1 23 89 34 |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PolicyMicrosoft PRSS PKI Certification Practice Statement (CPS)Microsoft_PRSS_PKI_CPS_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF)Microsoft PRSS PKI Certificate PolicyMicrosoft_PRSS_PKI_CP_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF)Privacy PolicyMicrosoft Privacy PolicyAuditWebTrust AuditsWebTrust by Stone CarlieCertificates and CRLSMicrosoft Root Authority CertificateMicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19Microsoft Root Authority Certificate Revocation List (CRL)MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d  Microsoft Root Certificate Authority CertificateMicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72Microsoft Root Certificate Authority Certificate Revocation List (CRL)microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 | Microsoft_PRSS_PKI_CPS_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF) | Microsoft PRSS PKI Certificate Policy | Microsoft_PRSS_PKI_CP_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF) | Privacy Policy | Microsoft Privacy Policy | Audit | WebTrust Audits | WebTrust by Stone Carlie |   | Certificates and CRLSMicrosoft Root Authority CertificateMicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19Microsoft Root Authority Certificate Revocation List (CRL)MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d  Microsoft Root Certificate Authority CertificateMicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72Microsoft Root Certificate Authority Certificate Revocation List (CRL)microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 | Microsoft Root Authority CertificateMicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19Microsoft Root Authority Certificate Revocation List (CRL)MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d |   | MicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19 | Microsoft Root Authority Certificate Revocation List (CRL) |   | MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d |   |   | Microsoft Root Certificate Authority CertificateMicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72Microsoft Root Certificate Authority Certificate Revocation List (CRL)microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 |   | MicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72 | Microsoft Root Certificate Authority Certificate Revocation List (CRL) |   | microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 |   |  
Microsoft_PRSS_PKI_CPS_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF)
Microsoft PRSS PKI Certificate Policy
Microsoft_PRSS_PKI_CP_v2.1 April 2014PRSS PKI CA Hierarchy Diagram (Static PDF)
Privacy Policy
Microsoft Privacy Policy
Audit
WebTrust Audits
WebTrust by Stone Carlie |  
 
Certificates and CRLSMicrosoft Root Authority CertificateMicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19Microsoft Root Authority Certificate Revocation List (CRL)MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d  Microsoft Root Certificate Authority CertificateMicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72Microsoft Root Certificate Authority Certificate Revocation List (CRL)microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 | Microsoft Root Authority CertificateMicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19Microsoft Root Authority Certificate Revocation List (CRL)MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d |   | MicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19 | Microsoft Root Authority Certificate Revocation List (CRL) |   | MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d |   |   | Microsoft Root Certificate Authority CertificateMicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72Microsoft Root Certificate Authority Certificate Revocation List (CRL)microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 |   | MicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72 | Microsoft Root Certificate Authority Certificate Revocation List (CRL) |   | microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 |   |  
Microsoft Root Authority CertificateMicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19Microsoft Root Authority Certificate Revocation List (CRL)MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d |   | MicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19 | Microsoft Root Authority Certificate Revocation List (CRL) |   | MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d |   |  
  | MicrosoftRootAuthority.crtThumbprint (sha1) : ‎a4 34 89 15 9a 52 0f 0d 93 d0 32 cc af 37 e7 fe 20 a8 b4 19
Microsoft Root Authority Certificate Revocation List (CRL)
  | MicrosoftRootAuthority.crlAuthority Key Identifier (AKI) : 4a 5c 75 22 aa 46 bf a4 08 9d 39 97 4e bd b4 a3 60 f7 a0 1d
  |  
Microsoft Root Certificate Authority CertificateMicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72Microsoft Root Certificate Authority Certificate Revocation List (CRL)microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 |   | MicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72 | Microsoft Root Certificate Authority Certificate Revocation List (CRL) |   | microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4 |   |  
  | MicrosoftRootCert.crtThumbprint (sha1) : ‎‎cd d4 ee ae 60 00 ac 7f 40 c3 80 2c 17 1e 30 14 80 30 c0 72
Microsoft Root Certificate Authority Certificate Revocation List (CRL)
  | microsoftrootcert.crlAuthority Key Identifier (AKI) : 0e ac 82 60 40 56 27 97 e5 25 13 fc 2a e1 0a 53 95 59 e4 a4
  |  
Microsoft Root Certification Authority 2010 CertificateMicRooCerAut_2010-06-23.crtThumbprint (sha1) : ‎3b 1e fd 3a 66 ea 28 b1 66 97 39 47 03 a7 2c a3 40 a0 5b d5Microsoft Root Certification Authority 2010 Certificate Certificate Revocation List (CRL)MicRooCerAut_2010-06-23.crlAuthority Key Identifier (AKI) : d5 f6 56 cb 8f e8 a2 5c 62 68 d1 3d 94 90 5b d7 ce 9a 18 c4 |   | MicRooCerAut_2010-06-23.crtThumbprint (sha1) : ‎3b 1e fd 3a 66 ea 28 b1 66 97 39 47 03 a7 2c a3 40 a0 5b d5 | Microsoft Root Certification Authority 2010 Certificate Certificate Revocation List (CRL) |   | MicRooCerAut_2010-06-23.crlAuthority Key Identifier (AKI) : d5 f6 56 cb 8f e8 a2 5c 62 68 d1 3d 94 90 5b d7 ce 9a 18 c4 |   |  
  | MicRooCerAut_2010-06-23.crtThumbprint (sha1) : ‎3b 1e fd 3a 66 ea 28 b1 66 97 39 47 03 a7 2c a3 40 a0 5b d5
Microsoft Root Certification Authority 2010 Certificate Certificate Revocation List (CRL)
  | MicRooCerAut_2010-06-23.crlAuthority Key Identifier (AKI) : d5 f6 56 cb 8f e8 a2 5c 62 68 d1 3d 94 90 5b d7 ce 9a 18 c4
  |  
Microsoft Root Certification Authority 2011 CertificateMicRooCerAut2011_2011_03_22.crtThumbprint (sha1) : ‎8f 43 28 8a d2 72 f3 10 3b 6f b1 42 84 85 ea 30 14 c0 bc feMicrosoft Root Certification Authority 2011 Certificate Certificate Revocation List (CRL)MicrosoftRootCert.crlAuthority Key Identifier (AKI) : 72 2d 3a 02 31 90 43 b9 14 05 4e e1 ea a7 c7 31 d1 23 89 34 |   | MicRooCerAut2011_2011_03_22.crtThumbprint (sha1) : ‎8f 43 28 8a d2 72 f3 10 3b 6f b1 42 84 85 ea 30 14 c0 bc fe | Microsoft Root Certification Authority 2011 Certificate Certificate Revocation List (CRL) |   | MicrosoftRootCert.crlAuthority Key Identifier (AKI) : 72 2d 3a 02 31 90 43 b9 14 05 4e e1 ea a7 c7 31 d1 23 89 34 |   |  
  | MicRooCerAut2011_2011_03_22.crtThumbprint (sha1) : ‎8f 43 28 8a d2 72 f3 10 3b 6f b1 42 84 85 ea 30 14 c0 bc fe
Microsoft Root Certification Authority 2011 Certificate Certificate Revocation List (CRL)
  | MicrosoftRootCert.crlAuthority Key Identifier (AKI) : 72 2d 3a 02 31 90 43 b9 14 05 4e e1 ea a7 c7 31 d1 23 89 34
  |  

<div bi:type="oneMscomFooterLocaleLogo" id="ctl00_ctl22_mstFooterLocaleLogo" style="color: rgb(0, 0, 0); font-family: &quot;Architects Daughter&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; left: 0px; top: 0px;"><div id="ctl00_ctl22_mstFooterLogo"><p class="MsoNormal" style="margin: 0in 0in 0.0001pt; font-size: 12pt; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; vertical-align: baseline;"><a href="http://www.microsoft.com/en/us/default.aspx" style="color: rgb(162, 30, 33); text-decoration: underline;"><span style="font-size: 8.5pt; font-family: &quot;Segoe UI&quot;, &quot;sans-serif&quot;; color: rgb(21, 112, 166); text-decoration: none;"><img border="0" width="122" height="23" id="_x0000_i1025" src="microsoft_logo_footer_v3.png" alt="Microsoft"></span></a><span style="font-size: 8.5pt; font-family: &quot;Segoe UI&quot;, &quot;sans-serif&quot;; color: rgb(51, 51, 51);"><o:p></o:p></span></p></div></div><div style="color: rgb(0, 0, 0); font-family: &quot;Architects Daughter&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; left: 0px; top: 0px;"><div id="ctl00_ctl22_mstFooterCopyRight"><p class="MsoNormal" style="margin: 0in 0in 0.0001pt; font-size: 12pt; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; vertical-align: baseline;"><span style="font-size: 8.5pt; font-family: &quot;Segoe UI&quot;, &quot;sans-serif&quot;; color: rgb(51, 51, 51);">©2014 Microsoft<o:p></o:p></span></p></div><div bi:type="oneMscomFooterCorpLink" id="ctl00_ctl22_mstFooterCorpLink"><p class="MsoNormal" style="margin: 0in 0in 0.0001pt; font-size: 12pt; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; text-indent: -0.25in; vertical-align: baseline;"><span style="font-size: 10pt; font-family: Symbol; color: rgb(51, 51, 51);"><span>·<span style="font: 7pt &quot;Times New Roman&quot;;">        <span> </span></span></span></span><span style="font-size: 8.5pt; font-family: &quot;Segoe UI&quot;, &quot;sans-serif&quot;; color: rgb(51, 51, 51);"><a href="http://support.microsoft.com/contactus/?ws=mscom" style="color: rgb(162, 30, 33); text-decoration: underline;"><span style="color: rgb(0, 96, 166); text-decoration: none;">Contact Us</span></a><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt; font-size: 12pt; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; text-indent: -0.25in; vertical-align: baseline;"><span style="font-size: 10pt; font-family: Symbol; color: rgb(51, 51, 51);"><span>·<span style="font: 7pt &quot;Times New Roman&quot;;">        <span> </span></span></span></span><span style="font-size: 8.5pt; font-family: &quot;Segoe UI&quot;, &quot;sans-serif&quot;; color: rgb(51, 51, 51);"><a href="http://www.microsoft.com/About/Legal/EN/US/IntellectualProperty/Copyright/default.aspx" style="color: rgb(162, 30, 33); text-decoration: underline;"><span style="color: rgb(0, 96, 166); text-decoration: none;">Terms of Use</span></a><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt; font-size: 12pt; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; text-indent: -0.25in; vertical-align: baseline;"><span style="font-size: 10pt; font-family: Symbol; color: rgb(51, 51, 51);"><span>·<span style="font: 7pt &quot;Times New Roman&quot;;">        <span> </span></span></span></span><span style="font-size: 8.5pt; font-family: &quot;Segoe UI&quot;, &quot;sans-serif&quot;; color: rgb(51, 51, 51);"><a href="http://www.microsoft.com/About/Legal/EN/US/IntellectualProperty/Trademarks/EN-US.aspx" style="color: rgb(162, 30, 33); text-decoration: underline;"><span style="color: rgb(0, 96, 166); text-decoration: none;">Trademarks</span></a><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 0.0001pt; font-size: 12pt; font-family: &quot;Times New Roman&quot;, &quot;serif&quot;; text-indent: -0.25in; vertical-align: baseline;"><span style="font-size: 10pt; font-family: Symbol; color: rgb(51, 51, 51);"><span>·<span style="font: 7pt &quot;Times New Roman&quot;;">        <span> </span></span></span></span><span style="font-size: 8.5pt; font-family: &quot;Segoe UI&quot;, &quot;sans-serif&quot;; color: rgb(51, 51, 51);"><a href="http://go.microsoft.com/fwlink/?LinkId=248681" style="color: rgb(162, 30, 33); text-decoration: underline;"><span style="color: rgb(0, 96, 166); text-decoration: none;">Privacy Statement</span></a></span></p></div></div>
</body>
</html>

But when you try and open up their links it sends me errors
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee20453a-60c5-91b0-0e1c-4c0fd48de570
* Version Independent ID: e61856a8-ad86-bed6-601f-69b69128f06c
* Content: [What's new in DevTools (Microsoft Edge 94) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2021/09/devtools)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2021/09/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/whats-new/2021/09/devtools.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Sorry @louisthedevil but this isn't the right place to post about this. This repository is for discussing issues with the Microsoft Edge developer documentation. I will close this now. Thank you for your understanding.
