### ISSUE TITLE
Learned the difference between HTML and the DOM

### ISSUE THREAD

**Issue by JunhaumHayden** [MicrosoftDocs/edge-developer#1629]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af36f2d-2484-c91c-fb12-e7578e806a74
* Version Independent ID: b3314d62-4834-f737-0e6a-8ab762435fae
* Content: [DevTools for beginners: Get started with HTML and the DOM - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/beginners/html#prerequisites)
* Content Source: [microsoft-edge/devtools-guide-chromium/beginners/html.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/beginners/html.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing for lack of information. Please feel free to respond and we can re-open the issue.
