### ISSUE TITLE
WebView2 Evergreen installer no longer adds the registry key recommended for detection

### ISSUE THREAD

**Issue by psycholns** [MicrosoftDocs/edge-developer#1633]
To verify that the webview2 runtime is installed we check (as recommended) the registry key at:
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}

This has worked so far, but now, if uninstalling the webview2 component (then the above key is deleted) and installing it again won't add that key, and therefore our users without the runtime end up in a (manual) install loop.

Verified on 2 machines so far.  And looking at our logs it seems to have been an issue since around the 3rd (installer successful but no runtime detected afterwards).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute a WebView2 app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@psycholns - sorry to hear about this issue. Can you post on the following repo where the Engineering team can provide the support you need to get unblocked?
https://github.com/MicrosoftEdge/WebView2Feedback
