### ISSUE TITLE
No mention of Linux in the roadmap?

### ISSUE THREAD

**Issue by StephenMcConnel** [MicrosoftDocs/edge-developer#1638]
[Enter feedback here]
Why is there no mention of Linux in the roadmap?  Has that been dropped?  If so, WebView2 is almost worthless from my company's viewpoint since we support both Windows and Linux in many of our products.  If it were easy, we'd love to support MacOS as well but have limited resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dec166ea-3192-50ac-a930-f2185226801f
* Version Independent ID: a7055048-1b57-b2dc-78ae-6786d8765467
* Content: [Roadmap for Microsoft Edge WebView 2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap)
* Content Source: [microsoft-edge/webview2/roadmap.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/roadmap.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for your question. Linux support is on the roadmap, but there are no concrete plan for it yet. Please see more details and (register your interest) on this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/645

As for updating the roadmap doc you linked to, good question, I'll add a task on our backlog to update the doc. Thanks!
