### ISSUE TITLE
Dev tools failed to load service worker

### ISSUE THREAD

**Issue by Rodern** [MicrosoftDocs/edge-developer#1639]
DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/npm/@pwabuilder/pwa-update.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

The error show that the file is not there
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ce6ac4-36b1-0520-6474-37a2bb2f78bd
* Version Independent ID: a17cb98d-72db-1b3c-9d89-1af2773617ab
* Content: [Get started with Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/index.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing for lack of response.
