### ISSUE TITLE
background property key documentation does not include persistent property key

### ISSUE THREAD

**Issue by Yetoo1** [MicrosoftDocs/edge-developer#164]
The background manifest key and subkeys documented here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background
does not include the persistent subkey featured here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e322d0db-8a91-6fff-7510-a5ec18fa4a65
* Version Independent ID: 0c60d518-08f5-3b4e-0f4b-b7cd71455951
* Content: [Extensions - Creating an extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/creating-an-extension)
* Content Source: [microsoft-edge/extensions/guides/creating-an-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/creating-an-extension.md)
* Product: **microsoft-edge**
* GitHub Login: @libbymc
* Microsoft Alias: **libbymc**

**Comment by mattwojo** [comment]
Working on a re-write of this Extension content @Yetoo1 --- I'll update once we have things corrected.

**Comment by goneneren** [comment]
This example is not working... Will there be any updates?

**Comment by Reezaali** [comment]
Hi @Yetoo1 and @goneneren, with the release of the new Microsoft Edge, can you look at the updated documentation [here](https://docs.microsoft.com/microsoft-edge/extensions-chromium/getting-started/)?
