### ISSUE TITLE
Angular and WebView2

### ISSUE THREAD

**Issue by afbarksd** [MicrosoftDocs/edge-developer#1647]
[Enter feedback here]

It would be very helpful to have an example on getting data to C# from Angular using WebView2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0f291fb-5bcf-0319-da09-ca1a2dc9b023
* Version Independent ID: d96ef94e-4a68-0671-bb38-47bde4035be9
* Content: [Get started with WebView2 in Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32)
* Content Source: [microsoft-edge/webview2/get-started/win32.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/win32.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for your feedback. My immediate thought is that this part of the docs is probably not likely to focus on one specific JavaScript framework (Angular), but instead should keep it pretty generic. That being said, having an example of getting data from JavaScript to the native code does seem useful to add.

I believe this is what this section is for: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32#step-6---communication-between-host-and-web-content
Indeed, your JavaScript code (whether you use Angular, React, or anything else), can use the `window.chrome.webview.postMessage` method to send data to the host native code.

Does this help? Or were you looking for something different @afbarksd ?

**Comment by captainbrosset** [comment]
Closing now, I think the doc I linked to above addresses the issue.

**Comment by afbarksd** [comment]
Thanks.
