### ISSUE TITLE
[DevTools Docs Feedback]

### ISSUE THREAD

**Issue by Hasmukhginoya** [MicrosoftDocs/edge-developer#1649]
how to hide "All sites in this tab will be opened in internet explorer mode" in Edge with IE Mode?
Hi
I have create C# application to to launch MSEDGE.exe in IE mode using command line switch.
               ProcessStartInfo processInfo = new ProcessStartInfo();
                processInfo.FileName = "msedge";                
                StringBuilder arguments = new StringBuilder();                
                arguments.Append(" --ie-mode-force");
                arguments.Append(" --internet-explorer-integration=iemode");
                arguments.Append(" --no-first-run");
                arguments.Append(" --no-service-autorun");
                arguments.Append(" --disable-sync");
                arguments.Append(" --test-type");              
                arguments.Append(" --disable-features=msImplicitSignin");
                arguments.Append(" --user-data-dir=" + getEdgeTempFolder());
                arguments.Append(" www.google.com");
                processInfo.Arguments = arguments.ToString();              
                Process process = new Process();
                process.StartInfo = processInfo;
                process.Start();

The above code will launch Microsoft Edge with IE mode. but when the page is displayed it will also display information bar on the top with "All sites in this tab will be opened in internet explorer mode".
How can i hide this information bar when it launch through any command line switch ?

this is the image of launching Edge with IE mode
![Edge with IE mode](https://user-images.githubusercontent.com/87067999/147384639-9a235dae-7462-41a7-8256-848ba4880504.JPG)
.

**Comment by captainbrosset** [comment]
Sorry about the delay. I'm currently trying to get information about this, and will update this issue as soon as I can.
