### ISSUE TITLE
gyeongche-githup.com

### ISSUE THREAD

**Issue by gyeongche** [MicrosoftDocs/edge-developer#1652]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bdbaf0-1a39-c369-deca-d22e0d4e6ec0
* Version Independent ID: 7ec272a7-8291-5d33-f320-ef7f1bcd9648
* Content: [Contact Microsoft Edge extensions support - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team)
* Content Source: [microsoft-edge/extensions-chromium/publish/contact-extensions-team.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/publish/contact-extensions-team.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
No feedback was entered here. This is likely a spam issue.

**Comment by gyeongche** [comment]
QQmail


------------------ Original ------------------
From: Patrick Brosset ***@***.***&gt;
Date: Mon,Jan 3,2022 11:50 PM
To: MicrosoftDocs/edge-developer ***@***.***&gt;
Cc: 김경철 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [MicrosoftDocs/edge-developer] gyeongche-githup.com (Issue #1652)






Closed #1652.

**Comment by gyeongche** [comment]
杰森
***@***.***

个人
经商
01051057772
韩国



------------------ Original ------------------
From: Twitter ***@***.***&gt;
Date: Sun,Mar 13,2022 11:56 AM
To: 경철김 ***@***.***&gt;
Subject: Fw: New login to Twitter from 9.3.0 on iPhone



           
    
       &nbsp;  
         
     
            We noticed a login to your account @gimgyeongche from a new device. Was this you?  
   
   New login  
   
           Location*   대한민국 광주시, 대한민국  
  Device   9.3.0 on iPhone  
    
    
   
   *Location is approximate based on the login's IP address.  
   
   If this was you  
   
   You can ignore this message. There's no need to take any action.  
   
   If this wasn’t you  
   
   Complete these steps now to protect your account.  
   
    
Change your password. You'll be logged out of all your active Twitter sessions except the one you're using at this time.  

Review the apps that have access to your account and revoke access to any unfamiliar apps. Learn more. 
  
   
     
        &nbsp;  
   &nbsp;       How do I know an email is from Twitter?  
   
   Links in this email will start with “https://” and contain “twitter.com.” Your browser will also display a padlock icon to let you know a site is secure.  
     &nbsp;  
   &nbsp;  
     
       
    Help &nbsp;|&nbsp; Email security tips   
   
    We sent this email to @gimgyeongche   
   
    Twitter, Inc. 1355 Market Street, Suite 900 San Francisco, CA 94103

**Comment by gyeongche** [comment]
四合院
***@***.***

个体
+821051057772



------------------ Original ------------------
From: 四合院 ***@***.***&gt;
Date: Sun,Mar 13,2022 0:14 PM
To: Google ***@***.***&gt;, gyeongche ***@***.***&gt;, jin8899qing ***@***.***&gt;, kim1388 ***@***.***&gt;, Twitter Support ***@***.***&gt;, 네이버 ***@***.***&gt;, help+id6278714 ***@***.***&gt;, media.help ***@***.***&gt;, CyberNews ***@***.***&gt;, officialpartner ***@***.***&gt;, Apple ***@***.***&gt;, Apple 지원 커뮤니티 알림 ***@***.***&gt;, appleid ***@***.***&gt;, BMW ID ***@***.***&gt;, appleid_cnzh ***@***.***&gt;, appleid_krko ***@***.***&gt;, applesupport ***@***.***&gt;, author ***@***.***&gt;, edge-developer ***@***.***&gt;, gyeongche ***@***.***&gt;, imprint.driversguide ***@***.***&gt;, info ***@***.***&gt;, itunes_china_support ***@***.***&gt;, jinqingzhe5102 ***@***.***&gt;, 极客狗 ***@***.***&gt;, シ Pluto ***@***.***&gt;, kim1388 ***@***.***&gt;, kim1388 ***@***.***&gt;, kim1388 ***@***.***&gt;, kim1388 ***@***.***&gt;, ***@***.*** ***@***.***&gt;, ***@***.*** ***@***.***&gt;, 孔老大 ***@***.***&gt;, LinkedIn 채용공고 알림 ***@***.***&gt;, 流浪人2 ***@***.***&gt;, 牡丹江八面通时彦英 ***@***.***&gt;, Microsoft 계정 팀 ***@***.***&gt;, mok ***@***.***&gt;, olleh.app ***@***.***&gt;, 思杰马克丁软件 ***@***.***&gt;, privacy_response ***@***.***&gt;, recommendations ***@***.***&gt;, reply+avamjfournp72mlyzjprsxv733xedevbnhheceggxe ***@***.***&gt;, support ***@***.***&gt;, 腾讯视频 ***@***.***&gt;, wecom_dp ***@***.***&gt;, wgo ***@***.***&gt;, wxsticker_support ***@***.***&gt;, 875125881ji ***@***.***&gt;, 875125881jin ***@***.***&gt;, 김경철 ***@***.***&gt;, 경철김 ***@***.***&gt;
Subject: Re: Fw: New login to Twitter from 9.3.0 on iPhone



 





杰森
***@***.***

个人
经商
01051057772
韩国



------------------ Original ------------------
From: Twitter ***@***.***&gt;
Date: Sun,Mar 13,2022 11:56 AM
To: 경철김 ***@***.***&gt;
Subject: Fw: New login to Twitter from 9.3.0 on iPhone



           
    
       &nbsp;  
         
     
            We noticed a login to your account @gimgyeongche from a new device. Was this you?  
   
   New login  
   
           Location*   대한민국 광주시, 대한민국  
  Device   9.3.0 on iPhone  
    
    
   
   *Location is approximate based on the login's IP address.  
   
   If this was you  
   
   You can ignore this message. There's no need to take any action.  
   
   If this wasn’t you  
   
   Complete these steps now to protect your account.  
   
    
Change your password. You'll be logged out of all your active Twitter sessions except the one you're using at this time.  

Review the apps that have access to your account and revoke access to any unfamiliar apps. Learn more. 
  
   
     
        &nbsp;  
   &nbsp;       How do I know an email is from Twitter?  
   
   Links in this email will start with “https://” and contain “twitter.com.” Your browser will also display a padlock icon to let you know a site is secure.  
     &nbsp;  
   &nbsp;  
     
       
    Help &nbsp;|&nbsp; Email security tips   
   
    We sent this email to @gimgyeongche   
   
    Twitter, Inc. 1355 Market Street, Suite 900 San Francisco, CA 94103
