### ISSUE TITLE
Can't share with alternative email clients.

### ISSUE THREAD

**Issue by FamilyMan** [MicrosoftDocs/edge-developer#1656]
[Enter feedback here]

My default email application is Thunderbird but when I use the navigator.share, the window that pops up only gives me the option to use Windows Mail. How can I add Thunderbird to this selection?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfe02e5-3055-2d0a-8182-50ae48604b68
* Version Independent ID: 79956c0d-e17f-c832-9d79-22e0cbcee96c
* Content: [Share content with other apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/share)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/share.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/share.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out.

In this case you can't really change what appears in the share dialog. When you use `navigator.share`, you ask the OS to display the share dialog. But it's then up to it to populate it with the right applications. Your code doesn't have a way to change this.

When applications get installed on Windows, they tell the OS to get registered as share targets.

So maybe Thunderbird doesn't do this, or maybe it needs to be re-installed again. I'm not sure.
I would advise trying to share from another app and seeing if Thunderbird appears in this case. For example, you can select some text on this page, then right-click on the selection and click on "Share". The share dialog should appear. If you see Thunderbird in the list, then that means it might be a Windows problem. If you don't see it, then I'd suggest getting in touch with the Thunderbird support, asking them why the app doesn't register itself as a share target (reporting thunderbird bugs is done on Mozilla's [bug tracker](https://bugzilla.mozilla.org/home)).

**Comment by FamilyMan** [comment]
Thanks for the quick response. I have seen over on Mozilla that this is a feature still yet to be implemented in Thunderbird.

**Comment by captainbrosset** [comment]
Ah, that makes sense then. Thanks for replying,
