### ISSUE TITLE
URL Handling Demo Does Not Work

### ISSUE THREAD

**Issue by rigiddesign** [MicrosoftDocs/edge-developer#1669]
The demo given here, for handling URLs, does not work in the current build of Edge, nor does it work in Edge Canary.

I have tried installing the app via both browsers and triggering a link; No links open in either PWA. I am trying to implement this for my own apps, but I am unable to do so as the documentation is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9788272c-700b-9e60-d419-0f845a1ff644
* Version Independent ID: 4e4fbf06-2d8e-bb66-ee1b-07f9d32a940e
* Content: [Handle URLs in Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-urls)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/handle-urls.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/handle-urls.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out and reporting this issue. Unfortunately the URL handling PWA feature is being phased out in favor of 3 other features. The design of the feature wasn't satisfactory, and so the teams have gone back to the drawing board.
The 3 new features that this will be replaced with are:

* A new (and simpler) `handle_links` manifest member, for simple cases where same-context URLs need to be handled. https://github.com/WICG/pwa-url-handler/blob/main/handle_links/explainer.md
* A new `scope_extensions` members to allow web apps to tell the OS which other contexts they own (like when an app has several domain names). https://github.com/WICG/manifest-incubations/blob/gh-pages/scope_extensions-explainer.md
* A new launch handler mechanism to let apps decide if new instances need to be launched or if the existing one should be reused. https://github.com/WICG/sw-launch/blob/main/launch_handler.md

So we need to update this documentation page and sample, and we have this on our backlog already.
But, even before that happens, I think it makes sense for us to update the page by removing the demo, and adding a banner telling people that the API will change soon.

**Comment by captainbrosset** [comment]
I tested again the demo app and it still worked for me though. Even if the feature is being phased out, it's still available in Edge (all versions, as far as I can tell), and is still in an origin trial.

@rigiddesign could you please test these 2 things:

* make sure you enable the feature in `edge://flags`, as described in the docs
* test the link handling outside of the browser. In-browser navigation isn't supported by this feature. For example, you can use the Windows Run app to launch a URL.

If it still doesn't work, please provide more information about your testing setup.

Overall though, I wouldn't spend too much time learning to use this feature as it's going away soon.
One related feature recently came out of origin trial, and you might interested in it: protocol handling. You can learn more about it here: https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-protocols

**Comment by rigiddesign** [comment]
Hello buddy,

Thank you for responding to this. The flag is definitely on:

[Graphical user interface, text  Description automatically generated]

Running this just opens it in the browser:

[Graphical user interface  Description automatically generated]

I installed this via Edge Canary and also the current build of Edge, so very strange it is not working. My own PWA was opening links previously, so when it stopped working, I stumbled across the demo and found to find it had the same issue.

I even tried switching which of the Edge versions was my default browser during testing. Could the issue relate ot having Canary & the current build installed?

I did find the Launch Handler stuff, as per the experimental flags but, after trying to get it to work for a bit, I then realised it’s only currently ready in Chrome OS.

Thank you for pointing out the protocol handling. I can try this. That flag isn’t in Canary though, so is it being dropped? I noticed the tabbed stuff is no longer in Canary which I am shocked about. It seems the tabbed interface is being removed too ☹

Regards,

Tim Maiden
Developer
0113 524 1791
07745 706666

**Comment by captainbrosset** [comment]
Unfortunately the screenshots didn't come through on github. If you get a chance, please try to attach them again here.

There may be a case where the feature only works if "stable" is your default browser, and you installed the PWA from that browser. But I'm not 100% sure.
@diekus might be able to help us get to the bottom of this.

> Thank you for pointing out the protocol handling. I can try this. That flag isn’t in Canary though, so is it being dropped?

No it isn't being dropped, the feature is now on by default on all channels of Edge. No need to turn on any flags at all. I'm currently updating the docs to remove the section about the flag and origin trial.

**Comment by rigiddesign** [comment]
Apologies, I have updated that above comment.

**Comment by captainbrosset** [comment]
> The tabbed interface of PWAs is missing from Edge and Chrome Canary, though. Has that been scrapped?

I am not very familiar with the tabbed interface. Are you talking about the feature behind flag `#enable-desktop-pwas-tab-strip`?
If so, it seems like this has been extended in Chrome: `3379602: Extend tabbed web app feature flag expiries` -> https://chromium-review.googlesource.com/c/chromium/src/+/3379602

Edge will likely do the same thing.

That being said, here isn't the best place to discuss this. If the problem persists, could you please send feedback about this through the feedback button in Edge? (click the `...` button in the toolbar, then `help and feedback, and then `Send feedback`.

**Comment by rigiddesign** [comment]
Yes, I do that pretty frequently :-)

I see, after weeks, the [tabbed] flags are back in Chrome Canary so, like you say, they will likely appear in Edge Canary again, too.

**Comment by captainbrosset** [comment]
Closing this issue as a PR was just merged with the following changes:

1. https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-protocols now doesn't mention the flag/origin trial, since the feature is on by default.
2. https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-urls a note about the feature being phased out and replaced by 3 other features was added.
