### ISSUE TITLE
Character limit?

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/edge-developer#167]
It seems that there is a character limit for the api. console.log() for example, truncates the output after 1024 characters. This limit should be in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdce36b3-a44f-e2b3-75b1-279409a15bbf
* Version Independent ID: afc9bceb-934f-c259-f872-747765121720
* Content: [Microsoft Edge DevTools - Console - Console API - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console/console-api#logging-custom-messages)
* Content Source: [microsoft-edge/devtools-guide/console/console-api.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/console/console-api.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by mattwojo** [comment]
Thanks for pointing this out @damienestewart!  We're going to confirm whether there is a plan to drop this character limit in the near future and will update the doc to reflect.
