### ISSUE TITLE
Offline deployment recommendations are now obsolete - running installer elevated and checking registry key

### ISSUE THREAD

**Issue by Scottj1s** [MicrosoftDocs/edge-developer#1670]
In the offline-deployment section, two techniques are suggested for detecting whether the runtime is installed.  A recent change to the installer permits it to be run without elevation.  The install still succeeds, but the registry key is no longer written, so cannot be checked for installation status.  Instead, the only reliable technique now is to call GetAvailableCoreWebView2BrowserVersionString.  

Note that for WindowsAppSDK apps, this also requires the workaround documented here:
https://github.com/microsoft/microsoft-ui-xaml/issues/5689#issuecomment-982128778

The Offline deployment section should remove references to checking the registry key, and to running the installer elevated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute a WebView2 app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#feedback)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Scottj1s** [comment]
Alternatively, docs could be updated to state that registry checking must now look for the key in both HKLM and HKCU.  But mention of running elevated should still be removed.

**Comment by captainbrosset** [comment]
Thanks for filing. We've added an item on our backlog to address the documentation change. We'll come back and update this issue.

**Comment by champnic** [comment]
@Scottj1s The deployment docs have been updated to include the new reg key. Thanks!
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment
