### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by savaged** [MicrosoftDocs/edge-developer#1672]
Followed the steps including the prerequisites and the CoreWebView2 is always null.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99f63e2b-08f3-0123-0290-81ed8e9007a8
* Version Independent ID: ddea56f8-1ea4-ac98-1a18-00b107f46a3e
* Content: [Get started with WebView2 in WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/wpf)
* Content Source: [microsoft-edge/webview2/get-started/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jasonstephen15** [comment]
@savaged - which step in the getting started guide are you stuck on?

**Comment by max-meng1** [comment]
You need to call EnsureCoreWebView2Async before accessing CoreWebView2 object, also did you installed Webview runtime?

**Comment by captainbrosset** [comment]
It does not seem to me like documentation changes are needed here, so I will close this issue for now. You might be interested in opening issues on [the WebView2Feedback repository](https://github.com/MicrosoftEdge/WebView2Feedback) instead.
But please, do let me know if the docs need to be improved, in which I can re-open the issue and work on the improvements.
