### ISSUE TITLE
the github for this page only has Core, not Framework

### ISSUE THREAD

**Issue by abaljeu** [MicrosoftDocs/edge-developer#1687]
Although the instructions provided here seem to be for either framework, I cannot access a working project from Github that is compatible with .net framework 4.8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99f63e2b-08f3-0123-0290-81ed8e9007a8
* Version Independent ID: ddea56f8-1ea4-ac98-1a18-00b107f46a3e
* Content: [Get started with WebView2 in WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/wpf)
* Content Source: [microsoft-edge/webview2/get-started/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out, we've discussed about this today and will find out more and get back to you!

**Comment by champnic** [comment]
Hey @abaljeu - Are you looking for a sample project on GitHub, like the ones we have here?
https://github.com/MicrosoftEdge/WebView2Samples

Or are you trying the Framework version and running into an issue specifically with 4.8?

**Comment by captainbrosset** [comment]
We unfortunately didn't get an answer. Let me close the issue for now. 
Feel free to comment on this issue still and I'll re-open it if needed.
