### ISSUE TITLE
[DevTools Docs Feedback]

### ISSUE THREAD

**Issue by dhammondhelient** [MicrosoftDocs/edge-developer#1688]
Hello!  I am trying to understand relationship between Microsoft Edge, Microsoft Edge WebView2 Runtime, and WebView2 SDK.  I know that there are independent release notes for Microsoft Edge and WebView2 SDK, but I can't seem to find where WebView2 Runtime's own release notes are.  Like for example, where would I go to find the release notes for Microsoft Edge WebView2 Runtime 97.0.1072.69 (the latest release)?  Are they included under Edge's or SDK's notes?  Also is WebView2 SDK a required component to download for Runtime, or is it an optional add-on?

**Comment by captainbrosset** [comment]
Thanks for your feedback. Great questions. I think you'll have more luck with getting answers to these over on the [WebView2Feedback repository](https://github.com/MicrosoftEdge/WebView2Feedback) though. So I'll transfer the issue over there.
