### ISSUE TITLE
cookies.remove  does not take effect

### ISSUE THREAD

**Issue by wzqiang1332** [MicrosoftDocs/edge-developer#169]
browser.cookies.getAll({
        url:"http://**/"
    },function(){
         for (let cookie of cookies) {
            console.log(cookie.value);
        }
   });
   
    browser.cookies.remove({url:"http://**",name:"JSESSIONID"},function(results){
        console.log(results)
    })

   getAll can get the cookies data,but can not remove

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06926489-8d16-3995-4965-810523179b4d
* Version Independent ID: a6a96e02-8db8-98ab-0bd6-bb93a2b5b4ea
* Content: [Extensions - JSON manifest example - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-manifest-keys/json-manifest-example)
* Content Source: [microsoft-edge/extensions/api-support/supported-manifest-keys/json-manifest-example.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/api-support/supported-manifest-keys/json-manifest-example.md)
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by mattwojo** [comment]
Investigating. Thanks @wzqiang1332

**Comment by gebansal** [comment]
Considering its an old thread and we have rolled out a new Chromium-based Edge browser, I'll go ahead and close it. If you still are facing any issues, please feel free to reopen this issue or file a new one.
