### ISSUE TITLE
force-major-version-to-100 flag is available only v98 or later

### ISSUE THREAD

**Issue by SIkebe** [MicrosoftDocs/edge-developer#1703]
777ef6f01f607f86bb692e3e59e3776e731713e9 changed how to emulate v100 to this phrase.
>Starting in Edge97, site owners can emulate this condition before v100 by enabling the experiment flag #force-major-version-to-100 in `edge://flags`

However, AFAIK, this flag is available only Edge v98 or later. 

Beta 98.0.1108.33
![image](https://user-images.githubusercontent.com/17608272/151296555-7fb9868a-06de-4fe2-a801-a2d97e946100.png)

Stable 97.0.1072.69
![image](https://user-images.githubusercontent.com/17608272/151296767-991b6e18-75e7-4d83-b3e2-634eee58463c.png)

@majenny Will this feature be backported to v97 as well ?

**Comment by captainbrosset** [comment]
Thanks for filing!
Just for context, the documentation being referred to here is this one: https://docs.microsoft.com/en-us/microsoft-edge/web-platform/site-impacting-changes.

Jenny is already pinged, so let's wait for her to come and respond. If the change is only available in 98, we'll go ahead and update the docs.

**Comment by majenny** [comment]
nice catch! The flag was released to the most recent version of Edge 97, which will be going out today (1/27)!
