### ISSUE TITLE
Quick example using webView.CoreWebView2.GetDevToolsProtocolEventReceiver 

### ISSUE THREAD

**Issue by ThomCBlackwellBSS** [MicrosoftDocs/edge-developer#1709]
A quick use example of webView.CoreWebView2.GetDevToolsProtocolEventReceiver would be very helpful. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4427408a-76c3-cd66-9232-ebc753b12112
* Version Independent ID: 0fa3d591-7cdb-aa6e-2b08-9dab228591a6
* Content: [Use the Chrome DevTools Protocol in WebView2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/chromium-devtools-protocol)
* Content Source: [microsoft-edge/webview2/how-to/chromium-devtools-protocol.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/chromium-devtools-protocol.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out. I'll create a task on our internal backlog to add an example as you requested. We'll get back to this issue with more information.

**Comment by ThomCBlackwellBSS** [comment]
Hi Patrick,
Thanks!
I was able to sort through it. Like anything I learn new, it’s always missing simple detail that trips me up – which was why I posted the suggestion.

What was tripping me up was a combination of needing to use the appropriate .enable method, realizing that the parameters needed to be JSON (which the methods do clearly indicate)  and of course learning DevToolsProtocol terminology in general, but that’s beyond the scope of this document).

Now that I’ve got the hang of it, DevToolsProtocolExtention has been easy to learn/work with – orders of magnitude easier than any of the alternatives I tried. I’ve made far more headway in my project than I imagined. You all have done a great job with this!

Regards,
Thom

Thom C. Blackwell,  VP Technical Services
Boston Software Systems, Inc.
Phone: 866.653.5105 x807
Mobile: 508.423.8463
Fax: 508.319.3015
www.bostonsoftwaresystems.com<http://www.bostonsoftwaresystems.com/>


Healthcare Automation - Revolutionizing How You Work.

Breaking News: KLAS Emerging Technology Spotlight Report on Boston Software Systems<https://www.bostonsoftwaresystems.com/KLAS-Research-eTech-Spotlight>

***@***.***<https://www.bostonsoftwaresystems.com/KLAS-Research-eTech-Spotlight>
The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.

**Comment by captainbrosset** [comment]
Thank you so much for getting back to me and sharing your experience with this.

**Comment by captainbrosset** [comment]
Over in #1736 @spustlik is also asking for an example of `DevToolsProtocolEventReceived` and provided the following code snippet:

```
            var handlerConsole = browser.CoreWebView2.GetDevToolsProtocolEventReceiver("Runtime.consoleAPICalled");
            handlerConsole.DevToolsProtocolEventReceived += (sender, e) =>
              {
                  var data = JObject.Parse(e.ParameterObjectAsJson);
                  // process data
              };
            await browser.CoreWebView2.CallDevToolsProtocolMethodAsync("Runtime.enable", "{}");
```

**Comment by captainbrosset** [comment]
After evaluation, we decided not to prioritize this particular request at this time in this repository.
If you need help on this, please check the https://github.com/MicrosoftEdge/WebView2Feedback repository where you can discuss with the team and other WebView2 users.
Thank you for your input.
