### ISSUE TITLE
What was wrong with HTA?

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftDocs/edge-developer#1712]
[Bad architecture](https://arstechnica.com/gadgets/2022/02/if-you-dont-use-teams-or-edge-in-windows-11-disabling-some-features-can-save-ram/) is impossible to change, on the delivered whatever.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Introduction to Microsoft Edge WebView2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out, but I fail to see how this is relevant to improving the Microsoft Edge developer documentation. So I will close this issue now.
