### ISSUE TITLE
WiX Bootstrapper Sample

### ISSUE THREAD

**Issue by chrpai** [MicrosoftDocs/edge-developer#1714]
This document is very comprehensive.  It would be useful if it went a step farther and just provide a WiX bootstrapper bundle sample including all the relevant details such as:

1) download urls
2)  digital signing thumbprint for download validation
3) install commands
4) detection logic... 32bit and this registry key  or 64bit and this registry key

For online and offline installation scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute a WebView2 app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by liminzhu** [comment]
Thanks for opening the issue @chrpai ! We have some example about WiX on https://github.com/MicrosoftEdge/WebView2samples#webview2-deployment. Note that the samples were done before we added the ability to install without elevation, so it only checks for the HKLM regkey not the HKCU one for WebView2's presence. We will have a bug tracking updating the samples. Cheers.

**Comment by captainbrosset** [comment]
Because WiX is one of many 3rd party installer tools available out there, we're not going to be adding specific documentation about it, but hopefully the sample @liminzhu provided is helpful enough.
