### ISSUE TITLE
Distribute WebView2 FixedRuntime: Incorrect code snippet

### ISSUE THREAD

**Issue by ottah** [MicrosoftDocs/edge-developer#1716]
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#details-about-the-fixed-version-runtime-distribution-mode

Closing tag for `CopyToOutputDirectory` is malformed
```
<Content Include="FixedRuntime\(version number)\\**\*.*">
<CopyToOutputDirectory>PreserveNewest<CopyToOutputDirector>
</Content>
```

Also might be more helpful to have include the `ItemGroup`:
```
<ItemGroup>
<Content Include="FixedRuntime\(version number)\\**\*.*">
	<CopyToOutputDirectory>
		PreserveNewest
	</CopyToOutputDirectory>
</Content>
</ItemGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute a WebView2 app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikehoffms** [comment]
Scroll up above section https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution?branch=main#known-issues-for-fixed-version
It now reads:
```
<ItemGroup>
  <Content Include="FixedRuntime\(version number)\\**\*.*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>
```

**Comment by captainbrosset** [comment]
Thank you @ottah for reporting the issue! Let's close it now since @mikehoffms says it's fixed.
