### ISSUE TITLE
Why is WebView2 so needlessly difficult to set up?

### ISSUE THREAD

**Issue by goldwaving** [MicrosoftDocs/edge-developer#1719]
When using Web View on Android and iOS, developers are not forced to manually download and install the Web View module on the end user's devices.  Most Windows 10 systems already include the entire Edge/Chrome browser, so the distribution model for WebView2 is ridiculous.

Forcing all developers to bundle WebView2Loader.dll is a waste.  This DLL should not even exist when it could easily be replaced by COM.

Forcing all developers to write code to download and run the installer is also an incredible waste.  What ever happened to "developers, developers, developers, ..."?

This module should be installed by Windows Update.  Make it an "optional update", if you have to.  But Windows should be taking care of all this and developers can simply advise users to just "get the update" and not some weird "Evergreen bootstrap" thing. 

As with Android and iOS, WebView2 should just be there on Windows and easily accessible.  Please make this easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0f291fb-5bcf-0319-da09-ca1a2dc9b023
* Version Independent ID: d96ef94e-4a68-0671-bb38-47bde4035be9
* Content: [Get started with WebView2 in Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32)
* Content Source: [microsoft-edge/webview2/get-started/win32.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/win32.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
@goldwaving thanks for reaching it. Have you already seen the different distribution models: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution ? Does this help?
If so, could it be that the Getting Started guide need to include this information for it to be more obvious from the start?

**Comment by goldwaving** [comment]
Why do these distribution models even exist?  Why is the developer burdened with the distribution of WebView2 at all?  It should "just be there" as it is in other OSes.  Why does WebView2Loader.dll even exist when COM could do the same thing?  These seem to be unnecessary complications that make it difficult for all developers.  A simplified creation function should exist that doesn't involve multiple levels of callbacks.

**Comment by liminzhu** [comment]
hey thanks for opening the issue @goldwaving. Some added context - 
 - We have WebView2 inboxed on Win11, so essentially like any other OSes, after a certain version, the platform is included as part of the OS. 
 - Right now WebView2 is on 200M+ Win10 devices. We are looking into what can be improved on Win10 to get more coverage. However, you can never 100% patch older OSes so we do expect developers to have the distribution workflow in place if they want all their downlevel end users to be covered. The workflow is captured in https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution.
 - The main function of the loader is to locate where the WebView2 binaries are and establish a connection between the APIs and the actual runtime that may or may not be there. You can statically link the loader to avoid bundling - https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/static.

**Comment by captainbrosset** [comment]
Closing this issue since it doesn't look like we'll need to update our docs (which this repo is about).
@goldwaving feel free to continue the conversation however. I would also like to point out that the [WebView2Feedback repo](https://github.com/MicrosoftEdge/WebView2Feedback) is a good place for this kind of conversation too.
