### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by feleciathom** [MicrosoftDocs/edge-developer#1722]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb159348-28e5-18af-cba2-1dbcde857de0
* Version Independent ID: 1049da4f-215a-0f72-f25a-9eba13bca908
* Content: [Inspect network activity - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/)
* Content Source: [microsoft-edge/devtools-guide-chromium/network/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/network/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Unfortunately this issue doesn't have enough information for us to investigate a potential problem.
Feel free to comment with more information if you have any, but in the meantime I'll close the issue.
