### ISSUE TITLE
Store release with WebView2 Runtime Fixed Version in WinUI2 app

### ISSUE THREAD

**Issue by alexispolakMURAL** [MicrosoftDocs/edge-developer#1726]
We want to publish a WinUI2 app package using WebView2 Fixed Runtime and distribute it in the Microsoft Store but I can't. When I make a relase build of the app using Fixed Version binaries the size of the package is around 15mb and doesn't include de 200+mb of the WebView2 Fixed Runtime. Is there any documentation on how to make the package with the WebView Fixed Runtime in it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute a WebView2 app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
@alexispolakMURAL I would encourage you to please ask the question again by filing an issue on the WebView2Feedback repository instead. Thanks!

➡️ https://github.com/MicrosoftEdge/WebView2Feedback
