### ISSUE TITLE
example for DevToolsProtocolEventReceived

### ISSUE THREAD

**Issue by spustlik** [MicrosoftDocs/edge-developer#1736]
Please add some example for DevToolsProtocolEventReceived, which is needed to enable like

```c#
            var handlerConsole = browser.CoreWebView2.GetDevToolsProtocolEventReceiver("Runtime.consoleAPICalled");
            handlerConsole.DevToolsProtocolEventReceived += (sender, e) =>
              {
                  var data = JObject.Parse(e.ParameterObjectAsJson);
                  // process data
              };
            await browser.CoreWebView2.CallDevToolsProtocolMethodAsync("Runtime.enable", "{}");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4427408a-76c3-cd66-9232-ebc753b12112
* Version Independent ID: 0fa3d591-7cdb-aa6e-2b08-9dab228591a6
* Content: [Use the Chrome DevTools Protocol in WebView2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/chromium-devtools-protocol)
* Content Source: [microsoft-edge/webview2/how-to/chromium-devtools-protocol.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/chromium-devtools-protocol.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Sorry about the delay here. I think this is already tracked in #1709 so I'll close this issue and add your comment in that other one. Thanks!
