### ISSUE TITLE
Configuration of raised issues, browserlist, etc.

### ISSUE THREAD

**Issue by tswaters** [MicrosoftDocs/edge-developer#1739]
This is a useful feature and all, but I wonder how it gets it's data re: browser support, how that data can be updated if at all.

As example, using  a `<dialog />` today will raise the following warning:

> 'dialog' is not supported by Firefox, Firefox for Android, Safari, Safari on iOS.

Which is _mostly_ true, however according to https://caniuse.com/dialog , support for firefox was added in version 98-99.

There is a hyperlink to 'webhint.io' which does make reference to support for browserlist under the heading "Can the hint be configured?" -- https://webhint.io/docs/user-guide/hints/hint-compat-api/html/?source=devtools#can-the-hint-be-configured

It looks like there's a separate extension specifically for webhint -- but the question can be raised -- what is the browserlist that the vanilla edge devtools are using, and can it be updated or configured?  

I poked around in the preferences and didn't see anything related to browserlist and there are no configuration options on the issues pane itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d3ec99-16ab-400e-5f1a-aaf1f79ef900
* Version Independent ID: a68ce21e-74ba-b319-a586-355918f499f7
* Content: [Find and fix problems using the Issues tool - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/issues/)
* Content Source: [microsoft-edge/devtools-guide-chromium/issues/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/issues/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out about this. The **Issues** tool in DevTools is indeed powered by [webhint](https://webhint.io/). And in this particular case, the **compat-api** hint relies on [browser-compat-data (BCD)](https://github.com/mdn/browser-compat-data/) which both caniuse and MDN also use to display browser compatibility information.

So it might just be a a dependency that's a bit outdated. Perhaps the version of Edge DevTools you currently have includes a version of webhint that relies on an outdated BCD package.

Let me ping @antross so he can investigate this a bit more and decide if this should be turned into an issue on the [webhint](https://github.com/webhintio/hint/) repo.

**Comment by antross** [comment]
Thanks @captainbrosset.

@tswaters we have some additional configuration options being added to the Issues panel, specifically to enable customizing your target browsers. It's technically in Edge Canary already, but there's a separate bug with the Issues panel there at the moment that needs resolved first before you can try it out. Prior to this update the Issues panel was using `defaults, not IE 11` for its browserslist configuration, but going forward it will be tailored based on the specific browsers you select.

As for the data about `<dialog>` this does come from the MDN browser-compat-data as @captainbrosset mentioned. That data was just updated recently to show support in Firefox: https://github.com/mdn/browser-compat-data/commit/ce9b0eb87d565f8d5e90f2d53efa9bdadb2a8865. The MDN update hasn't made it into webhint yet but should shortly (after which we'll include the update in the Issues panel).

**Comment by captainbrosset** [comment]
Thanks @antross. So based on the above, I'm closing this issue since there is no documentation changes needed. And the 2 problems (outdated dialog compat data and ability to configure browsers) are being worked on in other places.

**Comment by tswaters** [comment]
Thank you both for the detailed answer, much appreciated!
