### ISSUE TITLE
Instructions for Undocking unclear

### ISSUE THREAD

**Issue by simsal0r** [MicrosoftDocs/edge-developer#1741]
I want to "Undock into separate window" using "Change placement from the main menu". Yet, the screenshots and the descriptions do not help me to find "Click Customize and control DevTools". If this tutorial is only vaild for some beta/insiders build, this info is missing (found the page via Google).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0dff9d4-34da-5563-4b34-ca5ef03ade06
* Version Independent ID: 55519333-e802-ec65-1b49-8fe64fe04825
* Content: [Change DevTools placement (Undock, Dock to bottom, Dock to left) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/customize/placement)
* Content Source: [microsoft-edge/devtools-guide-chromium/customize/placement.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/customize/placement.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for your feedback. I agree that the screenshot is not helpful. We usually draw red rectangles around the areas that need to be clicked to match with the text instructions. But this one doesn't have anything.

I'll create a task on our backlog to improve this and we'll close this issue once the change has been made.

**Comment by mikehoffms** [comment]
@captainbrosset - Already fixed, as part of the pending, open PR 1665.
https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/customize/placement?branch=pr-en-us-1665 - shows entire window as context, with red box around Customize and control DevTools (...) and red box around the list of layouts.
