### ISSUE TITLE
Capital letter

### ISSUE THREAD

**Issue by ZachBagwell** [MicrosoftDocs/edge-developer#1742]
**bullet point 3 under the 'Log Network Activity' section has a capital letter where it doesn't belong. The 'H' in 'Choosing' is capitalized in the live version. It shouldn't be.

'....Initiator. The cause of the resource request. CHoosing a link in the Initiator column takes you to the source code that caused the request.'**
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb159348-28e5-18af-cba2-1dbcde857de0
* Version Independent ID: 1049da4f-215a-0f72-f25a-9eba13bca908
* Content: [Inspect network activity - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/)
* Content Source: [microsoft-edge/devtools-guide-chromium/network/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/network/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikehoffms** [comment]
Fixed; find "clicking" and "won't", in h2 section https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/#log-network-activity
