### ISSUE TITLE
The last 2 sections are missing

### ISSUE THREAD

**Issue by realivanjx** [MicrosoftDocs/edge-developer#1756]
The last 2 sections are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5949a483-1a4d-0f77-5576-af0a335fc959
* Version Independent ID: 824cf57c-044d-9dac-085a-8bcfd6f2dc15
* Content: [Customize the password reveal button - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal)
* Content Source: [microsoft-edge/web-platform/password-reveal.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/password-reveal.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikehoffms** [comment]
To fix, we'll change from ::: image tagging to Markdown image tagging.

**Comment by mikehoffms** [comment]
@realivanjx - Retagged & rewrote the page:
https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal
(I didn't go so far as to clean up red boxes on 2nd image.)
