### ISSUE TITLE
In VS2022 Using framework 4.6.2 The nuget packages raise warnings after a couple of builds

### ISSUE THREAD

**Issue by SabrinaCs** [MicrosoftDocs/edge-developer#1761]
I'm using WebView2 on a WPF project, with framework 4.6.2 and as stated above, after a couple of Builds of the projects with references to the Webview2 components from nuget show the following warnings:

Warning		The referenced component 'C:\Users\Myuser\.nuget\packages\microsoft.web.webview2\1.0.1108.44\build\..\lib\Microsoft.Web.WebView2.Core.winmd' could not be found.	ProjectName1			
Warning		The referenced component 'myprojectfolder\MIxerConsole\packages\Microsoft.Web.WebView2.1.0.1108.44\build\..\lib\Microsoft.Web.WebView2.Core.winmd' could not be found.	ProjectName2			
Warning		The referenced component 'Microsoft.VCLibs.Desktop' could not be found.	ProjectName1			
Warning		The referenced component 'Microsoft.VCLibs.Desktop' could not be found.	projectName2		

The warnings are repeated for each of the projects.

If I take a look I find two references with the warning signs

D:\Dev\Current\BokMixer\BokMixerSolution\MIxerConsole\packages\Microsoft.Web.WebView2.1.0.1108.44\build\..\lib\Microsoft.Web.WebView2.Core.winmd	(name and identity are the same)

Microsoft.VCLibs.Desktop  (name)
Microsoft.VCLibs.Desktop, Version=14.0 (identity)

There is also the Webview2 Nuget Package (with no warning)

I suspect there is some glitch in the generation of the nuget packages that creates this small problem, because if I delete the two references and rebuild the warnings disappear and the webview2 component works correctly
If I leave the two references with the warnings the component works also correctly probably because the nuget packages are somehow repaired. 
After the delete, when I rebuild a couple of times the references with the warning reappear.

I wanted to give you this feedback so you can take a look and tell us how to solve the problem.

Regards
Sabrina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Introduction to Microsoft Edge WebView2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out @SabrinaCs. Could you please create a new issue on the WebView2Feedback repository instead?
https://github.com/MicrosoftEdge/WebView2Feedback/issues

I think your problem will be better solved over there.

**Comment by SabrinaCs** [comment]
I've added the issue as you suggested so I close this one. Thanks Sabrina

**Comment by captainbrosset** [comment]
Thanks a lot SabricaCs.
