### ISSUE TITLE
Page keeps locking up and cannot x out of it

### ISSUE THREAD

**Issue by SpEcIaLiStJoKeR** [MicrosoftDocs/edge-developer#1765]
I dropped a screenshot. This is all its doing. I have to close it out and restart.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af36f2d-2484-c91c-fb12-e7578e806a74
* Version Independent ID: b3314d62-4834-f737-0e6a-8ab762435fae
* Content: [Get started with HTML and the DOM - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/beginners/html)
* Content Source: [microsoft-edge/devtools-guide-chromium/beginners/html.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/beginners/html.md)
* Product: **microsoft-e
![Screenshot 2022-02-24 020638](https://user-images.githubusercontent.com/83060111/155484339-e2171dc4-28b9-4b00-ac4a-f9bffc2e4d52.png)
dge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
@SpEcIaLiStJoKeR can you please be more specific as to what your problem is? When does this happen exactly? Can you write the steps one would need to take to replicate the issue?

**Comment by SpEcIaLiStJoKeR** [comment]
Good morning Mr. Brosset, I apologize. It's not doing it now. I don't know. If it does it again I'll write the step by step process.
________________________________

**Comment by captainbrosset** [comment]
Thanks. Closing the issue now until the problem happens again.
