### ISSUE TITLE
Install PWA to Windows without Windows Store(UWP).

### ISSUE THREAD

**Issue by omonoe** [MicrosoftDocs/edge-developer#177]
Google chrome is able to install PWA to desktop without any app runtime. 
https://developers.google.com/web/updates/2018/05/dpwa
Will MSEdge also be able to do it?
I think PWA is PWA, UWP is UWP, it's different from each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31da9c54-4efd-6f71-1ef3-67d796c71cb4
* Version Independent ID: eb5e84cd-b850-fa16-a8b2-5900d6dce2ee
* Content: [Progressive Web Apps on Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps)
* Content Source: [microsoft-edge/progressive-web-apps.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
At this time PWAs require WWAHost.exe to run as full-fledged Windows 10 apps. We're listening to customers like you though @omonoe. Please do add your ideas and requests for the future of PWAs on Windows to the Edge team UserVoice forum: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer . Thank you!

**Comment by WhatFreshHellIsThis** [comment]
Seriously?  The whole point of PWA's is to avoid the walled garden issue and the first time you enable it you put it in a walled garden?  What a joke.
