### ISSUE TITLE
webdriver.EDGE() does not give options as a possible argument. How would I have a headless edge browser?

### ISSUE THREAD

**Issue by DylanTMeyers** [MicrosoftDocs/edge-developer#1780]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver to automate Microsoft Edge - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=python)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by DylanTMeyers** [comment]
I figured it out I was using the old version of Selenium. Selenium 3, I upgraded to Selenium 4. 

Thx!

**Comment by captainbrosset** [comment]
Awesome! Glad things are working for you now.
