### ISSUE TITLE
The disabling of the context menu and drag and drop needs to be done after navigation is completed to work.

### ISSUE THREAD

**Issue by TheUsual251** [MicrosoftDocs/edge-developer#1794]
The disabling of the context menu and drag and drop needs to be done after navigation is completed to work. Do it in the NavigationCompleted event handler.

```
private async void webView_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
{
    await webView.CoreWebView2.ExecuteScriptAsync("window.addEventListener('contextmenu', window => {window.preventDefault();});");

    await webView.CoreWebView2.ExecuteScriptAsync("window.addEventListener('dragover',function(e){e.preventDefault();},false);");

    await webView.CoreWebView2.ExecuteScriptAsync("window.addEventListener('drop',function(e){" +
    "e.preventDefault();" +
    "console.log(e.dataTransfer);" +
    "console.log(e.dataTransfer.files[0])" +
    "}, false);");
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 177fdaec-b7fe-06f9-6fba-0828e9c0e00b
* Version Independent ID: 532a4b26-8e09-964b-5510-9d4dec158cdb
* Content: [Call web-side code from native-side code - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/javascript)
* Content Source: [microsoft-edge/webview2/how-to/javascript.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/javascript.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
We added the content. See here for more details: https://github.com/MicrosoftDocs/edge-developer/pull/1851/commits/ee7b4a4ce8d80f51b3343f43ec78e44c86c1908d
