### ISSUE TITLE
Does not work, Are there verrsioning issues

### ISSUE THREAD

**Issue by Robin-m-Sartorius** [MicrosoftDocs/edge-developer#1797]
[Enter feedback here]
I have downloaded the Fixed Version WebView2 installed in a well known folder and set the BrowserExecutableFolder  to point to that folder but this.webBrowser.Source still throws an exception.
I set the CreationProperties on the line before setting the Source. I expect this is user error but I cannot spot my mistake. Do the .NET Assemblies have to match the Fixed Version's version if so where do we get them from?

      this.webBrowser.CreationProperties.BrowserExecutableFolder = Path.Combine(Environment.CurrentDirectory, "WebView2");
      this.webBrowser.Source = new Uri("http://localhost:5000");
But that throws: 
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: 'Couldn't find a compatible Webview2 Runtime installation to host WebViews.'
Inner exception
{"The system cannot find the file specified. (Exception from HRESULT: 0x80070002)":null}

![image](https://user-images.githubusercontent.com/101461998/158020336-cecae544-c319-4d13-a30a-d2125b47c989.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute your app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. This repo is focused on the developer documentation only, and it seems like your issue would be better handled on our WebView2 developer feedback repo: https://github.com/MicrosoftEdge/WebView2Feedback
Could you please move it there? Once your issue is solved, and if you think the documentation should be improved, please file an issue here so we can make the necessary changes!
