### ISSUE TITLE
How long does it takes once you've filled the submission form

### ISSUE THREAD

**Issue by tbigueres** [MicrosoftDocs/edge-developer#180]
Hi, 

I've filled the submission form already twice or three time, but I didn't have any answer yet. 

Can you please explain the process and how long it's suppose to take once you've filled the submission form to get an answer ? 

Thank you. 
Thoma

**Comment by mattwojo** [comment]
Hi @tbigueres -- I'm sorry that you haven't received an answer yet. Could you help me with a bit more context about what submission form you're referring to? 
Thank you!

**Comment by thoma202** [comment]
Hi.
Thanks for your answer.
It concerns the following request :

Extension Name : MacifAvantages.MacifAvantages
Store ID : 9NR1HDPFLR53
Lien chrome : https://chrome.google.com/webstore/detail/macif-avantages/oipjcohppciapfdojclipkpddkncidjo

**Comment by tbigueres** [comment]
Hi ! 

Still No News on our end !

Thanks 
Thoma

**Comment by mattwojo** [comment]
@tbigueres - I'm still looking into this. I don't have any direct access to the submission process (my job is to help with the docs), but I have a message out to someone on the Extensions team who has been out of office and returning next week, so I hope to have more information to share then.

**Comment by MrChrisRodriguez** [comment]
Agreed. We've tried to go through the process multiple times over the past year and have received literally zero feedback and have no clue what we're doing wrong. We have extensions in Chrome and Firefox. Is this typical right now? What's the best vector to get these sorts of time lag issues resolved?

CC @mariochampion

**Comment by tbigueres** [comment]
Hi, 
We still didn't have any news on the submission form. 
Is there any problem in it ? Are you blocking new extensions from deploying ? 

Thanks

**Comment by tbigueres** [comment]
Hi @erikadoyle ! 

Have you had any news about this problem ? 
It's been some time now and we still don't have any news from anyone ! 

are you blocking new extensions from being deployed ? 

Thanks

**Comment by erikadoyle** [comment]
Hi @tbigueres, sorry! I've moved to a different project and no longer in the know.

Adding @balajek, in case he knows if the Edge team has anything to share on the current and/or future plan for Edge extensions in the Microsoft Store, given the [upcoming transition](https://blogs.windows.com/msedgedev/2018/12/07/recapping-open-source-announcements/) to Chromium.

**Comment by tbigueres** [comment]
Thanks @erikadoyle 

@balajek : do you know if the extensions are frozen on Edge ? 

Thank you

**Comment by tbigueres** [comment]
Hi @balajek, 
Any news on this ?

**Comment by gebansal** [comment]
Considering its an old thread and we have rolled out a new Chromium-based Edge browser, I'll go ahead and close it. If you still are facing any issues, please feel free to reopen this issue or file a new one.
