### ISSUE TITLE
issue has been found

### ISSUE THREAD

**Issue by Gaurav825** [MicrosoftDocs/edge-developer#1800]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9a52771-a3f6-df50-ebf0-c9a399658bd6
* Version Independent ID: 8131dcac-31d4-76ec-40a6-f74d4a3a351d
* Content: [View Web SQL data - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/storage/websql)
* Content Source: [microsoft-edge/devtools-guide-chromium/storage/websql.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/storage/websql.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
This issue appears to be empty. I'll close it for now. Please comment back with more information if you have any, and we can re-open the issue then.
