### ISSUE TITLE
Unable to open WebView2 task manager as documented

### ISSUE THREAD

**Issue by alesandroortiz** [MicrosoftDocs/edge-developer#1801]
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model#handling-process-events-and-lifetime says
> To open the Browser Task Manager window from the DevTools window of a WebView2 instance, right-click the DevTools window title bar, and then select Browser task manager. Or, press Shift+Escape.
> 
> All processes that are associated with the browser process of your WebView2 are displayed, including their associated purposes.

However, using either the example project from https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2WpfBrowser or following the tutorial at https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/wpf I was unable to open the task manager using the documented instructions. I was also unable to find any other way to open the browser task manager within DevTools.

This might have been a change in Chromium that made its way to Edge and then WebView2, since I'm also unable to find how to open the task manager in Edge or Chrome DevTools using context menus or other UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 687b242b-3d19-3f97-2e24-2058ba7f2b78
* Version Independent ID: 492a9d07-105b-269b-770e-3a9b69f56b83
* Content: [Process model for WebView2 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model)
* Content Source: [microsoft-edge/webview2/concepts/process-model.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/process-model.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by alesandroortiz** [comment]
Not sure where to report feedback for the following page (see https://github.com/MicrosoftDocs/Contribute/issues/607) but adding comment here since it's related.

This page also needs to be updated
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.opentaskmanagerwindow?view=webview2-dotnet-1.0.1150.38#microsoft-web-webview2-core-corewebview2-opentaskmanagerwindow
> WebView2 currently blocks the Shift+Esc shortcut for opening the task manager. An end user can open the browser task manager manually via the Browser task manager entry of the DevTools window's title bar's context menu.

The API reference page partially contradicts the Architecture page about the keyboard shortcut. The context menu instructions are also incorrect.

The method `CoreWebView2.OpenTaskManagerWindow()` can still be called by an application and it works successfully, so the functionality is still there.

**Comment by Reezaali** [comment]
@alesandroortiz - sorry to hear about this issue, and thanks for reporting it. I've reached out to Engineering for assistance and will reply when I get a response.

**Comment by Reezaali** [comment]
Updated here: https://github.com/MicrosoftDocs/edge-developer/pull/1847

**Comment by alesandroortiz** [comment]
@Reezaali: Thanks! For the other page mentioned in my comment on this issue, should I open a new issue?

The page is: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.opentaskmanagerwindow?view=webview2-dotnet-1.0.1150.38#microsoft-web-webview2-core-corewebview2-opentaskmanagerwindow
