### ISSUE TITLE
Edge-management of service-handlers

### ISSUE THREAD

**Issue by Insectiside** [MicrosoftDocs/edge-developer#1802]
[Enter feedback here]
Hey guys, 

In regards to service-handler management i've noticed there does not seem to be a equal counterpart for Chrome's implementation to service-handlers. Just to deal with errors or just to check which handlers are active this comes in handy. In Chrome this is possible through chrome://settings/handlers. In Edge this does not seem to work or it is not implemented through edge://settings/handlers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fefe47b-4c2b-c308-6628-55c657b4712f
* Version Independent ID: 2e82a17f-7b76-22a0-41f5-0278c47bab72
* Content: [What's New in Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/whats-new/pwa)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/whats-new/pwa.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/whats-new/pwa.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Good catch! Indeed, there doesn't seem to be an equivalent in Edge.
I found this setting though, which might or might not be related: edge://settings/content/applicationLinks

@diekus do you know if Edge exposes any settings in its UI, like Chrome does, for managing whether apps can handle protocols?

**Comment by samtan-msft** [comment]
Hi, thanks for raising this issue! 
You can find the protocol handling management for pwas in edge://settings/content/handlers. This should be equivalent to chrome://settings/handlers. 
You can also change the default pwas/apps for protocol handlers within the OS settings. In Windows, you can find the settings under Default Apps -> Choose default apps by protocol. Any pwas that registers for a protocol handler can be found in there as well.

**Comment by captainbrosset** [comment]
@Insectiside see Sam's reply above. Does that answer your question?

**Comment by Insectiside** [comment]
Samuel, Patrick

It does answer the issue, thanks for the clarification. I was aware of Settings  --> default apps. The default apps by protocol is a long list (not searchable) whereas the handlers in Edge provide a specific (and limited- view on the handlers it is responsible for.

Keep those PWA improvements coming, i love em ;-)

Thanks again.
