### ISSUE TITLE
Unable to find in Registry Editor

### ISSUE THREAD

**Issue by RSV-5** [MicrosoftDocs/edge-developer#1806]
Unable to find the below
HKEY_CURRENT_USER\Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}

Can someone help me.....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute your app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out, but could you please ask again your question on the WebView2Feedback repository instead? You can create a new issue there by following this link: https://github.com/MicrosoftEdge/WebView2Feedback/issues/new

The repo here is only for tracking changes to the documentation. The WebView2Feedback repo however is great to ask for help about using WebView2.

Thanks a lot!
