### ISSUE TITLE
NPM Package for Publishing API

### ISSUE THREAD

**Issue by arnoudkooi** [MicrosoftDocs/edge-developer#1813]
Will a NPM package be made available, that leverages the new publishing API, or is a code example available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f22ef0a-202d-482d-be95-1a772c2addc9
* Version Independent ID: 1a2f5a98-fbb2-ce6b-698c-09b3d878f168
* Content: [Using the Microsoft Edge Add-ons API (in private preview) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api)
* Content Source: [microsoft-edge/extensions-chromium/publish/api/using-addons-api.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/publish/api/using-addons-api.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for your question. The Publishing API is still in development. Once it is released we'll update this documentation with code samples for sure. I'll close this issue for now as we already are tracking this on our backlog.
