### ISSUE TITLE
Complex and confusing

### ISSUE THREAD

**Issue by ericlaw1979** [MicrosoftDocs/edge-developer#182]
This documentation is both complex and confusing. Forcing extensions through the store flow ("What forms of virtual reality does this application support") is bizarre.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e606632-9492-a033-f5cd-763143ab90f7
* Version Independent ID: a37bced5-fe53-6182-9a08-1fa2080889a3
* Content: [Extensions - Packaging - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/packaging)
* Content Source: [microsoft-edge/extensions/guides/packaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/packaging.md)
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by MrChrisRodriguez** [comment]
Agreed. We've tried to go through the process multiple times over the past year and have received literally zero feedback and have no clue what we're doing wrong. We have extensions in Chrome and Firefox with no problem whatsoever.

**Comment by gebansal** [comment]
Considering its an old thread and we have rolled out a new Chromium-based Edge browser, I'll go ahead and close it. If you still are facing any issues, please feel free to reopen this issue or file a new one.
