### ISSUE TITLE
conflict in allowed_origins between this page and another

### ISSUE THREAD

**Issue by GregHNZ** [MicrosoftDocs/edge-developer#1822]
This page says  native messaging host manifest file looks like this:

{
    "name": "com.my_company.my_app",
    "description": "My App",
    "path": "C:\\Program Files\\My App\\chrome_native_messaging_host.exe",
    "type": "stdio",
    "allowed_origins": [
        "**chrome-extension**://knldjmfmopnpolahpmmgbagdohdnhkik/"
    ]
}

However, the instructions on "Port a Chrome extension to Microsoft Edge" 
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension

Says:
make sure that you set allowed_origins to **extension**://[Microsoft-Catalog-extensionID] in your native messaging host manifest file. The setting allows the app to identify your extension

So, which should it be ?  `extension` or `chrome-extension`

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6baf3ba3-2850-707d-fdfc-9b65f88655c7
* Version Independent ID: 661b537b-bba6-cb07-9979-cddcc35421e3
* Content: [Native messaging - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging?tabs=linux)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/native-messaging.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for filing this @GregHNZ, let's ask @ashishnirvana1 who should be able to help us.

**Comment by sonakshimore** [comment]
Thank you for bringing this to our attention, @GregHNZ.

It is **"chrome-extension"**. The correct native messaging host manifest file will look like this -

```
{
"name": "com.my_company.my_app",
"description": "My App",
"path": "C:\Program Files\My App\chrome_native_messaging_host.exe",
"type": "stdio",
"allowed_origins": [
"chrome-extension://[Microsoft-Catalog-extensionID]/"
]
}
```

We are working on making this change to the [Port a Chrome extension to Microsoft Edge](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension#setting-allowed_origins-for-a-native-app) documentation.
