### ISSUE TITLE
Can Edge driver download automatically each time the Edge stable version is updated?

### ISSUE THREAD

**Issue by Renjuchang** [MicrosoftDocs/edge-developer#1824]
Hello developer,

        I found Edge driver updated so frequently.  The version of driver needs to match with Edge's version.
        Is there a way to download the Edge driver automatically when Edge stable version for x64 is updated?
        In this way, I do not worry the issue that  Edge driver version is not matched with Edge's version 
        The application can run successfully. 

         Thanks!

 Renjuchang

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver to automate Microsoft Edge - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Hi @Renjuchang, thank you for your feedback. Since this is a question about Edge WebDriver, could you please ask it again on the Edge WebDriver feedback repository? To do this, please create a new issue here: https://github.com/MicrosoftEdge/EdgeWebDriver/issues

Thanks a lot!
