### ISSUE TITLE
webNavigation.onCommited

### ISSUE THREAD

**Issue by ericlaw1979** [MicrosoftDocs/edge-developer#183]
Is the typo in the documentation or in the API? (Should be webNavigation.onCommitted)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81537c8b-8cc2-1f01-40b3-16f0ad0a464f
* Version Independent ID: 1b81f7ce-aa4d-5397-1975-79742854635e
* Content: [Extensions - Supported APIs - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-apis)
* Content Source: [microsoft-edge/extensions/api-support/supported-apis.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/api-support/supported-apis.md)
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by charlottetan** [comment]
I'd love to take a stab at this

**Comment by charlottetan** [comment]
@erikadoyle, I already have a PR out to fix the typo :D

**Comment by tatted001** [comment]
SHOVE IT UP TOUR ASSHOLE!

**Comment by erikadoyle** [comment]
Thanks @charlottetan, saw that and also confirmed the typo doesn't repro in the source code. Will merge in shortly.
