### ISSUE TITLE
Edge web driver - Console window pops up when we automate webapplication

### ISSUE THREAD

**Issue by aarush15** [MicrosoftDocs/edge-developer#1830]
We are in process of automating the web application using C# + Selenium.
For Edge web browser we are facing issue of seeing the console popup during the automation flow

1. Console window pops up when trying to open Edge browser from C# +Selenium 
        _**you can see in the below code that we are changing the status of "HideCommandPromptWindow = true" but still the popup comes up**_
        =============================================================
   try
    {     
           var options = new EdgeOptions();
            var service = EdgeDriverService.CreateDefaultService(@"C:\", @"msedgedriver.exe");
            options.AddArgument("--disable-extensions");
            options.AddArgument("--disable-popup-blocking");
            options.AddArgument("--disable-infobars");
            options.AddArgument("--disable-save-password-bubble");
            options.AddArgument($"--remote-debugging-port={GetAvailablePort()}");
            options.AddArgument("--log-level=3");
            options.AddUserProfilePreference("credentials_enable_service", false);
            options.AddUserProfilePreference("profile.password_manager_enabled", false);
            options.AddUserProfilePreference("profile.default_content_setting_values.notifications", 2);
            options.AddExcludedArgument("enable-automation");
            options.AddAdditionalCapability("useAutomationExtension", false);
            options.AddArgument("--log-level=0");
            options.BinaryLocation = System.IO.Path.
                Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86), 
                @"Microsoft\Edge\Application\msedge.exe");            
            **_service.HideCommandPromptWindow = true;_**
            var driver = new EdgeDriver(service, options);
            driver.Navigate().GoToUrl("https://www.google.com/");
    }catch
    {
    }

![image_1](https://user-images.githubusercontent.com/25999183/159957997-6bdff561-ed95-4b3f-871c-d537e135011b.jpg)

   ========================================================================
2. Console window does not popup but message being displayed on the edge browser as shown below

 try
    {     
           var options = new EdgeOptions();
            var service = EdgeDriverService.CreateDefaultService(@"C:\", @"msedgedriver.exe");
            options.AddArgument("--disable-extensions");
            options.AddArgument("--disable-popup-blocking");
            options.AddArgument("--disable-infobars");
            options.AddArgument("--disable-save-password-bubble");
            options.AddArgument($"--remote-debugging-port={GetAvailablePort()}");
            options.AddArgument("--log-level=3");
            options.AddUserProfilePreference("credentials_enable_service", false);
            options.AddUserProfilePreference("profile.password_manager_enabled", false);
            options.AddUserProfilePreference("profile.default_content_setting_values.notifications", 2);
            **_//options.AddExcludedArgument("enable-automation");_**
            options.AddAdditionalCapability("useAutomationExtension", false);
            options.AddArgument("--log-level=0");
            options.BinaryLocation = System.IO.Path.
                Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86), 
                @"Microsoft\Edge\Application\msedge.exe");            
            **_service.HideCommandPromptWindow = true;_**
            var driver = new EdgeDriver(service, options);
            driver.Navigate().GoToUrl("https://www.google.com/");
    }catch
    {
    }
![image](https://user-images.githubusercontent.com/25999183/159958507-c6cc8e2b-fac5-463a-b43b-eeb9253bf64b.png)

![image_2](https://user-images.githubusercontent.com/25999183/159958464-6a621465-9ff7-476d-bc7f-ad1a395581e1.jpg)

 
==========================================================================
Configuration used 
1. MS Edge version = 99.0.1150.46
2. Edge driver used = 99.0.1150.46

**Comment by captainbrosset** [comment]
Thanks so much for the detailed feedback. Would it be possible for you to copy and paste it as a new issue on this repository instead: https://github.com/MicrosoftEdge/EdgeWebDriver ?

That is where we keep issues related to using Edge WebDriver. This repo here is just about documentation.
If you open an issue on that other repo, you'll get in touch directly with the team working on Edge WebDriver!

Thanks for your understanding.
