### ISSUE TITLE
Ambiguity in WebDriver documentation

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/edge-developer#1832]
The [Download Microsoft Edge WebDriver](https://docs.microsoft.com/microsoft-edge/webdriver-chromium/#download-microsoft-edge-webdriver) section of the page reads:

> 2. Go to [Microsoft Edge WebDriver](https://developer.microsoft.com/microsoft-edge/tools/webdriver).
>
> 3. In the Get the latest version section of the page, select a platform in the channel that matches your version number of Microsoft Edge.

However, Microsoft WebDriver has become an optional OS component.

So, does this instruction in the documentation still apply?

If so, please add an information box telling the difference between the suggested download and the optional Windows OS component.
<br/>

Moreover, the [Relationship between WebDriver and other software](https://docs.microsoft.com/microsoft-edge/webdriver-chromium/#relationship-between-webdriver-and-other-software) section of the document contains a table showing four different technologies:

![Table](https://user-images.githubusercontent.com/9283914/160116337-6ec07d48-b709-4909-89ae-dfd57c2d2d80.png)

"Microsoft WebDriver" (the optional Windows OS component) is not one of them.

Please add a row explaining what "Microsoft WebDriver" is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver to automate Microsoft Edge - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for filing!

For your first question, let's ask @bwalderman whether the instructions still apply, or if users should download via the "optional features" settings UI.

As for the second question, I think the confusion comes from the fact that "Microsoft WebDriver" is actually the same thing as "Microsoft Edge WebDriver". It looks like branding isn't consistent yet.

1. In the Optional features UI:
    <img width="682" alt="image" src="https://user-images.githubusercontent.com/1152698/160350768-87ac4827-1491-441c-87fc-c85d62d52e76.png">
1. In the docs:
    <img width="683" alt="image" src="https://user-images.githubusercontent.com/1152698/160350887-f69b36ef-d05f-4185-a1fc-1ccc04d1c1cd.png">
1. On the [download page](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/):
     <img width="623" alt="image" src="https://user-images.githubusercontent.com/1152698/160351127-ae9d2e7d-237b-4729-9c20-494c4c082a69.png">

**Comment by bwalderman** [comment]
Microsoft WebDriver is the legacy WebDriver implementation for EdgeHTML-based Edge. It was distributed as an optional Windows component because legacy Edge was updated with the OS. It isn't compatible with the latest Chromium-based versions of Edge. It is still made available for developers who have written WebDriver-based tests for UWP apps since these rely on EdgeHTML, but its use is no longer recommended.

**Comment by captainbrosset** [comment]
Will do, thanks all. I'll add something on our backlog to add the info, and will get back to this issue once we have an update.

**Comment by SetTrend** [comment]
Thanks a lot, @mikehoffms, for adding this information!

Though, I believe the new information still is quite sparse. Developers without the knowledge that @bwalderman shared still won't know the difference. The Docs article you've been referencing to do doesn't clarify things. It doesn't bear the word "legacy".

Just to make things clear, I would suggest to add a side note (i.e. warning box) below the table, reflecting exactly the text @bwalderman gave:

> Microsoft WebDriver is the legacy WebDriver implementation for EdgeHTML-based Edge. It was distributed as an optional Windows component because legacy Edge was updated with the OS. It isn't compatible with the latest Chromium-based versions of Edge. It is still made available for developers who have written WebDriver-based tests for UWP apps since these rely on EdgeHTML, but its use is no longer recommended.

**Comment by mikehoffms** [comment]
@SetTrend - Added bottom row of table at top, and also added a major section at end of page:
https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp#legacy-microsoft-webdriver-for-edgehtml

**Comment by mikehoffms** [comment]
@bwalderman - Added bottom row of table at top, and also added a major section at end of page:
https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp#legacy-microsoft-webdriver-for-edgehtml

**Comment by SetTrend** [comment]
Excellent! Thank you 👍
