### ISSUE TITLE
ELVIS MUNYI KIIRU PEACE IAWIA 

### ISSUE THREAD

**Issue by elvismunyikiiru** [MicrosoftDocs/edge-developer#1833]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87aef5c6-630f-992c-5813-813cb861de4a
* Version Independent ID: 87aef5c6-630f-992c-5813-813cb861de4a
* Content: [What's new in DevTools (Microsoft Edge 97) - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing and locking this as potential spam. If you have found a real problem with the DevTools docs, please file a new issue with a description of the problems.
