### ISSUE TITLE
MINISTERY

### ISSUE THREAD

**Issue by Drewp2020** [MicrosoftDocs/edge-developer#1838]
<script>
!function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments);
},s.version='1.1',s.queue=[],u=t.createElement(n),u.async=!0,u.src='//static.ads-twitter.com/uwt.js',
a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,'script');
// Insert Twitter Pixel ID and Standard Event data below
twq('init','o88c0');
twq('track','PageView');
</script>

⚠ If your feedback isn't about the Microsoft Edge developer documentation, consider submitting it here instead:

* For DevTools: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/contact
* For WebView2: https://github.com/MicrosoftEdge/WebView2Feedback/issues
-->

**Link to the documentation page**: The URL to the page.

**Description of the issue**: A clear and concise description of what the issue is.

**Screenshots**: If applicable, add screenshots to help explain the issue.

**Microsoft Edge version**: If the issue occurs with a specific version of Microsoft Edge.

**Comment by captainbrosset** [comment]
Closing and locking this as potential spam. If you have found a real problem with the DevTools docs, please file a new issue with a description of the problems.
