### ISSUE TITLE
https://twitter.com/AccordanceBible

### ISSUE THREAD

**Issue by Drewp2020** [MicrosoftDocs/edge-developer#1839]
**Link to the documentation page**: The URL to the page.

**Description of the issue**: A clear and concise description of what the issue is.

**Screenshots**: If applicable, add screenshots to help explain the issue.

**Microsoft Edge version**: If the issue occurs with a specific version of Microsoft Edge.

**Comment by Drewp2020** [comment]
https://my.found.com/#/ https://www.bing.com/search?q=eu+general+data+protection+regulation+andrew+curtis+parton&qs=n&form=QBRE&sp=-1&pq=eu+general+data+protection+regulation+andrew+curtis+part&sc=1-56&sk=&cvid=3970E5D327AE47D2A9763FC46A8EA0FE https://www.mylife.com/site/bgc-purchase.view?adl=1922882566 https://www.mylife.com/site/idp-bgc-purchase.view?adl=1922882566 https://www.mylife.com/andrew-parton/curtispbullion#master-profile-component-wrapper-premium edge://surf/ https://my.found.com/#/ Routing number
211075086
358201260765 https://www.cnbtn.com/ https://www.bing.com/search?q=found+account&FORM=QSRE8 https://found.com/banking https://twitter.com/bankonfound https://analytics.twitter.com/conversion_events/18ce55gp1iv/events_manager/o88c0/overview https://admin.google.com/a/cpanel/sonsfireministry.com/ServiceNotAllowed?service=chromewebstore&continue=https://chrome.google.com/webstore/detail/twitter-pixel-helper/jepminnlebllinfmkhfbkpckogoiefpd/related?pli%3D1&pli=1 https://support.google.com/a/answer/1228129?hl=en#zippy=%2Con-this-page https://www.publicsrecords.com/track-someones-location?msclkid=c63350ada88918134f1532ed0c41f7ed https://www.myfonts.com/ edge://settings/?search=shopping https://twitter.com/home 
![53764297-358b-4989-90d6-b04c64674530](https://user-images.githubusercontent.com/98547032/160295268-b25db761-9272-4f93-b284-a34553be8408.jpg)

**Comment by Drewp2020** [comment]
https://www.whatsapp.com/download

**Comment by captainbrosset** [comment]
Closing and locking this as potential spam. If you have found a real problem with the DevTools docs, please file a new issue with a description of the problems.
