### ISSUE TITLE
ANDREW PARTN BANK ACCOUNT 3888757 CNBTN

### ISSUE THREAD

**Issue by Drewp2020** [MicrosoftDocs/edge-developer#1842]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad294101-a818-19ae-deaa-7bfcd3774ea3
* Version Independent ID: ad294101-a818-19ae-deaa-7bfcd3774ea3
* Content: [What's new in DevTools (Microsoft Edge 99) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/03/devtools#securely-debug-your-production-code-with-source-maps-from-azure-artifacts-symbol-server)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2022/03/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/whats-new/2022/03/devtools.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing and locking this as potential spam. If you have found a real problem with the DevTools docs, please file a new issue with a description of the problems.
