### ISSUE TITLE
Corporate Needs - WebView2 Documentation

### ISSUE THREAD

**Issue by WFDexter** [MicrosoftDocs/edge-developer#1850]
For those of us targeting corporate environments, we need to know what server(s) and ports the updater needs to access, how and how often it runs, and what the upgrade experience is like if there is an upgrade.

For support purposes we need to be know how to tell what version of WebView2 is currently installed.

I may ultimately be deploying to ~7000 devices scattered around the country.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute your app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out @WFDexter. Let's ping @champnic as he's the expert in this area. 
I would also like to bring to your attention that we have a GitHub repository for discussing WebView2 questions/features/bugs: https://github.com/MicrosoftEdge/WebView2Feedback/issues

**Comment by champnic** [comment]
I've reached out to our deployment team and will respond when I hear back from them. Thanks!

**Comment by captainbrosset** [comment]
Closing as inactive. Please feel free to add more information if you have any and we can re-open the issue.
