### ISSUE TITLE
VCQ 171989 - VCQ: RWS Moravia: [Source issue] [Incomprehensible instruction]

### ISSUE THREAD

**Issue by cdowling1971** [MicrosoftDocs/edge-developer#1858]
Please check this source string and see if it needs to be updated, the highlighted part is not clear: "Arrange the text box to the left of the button, aligned next to the text box, as shown below:"

I guess it should be "Arrange the text box to the left of the button, aligned next to the button, as shown below:". Another option could be: "Arrange the text box to the left of the button, aligned with the text in the button, as shown below:".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ba6a76-eb0b-e8f2-dfc9-d2c0df6261a4
* Version Independent ID: 8d62fdee-f44a-3d40-6800-04d7bd6193f8
* Content: [Get started with WebView2 in WinForms apps - Microsoft Edge Development](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms)
* Content Source: [microsoft-edge/webview2/get-started/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for filing this. I'll open a task on our backlog to take care of this.

**Comment by cdowling1971** [comment]
Thankyou

**Comment by captainbrosset** [comment]
The screenshot below the instructions do show a baseline alignment overlay (a pink line that is aligned with where the text sits in the button, and where the text will also be aligned in the textbox). So I believe the right wording should be:

"Arrange the text box to the left of the button, aligned with the text in the button, as shown below".

**Comment by cdowling1971** [comment]
Got it thanks!
