### ISSUE TITLE
Permissions list not updated?

### ISSUE THREAD

**Issue by adamkimsft** [MicrosoftDocs/edge-developer#1865]
[Enter feedback here]

The list of permissions doesn't include some permissions like "usb" as listed in Chrome's documentation at https://support.google.com/chrome/a/answer/7515036?hl=en&ref_topic=6178561.  Was this intentional?  If not, are there other permissions that should be included such as videoCapture, etc?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dee597b4-fae1-7c57-ba42-1659a647dfba
* Version Independent ID: 717aa76c-8243-2bbc-33b8-88264373c91c
* Content: [Declare API permissions in extension manifests - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/enterprise/declare-permissions)
* Content Source: [microsoft-edge/extensions-chromium/enterprise/declare-permissions.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/enterprise/declare-permissions.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. I think the question we should answer here is whether the browser extension API does have access to USB or videoCapture, or other things that are not yet listed on this doc.
The original doc that ours was built upon, originally, is this one: https://developer.chrome.com/docs/extensions/mv3/declare_permissions/ and that one also does not have USB or videoCapture.

So, what we need here is a complete review of all of the APIs available to browser extensions, and based on this, possibly updating the list of permissions if any are missing.

I will log a task on our backlog to do this at some point. Thanks!

**Comment by adamkimsft** [comment]
That declare_permissions page was lasted updated 2014 so it sounds like it was based on a page was stopped getting updated.  Thanks.

**Comment by captainbrosset** [comment]
Right, we'll need to review the extension APIs that do require permissions in order to update our page.
