### ISSUE TITLE
Fixed Version Runtime of WebView2 on USB flash drive

### ISSUE THREAD

**Issue by fangliq** [MicrosoftDocs/edge-developer#1866]
I put the Fixed Version Runtime onto a USB flash drive for a simple application. It worked first time and then failed next time (The exactly same copy works well on a non-removable drive). Please give some instructions for this issue in your next update of this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Introduction to Microsoft Edge WebView2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Hi @fangliq, thanks for reaching out. That sounds like an odd issue. I think it would be better for you to get in touch with the WebView2 team so they can help you get to the bottom of the problem.
Could you please open a new issue on this repository instead: https://github.com/MicrosoftEdge/WebView2Feedback/issues (click **New issue** and describe the issue you re having with using wv2 from the USB flash with as much details as possible).

Thanks!

**Comment by fangliq** [comment]
Captainbrosset, 
Thank you for timely reply. I opened a new issue as below. 
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2334
