### ISSUE TITLE
Page is missing information about Background Services

### ISSUE THREAD

**Issue by TotallyInformation** [MicrosoftDocs/edge-developer#1867]
Hi, The referenced docs page is missing help on a number of features on the Application tab of the dev tools.

Specifically, Payment Handler, Perioding Background Sync (as opposed to Background Sync) and Reporting API.

![image](https://user-images.githubusercontent.com/1591850/161384820-3716362b-6df3-4629-8b5a-8466f46ffb0a.png)

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 004be442-ec1f-1231-4b3a-96d66bcd625c
* Version Independent ID: 5fd81298-0533-7825-26d5-c09060fcecd7
* Content: [Debug background services - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/background-services?source=docs)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript/background-services.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/javascript/background-services.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reporting. I'll add this to our backlog for prioritization.
However, since writing docs about this might take some time, let me know if there is anything specific you need to know about these features. Maybe I, or someone else, can help you even before the docs are written.

**Comment by captainbrosset** [comment]
Note that we do have some docs about debugging Periodic Background Sync events in the PWA part of the docs: https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/background-syncs#debug-periodic-background-syncs-with-devtools
I hope this helps.

**Comment by TotallyInformation** [comment]
Thanks for responding. No particular hurry, I'm building a data-driven UI builder component for the low-code Node-RED platform and was looking for some inspiration of what to implement next, in particular around newer web API's. I did eventually find what I needed elsewhere but it would be much easier for Edge users/developers to be able to find a little more info direct from the Microsoft docs.

Thanks for the additional reference. Of course, from just looking at the dev tools UI, it isn't immediately obvious - unless you already know - that it relates to PWA's.

Anyway, thanks for the docs and keep up the great work. Edge is my daily driver browser and I live in it for far too many hours a day so I appreciate the work put into it.

**Comment by captainbrosset** [comment]
Thanks for the context and kind words. We'll definitely work on adding the missing content.

**Comment by captainbrosset** [comment]
I've started working on this. I will provide docs for Reporting API and Periodic Background Sync, but Payment Handler is harder and might take some more time. In the meantime, you can learn more about it here: https://developer.chrome.com/blog/new-in-devtools-78/#payments

**Comment by captainbrosset** [comment]
Payment Handler docs didn't make it in this PR, but I will work on this in a separate PR.
