### ISSUE TITLE
Not clearly guiding which one to use either M365 account or Microsoft personal account

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/edge-developer#1868]
The document does not clearly say which account has to be used either Microsoft personal account or M365 business account.

***********************ERROR MSSG**************************
Sign in with your Microsoft account to continue
We support only Microsoft accounts (Outlook/Live) for registering into the Windows & Xbox program.

You are signed in as sing_ideas@stackradius.com which is not a Microsoft account.

If you believe this is an error, try deleting your browser cookies and sign in again with a Microsoft account (Outlook/Live) that you’d like to use to register for the program.

***********************************************
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7f49d04-dd9e-9d95-6bc3-f158e4eacada
* Version Independent ID: 5e3a5695-0978-7051-45d1-623dbb757f22
* Content: [Publish a Progressive Web App to the Microsoft Store - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/microsoft-store)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/microsoft-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/microsoft-store.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. My understanding is that both personal and work accounts should work. This doc describes when to use which one and the associated costs: https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees

Let me know if this helps. We might want to link to this doc in the one you mentioned.

**Comment by captainbrosset** [comment]
Closing this issue as my last comment seems to have helped. Feel free to reply back if there's anything more you think we need to do here.
