### ISSUE TITLE
Add NPM package for using Publish API [Add-ons API]

### ISSUE THREAD

**Issue by ColdSauce** [MicrosoftDocs/edge-developer#1871]
Hi folks,

We've built an [NPM package](https://www.npmjs.com/package/@plasmo-corp/ewu) to make it easier for Javascript projects to leverage the excellent new Edge Add-ons Publish API. It would help many people leverage the new API as they wouldn't have to implement the raw REST calls themselves. 

Perhaps it could be in a Recommended Tools section or something of that sort?

**Comment by captainbrosset** [comment]
Thanks for reaching out, and for the proposal. Excellent work!
I'll ping the team for evaluation and prioritization.
