### ISSUE TITLE
[Edge WebDriver Docs Feedback]

### ISSUE THREAD

**Issue by StephendillonMS** [MicrosoftDocs/edge-developer#1875]
Is there a way to sync webdriver versions with Edge verison, please? Updating it manually each month (or each week in the DEV Edge channel) is untenable for my customer. Also, what is the impact if the version isn't in sync, e.g. Edge is on version 101 and Webdriver is on version 99? Thanks.

**Comment by bwalderman** [comment]
This is a known issue which impacts both ChromeDriver and EdgeDriver. The feature request to automatically update EdgeDriver is tracked with https://github.com/MicrosoftEdge/EdgeWebDriver/issues/2

The customer can also consider using https://bonigarcia.dev/webdrivermanager/ which automatically fetches the appropriate driver for any installed browser, including Microsoft Edge.

**Comment by captainbrosset** [comment]
Thank you Brandon. Closing this issue knowing that there is no doc changes to be made, and that there's already another tracking issue on the EdgeWebDriver repo.
