### ISSUE TITLE
The walkthrough says to use manifest version 2, but that causes a warning in Edge

### ISSUE THREAD

**Issue by Eilon** [MicrosoftDocs/edge-developer#1878]
The extension walkthrough says to use manifest version 2, but that causes a warning in Edge:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/202643/162076833-ea6ff41d-e04e-4abf-93ea-57f59f337ce8.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d70c4902-5246-ea94-a95f-f4ac94611c4c
* Version Independent ID: c7f1c45d-32ad-90f7-bfd6-d44ecd2bc941
* Content: [Create an extension tutorial, part 1 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks a lot for reporting this. You're right, v2 is deprecated and v3 should be used instead. We need to update this page.
I will open a task on our backlog to deal with it.

**Comment by Eilon** [comment]
Great! Fortunately between the Edge extension docs and Chrome extension docs there's enough info on it. But I was a little disappointed when I did the Edge tutorial to get started and then immediately the extension I wrote was frowned on by Edge.

**Comment by captainbrosset** [comment]
Glad you managed to make it work, and sorry for the bad experience. We'll update the docs as soon as we can.

**Comment by Reezaali** [comment]
@Eilon we've updated the doc. Thanks for reporting the issue.
