### ISSUE TITLE
Really

### ISSUE THREAD

**Issue by RabbitBig** [MicrosoftDocs/edge-developer#188]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f2cc1ee-ec39-f274-1880-69bed835bad4
* Version Independent ID: 121dbb65-9ebe-8b6c-c654-a6529ea6fd82
* Content: [Extensions - Troubleshooting - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/troubleshooting)
* Content Source: [microsoft-edge/extensions/troubleshooting.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/troubleshooting.md)
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by tatted001** [comment]
GO FUCK YOURSELVES!!!!!!!
