### ISSUE TITLE
file

### ISSUE THREAD

**Issue by 6liv6vil6** [MicrosoftDocs/edge-developer#1888]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2ecc9a-c883-9097-bcdc-9f812cbe5d53
* Version Independent ID: 0b2ecc9a-c883-9097-bcdc-9f812cbe5d53
* Content: [Securely debug original code by using Azure Artifacts symbol server source maps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/consume-source-maps-from-azure)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript/consume-source-maps-from-azure.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/javascript/consume-source-maps-from-azure.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. Unfortunately, there is not enough information here for us to investigate and fix a docs problem.
I'll close the issue now, but feel free to comment with more information if you have any.
