### ISSUE TITLE
content_scripts permission

### ISSUE THREAD

**Issue by earbullet** [MicrosoftDocs/edge-developer#189]
In order to get my extension working I had to add the content_scripts permission in my manifest.

{
  "name": "acme",
  "author": "Name",
  "version": "1.0",
  "description": "Do stuff",
  "permissions" : 
	[
	"content_scripts"
	],
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e322d0db-8a91-6fff-7510-a5ec18fa4a65
* Version Independent ID: 0c60d518-08f5-3b4e-0f4b-b7cd71455951
* Content: [Extensions - Creating an extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/creating-an-extension)
* Content Source: [microsoft-edge/extensions/guides/creating-an-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/creating-an-extension.md)
* Product: **microsoft-edge**
* GitHub Login: @libbymc
* Microsoft Alias: **libbymc**

**Comment by gebansal** [comment]
Considering its an old thread and we have rolled out a new Chromium-based Edge browser, I'll go ahead and close it. If you still are facing any issues, please feel free to reopen this issue or file a new one.
