### ISSUE TITLE
C# code example is incorrect  \M is unrecognised escape sequence

### ISSUE THREAD

**Issue by KirkBates** [MicrosoftDocs/edge-developer#1892]
string UserDataFolder;
UserDataFolder = "C:\MyAppUserDataFolder";                                                  // This should have '\\\\'
_task = CoreWebView2Environment.CreateAsync(BrowserExecutableFolder, 
                                            UserDataFolder, 
                                            new CoreWebView2EnvironmentOptions(null, Language, null));

(I think the problem may be related to the editing platform automatically converting the original code that contained \\\\ to a single \\ )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588e1782-3942-288e-a844-d4e95054a1e8
* Version Independent ID: c7e7c7c6-0180-b28b-38c5-ce9d5e9a8159
* Content: [Manage user data folders - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=win32)
* Content Source: [microsoft-edge/webview2/concepts/user-data-folder.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/user-data-folder.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reporting this issue! Indeed, it may be due to the platform we use. We'll investigate and fix.

**Comment by mikehoffms** [comment]
Changed c:\ to c:\\ in tabs 1-3 at https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=clickonce#specifying-a-custom-udf-location
