### ISSUE TITLE
Small issue with brackets in `webpack.plugin-symbols.js` code example

### ISSUE THREAD

**Issue by johanndev** [MicrosoftDocs/edge-developer#1898]
The first code example for `webpack.plugin-symbols.js' contains a small issue regarding the closing brackets, here is a diff to fix it:

```diff
--- a/webpack.plugin-symbols.js
+++ b/webpack.plugin-symbols_fixed.js
@@ -51,5 +51,6 @@ module.exports = class PrepareSourceMapsForSymbolServerPlugin {
           sourceMapAsset,
         };
       });
+    })
   }
};
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3efb02b4-e5e3-7b6a-542a-1f588383acae
* Version Independent ID: 3efb02b4-e5e3-7b6a-542a-1f588383acae
* Content: [Securely debug original code by publishing source maps to the Azure Artifacts symbol server - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/publish-source-maps-to-azure)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript/publish-source-maps-to-azure.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/javascript/publish-source-maps-to-azure.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks so much for taking the time to report this. We'll get this fix as soon as possible.

**Comment by captainbrosset** [comment]
Code snippet is now fixed in the repository, and the fix should be live in a few minutes.
