### ISSUE TITLE
Local Storage of "Network request blocking" and Wildcards Within

### ISSUE THREAD

**Issue by eliotcolebc** [MicrosoftDocs/edge-developer#1899]
Hello

Couple of things that I couldn't work out from this document:

1. How can I use a wildcard or regex in 'Network request blocking'?
2. Where are these lists kept?

On, `#1`: It mentions patterns, but as far as my experiments using `*` as a wildcard I've been unable to use _actual_ patterns to block, only literal strings. How can I use a wildcard or regex to better enable this functionality?

With regard to `#2`; I have a couple set up for a couple of sites that I assist with, and searching for the text in my user folder on Windows couldn't find it stored anywhere.

Best
E

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 339c9e37-b0c8-5ebf-0764-c281451b8fc6
* Version Independent ID: 339c9e37-b0c8-5ebf-0764-c281451b8fc6
* Content: [Network request blocking tool - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network-request-blocking/network-request-blocking-tool)
* Content Source: [microsoft-edge/devtools-guide-chromium/network-request-blocking/network-request-blocking-tool.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/network-request-blocking/network-request-blocking-tool.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reporting this. I'll add this to our list of tasks so we can prioritize and get this fixed as soon as we can.

On the regex/pattern question, my experience is that the `*` character can be used in any place of the string. I don't think other regex syntaxes are allowed though, but we'll have to check in more details to make sure.
Here's a quick example showing 2 patterns that use `*` and they successfully blocked a couple of requests on my site:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/1152698/163348534-b90ea1a3-2894-4ea1-9c5f-c33cbeb1aed8.png">

On the persistence question, I don't know the exact details. I thought the patterns would be stored in DevTools local storage, but debugging devtools with devtools showed that I was wrong. I think a bunch of DevTools are saved more globally at the browser level, and that's probably what happens here, but I don't know which files this would translate to.

@antross would you be able to shade some light on this particular question please?

**Comment by captainbrosset** [comment]
Thinking more about the persistence question, that might even be a good feature to add to DevTools: the ability export and import blocking patterns in the DevTools. Do you think this would be useful? If so, would you be interested in submitting this idea on the Edge DevTools repo? Just file a new issue here https://github.com/MicrosoftEdge/DevTools/issues .

**Comment by captainbrosset** [comment]
With regards to persistence, here are 2 ways you can retrieve the blocked request patterns:

1. Open the following file: `C:\Users\<username>\AppData\Local\Microsoft\Edge\User Data\Default\Preferences` and search for `networkBlockedPatterns`. You'll find the blocked patterns in there.
2. Open the following URL in Edge: `edge://prefs-internals` and also search for `networkBlockedPatterns` on the page. You'll find the blocked patterns there too.

We'll update the docs to make sure using `*` in patterns is clearer.
