### ISSUE TITLE
Time out exception

### ISSUE THREAD

**Issue by harinathareddym** [MicrosoftDocs/edge-developer#1906]
Getting timeout exception while opening in IE mode, can you please help me

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Version Independent ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Content: [Use Internet Explorer Driver to automate IE mode in Microsoft Edge - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp#automate-ie-mode-in-microsoft-edge)
* Content Source: [microsoft-edge/webdriver-chromium/ie-mode.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/ie-mode.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out @harinathareddym. We now have a new GitHub repository for tracking issues with automating Edge (including with IE Mode): https://github.com/MicrosoftEdge/EdgeWebDriver/issues

Could you please report this issue there instead? That would be great! Also, if you have any more details you can provide, this would be very useful.
