### ISSUE TITLE
IE to Edge updates

### ISSUE THREAD

**Issue by flippidippi** [MicrosoftDocs/edge-developer#1912]
We've submitted our site to `ietoedge@microsoft.com` to have our site added to the XML file, and are still not seeing the update.
Is there progress on the XML being updated or will there be a different way to indicate this (like a meta tag or something)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe5c21b-2296-8b5c-208a-f41eb967c24e
* Version Independent ID: c3722063-7455-5ba9-a78d-102823dfd474
* Content: [Move users to Microsoft Edge from Internet Explorer - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection)
* Content Source: [microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out, and sorry that you're not seeing the update yet. I'll report this to the team.
