### ISSUE TITLE
Extension Toolkit doesn't work at all

### ISSUE THREAD

**Issue by cameronwh** [MicrosoftDocs/edge-developer#193]
Hello,

I am trying to use your extension toolkit to convert my Chrome extension to an Edge extension, however once I specify the folder the chrome extension is in, the UI does not change, nor update. 

Sometimes it adds two .js files, but most of the time it will just close the explorer window and then the toolkit UI does not change at all.

Is there a log file I can access to check for any exceptions/issues with my chrome extension?

Or, is there a step-by-step guide to convert a chrome extension to be able to be used in Edge?

**Comment by lmj0011** [comment]
if you have a complex chrome extension you might as well start rebuilding it from scratch just to figure out why it doesn't work in the Edge browser.

This will likely be one of your problems: https://github.com/MicrosoftDocs/edge-developer/issues/200

**Comment by cameronwh** [comment]
@lmj0011 thank you for your reply.

I've checked and most of the API's we are using are fully supported which is great. However the 'Identity' API is not supported (and currently only 'Under Consideration') which would be necessary for us to continue with edge extension development.

Is authentication via Identity Providers even possible within an edge extension? If so - could you (or someone else!) point me in the right direction?

**Comment by gebansal** [comment]
Considering its an old thread and we have rolled out a new Chromium-based Edge browser, I'll go ahead and close it. If you still are facing any issues, please feel free to reopen this issue or file a new one.
