### ISSUE TITLE
Water Fall

### ISSUE THREAD

**Issue by anis431** [MicrosoftDocs/edge-developer#1935]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5a6efb3-262c-c192-d18b-5275ce8c530d
* Version Independent ID: f5a6efb3-262c-c192-d18b-5275ce8c530d
* Content: [What's new in DevTools (Microsoft Edge 100) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/03/devtools-100#fix-the-waterfall-view-in-the-network-tool-now-matches-visual-studio-code-themes)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2022/03/devtools-100.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/whats-new/2022/03/devtools-100.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
@anis431 can you please comment here explaining what issue you are having with this doc exactly. You did not enter any feedback here and it's therefore hard for us to act on it.

**Comment by captainbrosset** [comment]
This repository is not a place that Microsoft uses for recruiting. If you are interested in working for Microsoft, please use the https://careers.microsoft.com/us/en website.

**Comment by anis431** [comment]
Thanks a lot.

Hello,
Thanks for your mail. I'm interested in working for your company. I
completed my Bachelor degree last 1987. I worked in various public and Non
government organizations. I have experience in this position.
I will wait for your message and prepare for a good interview.
For your consideration.
Thanking you,
Anis Ahmed Siddeque

WhatsApp Number : +8801788822510
Cell : +8801788822510
Zip code : 6600
Mail : ***@***.***
(28) LinkedIn
<https://www.linkedin.com/in/polash-sidddeque-8b8033202/recent-activity/>


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/11/22,
11:17:37 AM

**Comment by anis431** [comment]
Thanks, I'll check it out.

Hello,
Thanks for your mail. I'm interested in working for your company. I
completed my Bachelor degree last 1987. I worked in various public and Non
government organizations. I have experience in this position.
I will wait for your message and prepare for a good interview.
For your consideration.
Thanking you,
Anis Ahmed Siddeque

WhatsApp Number : +8801788822510
Cell : +8801788822510
Zip code : 6600
Mail : ***@***.***
(28) LinkedIn
<https://www.linkedin.com/in/polash-sidddeque-8b8033202/recent-activity/>


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/11/22,
11:17:57 AM
