### ISSUE TITLE
How to set English as default language in Edge Options

### ISSUE THREAD

**Issue by aalexeyenko** [MicrosoftDocs/edge-developer#1938]
Hi,
I am looking for an JAVA example how I can set default language (English) for Edge webdriver.
Unfortunately I haven't found example on how to do so in documentation.

```
EdgeOptions edgeOptions = new EdgeOptions();
WebDriver driver = new EdgeDriver(edgeOptions);
```

What should I set in edgeOptions to set the language? 
Thank you in advance,
Ganna Alieksieienko
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c37572ac-327b-4497-86aa-117434aafa93
* Version Independent ID: 00c6e970-68d3-c53b-dcf1-67a535e482f8
* Content: [Capabilities and EdgeOptions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/capabilities-edge-options)
* Content Source: [microsoft-edge/webdriver-chromium/capabilities-edge-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/capabilities-edge-options.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
@bwalderman could you please take a look at this?

**Comment by bwalderman** [comment]
@aalexeyenko, try adding this command line argument:

```java
EdgeOptions edgeOptions = new EdgeOptions();
edgeOptions.addArguments("--lang=en_US")
```

**Comment by captainbrosset** [comment]
I'm assuming the lack of response means Brandon's comment was helpful. So I will close this issue now.

**Comment by aalexeyenko** [comment]
Thank you! That was helpful.
