### ISSUE TITLE
Wrong Windows Target and Minimum version

### ISSUE THREAD

**Issue by datvm** [MicrosoftDocs/edge-developer#1939]
Hi,

With the setup in the article:

> Target version: Windows 10, version 1903 (build 18362) or later.
> 
> Minimum version: Windows 10, version 1803 (build 17134).

I could not build the project. I had to upgrade both version to:

- Target Version: Windows 10, version 2004 (build 19041)

- Min Version: Windows 10, version 1809 (build 17763)

Any lower and the compiler cannot find a missing assembly or incompatible version:

> Could not find SDK "Microsoft.UniversalCRT.Debug, Version=10.0.18362.0".

> Your application is taking a dependency on a framework package that has a TargetPlatformMinVersion that is higher than what your app is depending on. Change your app manifest to make sure the TargetPlaformMinVersion of your app’s dependencies is greater than or equal to the framework’s TargetPlatformMinVersion. TargetPlatformIdentifier: 'Windows.Universal'. Application's TargetPlatformVersion: '10.0.17134.0'. Dependent framework's TargetPlatformVersion: '10.0.17763.0'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6747d603-e773-dec7-7580-f18f4365cec9
* Version Independent ID: 5f7cd45b-5739-ad85-4b61-c9f94921df98
* Content: [Get started with WebView2 in WinUI 3 (Windows App SDK) apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui)
* Content Source: [microsoft-edge/webview2/get-started/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/winui.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out and reporting this documentation problem.
@champnic could you please take a look at the above and let me know what documentation changes are needed here.

**Comment by champnic** [comment]
I've created a bug on our backlog to track updating the min version and corresponding screenshot. Thanks!

**Comment by nishitha-burman** [comment]
@datvm Were you promoted with the "New Universal Windows Platform Project" window to set the target and minimum version as described here in item 9, right after you click "Create": https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui?branch=pr-en-us-2025#step-3---create-the-project-in-visual-studio?

**Comment by datvm** [comment]
@nishitha-burman hi, yeah I just noticed there is no step 9. After step 7 I am presented with the VS main window and the project. Also my template name is: Blank App, Packaged (WinUI **3** in Desktop). Also somehow now I don't have a package project created for me anymore, I wonder if there was an update to it? I am sure before I had 2 projects. Now the default and min targets when creating projects are:

```
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
```

And with that default values, I can use `WebView2` without any issue. I don't even need to add `xmlns:controls="using:Microsoft.UI.Xaml.Controls"`

**Comment by mikehoffms** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui#step-3---create-the-project-in-visual-studio

**Comment by mikehoffms** [comment]
Did a general update of the article.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui
