### ISSUE TITLE
Documentation short on prerequisites

### ISSUE THREAD

**Issue by stephenegriffin** [MicrosoftDocs/edge-developer#1940]
This page assumes you're already fluent in launch.json and visual studio code. If you're not, it's incomprehensible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da78c553-7954-49e7-52ff-35c2a0bef717
* Version Independent ID: da78c553-7954-49e7-52ff-35c2a0bef717
* Content: [Debug WebView2 apps with Visual Studio Code - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug-visual-studio-code)
* Content Source: [microsoft-edge/webview2/how-to/debug-visual-studio-code.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/debug-visual-studio-code.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikehoffms** [comment]
Possible leads:

Edge Dev docs:
* [Microsoft Edge DevTools extension for Visual Studio Code](https://docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension) - the only other article in the present repo that discusses launch.json.

VS Code docs:
* [Configure launch.json for C/C++ debugging in Visual Studio Code](https://code.visualstudio.com/docs/cpp/launch-json-reference)
* [JSON editing in Visual Studio Code](https://code.visualstudio.com/Docs/languages/json)

**Comment by captainbrosset** [comment]
Thanks a lot for raising this issue. You're right, the page doesn't explain what launch.json is, and how/where to create it. We need to fix this. I'll add this to our backlog for prioritization, and will keep you posted when a documentation fix has been made.

**Comment by mikehoffms** [comment]
A research query I should have added above:
* https://code.visualstudio.com/Search?q=launch.json

**Comment by mikehoffms** [comment]
see related article in same doc-set: 
https://learn.microsoft.com/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension/launch-json
