### ISSUE TITLE
distribution.md: Broken link

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/edge-developer#1947]
Hi.

The following link is broken: <https://developer.microsoft.com/microsoft-edge/webview2>

**Expected behavior:** It is supposed to be the language-agnostic link to the WebView2 page. For example, a German user clicking on it is expected to be taken to <https://developer.microsoft.com/de-de/microsoft-edge/webview2/>.

**Actual behavior:** The affected link redirects to: <https://developer.microsoft.com/en-US/microsoft-edge/>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute your app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution?source=docs)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks @skycommand for filing this. This is a known issue that hasn't been fixed yet unfortunately. We have a dev team working on this at the moment, so hopefully this should be resolved soon.

@mikehoffms thanks!

**Comment by mikehoffms** [comment]
I confirmed that clicking the link at top of Issue,
https://developer.microsoft.com/microsoft-edge/webview2
brings me to correct deep-nested page per original URL, auto-inserting my own "user's default lang":
https://developer.microsoft.com/en-us/microsoft-edge/webview2/
