### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by Jiggnubs** [MicrosoftDocs/edge-developer#1962]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87aef5c6-630f-992c-5813-813cb861de4a
* Version Independent ID: 87aef5c6-630f-992c-5813-813cb861de4a
* Content: [What's new in DevTools (Microsoft Edge 97) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools#3d-view-tool-supports-changing-color-themes-in-devtools)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Hello yourself!
I will close this issue as there is nothing actionable here. Please feel free to open a new one if you find a problem with the Edge developer docs.
