### ISSUE TITLE
Error when installing Edge via apt install microsoft-edge-stable

### ISSUE THREAD

**Issue by AGrosserHH** [MicrosoftDocs/edge-developer#1969]
HI all,

I am trying to install the edge driver stable on Linux and since two weeks I am getting an error that some file is not found anymore. I was wondering if someone has got an idea on how to solve this.

My command is:

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg 
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/ sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list' 
/usr/bin/yes | sudo apt update && /usr/bin/yes | sudo apt install microsoft-edge-stable=95.0.1020.44-1 

The most important error message at the end is 

"E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/udev_245.4-4ubuntu3.16_amd64.deb 404 Not Found [IP: 185.125.190.36 80]"

Any idea how to solve or do I need to contact Microsoft directly?

Here is the complete error message:

WARNING: apt does not have a stable CLI interface. Use with caution in scripts. 
Reading package lists... 
Building dependency tree... 
Reading state information... 
The following additional packages will be installed: fonts-liberation libgbm1 libu2f-udev libwayland-server0 udev The following NEW packages will be installed: fonts-liberation libgbm1 libu2f-udev libwayland-server0 microsoft-edge-stable udev 0 upgraded, 6 newly installed, 0 to remove and 12 not upgraded. Need to get 118 MB of archives. After this operation, 399 MB of additional disk space will be used. Do you want to continue? [Y/n] 
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 fonts-liberation all 1:1.07.4-11 [822 kB] 
Get:2 https://packages.microsoft.com/repos/edge stable/main amd64 microsoft-edge-stable amd64 95.0.1020.44-1 [116 MB]
Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 libwayland-server0 amd64 1.18.0-1 [31.6 kB] 
Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgbm1 amd64 21.2.6-0ubuntu0.1~20.04.2 [29.2 kB] Err:
5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 udev amd64 245.4-4ubuntu3.16 404 Not Found [IP: 185.125.190.36 80] 
Get:6 http://archive.ubuntu.com/ubuntu focal/main amd64 libu2f-udev all 1.1.10-1 [6,108 B] 
debconf: delaying package configuration, since apt-utils is not installed 
Fetched 116 MB in 2s (74.5 MB/s) 
Selecting previously unselected package fonts-liberation. 
(Reading database ... 
(Reading database ... 5% 
(Reading database ... 10% 
(Reading database ... 15% 
(Reading database ... 20% 
(Reading database ... 25% 
(Reading database ... 30% 
(Reading database ... 35% 
(Reading database ... 40% 
(Reading database ... 45% 
(Reading database ... 50% 
(Reading database ... 55% 
(Reading database ... 60% 
(Reading database ... 65% 
(Reading database ... 70% 
(Reading database ... 75% 
(Reading database ... 80% 
(Reading database ... 85% 
(Reading database ... 90% 
(Reading database ... 95% 
(Reading database ... 100% 
(Reading database ... 93064 files and directories currently installed.) 
Preparing to unpack .../fonts-liberation_1%3a1.07.4-11_all.deb ... 
Unpacking fonts-liberation (1:1.07.4-11) ... 
Selecting previously unselected package libwayland-server0:amd64. 
Preparing to unpack .../libwayland-server0_1.18.0-1_amd64.deb ... 
Unpacking libwayland-server0:amd64 (1.18.0-1) ... 
Selecting previously unselected package libgbm1:amd64. 
Preparing to unpack .../libgbm1_21.2.6-0ubuntu0.1~20.04.2_amd64.deb ... 
Unpacking libgbm1:amd64 (21.2.6-0ubuntu0.1~20.04.2) ... 
Selecting previously unselected package microsoft-edge-stable. 
Preparing to unpack ...
/microsoft-edge-stable_95.0.1020.44-1_amd64.deb ... 
Unpacking microsoft-edge-stable (95.0.1020.44-1) ... S
etting up libwayland-server0:amd64 (1.18.0-1) ... 
Setting up libgbm1:amd64 (21.2.6-0ubuntu0.1~20.04.2) ... Setting up fonts-liberation (1:1.07.4-11) ... 
Setting up microsoft-edge-stable (95.0.1020.44-1) ... 
update-alternatives: using /usr/bin/microsoft-edge-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode update-alternatives: using /usr/bin/microsoft-edge-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) i auto mode update-alternatives: using /usr/bin/microsoft-edge-stable to provide /usr/bin/microsoft-edge (microsoft-edge) in auto mode
Processing triggers for mime-support (3.64ubuntu1) ... 
Processing triggers for libc-bin (2.31-0ubuntu9.7) ... 
Processing triggers for man-db (2.9.1-1) ... 
Processing triggers for fontconfig (2.13.1-2ubuntu3) ... 
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/udev_245.4-4ubuntu3.16_amd64.deb 404 Not Found [IP: 85.125.190.36 80]

**Comment by captainbrosset** [comment]
Thanks for raising this issue. I'm trying to find the right place for this feedback to go to. I'll get back to you as soon as I know more.

**Comment by captainbrosset** [comment]
Hi @AGrosserHH, unfortunately this repository is about the Edge docs so this isn't the right place for us to help you on this specific issue. The best place I found is the Microsoft Edge insider support page here: https://www.microsoftedgeinsider.com/en-us/support

Please do submit a request for support there. I hope you get the help you need to resolve this. Thanks for your understanding.
