### ISSUE TITLE
browserAction.openPopup()

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/edge-developer#197]
Are there plans to support browserAction.openPopup()? It would be great to be able to trigger interaction with the browserAction popup via the a context menu item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0570b6f-559c-e512-49b4-8c78341407d1
* Version Independent ID: 85c8aa17-9d5e-ce7d-be50-0e1e9cb85e88
* Content: [Extensions - Extension API roadmap - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/extension-api-roadmap)
* Content Source: [microsoft-edge/extensions/api-support/extension-api-roadmap.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/api-support/extension-api-roadmap.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by LexSwed** [comment]
Since Edge is in hands of Chromium now, we can refer to the long hanging issue: https://stackoverflow.com/questions/10479679/how-can-i-open-my-extensions-pop-up-with-javascript

**Comment by gebansal** [comment]
@damienestewart, @LexSwed  has rightly pointed out considering the new Edge browser is Chromium-based.
I am closing this thread for now. If you are still facing any issues, please feel free to either reopen this issue or create a new one.
