### ISSUE TITLE
how to install on windows?

### ISSUE THREAD

**Issue by RichardJECooke** [MicrosoftDocs/edge-developer#1974]
This doesn't explain how to install or run your PWA on Windows. That's a crucial feature for this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ce6ac4-36b1-0520-6474-37a2bb2f78bd
* Version Independent ID: a17cb98d-72db-1b3c-9d89-1af2773617ab
* Content: [Get started with Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/index.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
The page @mikehoffms linked to is indeed the right place for understanding how to install and run PWAs on Windows.
The page you linked to (Get started) is targeted at web developers instead. But I agree, we should probably cross-link to help people navigate these pages.
