### ISSUE TITLE
Facebook feedback 

### ISSUE THREAD

**Issue by RabbitBig** [MicrosoftDocs/edge-developer#198]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4ba40e-71a3-0e5b-0f6f-c22fe6fb93dd
* Version Independent ID: 7d51bd1b-8f03-9786-3615-cda14732e8a3
* Content: [Extensions - Adding and removing extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/adding-and-removing-extensions)
* Content Source: [microsoft-edge/extensions/guides/adding-and-removing-extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/adding-and-removing-extensions.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by RabbitBig** [comment]
Facebook

**Comment by mainuddinprodan** [comment]
https://github.com/MicrosoftDocs/edge-developer/issues/198#issuecomment-435710612
