### ISSUE TITLE
Great article! (Not an Ordinary Issue - explained inside) 

### ISSUE THREAD

**Issue by IamLizu** [MicrosoftDocs/edge-developer#199]
Actually, it was a feedback field and feedback can be positive too, right? So, why add every feedback as issue on GitHub? It would be cool if some filters applied (if possible).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcef5936-232e-1ab0-c1c4-77026c79e277
* Version Independent ID: b6ec450d-ead9-ffcf-0d5b-7a408bf0e13d
* Content: [Get started with Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/get-started)
* Content Source: [microsoft-edge/progressive-web-apps/get-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/get-started.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
Interesting idea, @IamLizu! Would you mind posting the suggestion to our MicrosoftDocs (docs.microsoft.com) feedback channel: https://github.com/MicrosoftDocs/feedback/issues

Thanks!

**Comment by IamLizu** [comment]
Done. Did in Feature request. But accidentally posted twice.
