### ISSUE TITLE
Running tests in EdgeInIE Mode on VM does not work unless the machine is connected.

### ISSUE THREAD

**Issue by MatsMats100** [MicrosoftDocs/edge-developer#1991]
We are trying to execute Selenium GUI Tests on Virtual Machines through Jenkin for the browser EdgeInIEMode. The Test runs without any issues when the remote machine is connected (and maximized)to our local laptop. However, the test execution halts if the machine is not connected or even if the remote machine is connected but minimized. Automation is getting started but doing nothing by displaying the below log all the time. (When I connect back to the machine, I can see that the browser is launched but no more steps beyond that.)

Writing to Selenium trace log: C:\LogRepo\Logs\Selenium.txt
Started InternetExplorerDriver server (32-bit)
4.0.0.0
Listening on port 45227
Only local connections are allowed

Please note: Same Tests can be executed in the same setup for other browsers without any issues even if the virtual machine/remote machine is disconnected/minimized.

Virtual machine Operating System: Win10
Selenium version: 3.141
Edge browser version: 103
IE Driver version: 4.0

The code used to launch EdgeInIE mode is

System.setProperty("webdriver.ie.driver", "IE driver path");
InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
ops.put("ie.edgechromium", true);
ops.put("ie.edgepath", " C:\\Program Files (x86)[\\Microsoft\\Edge\\Application\\msedge.exe](file://microsoft/Edge/Application/msedge.exe)");
InternetExplorerDriver driver = new InternetExplorerDriver(edgeIe11Options);
driver.get(http://www.google.com);

With the above code, Tests are running without any issues in EdgeInIEMode on the local laptop.

**Comment by captainbrosset** [comment]
Thanks for reaching out. We recently launched a new github repo specifically for discussing and asking technical questions about Microsoft Edge WebDriver. Your issue would have a lot more visibility and chances of being resolved on that new repo. So could you please re-create it there? Here is the URL to the repo: https://github.com/MicrosoftEdge/EdgeWebDriver/issues

Thank you for your understanding.
