### ISSUE TITLE
Page not Found

### ISSUE THREAD

**Issue by MrMaavin** [MicrosoftDocs/edge-developer#1992]
This (https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/webauthn/) tutorial has a dead link:
https://webauthndemo.appspot.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c40654f-15fb-71ff-fb2c-24f0ea0cd7bb
* Version Independent ID: d4ab57a2-ee0b-efd6-2a8d-69399d3c59bf
* Content: [Emulate authenticators and debug WebAuthn - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/webauthn/)
* Content Source: [microsoft-edge/devtools-guide-chromium/webauthn/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/webauthn/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for the report. It seems like the demo app for webauthn has moved to https://try-webauthn.appspot.com/
We should update the link and make sure the documentation is still up to date with the demo.
