### ISSUE TITLE
[DevTools Docs Feedback] The Javascript example of the Selenium Internet Explorer Driver is not working 

### ISSUE THREAD

**Issue by luckyBricks** [MicrosoftDocs/edge-developer#1996]
I'm trying to start using the Internet Explorer Driver by referring the official document. 
[Use Internet Explorer Driver to automate IE mode in Microsoft Edge - Microsoft Edge Development | Microsoft Docs](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=javascript)

When I tried to startup the automated Edge instance by the codes, the browser will just freeze and won't type 'IE mode' for searching.
I'm using the 32-bit driver.

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/44552873/172795089-372b3720-66cf-44a9-9856-02388928235b.png">

**Version Information:**
`nodejs v16.15.1`
`IEDriverServer.exe 4.2.0.0`
`selenium-webdriver 4.2.0`
`Edge 102.0.1245.33 (Official build) (64-bit) `

**Comment by captainbrosset** [comment]
Thanks for filing this. I tested locally and got the same problem. This call never resolves `await driver.get('http://www.bing.com');` it seems.

@bwalderman do you think this is a documentation problem, or a bug with the driver?

**Comment by bwalderman** [comment]
This doesn't appear to be a documentation problem. The code samples were all tested, so the driver may have regressed recently.

**Comment by captainbrosset** [comment]
Thanks Brandon! Because this isn't a docs problem, let me close out this issue now.
