### ISSUE TITLE
Many missing Web Extension APIs

### ISSUE THREAD

**Issue by nero120** [MicrosoftDocs/edge-developer#200]
Edge still does not (fully) support the full Web Extension API platform due to many missing APIs.

Yes I've looked at the [Microsoft Edge Developer UserVoice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer?category_id=87962) site and can see that there are many requests for the missing APIs to be supported, yet Microsoft have not responded or committed to any of these. It seems that Microsoft arbitrarily decided which APIs to implement, and even those are not fully implemented with missing properties/methods. It is ludicrous to tell users to raise these issues as "feature requests" - if you commit Edge to supporting the Web Extension API platform then you must support 100% or it is not supported!!

I would like to know what is Microsoft's intention is regarding implementing these missing APIs, as it's of no use to any extension developer that Edge only partly implements these APIs. Our users would like us to support Edge but unless it supports the Web Extensions API 100% then it is not fit for purpose for Web Extensions.

Also, your [roadmap](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/extension-api-roadmap) page is incorrect, it states than certain APIs are supported when those APIs are only part-implemented. The statements that APIs are "supported" should be corrected to prevent further confusion.

**Comment by gebansal** [comment]
@nero120, Considering its an old thread and we have rolled out a new Chromium-based Edge browser, I am assuming your concern is resolved and closing the issue. If you still are facing any issues, please feel free to reopen this issue or file a new one.

**Comment by nero120** [comment]
Indeed @gebansal thanks!
