### ISSUE TITLE
Omnifood

### ISSUE THREAD

**Issue by Roya13** [MicrosoftDocs/edge-developer#2005]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f96b9489-8f01-cb4e-4a61-f1817303c287
* Version Independent ID: f96b9489-8f01-cb4e-4a61-f1817303c287
* Content: [Overview of DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/overview)
* Content Source: [microsoft-edge/devtools-guide-chromium/overview.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/overview.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing this issue as it is incomplete. Please add more information about the issue you are having and we can re-open it.
