### ISSUE TITLE
IE mode automation issue

### ISSUE THREAD

**Issue by jnoelilab** [MicrosoftDocs/edge-developer#2008]
For additional info: The public facing BMV sites seem to work ok with Edge/Chrome, Safari, etc.  

The internal sites (the ones that folks are using when you show up at a BMV branch to renew your plates/license, etc. are the problem.  They use specific javascript/etc popups and animations. that rely on IE.  While they run ok in Edge in IE mode from a manual perspective, they do not necessarily behave as expected from an automation perspective.  To automate Edge requires the Edge webdriver, while Edge in IE mode requires the IE (4.x) webdriver.  BMV is looking to eliminate the use of the standalone verion for all manual testing.  I am tasked with emulating the manual experience as closely as possible.  The latest IE webdriver, which is required in order to use Edge in IE mode seems to have some issues with non-standard dropdown menus and text boxes.

I can make most (probably 90%) of the scripts run in straight Edge (or other browsers) but operating in IE mode in Edge requires some additional finessing (I'm maintaining/executing 300+ scripts on a regular basis.  However, the manual testers, and the actual users are operating in Edge/IE mode which means my tests are not that closely resembling actual user interactions.

Note: this is not a Python vs. Java issue.  It appears to be a Selenium issue.

I find that I've been having trouble summarizing the issue(s) but I will try.  In a nutshell, Edge would work for most of the test cases.  However, at least 10 percent of them would require Edge/IE mode.  Edge in IE/mode breaks many of our scripts.  To complicate things, the manual testers and end users are running Edge/IE mode which means that if I'm testing in straight Edge, then I'm not really emulating the user experience, validations, etc.

I can re-work the scripts to run in Edge/IE mode until the developers of the BMV product migrate away from the IE requirements, but it looks like that is not going to happen soon.  I can make it all work, but I am not aware of the original proposed scope or scale of this project.

I'll look forward to input and discussions about this issue.

I’d finally, add some a couple of screenshots that I haven’t shared with the client yet, but thought they may be pertinent and perhaps add to the discussion about running in IE mode in automation vs. manual testing.

The client has indicated that they will be removing IE from their end users’ machines by sometime next week.

**Comment by mikehoffms** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode

**Comment by captainbrosset** [comment]
Thank you for reaching out and apologies for the delay replying. We recently created a new GitHub repository specifically for reporting automation issues with Edge/IE, sharing feedback, and asking questions: https://github.com/MicrosoftEdge/EdgeWebDriver

Could you please create an issue on that repository instead? We use this one here for documentation changes only.
Thanks! And sorry about the inconvenience.
