### ISSUE TITLE
Please add C# example for each parts

### ISSUE THREAD

**Issue by soroshsabz** [MicrosoftDocs/edge-developer#2018]
ITNOA

The very interesting feature of WebView2 is that we can use it in C# native app like UWP or WPF, so please add C# snippet code in each part alongside of C++ code example

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d67f5bc-64e7-b958-6626-5238d8cf3d52
* Version Independent ID: 9d67f5bc-64e7-b958-6626-5238d8cf3d52
* Content: [Interop of native-side and web-side code - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/communicate-btwn-web-native)
* Content Source: [microsoft-edge/webview2/how-to/communicate-btwn-web-native.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/communicate-btwn-web-native.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for filing this, I've created a task on our backlog for consideration / prioritization.

**Comment by soroshsabz** [comment]
@captainbrosset Please link your issue to this issue

**Comment by captainbrosset** [comment]
Oh it's unfortunately not tracked on github or any other publicly visible site. So I can't link it here.
But we'll definitely update this issue once we have something to share.

**Comment by aarupaliya** [comment]
Soryy Its is a bad will do cant example for each

**Comment by captainbrosset** [comment]
After evaluation, we decided not to prioritize this particular request at this time in this repository.
If you need help on this, please check the https://github.com/MicrosoftEdge/WebView2Feedback repository where you can discuss with the team and other WebView2 users.
Thank you for your input.
