### ISSUE TITLE
Service Workers not registered

### ISSUE THREAD

**Issue by vermaraj83** [MicrosoftDocs/edge-developer#202]
In the Debugger panel , not able to see the Service Workers.
I followed the same steps as given in this article. What am I missing?
I am seeing "pwabuilder-sw-register.js" under localhost:1337 folder in debugger panel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcef5936-232e-1ab0-c1c4-77026c79e277
* Version Independent ID: b6ec450d-ead9-ffcf-0d5b-7a408bf0e13d
* Content: [Get started with Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/get-started)
* Content Source: [microsoft-edge/progressive-web-apps/get-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/get-started.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
Service Workers debugging tools were moved to their own dedicated DevTools panel in the very latest Windows update: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/whats-new

Could that be the issue? Thanks for calling this to my attention--looks like this tutorial needs updated.

**Comment by billhoelzer** [comment]
The error appears to be in the pwabuilder-sw-register.js file.

The line: navigator.serviceWorker.register('pwabuider-sw.js', {

should be: navigator.serviceWorker.register('pwabuilder-sw.js', {

Notice the missing "l".

**Comment by dcannova** [comment]
i would have find this comment before! i've just find the missing "L" by myself.... after 2 months the error on pwabuilder.com is still there :(

**Comment by ststimac** [comment]
@Reezaali I don't think I'm the right person to be assigned to this. This appears to be a PWA issue but I don't know how relevant this is anymore due to it being EdgeHTML content.

**Comment by JudahGabriel** [comment]
Hey folks, we've fixed the typo on pwabuilder.com and are updating these docs to account for it.

**Comment by Reezaali** [comment]
Here's a [link ](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/get-started)to the updated docs. I'll go ahead and close this issue. Thanks.
