### ISSUE TITLE
let script = document.createElement('script'); script.src = 'https://code.jquery.com/jquery-3.2.1.min.js'; script.crossOrigin = 'anonymous'; script.integrity = 'sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4='; document.head.appendChild(script);

### ISSUE THREAD

**Issue by Nelkins3** [MicrosoftDocs/edge-developer#2028]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 343cbd5d-9797-4325-5cb7-5b8facc23f41
* Version Independent ID: 11baa4fb-8b84-45c4-5507-a04df88c77bb
* Content: [Run snippets of JavaScript on any webpage - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/snippets)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript/snippets.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/javascript/snippets.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out, unfortunately I'm not seeing any description of what your issue might be with the documentation.
So I'll close this issue for now but feel free to comment with more information if you have any.
