### ISSUE TITLE
Revision of sections

### ISSUE THREAD

**Issue by JasonAndrewWriter** [MicrosoftDocs/edge-developer#2052]
WebView2 contains hundreds of APIs that provide a vast set of capabilities, ranging from enhancing your app's native-platform capabilities, to enabling your app to modify browser experiences. Leveraging this technology for your app grants it access to various methods and properties that are provided through the WebView2 classes or interfaces.
This article provides a high-level grouping of these APIs to help you understand the different things you can do using WebView2.

Hybrid app approach
When deciding between building a web app or a native app, a Developer should consider the tradeoff between reach and power:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e2e1f6-9d4d-1b6e-dc60-d03c95e5e366
* Version Independent ID: 75e2e1f6-9d4d-1b6e-dc60-d03c95e5e366
* Content: [Overview of WebView2 features and APIs - Microsoft Edge Development](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/overview-features-apis?branch=pr-en-us-1971&tabs=dotnetcsharp)
* Content Source: [microsoft-edge/webview2/concepts/overview-features-apis.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/overview-features-apis.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
@JasonAndrewWriter how is this different from #2051? Do we need 2 issues for this? Or should one of them be closed?
