### ISSUE TITLE
IE had been lock cant use this solution to use IE mode

### ISSUE THREAD

**Issue by osakajim** [MicrosoftDocs/edge-developer#2053]
[Enter feedback here]
after 6.29 system lock IE driver so when we use IEDriverServer to extend path Edge 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Version Independent ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Content: [Use Internet Explorer Driver to automate IE mode in Microsoft Edge - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=python)
* Content Source: [microsoft-edge/webdriver-chromium/ie-mode.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/ie-mode.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for the feedback and sorry about the delay replying. I think you will get more help by posting your feedback to this repository instead: https://github.com/MicrosoftEdge/EdgeWebDriver/issues
Can you create a new issue there and describe the problem you are experiencing?
Thanks, and sorry for the inconvenience.
