### ISSUE TITLE
Does WebView2 development really depend on customers having a "Preview" release of Edge?

### ISSUE THREAD

**Issue by MikeyWetzel** [MicrosoftDocs/edge-developer#2055]
Here we are in July 2022, and the directions clearly state to "Install a preview channel of Microsoft Edge". Is that really the current state?

The directions are for how to get WebView2 up in a development environmnet, fair enough, but how do you deploy code to cusomters? Do they have to install a preview version of Edge? Do they have to install the WebView2 component on Windows 10 and Windows 11?

The instructions are not adequate for creating production code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ba6a76-eb0b-e8f2-dfc9-d2c0df6261a4
* Version Independent ID: 8d62fdee-f44a-3d40-6800-04d7bd6193f8
* Content: [Get started with WebView2 in WinForms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms#feedback)
* Content Source: [microsoft-edge/webview2/get-started/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikehoffms** [comment]
I did a quick test of WinForms GetStarted from WebView2Samples repo: when loading or building the solution, VS prompted me to Update WebView2 SDK from Prerelease to Latest Stable.

Thanks for your valuable and helpful input.  The articles and readmes and samples are being updated, including for WinForms.  I entered a work item to track this issue, re:
*  GetStart WinForms tutorial article.
* Completed GetStart WinForms project in WebView2Samples repo - needs a Readme, will point to the above article.
* Also looking into non-GetStart article & readme & sample, for WinForms.

**Comment by mikehoffms** [comment]
OP also raises points, related to GetStart WinForms tutorial article:
> How do you deploy code to customers? 

> Do they have to install a preview version of Edge? 

> Do they have to install the WebView2 component on Windows 10 and Windows 11?

>The instructions are not adequate for creating production code."

Related articles: 
* Distribute your app and the WebView2 Runtime
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

Deployment is not mentioned or linked to directly, in the GetStart WinForms tutorial article.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms#see-also

**Comment by captainbrosset** [comment]
Thank you both. It sounds like we have this tracked and being worked on. So I'm just tagging this accordingly.

**Comment by captainbrosset** [comment]
This can now be closed since #2262 has been merged.
