### ISSUE TITLE
Edge IE Mode no option to copy the xpath after doing an inspect element in Developer Tools

### ISSUE THREAD

**Issue by julsjack** [MicrosoftDocs/edge-developer#2067]
I am running selenium automation in Edge with IE mode on. If I inspect an element to find it's attributes, then right click on longer longer see the option to copy xpath. Can you help me?

**Comment by captainbrosset** [comment]
Thanks for reaching out @julsjack. Unfortunately, this repository is about the documentation of the tool, not about the tool itself. Can you please ask your question again on this repository: https://github.com/MicrosoftEdge/EdgeWebDriver/issues
Thanks a lot!
