### ISSUE TITLE
Preview edge not needed

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/edge-developer#2068]
In doc page it is stated:
>  Install a preview channel of Microsoft Edge

I was able to go through the steps with just using the non-preview Edge browser that comes preinstalled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99f63e2b-08f3-0123-0290-81ed8e9007a8
* Version Independent ID: ddea56f8-1ea4-ac98-1a18-00b107f46a3e
* Content: [Get started with WebView2 in WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/wpf)
* Content Source: [microsoft-edge/webview2/get-started/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#40553960

**Comment by captainbrosset** [comment]
Thanks for the report. I'll add this to our documentation backlog and will report back once we have a fix for it.
