### ISSUE TITLE
Out of date?

### ISSUE THREAD

**Issue by sopatt** [MicrosoftDocs/edge-developer#207]
I have edge version 44.17763.1.0. The "Inspect: Background page" link does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b754b2f-8fdb-611a-fd7e-b9b8503db79a
* Version Independent ID: 9f673ab0-9bd6-3780-43b8-b36c5d4876af
* Content: [Extensions - Debugging extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/debugging-extensions)
* Content Source: [microsoft-edge/extensions/guides/debugging-extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/debugging-extensions.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by sopatt** [comment]
Solved. https://github.com/MicrosoftDocs/edge-developer/issues/97

**Comment by jm-trd-ms** [comment]
Closed in https://github.com/MicrosoftDocs/edge-developer/issues/97.
