### ISSUE TITLE
Consider adding "Quota usage" details to other topics

### ISSUE THREAD

**Issue by kypflug** [MicrosoftDocs/edge-developer#2070]
The details under "[Quota Usage](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/progressive-web-apps/#quota-usage)" on the "[Debug Progressive Web Apps (PWAs)](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/progressive-web-apps/)" topic are important to accurately interpret the Storage Usage chart on the Application tab and to understand what Cache data means, since they can substantially inflate the apparent storage usage.

Consider adding a pointer to this section, or repeating some of these details, on topics like [Application tool, to manage storage](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/storage/application-tool) or [View Cache data](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/storage/cache); a user seeking to understand their storage usage may not intuitively know to check the Debug Progressive Web Apps (PWAs) topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 760547ef-76e5-9c94-2150-38be89db9dc7
* Version Independent ID: e7141f3c-13f1-7edf-0368-792a700502c4
* Content: [Debug Progressive Web Apps (PWAs) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/progressive-web-apps/)
* Content Source: [microsoft-edge/devtools-guide-chromium/progressive-web-apps/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/progressive-web-apps/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by kypflug** [comment]
Note: Related CRBug here seeking to use actual usage rather than padded usage for the "Storage Usage" view: https://bugs.chromium.org/p/chromium/issues/detail?id=1346049

**Comment by captainbrosset** [comment]
Thank you Kyle. I will make a task on our backlog to improve this.

**Comment by captainbrosset** [comment]
This was recently implemented in PR #2192. Closing.
