### ISSUE TITLE
samples

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [MicrosoftDocs/edge-developer#2075]
where are the sample codes on github? half of the links are dead, and github only have .md files without the code, where it is?

**Comment by mikehoffms** [comment]
@MyTDT-Mysoft - could you please provide some specific pages (URLs for articles or readme.md files) to inspect?  Do you mean WebView2 samples, or samples for other technologies?

Are you rereferring to dead links in Readme pages at this main GitHub repo for WebView2 samples?
https://github.com/MicrosoftEdge/WebView2Samples/

I'm looking for dead links or missing sample code at or near these pages/URLs:

In the regular docs, the main, high-level page that links to articles about samples and links to the samples repo too:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/code-samples-links

Location of Samples Repo 1 on GitHub:
The main WebView2 sample, which has many files other than .md:
https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample

Location of Samples Repo 2 on GitHub:
A 2nd repo for WebView2 samples:
https://github.com/MicrosoftEdge/WebView2Browser

Microsoft's Samples Browser, which currently lists 3 of the WebView2 samples (the 3 are getstart completed tutorial projects):
https://docs.microsoft.com/en-us/samples/browse/

**Comment by captainbrosset** [comment]
@MyTDT-Mysoft without more specific information from you on this, I'll have to close this issue. Feel free to comment back with more information and I can re-open it.
