### ISSUE TITLE
Get info about the latest version of Evergreen Bootstrapper

### ISSUE THREAD

**Issue by skident** [MicrosoftDocs/edge-developer#2077]
Hi! 
I'd like to know if there is a way to get the latest version of Evergreen Bootstrapper available to download?
For example: I have an installed version 1.1.1.1 on my machine but there is a newer version available 2.2.2.2. So, do you have some end-point URL which could be used to get an info that my current version of Evergreen Bootstrapper is not the latest one.

Example of request:
`GET https://go.microsoft.com/evergreenLatestVersion`
Example of response:
`{"version": "2.2.2.2"}`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute your app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for your question. We have a different repository specifically for WebView2 feedback/discussions/questions: https://github.com/MicrosoftEdge/WebView2Feedback/issues
Can you please post your question there instead? Thanks for your understanding!
