### ISSUE TITLE
The console.timeStamp() description conflicts with the linked MDN documentation

### ISSUE THREAD

**Issue by Garee** [MicrosoftDocs/edge-developer#209]
The [console.timeStamp()](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console/console-api#timing-your-code) description is `Reports the current system time (in milliseconds).`

The behaviour in Firefox, and the description in the linked MDN docs, is to add a single marker to the browser's performance waterfall.

Should the link be removed? Should the description be updated if Edge matches the behaviour?

**Comment by Reezaali** [comment]
Since the issue appears to be related to EdgeHTML, I'll go ahead and close this issue.
