### ISSUE TITLE
[DevTools Docs Feedback] RE: MS Edge & MS Webview 2 crashes Photoshop

### ISSUE THREAD

**Issue by jaquelin777777** [MicrosoftDocs/edge-developer#2095]
Webview2 was latched onto Photoshop and kept crashing it with 7+ processes running under Photoshop in task manager. 

Microsoft Edge is an absolute shitshow and should be eradicated from Microsoft products effective yesterday.

PS: a solution is to find the folder somewhere under Program Files>Adobe>Webview2(check 'properties
 of task manager processes to find exact location) and delete the whole Webview folder.

**Comment by captainbrosset** [comment]
This isn't the right channel for this kind of feedback, it's also not specific enough for someone to investigate a potential problem. Plus it's rude and does not conform to our open source code of conduct: https://opensource.microsoft.com/codeofconduct
So I will close and lock this conversation.
