### ISSUE TITLE
How does the distribution of the WebView2 runtime work with the WinUI 2 WebView2 and the Microsoft Store?

### ISSUE THREAD

**Issue by aquinn39** [MicrosoftDocs/edge-developer#2103]
As per the article, it is possible to upload apps that use the WinUI 2 WebView2 to the Microsoft Store, so long as they are 64 bit only. However, I cannot find any information about how the distribution of the WebView 2 runtime. What is the case if a user who installs the app does not have the WebView 2 runtime installed? Will the Microsoft Store install the runtime? Is there a way to add the WebView 2 as a prerequisite? Obviously, general users aren't going to understand what the WebVIew2 runtime is or that/why they need it so I am curious about what the user experience is like for WebView2 apps installed from the Microsoft Store.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a41e6607-2207-13a3-e637-464e3504e0d4
* Version Independent ID: a41e6607-2207-13a3-e637-464e3504e0d4
* Content: [Publish a UWP WebView2 app to the Microsoft Store - Microsoft Edge Development](https://docs.microsoft.com/en-au/microsoft-edge/webview2/how-to/publish-uwp-app-store)
* Content Source: [microsoft-edge/webview2/how-to/publish-uwp-app-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/publish-uwp-app-store.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks a lot for reaching out. Let's ping @champnic on this one, he should be able to help. 
For information, there is also this WebView2 support/feedback repository that you can use: https://github.com/MicrosoftEdge/WebView2Feedback
Let's keep this issue here for now, depending on the answers to your questions, there may be some documentation changes to make.

**Comment by champnic** [comment]
Hey @aquinn39 - Like WinUI 3 apps, if the runtime is not available on the machine then the user is prompted to install the runtime by going to our runtime consumer site here: https://developer.microsoft.com/en-us/microsoft-edge/webview2/consumer/

We are also working on rolling out the WebView2 Runtimes downlevel to Windows 10 machines that would support WinUI 2 WebView2 apps, so the need for downloading and installing the runtime should be drastically reduced. I believe that rollout should be wrapping up soon. Thanks!
