### ISSUE TITLE
Is there a plan for 32 bit UWP apps to support WebView 2 in the future?

### ISSUE THREAD

**Issue by aquinn39** [MicrosoftDocs/edge-developer#2104]
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a41e6607-2207-13a3-e637-464e3504e0d4
* Version Independent ID: a41e6607-2207-13a3-e637-464e3504e0d4
* Content: [Publish a UWP WebView2 app to the Microsoft Store - Microsoft Edge Development](https://docs.microsoft.com/en-au/microsoft-edge/webview2/how-to/publish-uwp-app-store)
* Content Source: [microsoft-edge/webview2/how-to/publish-uwp-app-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/publish-uwp-app-store.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for your question. Can you please ask it again on this support/feedback repository for WebView2: https://github.com/MicrosoftEdge/WebView2Feedback
The current repo is about docs changes only. You'll get more support on the WebView2Feedback repository. Thanks for your understanding.
