### ISSUE TITLE
Code signing Certificate

### ISSUE THREAD

**Issue by towfiqi** [MicrosoftDocs/edge-developer#212]
Hi, does appx created with a hosted PWA, described in this page does not require a code signing certificate? On your building/publishing app documentation page, its written that all apps must be digitally before it can be published in Microsoft store. So I need some clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c306f3b9-d287-beba-eb3b-513e58df2440
* Version Independent ID: 787855c5-24d2-b772-e4c3-ce43118e5adb
* Content: [Tailor your PWA for Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/windows-features#feedback)
* Content Source: [microsoft-edge/progressive-web-apps/windows-features.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/windows-features.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by Maggers** [comment]
Hi Towfiqi,

We're looking back through old issues and cleaning these up. Apologies for the delay.

If you have Windows 10 in [developer mode](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development), you can do local testing and debugging without the need to digitally sign your package. 

If you are ready to add the app to the Microsoft Store for distribution, you will need to have the package signed.

Hope this helps.
