### ISSUE TITLE
Send CORS preflight requests for private network access needs updating

### ISSUE THREAD

**Issue by Ledge79** [MicrosoftDocs/edge-developer#2121]
For item: 
Send CORS preflight requests for private network access

This was removed in v98 and moved to 104 / 107.

See this for more info:
https://developer.chrome.com/blog/private-network-access-preflight/#rollout-plan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e08a40c-6a79-a8f1-64e6-8befc952684f
* Version Independent ID: e1ab6543-67eb-bc78-8466-2315d3906d2c
* Content: [Site compatibility-impacting changes coming to Microsoft Edge - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/site-impacting-changes)
* Content Source: [microsoft-edge/web-platform/site-impacting-changes.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/site-impacting-changes.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks. I'm creating a task on our backlog to address this.

**Comment by captainbrosset** [comment]
Closing this as I think the change has been done in the meantime. The article now does mention 104.
