### ISSUE TITLE
Confusing instructions for WPF - .Net Core or Framework

### ISSUE THREAD

**Issue by yowl** [MicrosoftDocs/edge-developer#2123]
Hi,

I find this a bit confusing. Step 3 part 6:
![image](https://user-images.githubusercontent.com/2720041/184413727-6fa4fe2a-9dc9-4a33-b7c3-501ec48cabb3.png)

There is no Next here, it is Create:

![image](https://user-images.githubusercontent.com/2720041/184413794-d01faa18-6984-48f2-8326-4cf7c31a8304.png)

Then step 8 tells you to select .Net Framework.
![image](https://user-images.githubusercontent.com/2720041/184413945-52650564-78fc-4f07-a1b3-a730d7c2f0d2.png)

Are both Core and Framework supported, the flow of the instructions is a bit unclear, IMHO.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99f63e2b-08f3-0123-0290-81ed8e9007a8
* Version Independent ID: ddea56f8-1ea4-ac98-1a18-00b107f46a3e
* Content: [Get started with WebView2 in WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/wpf)
* Content Source: [microsoft-edge/webview2/get-started/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks a lot for reporting this. I've created a task on our backlog, and we'll try to address this as soon as we can.
