### ISSUE TITLE
can't follow instructions.

### ISSUE THREAD

**Issue by pgee70** [MicrosoftDocs/edge-developer#2128]
My c# solution does not have a .vcproj file.
so i can't follow the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31b9c394-df9a-b0fd-5710-6c49f0354c0a
* Version Independent ID: a8c05336-1d5c-8fdc-0a47-aa99a927e6c1
* Content: [Distribute a WebView2 app as a single executable file - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/static)
* Content Source: [microsoft-edge/webview2/how-to/static.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/static.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
@champnic are you able to help @pgee70 with this issue? Do you think there a documentation change we need to make?

**Comment by champnic** [comment]
@pgee70 Can you share your sample app?

**Comment by captainbrosset** [comment]
Closing this issue as inactive for now. We can always re-open it later, so feel free to comment.
