### ISSUE TITLE
Extension API permission list missing declarativeNetRequestWithHostAccess

### ISSUE THREAD

**Issue by alesandroortiz** [MicrosoftDocs/edge-developer#2131]
Chrome 96+ supports the `declarativeNetRequestWithHostAccess` permission, but this particular permission is missing from the Edge docs. I haven't tested whether it works or not by Edge (I assume it does).

1. Can someone check whether it works or not in Edge?
2. If it does work, can someone add to the list of supported permissions? If not, might also be worth to explicitly note lack of compat here.

Docs for Chrome: https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#:~:text=declarativeNetRequestWithHostAccess%20(available%20since%20Chrome%2096)

Commit implementing permission: https://chromium.googlesource.com/chromium/src.git/+/a0ab02487c55c8e4955227d5ec6e0d1cfc77bbce

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90d301ef-7984-899c-dfa8-33a1825f2846
* Version Independent ID: 90d301ef-7984-899c-dfa8-33a1825f2846
* Content: [Declare API permissions in extension manifests - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/declare-permissions)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/declare-permissions.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/declare-permissions.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by alesandroortiz** [comment]
Realized this is also missing from the original Chrome page at https://developer.chrome.com/docs/extensions/mv3/declare_permissions/ which Edge uses as a base for its docs, so I've filed https://github.com/GoogleChrome/developer.chrome.com/issues/3470 with them.

**Comment by captainbrosset** [comment]
Thank you for filing this @alesandroortiz. I will create a task for us to prioritize and add the missing permission to the docs.
