### ISSUE TITLE
The Flashs

### ISSUE THREAD

**Issue by StarSyntaxStatic1** [MicrosoftDocs/edge-developer#2140]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6d02e68-5ae3-002a-5f56-712a421dbd2c
* Version Independent ID: 56993fe8-66d5-9599-c84f-5355a55107eb
* Content: [What's new in DevTools (Microsoft Edge 87) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2020/10/devtools#new-webauthn-tool)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2020/10/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/whats-new/2020/10/devtools.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
