### ISSUE TITLE
Webview2 - Fixed version : sometimes "not found"

### ISSUE THREAD

**Issue by jeff-1984** [MicrosoftDocs/edge-developer#2142]
Hello,

I could successfully use the option to specify the path to a fixed version of WebView2 (CreateCoreWebView2EnvironmentWithOptions , parameter WEBVIEW2_BROWSER_EXECUTABLE_FOLDER - https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1293.44#createcorewebview2environmentwithoptions)

But... on some specific computers, this does not work, I just get an error "NOT FOUND". 

I already tried to add the access rights on the folder as described here : https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution (icacls), but this has no impact.

The only thing I could find is a log in the event viewer that seems to be linked (in french) :
"Les paramètres d’autorisation propres à l’application n’accordent pas l’autorisation Local Activation pour l’application serveur COM avec le CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 et l’APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 au SID JEAN-MAES-E580\jeang de l’utilisateur (S-1-5-21-2010270883-1447936690-2847641450-1001) depuis l’adresse LocalHost (avec LRPC) s’exécutant dans le SID Non disponible du conteneur d’applications (Non disponible). Cette autorisation de sécurité peut être modifiée à l’aide de l’outil d’administration Services de composants."

Is there any place where we could have a hint on the error ? Any idea why the folder is not found ? 

With the evergreen version it's working, but we would like to avoid the automatic updates because we had an issue and we suspect this is linked to an automatic update.

For the moment, that "not found" problem is happening on 2 computers, 6 have no issue.

PS : The final application is a Java application using SWT + Edge brower (which is using the WebView2Loader.dll)

Thank you,
Jean-François

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute your app and the WebView2 Runtime - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#files-to-ship-with-the-app)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. In order to get this resolved quickly for you, I would advise posting this issue on this other repository instead: https://github.com/MicrosoftEdge/WebView2Feedback/issues
The WebView2 team and community are much more active over there as opposed to here, where we only deal with updating the documentation.

I hope this helps and I hope you can find a solution! Thanks for your understanding.
