### ISSUE TITLE
Not opening in IE Mode

### ISSUE THREAD

**Issue by Hoffman-Rihm** [MicrosoftDocs/edge-developer#2143]
I followed the instructions here but the browser stopped opening in IE mode.  I think edge may have had an update locking IE down more because it worked as recently as last week.

I can right click the tab and refresh in IE mode and the browser resumes as intended, but that defeats the purpose of the automation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Version Independent ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Content: [Use Internet Explorer Driver to automate IE mode in Microsoft Edge - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/ie-mode.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/ie-mode.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Hi @Hoffman-Rihm. Thanks for reaching out. This sounds more like an Edge/IE-mode automation bug than a documentation issue. Could you please post your issue on this feedback/discussion repository instead: https://github.com/MicrosoftEdge/EdgeWebDriver/issues ?

You will have more chances of getting a resolution to your problem over there. Thanks for your understanding. I hope you can find a solution to this soon.

**Comment by Hoffman-Rihm** [comment]
Thanks you @captainbrosset! Actually I had an outdated WebDriver in the directory overriding the updated one in PATH.  I deleted the old one and now it is working.  Sorry, my error, no bug, all is well.

**Comment by captainbrosset** [comment]
Oh that's even better! Glad you figured it out.
