### ISSUE TITLE
Clarify that XBox is not yet supported for UWP

### ISSUE THREAD

**Issue by LDS2020** [MicrosoftDocs/edge-developer#2151]
[Enter feedback here]

On the Webview2 runtime Roadmap page, you might wish to write (not for XBox or Hololens) after UWP and link to this discussion: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1604

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dec166ea-3192-50ac-a930-f2185226801f
* Version Independent ID: a7055048-1b57-b2dc-78ae-6786d8765467
* Content: [WebView2 Roadmap - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap)
* Content Source: [microsoft-edge/webview2/roadmap.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/roadmap.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. I've added a task on our team's backlog for prioritization.

**Comment by captainbrosset** [comment]
Closing this issue as this was recently implemented in PR #2193.
