### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by LDS2020** [MicrosoftDocs/edge-developer#2152]
[Enter feedback here]
You might wish to clarify that:

- that Webview 2 is not yet available for XBox or Hololens and possibly link to this discussion: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1604. I wasted a day trying to get it working on Xbox and having it mentioned here would have really helped.

- whether you have to initialize the control using EnsureCoreWebView2Async. I had to do this in a previous WinForms project but it doesn't appear you need to it for UWP. There is a passing mention in the Special Considerations section but I would clarify before the Special Considerations section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0042c10-cb18-e543-95ed-983f62afa37f
* Version Independent ID: 6bc76779-2539-5538-241e-2a9727f52398
* Content: [Get started with WebView2 in WinUI 2 (UWP) apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2)
* Content Source: [microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/winui2.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. I've added a task on our team's backlog for prioritization.

**Comment by captainbrosset** [comment]
Closing this issue as this was recently implemented in PR #2193.
