### ISSUE TITLE
chrome browser supports

### ISSUE THREAD

**Issue by srivanih** [MicrosoftDocs/edge-developer#216]
Hi,
I had a question, you specified that intent explorer doesn't support. May I know whether chrome supports? if yes, then what is the chrome version

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cabf96-7b2b-9eb6-c428-ff4b44a97312
* Version Independent ID: 922d390b-52b6-db2a-0aab-f338e8c21b85
* Content: [Dev guide - Web Authentication - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication)
* Content Source: [microsoft-edge/dev-guide/windows-integration/web-authentication.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/windows-integration/web-authentication.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by MatthewSteeples** [comment]
See https://www.caniuse.com/#search=webauthn for browser support

**Comment by Reezaali** [comment]
Hi @srivanih . I'm going to close this issue since there hasn't been additional discussion on the thread. Please open a new issue or comment on this issue if you have more questions. Thank you.
