### ISSUE TITLE
[Add-ons API]

### ISSUE THREAD

**Issue by evanller69** [MicrosoftDocs/edge-developer#2160]
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzhxlZ0LiLWheqV43BQKU
qlOXA1R9RZaQ3rrmtZ7yp7RCQlrfKc4LKBgA/pxk1RW0fP/CACt/VNG4twRCX9SV
OgnkBMkoVa14LYcYKeiUDeN4Az9mNGDMFkYrhLzYhW1BoQvHxl0Eqj1Rb0LWEQyO
tNBrCfPenNVgPv5ky8SYnhmsQYz3p+cVf6Fe8bcrldGBWofrc8IhHaB2W/1RwNlW
w8ck4sePu7xUHAAKKddgdWnqHGzx3nEUGMgGSq8kGtTPQ1LvWV8xI1n5T7BR0Mxo
2gM6KlCBZuKaekdMrqfrITm6KiuQSspnsG3q6bgbubr/peRAnP+6J3VA7ExBIonn
VQIDAQAB
-----END PUBLIC KEY----------BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzhxlZ0LiLWheqV43BQKU
qlOXA1R9RZaQ3rrmtZ7yp7RCQlrfKc4LKBgA/pxk1RW0fP/CACt/VNG4twRCX9SV
OgnkBMkoVa14LYcYKeiUDeN4Az9mNGDMFkYrhLzYhW1BoQvHxl0Eqj1Rb0LWEQyO
tNBrCfPenNVgPv5ky8SYnhmsQYz3p+cVf6Fe8bcrldGBWofrc8IhHaB2W/1RwNlW
w8ck4sePu7xUHAAKKddgdWnqHGzx3nEUGMgGSq8kGtTPQ1LvWV8xI1n5T7BR0Mxo
2gM6KlCBZuKaekdMrqfrITm6KiuQSspnsG3q6bgbubr/peRAnP+6J3VA7ExBIonn
VQIDAQAB
-----END PUBLIC KEY-----

**Comment by captainbrosset** [comment]
Closing as incomplete. Feel free to add a comment with more information about the issue you're having and we can re-open this.
