### ISSUE TITLE
https://thegolden7.com/

### ISSUE THREAD

**Issue by sailoa996** [MicrosoftDocs/edge-developer#2169]
[Enter feedback here]
https://thegolden7.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70229654-01d1-65e6-e84f-817935cd39a3
* Version Independent ID: 70229654-01d1-65e6-e84f-817935cd39a3
* Content: [What's new in DevTools (Microsoft Edge 105) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/09/devtools-105#focus-mode-improved-location-controls-for-devtools-activity-bar-and-quick-view)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2022/09/devtools-105.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/whats-new/2022/09/devtools-105.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
