### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by SememeS** [MicrosoftDocs/edge-developer#217]
Edge Dev tools needs a dark theme asap. I have switched recently to edge as my main personal-usage browser but not for development. Adding a dark theme for dev tools sooner rather than as an afterthought would entice more developers switching from chrome, firefox & others to use edge as their main development browser until you add more developer tools or/and link up edge more to microsoft IDEs(atom,vs code/community/vs/etc) and services(github).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7708ebf-b89b-168e-de02-bb00e9223318
* Version Independent ID: 48a20484-21fe-cbd3-7b84-f1992002eb63
* Content: [Microsoft Edge Developer Tools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide)
* Content Source: [microsoft-edge/devtools-guide.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by akinhwan** [comment]
I agree, is anyone working on a PR for this? Would be happy to help

**Comment by SememeS** [comment]
I found out recently that Microsoft is switching edge to be built on open source chromium, [here's a confirm from windows blog](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/)

Since visual studio code also uses chromium and has a dark theme developer tools. It would seem this will be either coming as well with the new edge on chromium or they're already builing their own custom skin for the new edge release. 

Based on this new info I'll be closing this issue until the new edge releases since the team is most likely focused on there.

**Comment by hkal** [comment]
Hey folks, the Edge DevTools team did ship a dark theme with [the new Edge](https://www.microsoftedgeinsider.com). You can read about the update [here](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new#new-dark-and-light-themes-for-the-devtools).
