### ISSUE TITLE
حل

### ISSUE THREAD

**Issue by Zaooa** [MicrosoftDocs/edge-developer#2171]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd03d41f-55ba-f51a-c121-c860d7e95d5d
* Version Independent ID: bd03d41f-55ba-f51a-c121-c860d7e95d5d
* Content: [Analyze pages using the Inspect tool - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/css/inspect)
* Content Source: [microsoft-edge/devtools-guide-chromium/css/inspect.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/css/inspect.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
