### ISSUE TITLE
New tab to Google

### ISSUE THREAD

**Issue by osman02** [MicrosoftDocs/edge-developer#2175]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b8d23f-25b3-6871-1c9d-afb4d15864d9
* Version Independent ID: 74185998-0136-f9e7-b156-19ef7017a59e
* Content: [Check for keyboard support by using the Tab and Enter keys - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/accessibility/test-tab-enter-keys)
* Content Source: [microsoft-edge/devtools-guide-chromium/accessibility/test-tab-enter-keys.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/accessibility/test-tab-enter-keys.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
