### ISSUE TITLE
App Capability Declarations

### ISSUE THREAD

**Issue by bastecklein** [MicrosoftDocs/edge-developer#219]
As stated above, "If your app needs programmatic access to user resources like pictures or music, or to devices like a camera or a microphone, you'll need to include the corresponding App capability declarations in your app package manifest file."

This is fine, except if you add capabilities to your PWA, you will fail certification with the following message:

"The Application cannot include an ApplicationContentUriRule with 'all' or 'allowForWebOnly' WindowsRuntimeAccess while any of the following capabilities are enabled: enterpriseAuthentication, sharedUserCertificates, musicLibrary, picturesLibrary, videosLibrary, removableStorage, documentLibrary, internetClientServer, privateNetworkClientServer."

So PWA's are effectively blocked from using many of the UWP runtimes features.  I was trying to allow Windows PWA users the ability to do Multiplayer games over their local LAN on an HTML5/JS PWA, but it is not possible to include the privateNetworkClientServer capability, and therefore socket networking is blocked for these apps.

It would be nice to open up these capabilities to PWA and Hosted Web Apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c306f3b9-d287-beba-eb3b-513e58df2440
* Version Independent ID: 787855c5-24d2-b772-e4c3-ce43118e5adb
* Content: [Tailor your PWA for Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/windows-features)
* Content Source: [microsoft-edge/progressive-web-apps/windows-features.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/windows-features.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by JudahGabriel** [comment]
You're right, `privateNetworkClientServer` can't be specified if you're also using WinRT for remote URIs. The [Cordova Win10 docs](https://github.com/apache/cordova-windows/blob/master/cordova-windows10.md#remote-access-and-capabilities) say this as well: 

> When the app manifest declares remote URIs or Web Context to have access to WinRT, then the public Windows Store will prevent on-boarding of apps that have the following capabilities declared:

> Enterprise Authentication (enterpriseAuthentication)
Shared User Certificates (sharedUserCertificates)
Documents Library (documentsLibrary)
Music Library (musicLibrary)
Pictures Library (picturesLibrary)
Videos Library (videosLibrary)
Removable Storage (removableStorage)
Internet client/server (internetClientServer) - note that internetClient is still permitted
Private network client/server (privateNetworkClientServer)

> Each of the library restrictions may be worked around by requesting that the user interact with the file system via a file picker. This prevents malicious injected code from arbitrarily accessing (for example) the file system.

> The network-related restrictions must be worked around by either using an API that doesn't use capability checks or by brokering communication via standard internet communication channels, such as XMLHttpRequest or Web Sockets.

We'll update the article with these details.

**Comment by captainbrosset** [comment]
@JudahGabriel I noticed that [the linked article](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/windows-features) ends up in a 404 error now, so I'm not sure if it was updated as you said last year and if this issue can now be closed.
Can you please update us on whether more work is needed here, and which documentation page would need to be changed?

**Comment by bastecklein** [comment]
Sorry @captainbrosset I can close this.  I don't think the legacy edge based hosted web apps are really supported anymore anyway, which was what the question was pertaining to in the first place!
