### ISSUE TITLE
[Add-ons API]

### ISSUE THREAD

**Issue by MahdiSayeh** [MicrosoftDocs/edge-developer#2200]
#Package : Bank_Servaer;

#import org.Jon.JsonException;
#import org.Json.Jsonobject;

#/**
 #* Created byTechno Service on 5/26/2018
 #*/
 #Public class json__Parser_Command  {
 
   # Public String Json_Parser (#"HEADER:"
             #"token=[https ://www.linkedinmobileapp.com/\?trk\=qrcode-on boarding]"
            #"token_issuer= 1"
    #"Method: POST"
    #"Url:http:\\login.parsgreen."
            #"[platform-address]/nzh/ServicePhoneNumber"
    #"Parameters:"
           #"productId= 2186"      
           #"paramNames= UserName" 
           #"paramValues= [ Alireza Mahboobi kia]"            #"paramNames= Timestamp" 
           #"paramValues= [20:45  2022/09/11]"              #"paramNames= SourceDepositNumber" 
           #"paramValues= [IR6101700000003442874860]"
           #"paramNames= TransferMoneyBillNumber"
           #"paramValues= [845036082]"
           #"paramNames= FileUniqueIdentifier" 
           #"paramValues= [BM/3096120]"
           #"paramNames=BatchPayaItemInfos=" 
           #"paramValues="                                "[{"
             #"Amount:635,000,000,000,000IRR,"
                                #"BeneficiaryFullName:BanaSazanAsoudAndish.co,"
                                #"Description:Transfer of resources,"
               #"DistCardNumber:'6104337811200870',''000','111','2164','101','238',%B6104337811200870^John/Doe,"     
#"BillNumber:845036082,"
        #"Amount:635,000,000,000,000IRR,ll"
        #"BeneficiaryFullName:BanaSazanAsoudAndish.co,"
            #"Description:Transfer of resources," 
#"DistCardNumber:'6104337811200870',''000','111','2164','101','238',%B6104337811200870^John/Doe,"     
#"BillNumber:845036082,"
                              
          #"paramNames= signature" 
           #"paramValues= [26115947]" 

#"Fwd :"='RIALL#Includ<@@'000,000,454,565,1"
# throws JSONException  {
 #String request=nuii;
#JSONObject jsonObject = new JSONObject(#"HEADER:"
            #"token=[https ://www.linkedinmobileapp.com/\?trk\=qrcode-on boarding]"
            #"token_issuer= 1"
    #"Method: POST"
    #"Url:http:\\login.parsgreen."
            #"[platform-address]/nzh/ServicePhoneNumber"
    #"Parameters:"
           #"productId= 2186"      
           #"paramNames= UserName" 
           #"paramValues= [ Alireza Mahboobi kia]"
#"paramNames= Timestamp" 
           #"paramValues= [20:45  2022/09/11]"             
 #"paramNames= SourceDepositNumber" 
           #"paramValues= [IR6101700000003442874860]"
           #"paramNames= TransferMoneyBillNumber"
           #"paramValues= [845036082]"
           #"paramNames= FileUniqueIdentifier" 
           #"paramValues= [BM/3096120]"
           #"paramNames=BatchPayaItemInfos=" 
           #"paramValues="                                "[{"
             #"Amount:635,000,000,000,000IRR,"
                                #"BeneficiaryFullName:BanaSazanAsoudAndish.co,"
                                #"Description:Transfer of resources,"
               #"DistCardNumber:'6104337811200870',''000','111','2164','101','238',%B6104337811200870^John/Doe,"     
#"BillNumber:845036082,"
        #"Amount:635,000,000,000,000IRR,ll"
        #"BeneficiaryFullName:BanaSazanAsoudAndish.co,"
            #"Description:Transfer of resources," 
#"DistCardNumber:'6104337811200870',''000','111','2164','101','238',%B6104337811200870^John/Doe,"     
#"BillNumber:845036082,"
                              
          #"paramNames= signature" 
           #"paramValues= [26115947]" 

#"Fwd :"='RIALL#Includ<@@'000,000,454,565,1");
#String Commandm = Jsonobject.getString("#<?xml version="1.0" encoding="UTF-8"?>
#<BEHAVIOR>
#<double_tap_lock value="true"/>
#<double_tap_cmd value=""/>
#<random_play value="true"/>
#<songs_folder value=""/>
#<songs_from_mediastore value="true"/>
#<tui_notification value="false"/>
#<auto_show_keyboard value="true"/>
#<auto_scroll value="true"/>
#<show_hints value="true"/>
#<show_alias_content value="false"/>
#<show_launch_history value="true"/>
#<clear_after_cmds value="-1"/>
#<clear_after_seconds value="-1"/>
#<max_lines value="-1"/>
#<time_format value="d MMM yyyy HH:mm:ss@HH:mm:ss"/>
#<time_format_separator value="@"/>
#<battery_medium value="50"/>
#<battery_low value="15"/>
#<device_format value="%d: %u"/>
#<ram_format value="Available RAM: %avgb GB of %totgb GB (%av%%)"/>
#<battery_format value="%(Charging: /)%v%"/>
#<storage_format value="Internal Storage: %iavgb GB / %itotgb GB (%iav%%)"/>
#<network_info_format value="%(WiFi - %wn/%[Mobile Data: %d3/No Internet access])"/>
#<input_format value="[%t] %p %i"/>
#<output_format value="%o"/>
#<session_info_format value="%u@%d:%p"/>
#<enable_app_launch value="true"/>
#<app_launch_format value="--&gt; %a"/>
#<alias_param_marker value="%"/>
#<alias_param_separator value=","/>
#<alias_replace_all_markers value="true"/>
#<multiple_cmd_separator value=";"/>
#<alias_content_format value="%a --&gt; [%v]"/>
#<external_storage_path value=""/>
#<home_path value="/storage/emulated/0"/>
#<app_installed_format value="App installed: %p"/>
#<app_uninstalled_format value="App uninstalled: %p"/>
#<enable_music value="false"/>
#<max_optional_depth value="2"/>
#<network_info_update_ms value="3500"/>
#<tui_notification_title value="T-UI"/>
#<tui_notification_subtitle value="T-UI is running"/>
#<tui_notification_click_cmd value=""/>
#<tui_notification_click_showhome value="true"/>
#<tui_notification_lastcmds_size value="5"/>
#<tui_notification_lastcmds_updown value="true"/>
#<tui_notification_priority value="0"/>
#<long_click_vibration_duration value="100"/>
#<long_click_duration value="700"/>
#<click_commands value="true"/>
#<long_click_commands value="true"/>
#<append_quote_before_file value="false"/>
#<optional_values_separator value="/"/>
#<notes_sorting value="0"/>
#<notes_allow_link value="true"/>
#<orientation value="2"/>
#<htmlextractor_default_format value="%t -&gt; %v%n%a(%an = %av)(%n)"/>
#<htmlextractor_notfound_message value="Not found"/>
#<tui_notification_time_color value="#03A9F4"/>
#<tui_notification_input_color value="#ff00ff00"/>
#<weather_key value="1f798f99228596c20ccfda51b9771a86"/>
#<weather_temperature_measure value="metric"/>
#<weather_location value="null"/>
#<weather_format value="Weather: %main, Temp: %temp"/>
#<clear_on_lock value="false"/>
#<unlock_counter_format value="Unlocked %c times (%a10/)%n%t(Unlock n. %i --&gt; %w)3"/>
#<unlock_time_divider value="%n"/>
#<unlock_time_order value="1"/>
#<unlock_counter_cycle_start value="6.00"/>
#<not_available_text value="n/a"/>
#<back_button_enabled value="true"/>
#<weather_update_time value="3600"/>
#<location_update_mintime value="20"/>
#<location_update_mindistance value="500"/>
#<show_weather_updates value="true"/>
#</BEHAVIOR>");
# String discardb = Jesonobject.getstring("6104337811200870',''000','111','2164','101','238',%B6104337811200870^John/Doe");
 #String Money = Jsonobject.getstring("633,992IRR");
 #System.out.println("635,000,000,000,000IRR : "+633,992IRR);
 #request = #<?xml version="1.0" encoding="UTF-8"?>
#<BEHAVIOR>
#<double_tap_lock value="true"/>
#<double_tap_cmd value=""/>
#<random_play value="true"/>
#<songs_folder value=""/>
#<songs_from_mediastore value="true"/>
#<tui_notification value="false"/>
#<auto_show_keyboard value="true"/>
#<auto_scroll value="true"/>
#<show_hints value="true"/>
#<show_alias_content value="false"/>
#<show_launch_history value="true"/>
#<clear_after_cmds value="-1"/>
#<clear_after_seconds value="-1"/>
#<max_lines value="-1"/>
#<time_format value="d MMM yyyy HH:mm:ss@HH:mm:ss"/>
#<time_format_separator value="@"/>
#<battery_medium value="50"/>
#<battery_low value="15"/>
#<device_format value="%d: %u"/>
#<ram_format value="Available RAM: %avgb GB of %totgb GB (%av%%)"/>
#<battery_format value="%(Charging: /)%v%"/>
#<storage_format value="Internal Storage: %iavgb GB / %itotgb GB (%iav%%)"/>
#<network_info_format value="%(WiFi - %wn/%[Mobile Data: %d3/No Internet access])"/>
#<input_format value="[%t] %p %i"/>
#<output_format value="%o"/>
#<session_info_format value="%u@%d:%p"/>
#<enable_app_launch value="true"/>
#<app_launch_format value="--&gt; %a"/>
#<alias_param_marker value="%"/>
#<alias_param_separator value=","/>
#<alias_replace_all_markers value="true"/>
#<multiple_cmd_separator value=";"/>
#<alias_content_format value="%a --&gt; [%v]"/>
#<external_storage_path value=""/>
#<home_path value="/storage/emulated/0"/>
#<app_installed_format value="App installed: %p"/>
#<app_uninstalled_format value="App uninstalled: %p"/>
#<enable_music value="false"/>
#<max_optional_depth value="2"/>
#<network_info_update_ms value="3500"/>
#<tui_notification_title value="T-UI"/>
#<tui_notification_subtitle value="T-UI is running"/>
#<tui_notification_click_cmd value=""/>
#<tui_notification_click_showhome value="true"/>
#<tui_notification_lastcmds_size value="5"/>
#<tui_notification_lastcmds_updown value="true"/>
#<tui_notification_priority value="0"/>
#<long_click_vibration_duration value="100"/>
#<long_click_duration value="700"/>
#<click_commands value="true"/>
#<long_click_commands value="true"/>
#<append_quote_before_file value="false"/>
#<optional_values_separator value="/"/>
#<notes_sorting value="0"/>
#<notes_allow_link value="true"/>
#<orientation value="2"/>
#<htmlextractor_default_format value="%t -&gt; %v%n%a(%an = %av)(%n)"/>
#<htmlextractor_notfound_message value="Not found"/>
#<tui_notification_time_color value="#03A9F4"/>
#<tui_notification_input_color value="#ff00ff00"/>
#<weather_key value="1f798f99228596c20ccfda51b9771a86"/>
#<weather_temperature_measure value="metric"/>
#<weather_location value="null"/>
#<weather_format value="Weather: %main, Temp: %temp"/>
#<clear_on_lock value="false"/>
#<unlock_counter_format value="Unlocked %c times (%a10/)%n%t(Unlock n. %i --&gt; %w)3"/>
#<unlock_time_divider value="%n"/>
#<unlock_time_order value="1"/>
#<unlock_counter_cycle_start value="6.00"/>
#<not_available_text value="n/a"/>
#<back_button_enabled value="true"/>
#<weather_update_time value="3600"/>
#<location_update_mintime value="20"/>
#<location_update_mindistance value="500"/>
#<show_weather_updates value="true"/>
#</BEHAVIOR>
#+":"+6104337811200870',''000','111','2164','101','238',%B6104337811200870^John/Doe +":"+633,992IRR;
       # return request;

 #   }
# }

**Comment by captainbrosset** [comment]
This isn't an issue, there's only a code snippet and no question or problem description. So I'll go ahead and close it. Feel free to comment with more information and we can re-open the issue then.
