### ISSUE TITLE
Trial Version of HWA, possible?

### ISSUE THREAD

**Issue by istudiomobile** [MicrosoftDocs/edge-developer#221]
Hi, I developed a HWA that is intended to be published in the Windows 10 store to make it installable on devices. Is there a way to make a trial version of it? ...and allow continous usage after payment is made?

Thanks in advance!

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 1ba583c8-c78b-49de-a68a-4fbc7a2bb568
* Version Independent ID: e71db58c-e513-eefd-3f4d-2644b88f405d
* Content: [Progressive Web Apps in the Microsoft Store - Microsoft Edge Development](https://docs.microsoft.com/es-es/microsoft-edge/progressive-web-apps/microsoft-store#feedback)
* Content Source: [microsoft-edge/progressive-web-apps/microsoft-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/microsoft-store.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by JudahGabriel** [comment]
Have a look at [implementing a trial version of your app](https://docs.microsoft.com/en-us/windows/uwp/monetize/implement-a-trial-version-of-your-app). It walks through how to do this through the dev center. The code sample is in C#, but you can use WinRT APIs from your Javascript.
