### ISSUE TITLE
Where are the release notes for 1.0.1343.22?

### ISSUE THREAD

**Issue by aquinn39** [MicrosoftDocs/edge-developer#2215]
No release notes at all are shown for version 1.0.1343.22.

![image](https://user-images.githubusercontent.com/43898231/192827600-d40b3908-ff5c-4a79-8397-87e4c0b49596.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ffdb8b5e-d4b0-1681-fd28-59828b905bd9
* Version Independent ID: d500292e-d873-7cb8-cdcb-02135c83d57d
* Content: [Release Notes for the WebView2 SDK - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp)
* Content Source: [microsoft-edge/webview2/release-notes.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/release-notes.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Pinging @nishitha-burman on this one. Do you know why that particular version seems empty?

**Comment by captainbrosset** [comment]
Oh I spoke too soon, I see @mikehoffms already opened a PR to address this!

**Comment by mikehoffms** [comment]
OK to close.  The PR that fixes this Issue has been merged.  Check the result, PR adds a General heading (not prop/d to my machine yet):
https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#10134322
