### ISSUE TITLE
Getting started guide shows outdated Manifest V2

### ISSUE THREAD

**Issue by bentorkington** [MicrosoftDocs/edge-developer#2219]
The Getting Started Guide demonstrates using Manifest V2, even though according to the timeline new extensions using V2 will not be accepted after July 2022

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d70c4902-5246-ea94-a95f-f4ac94611c4c
* Version Independent ID: c7f1c45d-32ad-90f7-bfd6-d44ecd2bc941
* Content: [Create an extension tutorial, part 1 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension?tabs=v2)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for filing this. I'll make sure this is tracked on our backlog (it might, in fact, already be).
For information, we also have a guide to migrate from v2 to v3 here: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/migrate-your-extension-from-manifest-v2-to-v3

**Comment by mikehoffms** [comment]
@captainbrosset - keeping V2 info b/c needed by some users.

**Comment by mikehoffms** [comment]
This Issue didn't auto-close.  ok to close now, per Merged indicator above.
V3 is now the default, left tab in Part 1 & Part 2 pages:
https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension?tabs=v3

**Comment by bentorkington** [comment]
Thanks for this Michael.

I know this will probably go nowhere and people will probably think I'm just an idiot, but I honestly didn't notice the tab view. It's probably instantly recognisable to someone who spends a lot of time on MS Learn, but I work on a variety of platforms each day and when skimming the page it just doesn't stand out like a tab view until you hover over it.

**Comment by mikehoffms** [comment]
Valuable UX feedback, much appreciated & interesting.

**Comment by captainbrosset** [comment]
I relate to this @bentorkington. Even if I work on the docs myself, I don't often work on a pages that do have these tabs. And when I first looked at the documentation you mentioned, I totally missed the tabs myself too. It took a second read to see them.
So this is definitely great UX feedback, and we'll make sure to pass it along.
