### ISSUE TITLE
UWP app is closed if no response sent back to Edge browser/Extension

### ISSUE THREAD

**Issue by GregDomjan** [MicrosoftDocs/edge-developer#222]
Could you expand the documentation to include some information about the issue further described in this link
https://stackoverflow.com/questions/47575689/edge-extension-native-messaging-uwp-app-is-closed-if-no-response-sent-back-to-e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4ed831-411d-6a45-8d8f-41cd527248fd
* Version Independent ID: 53f89058-afa1-f06a-8ea2-e836d82abde5
* Content: [Extensions - Native messaging - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/native-messaging)
* Content Source: [microsoft-edge/extensions/guides/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/native-messaging.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by gebansal** [comment]
Considering its an old thread and we have rolled out a new Chromium-based Edge browser, I'll go ahead and close it. If you still are facing any issues, please feel free to reopen this issue or file a new one.
