### ISSUE TITLE
Implement Google's updated Manifest v3 rollout

### ISSUE THREAD

**Issue by dxgldotorg** [MicrosoftDocs/edge-developer#2222]
Since Google has delated the deprecation of Manifest v3 to June 2023 and complete removal to January 2024, consider doing the same with Edge and its extension store.

Info at https://developer.chrome.com/blog/more-mv2-transition/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 815c941b-4a07-481a-9bb5-f8ef3d6b1118
* Version Independent ID: 815c941b-4a07-481a-9bb5-f8ef3d6b1118
* Content: [Overview and timelines for migrating to Manifest V3 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/manifest-v3)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for the feedback. This GitHub repository is about tracking the documentation of extensions only, not their implementation or manifest version support. So, I'll close this issue for now.
The v2->v3 migration is something the team has in mind and I'm we'll communicate about it in due course.

**Comment by dxgldotorg** [comment]
Where would I give feedback on Microsoft Edge development?

**Comment by captainbrosset** [comment]
I can suggest two ways to do this, depending on what you're looking for:

1. Using the feedback dialog directly in Edge itself. This is useful when you want to share something with the dev team, like a feature request or a bug report. Go to **Settings and more** (`...`) > **Help and feedback** > **Send feedback**.
2. Engaging in a conversation on the Microsoft Edge Insiders forum. This is useful when you want to start a conversation with the rest of the community. Go to: https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider
