### ISSUE TITLE
Please do no embrace Manifest V3 in Edge Browser

### ISSUE THREAD

**Issue by Nehaxak** [MicrosoftDocs/edge-developer#2223]
Any chance that this decision to use Manifest V3 from google can be deferred or even rejected for use with Edge browser?

Google's real intent of stopping the use of ad blockers should not be embraced by the wider Chromium based browsers, including Edge browser from Microsoft.

Or, as you will, fully embrace it publicly so users can outright then reject using Edge and all other Chromium based browsers.

It's shameful really on Microsoft's part that you would openly and eagerly accept such a change pushed and demanded by Google with their hidden intent of forcing adverts and trackers and so on without a users ability to block same, shameful.

Please reconsider following Googles obvious intent to block ad blockers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 815c941b-4a07-481a-9bb5-f8ef3d6b1118
* Version Independent ID: 815c941b-4a07-481a-9bb5-f8ef3d6b1118
* Content: [Overview and timelines for migrating to Manifest V3 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/manifest-v3)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for your feedback, unfortunately this isn't the right repository for it. 
Here, we only deal with issues and features about the documentation of Microsoft Edge's developer technologies. This isn't a place to discuss the strategic decisions of the product.

I would advise sending your feedback on the Edge tech community forum instead: https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider

Thanks for your understanding.
