### ISSUE TITLE
Is it correct that 32 bit WebView2 is not supported for UWP?

### ISSUE THREAD

**Issue by aquinn39** [MicrosoftDocs/edge-developer#2224]
According to the article, WebView2 is not supported in 32 but UWP apps, only 64 bit.

However, when testing, WebView2 seems to work fine in 32 bit UWP apps (tested on a 32 bit version of Windows and a 64 bit version). An example of this is the WinUI 2 Gallery - the WebView2 control there works fine on 32 bit Windows. So my question is, why does the article say WebView2 only works with 64 bit UWP apps when it clearly works with 32 as well? Are there specific issues with the 32 bit version or something like that it or is it an error in the article? Also, I can’t find any other information about this - this seems to be the only article that mentions 32 bit UWP apps not supporting WebView2.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a41e6607-2207-13a3-e637-464e3504e0d4
* Version Independent ID: a41e6607-2207-13a3-e637-464e3504e0d4
* Content: [Publish a UWP WebView2 app to the Microsoft Store - Microsoft Edge Development](https://learn.microsoft.com/en-au/microsoft-edge/webview2/how-to/publish-uwp-app-store)
* Content Source: [microsoft-edge/webview2/how-to/publish-uwp-app-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/publish-uwp-app-store.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for your question, let me ping @champnic here who would be a better person to answer it or would know someone who can.

**Comment by DavidShoe** [comment]
This is a documentation mistake, this should say that 32bit ARM is not supported.  Edge does not support 32bit arm at all so WebView2 can't.  x86 and x64 are both supported.  I will get the docs updated.
