### ISSUE TITLE
huel ipkme

### ISSUE THREAD

**Issue by elvismunyikiiru** [MicrosoftDocs/edge-developer#2226]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c6cd94a-404d-5ce5-91da-575d7af01b8c
* Version Independent ID: 1fc9a95f-6db4-77bf-048f-52903f62cc4f
* Content: [Keyboard shortcuts - Microsoft Edge Development](https://learn.microsoft.com/en-gb/microsoft-edge/devtools-guide-chromium/shortcuts/)
* Content Source: [microsoft-edge/devtools-guide-chromium/shortcuts/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/shortcuts/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
