### ISSUE TITLE
Offline mode stopped working after "Add push notifications"

### ISSUE THREAD

**Issue by TThorsager** [MicrosoftDocs/edge-developer#223]
After I had followed the chapter "Add push notifications" my application stopped working in offline mode. I can't seem to find the mistake, despite having retried from the beginning two times.

It does registre the service worker and it worked offline before this chapter.

The Google Chrome browser seems to be pointing at a mistake on line 5 in pwabuilder-sw.js :

Promise.then (async)
(anonymous) @ pwabuilder-sw.js:5

But I have not change anything in the top of that file.

Hope it makes sense
- Thanks

**Comment by Reezaali** [comment]
Hi @TThorsager, I'm sorry it's taken so long for someone to get back to you on this issue. We've updated our getting started content [here](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/get-started) which may solve your issue. We've also published an offline topic [here](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/offline) which may be interesting to look at. I'll go ahead and close this issue now. Thanks.
