### ISSUE TITLE
Limit to use "Publish Status" API ? 

### ISSUE THREAD

**Issue by 11Ashish11** [MicrosoftDocs/edge-developer#2231]
**Link to the documentation page**: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#check-the-publishing-status

**Description of the issue**:  I have a requirement, where I want to check if the Extension which is in review has been accepted or not. We want to run a cron job for it every 30 mins. So we will use the "Publish Status" API to check the status of the extension every 30 mins. So wanted to know if there is any daily limit which is set for this "Publish Status" API.  

**Screenshots**: -

**Microsoft Edge version**: -

**Comment by captainbrosset** [comment]
Thanks for reaching out with this question. I will try to find out, since I don't know myself, and report back.
Let me also ping @ashishnirvana1 who might be able to help.

**Comment by yvsubhash** [comment]
Hi @captainbrosset  Once every 30 minutes is acceptable under our throttling limit.  You may proceed with your cron job
