### ISSUE TITLE
summits 

### ISSUE THREAD

**Issue by kingofDaniel** [MicrosoftDocs/edge-developer#2239]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9a52771-a3f6-df50-ebf0-c9a399658bd6
* Version Independent ID: 8131dcac-31d4-76ec-40a6-f74d4a3a351d
* Content: [View Web SQL data - Microsoft Edge Development](https://learn.microsoft.com/en-gb/microsoft-edge/devtools-guide-chromium/storage/websql?source=docs)
* Content Source: [microsoft-edge/devtools-guide-chromium/storage/websql.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/storage/websql.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
