### ISSUE TITLE
Merci 

### ISSUE THREAD

**Issue by hamidmoutaouakil5** [MicrosoftDocs/edge-developer#224]
Bonjour 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1037a28d-7cd5-66dc-9826-1e626fa6e74b
* Version Independent ID: f90b56a3-db51-eeea-707c-0c30e81b4749
* Content: [Extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions)
* Content Source: [microsoft-edge/extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by plokmijnuhby** [comment]
Tais-toi.
