### ISSUE TITLE
Missing docs for logpoint?

### ISSUE THREAD

**Issue by pankajparashar** [MicrosoftDocs/edge-developer#2247]
Searching on "logpoint" yields two results, both of which talks about using new icons to represent lines with logpoints enabled. But none of them actually describes how to use the feature itself.

Chrome has a small section [here](https://developer.chrome.com/blog/new-in-devtools-73/#logpoints) describing the logpoint feature. Should this be ported to Edge Docs or is this a good opportunity to write new section in the docs for this feature?

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/38640616/195236140-884091f3-47e8-4328-9361-88c01ec3550d.png">

**Comment by captainbrosset** [comment]
Looks like you're right. I couldn't find any mentions of logpoints myself.
We should definitely add a new section on, at least, this page: https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/breakpoints
I'll add this to our backlog for prioritization.

Thanks for filing this.

**Comment by captainbrosset** [comment]
PR #2308 just got merged, and the new docs should be live any minute now. Closing this issue.
