### ISSUE TITLE
False statement in Manifest V2/3 extensions documentation

### ISSUE THREAD

**Issue by clandestine8** [MicrosoftDocs/edge-developer#2248]
> Manifest V3 is an initiative of the [Chromium project](https://www.chromium.org/Home/). Manifest V2 support ends in June of 2023 for all Chromium-based browsers.

This statement is blatantly false. The Chromium community is not dropping support for V2, only Chrome and Edge are. 
Source: https://twitter.com/brave/status/1574822799700541446?s=20&t=hoTATt8N1A3fOJXdyroSGg
Source: https://vivaldi.com/blog/manifest-v3-webrequest-and-ad-blockers/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 815c941b-4a07-481a-9bb5-f8ef3d6b1118
* Version Independent ID: 815c941b-4a07-481a-9bb5-f8ef3d6b1118
* Content: [Overview and timelines for migrating to Manifest V3 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/manifest-v3)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for your input on this.

**Comment by Reezaali** [comment]
Docs have been updated. Thanks.
