### ISSUE TITLE
Requesting SEC7134 documentation

### ISSUE THREAD

**Issue by unnisankarankutty** [MicrosoftDocs/edge-developer#225]
Hello,
This document has really helped me multiple times. I now currently am debugging an issue, which says 
SEC7134 Resource "https://..../" not allowed to load.
This happens on a window.open() call, but the URL otherwise opens when pasted directly on the address bar of Edge browser. 
Please guide me to the correct documentation for the issue.
Thanks and Regards,
Unni Sankarankutty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e413c6-445b-30c6-b2f8-7959c9c4a759
* Version Independent ID: 57c3967d-f4b1-7ede-11fc-56772cf616ae
* Content: [DevTools - Console error and status codes - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console/error-and-status-codes#security-codes)
* Content Source: [microsoft-edge/devtools-guide/console/error-and-status-codes.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/console/error-and-status-codes.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by tronza** [comment]
I also encountered this `SEC7134` error message and it prevented `window.location.href = url` operation. This does not happen if we remove the Content-Security-Policy -header from the document headers.

**Comment by okko** [comment]
SEC7134: Edge blocked the document from setting window.location.href due to the page's `Content-Security-Policy` having `sandbox` directive without `allow-top-documentation` in the value. This CSP violation is not reported to CSP's report-uri like other violations.

The behavior appears to have changed on 2019-09-25 with Microsoft's security updates.

**Comment by zoherghadyali** [comment]
Hi @unnisankarankutty, @tronza, and @okko! Thank you for using Microsoft Edge and for sending us your feedback. As we announced [our shift in the underlying web platform of Microsoft Edge to Chromium](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/), the legacy Microsoft Edge, built on the EdgeHTML platform, is no longer receiving updates. We strongly recommend [installing the new Microsoft Edge](microsoft.com/edge) which is now available on Windows 10, 8.1, 8, 7, and macOS! 

You can use the new Security tool in the new Chromium-based DevTools to further diagnose security issues. Definitely send us feedback using the feedback icon in the new Microsoft Edge DevTools:
![image](https://user-images.githubusercontent.com/34316555/83209741-de090000-a10d-11ea-82e9-e418698a2bb8.png)

Please include your email address and someone from the DevTools team will get back to you!
