### ISSUE TITLE
ht4569#

### ISSUE THREAD

**Issue by Masonta1976** [MicrosoftDocs/edge-developer#2253]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c1ef1bb-91a3-db70-2e06-b38c1a494bed
* Version Independent ID: 1b4e4189-04a9-f818-32ca-b3056e5fae3f
* Content: [Microsoft Edge DevTools extension for Visual Studio Code - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension#automated-quick-fixes-and-issue-filtering)
* Content Source: [microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
