### ISSUE TITLE
TakeAll

### ISSUE THREAD

**Issue by E3llE3** [MicrosoftDocs/edge-developer#2255]
[Enter feedback here]someone is giving me stuff

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42ed05ac-9e2a-0809-47fb-75919b50d4ba
* Version Independent ID: 00e0f6cf-74f8-29fa-3ac0-78291fd5f428
* Content: [Network features reference - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/reference)
* Content Source: [microsoft-edge/devtools-guide-chromium/network/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/network/reference.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
