### ISSUE TITLE
ma78945

### ISSUE THREAD

**Issue by Masonta1976** [MicrosoftDocs/edge-developer#2256]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93e96a57-d317-52f8-eec6-1f6d4648c0bb
* Version Independent ID: 93e96a57-d317-52f8-eec6-1f6d4648c0bb
* Content: [About the list of tools - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/about-tools#overview-of-all-tools)
* Content Source: [microsoft-edge/devtools-guide-chromium/about-tools.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/about-tools.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
