### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by G-u-c82** [MicrosoftDocs/edge-developer#2257]
[Enter feedback here]
is loqi

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a275bee-cee3-f0f4-407f-f4d5971f4a73
* Version Independent ID: 918a9e07-6982-630c-2d27-c5d5561f2157
* Content: [Override webpage resources with local copies (Overrides tab) - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/overrides)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript/overrides.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/javascript/overrides.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
