### ISSUE TITLE
DOM load time not displayed

### ISSUE THREAD

**Issue by Smaths** [MicrosoftDocs/edge-developer#226]
**Topic** Network 
**Sub Topic** Summary Bar
**Webpage** https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/network#summary-bar

**Edge Version**
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

The documentation linked above indicates that the summary bar at the bottom fo the network panel. The screenshot and summary bar description indicate that there are three (3) times recorded and displayed in this bar: 

1. Elapsed time
2. DOM load time
3. Page load time

I am only seeing Elapsed time, the other two options are not visible. (See attached screenshot)

![edgenetworkissuescreenshot](https://user-images.githubusercontent.com/13316137/52871489-29b1b900-3118-11e9-9631-a32dda33aebd.png)

**Comment by chelsey29** [comment]
Did you solve this issue? having same problem here.

**Comment by ststimac** [comment]
This may be a bug with DevTools. Tagging @zoherghadyali on our DevTools team.

**Comment by Reezaali** [comment]
I'll go ahead and close this issue for now. If the above solution does not solve the issue, I can reopen it. Thank you.
