### ISSUE TITLE
Linux edge driver link not on main page.

### ISSUE THREAD

**Issue by Leesaaaa** [MicrosoftDocs/edge-developer#2261]
**Link to the documentation page**: [The URL to the page](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#installation)  https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#installation.

**Description of the issue**: A link to the Linux driver is not included on the main page.  To find the Linux download you have to navigate to "Not finding what you need? Navigate to the full directory to down load it.  Then when you are in the msedgewebdriverstorage page, if you don't know have a list of stable versions to refer to, you end up having to look through each lin you think may be stable.  This happened the other day when the main page did not show the Stable Channel.  The point is, why not have a link to the Linux driver on the main page.  See screenshots for clear illustration of the issue.

**Screenshots**: 
![image](https://user-images.githubusercontent.com/89655531/196775558-109910fc-c602-4d15-97f5-ecbb5bfd2f86.png)

![image](https://user-images.githubusercontent.com/89655531/196775622-12a2f970-ded9-4494-b29e-d717861c74e7.png)

**Microsoft Edge version**: If the issue occurs with a specific version of Microsoft Edge.

**Comment by captainbrosset** [comment]
Thanks a lot for reaching out and filing this. I'll make sure this shows up on our team's backlog for prioritization.

**Comment by bwalderman** [comment]
This is already tracked by https://github.com/MicrosoftEdge/EdgeWebDriver/issues/52
