### ISSUE TITLE
Example code manifest version is incorrect.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [MicrosoftDocs/edge-developer#2264]
"The source code has been updated from Manifest V2 to Manifest V3"

No it hasn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec889040-6707-74fd-9086-d838c15a9172
* Version Independent ID: 73d6355a-b256-c8ab-9889-c51603d3052b
* Content: [Create an extension tutorial, part 2 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts?tabs=v3)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. However, I need a bit more information from you, if you can provide it, to investigate this issue.

I've got two questions in particular:

1. Which code snippet(s) do you think hasn't(haven't) been migrated?
2. Did you notice that code snippets have a v2 / v3 tab at the top, to allow you to switch between the 2 versions.

**Comment by Neutrino-Sunset** [comment]
It's not the snippets, it's the code in the Github repo that the comment about being updated to version 3 refers to, and that hasn't been updated.

**Comment by captainbrosset** [comment]
Oh ok, thanks for replying. In this case, I'll move this issue to that GitHub repo instead, and close this one.
Thanks again!
