### ISSUE TITLE
SCRIPT7002 executing POST request

### ISSUE THREAD

**Issue by capecape** [MicrosoftDocs/edge-developer#227]
Hello.What about this error executing a whilst jquery post : 
SCRIPT7002: XMLHttpRequest: Network Error 0x2eff, Could not complete the operation due to error 00002eff.
Why is it happening? Only windows 10 users within the company are facing this issue. Thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e413c6-445b-30c6-b2f8-7959c9c4a759
* Version Independent ID: 57c3967d-f4b1-7ede-11fc-56772cf616ae
* Content: [DevTools - Console error and status codes - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/devtools-guide/console/error-and-status-codes#javascript-run-time-errors)
* Content Source: [microsoft-edge/devtools-guide/console/error-and-status-codes.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/console/error-and-status-codes.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by nthouston** [comment]
Was there any resolution found for this issue?

**Comment by erdraud** [comment]
Hello @capecape! Have you updated the latest version of Edge (https://www.microsoft.com/en-us/edge?form=MY01BL&OCID=MY01BL)? If that doesn't help, let me know.

**Comment by Reezaali** [comment]
I'll go ahead and close this issue for now. If the above solution does not solve the issue, I can reopen it. Thank you.

**Comment by Emiya0306** [comment]
@erdraud @Reezaali Is any workaround to resolve this error? Our customer are using old version IE 11 just only.
Is there any information about this `0x2eff` error. Thanks!
