### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by Dmack23** [MicrosoftDocs/edge-developer#2274]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1311289-0892-7fa5-3540-96fc823fc8cd
* Version Independent ID: 1c69b077-dbd1-7105-9cc8-d11c99d1495d
* Content: [Microsoft Edge Privacy Whitepaper - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/)
* Content Source: [microsoft-edge/privacy-whitepaper/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/privacy-whitepaper/index.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
