### ISSUE TITLE
Edge browser is showing Profile Sync option

### ISSUE THREAD

**Issue by rlp6948** [MicrosoftDocs/edge-developer#2284]
Hi Team,

Recently I upgraded Selenium Server version from 3.141.59 ---> 4.5.3 and changed the scripts and added EdgeOptions .
Still I'm getting "Sync your Profile" Pop-Up during launching the Edge Browser with Latest version as per below info.

Microsoft Edge | 107.0.1418.26 (Official build) (64-bit)

Revision | 801aa30e905471d971868b02ed128260f15a3a04
Operating system | Windows 10 Version 21H2 (Build 19044.2130)
JavaScript | V8 10.7.10.4
Snippet:
EdgeOptions edgeOptions = new EdgeOptions();
HashMap<String, Object> prefs = new HashMap<String, Object>();
			prefs.put("credentials_enable_service", false);
			prefs.put("profile.password_manager_enabled", false);
                        edgeOptions.addArguments("--disable-notifications");
			edgeOptions.addArguments("--no-sandbox");
			edgeOptions.addArguments("--disable-dev-shm-usage");
			edgeOptions.addArguments("--disable-browser-side-navigation");
			edgeOptions.addArguments("--disable-gpu");
			edgeOptions.setExperimentalOption("excludeSwitches",Arrays.asList("disable-popup-blocking","enable-automation"));
			
			System.setProperty(EDGE_DRIVER, stCurrentPath+EDGE_DRIVER_PATH);
			prefs.put("profile.default_content_settings.popups", 0);
			prefs.put("profile.default_content_setting_values.notifications", 2);	
			prefs.put("plugins.always_open_pdf_externally", true);
driver = new EdgeDriver(edgeOptions);
			driver.manage().window().maximize();
			driver.get(URL);

![MSEdge_Browser_Issue_with_Selenium_4 5 3_version](https://user-images.githubusercontent.com/68288044/199750261-a2ddc42f-3446-414a-aec5-269458554cae.JPG)

Kindly look into the issue if possible provide the needful resolution for the same.
Thanks,
Lakshmi

**Comment by captainbrosset** [comment]
Thanks for reaching out. I think you should actually post this issue to the EdgeWebDriver feedback repository instead though. This repository is only for documentation changes.
Can you post it there instead: https://github.com/MicrosoftEdge/EdgeWebDriver ?

Thanks for your understanding.
