### ISSUE TITLE
Microsoft Edge Does Not Obey FIDO2/WebAuthn Attestation Conveyance of Relying Party

### ISSUE THREAD

**Issue by Kevin-Andrew** [MicrosoftDocs/edge-developer#229]
When performing the [Registration Ceremony](https://www.w3.org/TR/webauthn/#registration) of an authenticator, the Relying Party application creates a JSON object representing the [Options for Credential Creation](https://www.w3.org/TR/webauthn/#dictdef-publickeycredentialcreationoptions), of which contains a property for [Attestation Conveyance](https://www.w3.org/TR/webauthn/#enumdef-attestationconveyancepreference).  An example of this JSON object may look like the following:

![image](https://user-images.githubusercontent.com/22459191/54177162-891c9380-444e-11e9-9593-cba1f6f13570.png)

In that example, I have the `attestation` property set to **[none](https://www.w3.org/TR/webauthn/#dom-attestationconveyancepreference-none)**.  That entire object, `publicKey`, is then passed to the `navigator.credentials.create()` method, after which the Relying Party application has no control over the output.

The Microsoft Edge web browser with the following version information is not obeying the [Attestation Conveyance](https://www.w3.org/TR/webauthn/#enumdef-attestationconveyancepreference) property.
![image](https://user-images.githubusercontent.com/22459191/54177290-ee708480-444e-11e9-9e58-5afe235689a0.png)

Instead, it is causing the authenticator to send back whatever attestation format that the authenticator supports, for example **[packed](https://www.w3.org/TR/webauthn/#packed-attestation)** or **[fido-u2f](https://www.w3.org/TR/webauthn/#fido-u2f-attestation)**.

To me, the Microsoft Edge web browser is not following the specification.  If the Relying Party asks for **[none](https://www.w3.org/TR/webauthn/#none-attestation)**, then that is what should be returned.  In addition, the specification also states that **[none](https://www.w3.org/TR/webauthn/#dom-attestationconveyancepreference-none)** is the default.  So I also tried omitting the `attestation` property of the JSON object, but it did not change the result.  Finally, note that the same code, on the same computer, with the same authenticator produces the correct result when using the Chrome web browser instead.

**Comment by captainbrosset** [comment]
Microsoft Edge is now based on the Chromium project. I don't know much about webAuthn, but I'm guessing that the above scenario should now work.
Closing this issue based on this. Feel free to comment if the problem persists.
