### ISSUE TITLE
Automated testing for pure js extensions only

### ISSUE THREAD

**Issue by miksch123** [MicrosoftDocs/edge-developer#230]
In your documentation you were referring to be able to test edge extensions, though this only applies for pure JS extensions and not for extensions which use native messaging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d5f8503-00e3-1b62-0912-0789ae732d38
* Version Independent ID: 8e273172-c25a-0fdf-0d10-3cd9aa3f542c
* Content: [Creating and testing extension packages - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages#feedback)
* Content Source: [microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
Considering its an old thread and we have rolled out a new Chromium-based Edge browser, I'll go ahead and close it. If you still are facing any issues, please feel free to reopen this issue or file a new one.

**Comment by miksch123** [comment]
That is good with me.
