### ISSUE TITLE
How can we extend Mv2 support for 6 more months after jan 2023 for edge?

### ISSUE THREAD

**Issue by vinodbommi** [MicrosoftDocs/edge-developer#2300]
Hi,

Can some one please share the detailed steps to extend the support for 6 more months. As per the forums, I understand that we need to update group policy in enterprise level in-order to get additional support, but not sure on what exactly needs to be done within group policy. 

Thanks and Regards,
Vinod

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ef35cb8-c4f6-0f63-4b42-776655e82152
* Version Independent ID: bff44510-e5b6-e2ed-2d77-d8bb7e87c4a9
* Content: [Migrate an extension from Manifest V2 to V3 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/migrate-your-extension-from-manifest-v2-to-v3)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/migrate-your-extension-from-manifest-v2-to-v3.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/migrate-your-extension-from-manifest-v2-to-v3.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. I think this would be a better question to ask on the extensions feedback repository here: https://github.com/microsoft/MicrosoftEdge-Extensions/
Could you please ask your question there? Thanks a lot for your understanding!
