### ISSUE TITLE
Lack of example

### ISSUE THREAD

**Issue by naristov** [MicrosoftDocs/edge-developer#231]
Please add an example for this Api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d67b3640-16fe-57fc-4120-11506adcc6d4
* Version Independent ID: b38c2e51-5aca-46fa-0769-f8fd14bf3280
* Content: [JsCallFunction Function - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/hosting/chakra-hosting/jscallfunction-function)
* Content Source: [microsoft-edge/hosting/chakra-hosting/jscallfunction-function.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/hosting/chakra-hosting/jscallfunction-function.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by Reezaali** [comment]
Have you looked into the new WebView2 control? I'll go ahead and close this out. Feel free to reopen a new issue if this is still an issue for you. Thanks.
