### ISSUE TITLE
What "more actions" toolbar?

### ISSUE THREAD

**Issue by nbros** [MicrosoftDocs/edge-developer#2312]
The documentation mentions a "more actions" toolbar in:
https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/css/reference#reveal-the-more-actions-toolbar

But I don't see it in DevTools!

What I'm supposed to see according to the documentation:

![image](https://user-images.githubusercontent.com/141089/201513208-9aebdda5-738f-4407-ab92-fe340510e40b.png)

What I see instead when I hover:

![image](https://user-images.githubusercontent.com/141089/201513325-a5416a52-2e62-462c-b802-28bf3f485fde.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f4e719c-edd9-95fc-6b62-66f1a172f21d
* Version Independent ID: 0b55c280-1b8b-a84a-49a1-9f86c4aa85ed
* Content: [CSS features reference - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/css/reference#view-used-and-unused-css-with-the-coverage-tool)
* Content Source: [microsoft-edge/devtools-guide-chromium/css/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/css/reference.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for finding this problem and filing an issue about it. The "more actions" button is no longer available in DevTools it seems. We need to change the documentation accordingly.
I'll make sure this issue is tracked by our team and we'll get to this as soon as we can.

**Comment by captainbrosset** [comment]
Being fixed in #2314.

**Comment by captainbrosset** [comment]
Now fixed. The documentation should be up to date in a few minutes.
