### ISSUE TITLE
Nothing About Application Lifecycle management for Add-Ons

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/edge-developer#2318]
There should be a statement on the Application Lifecycle Management for each Add-On and a commitment to regularly address security vulnerabilities has not been stated and no end of support date is provided.

This means that Add-Ons will not be available on secure Tenancies without this information.

Regards

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 303075ec-ed9b-7ba4-15c5-242f93d53eb2
* Version Independent ID: 15d3653d-af25-8ee7-2e94-01057a734de4
* Content: [Publish a Microsoft Edge extension - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension?source=recommendations)
* Content Source: [microsoft-edge/extensions-chromium/publish/publish-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/publish/publish-extension.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you @NPrice99 for reaching out. Let me make sure the right team sees this.

**Comment by NPrice99** [comment]
Bump - any news on this one yet ?

**Comment by Thanvi-Rabia** [comment]
Hello @NPrice99 
Please find the documentation on Edge Lifecycle Policy here: [Microsoft Edge Lifecycle Policy](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-support-lifecycle)

Are you looking for Lifecycle management documentation for specific Add Ons? Could you please provide more details on the issue that you're facing ?

**Comment by NPrice99** [comment]
Hi

This was the addon I was trying to find the Lifecycle management documentation for :-
Responsive Web Design Tester - Microsoft Edge Addons<https://microsoftedge.microsoft.com/addons/detail/responsive-web-design-tes/nkhdggbojdjobojfjfhdfbfcpfecbfop>

My company has introduced a new policy on any installed software :-

Microsoft Edge Add on Responsive Web Design Tester
A commitment to regularly address security vulnerabilities has not been identified and no end of support date is provided.

This is not in compliance with our requirements for XXXXXX certification and is therefore currently rejected by the Software Request Assessors.



I hope this helps

Nigel

**Comment by Thanvi-Rabia** [comment]
Hello @NPrice99 
Since this is an extension specific ask, you will have to reach out to the extension developers to help with your ask.
The website [https://www.esolutions.se/](https://www.esolutions.se/) is given on the extension home page. You could try to reach out to them through the 'Contact Us' functionality on the website.

Hope this helps.

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. 
If you still need assistance, please feel free to reopen this issue, or open a new one. 
Thank you.
