### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by naristov** [MicrosoftDocs/edge-developer#232]
Please add quick example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee5af18-067c-b47c-9772-ceff0cc49a4f
* Version Independent ID: 4818c4b0-96f5-e19c-a0d4-26a814cea6a2
* Content: [JsGetProperty Function - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/hosting/chakra-hosting/jsgetproperty-function)
* Content Source: [microsoft-edge/hosting/chakra-hosting/jsgetproperty-function.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/hosting/chakra-hosting/jsgetproperty-function.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by Reezaali** [comment]
Have you looked into the new WebView2 control? I'll go ahead and close this out. Feel free to reopen a new issue if this is still an issue for you. Thanks.
