### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftDocs/edge-developer#2320]
1 2 3

**Link to the documentation page**: The URL to the page.

**Description of the issue**: A clear and concise description of what the issue is.

**Screenshots**: If applicable, add screenshots to help explain the issue.

**Microsoft Edge version**: If the issue occurs with a specific version of Microsoft Edge.

**Comment by Reezaali** [comment]
4 5 6

**Comment by captainbrosset** [comment]
I think it's safe to close this test issue now :)
