### ISSUE TITLE
Any known software/project using "The Fixed Version runtime distribution mode"

### ISSUE THREAD

**Issue by johnnylq** [MicrosoftDocs/edge-developer#2330]
We are working on a project based on Webview2 control. Our project need to support Win10 users.  Does that mean we can only use the Fixed version runtime distribution mode since we can't guarantee all Win10 users will have the runtime by default? 
  
Is there any known project or software using the "The Fixed Version runtime distribution mode"?

**Comment by captainbrosset** [comment]
Thanks for reaching out. Could you please file your issue again on the specific WebView2 feedback repository here: https://github.com/MicrosoftEdge/WebView2Feedback/issues
This will get you much more chances of getting answers to your question.

Thanks a lot for your understanding.
