### ISSUE TITLE
hyperlinks are not working

### ISSUE THREAD

**Issue by sedaradoykova** [MicrosoftDocs/edge-developer#2335]
Hyperlinks take me to the same page over and over. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver to automate Microsoft Edge - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Hello @sedaradoykova. Could you please explain which hyperlinks you are talking about here exactly? Are you saying that there's a link on the "Use WebDriver to automate Microsoft Edge" page that just goes back to that same page?

**Comment by captainbrosset** [comment]
No responses received. Let me close this issue for now. We can always re-open it later if needed.
