### ISSUE TITLE
Can't run Selenium side runner for Edge with a current profile

### ISSUE THREAD

**Issue by rdomingo11** [MicrosoftDocs/edge-developer#2341]
Even though the edge can be spawned, it couldn't inherit the current profile. In fact, the browser doesn't use the logged in profile.

Btw, this is the command that I've been running.
 selenium-side-runner -c "user-data-dir='C:\\Users\\<user>\\AppData\\Local\\Microsoft\\Edge\\User Data\\' profile-directory=Default browserName=MicrosoftEdge" -s "http:\\127.0.0.1:9515" -d *.side

**Comment by spdfrce** [comment]
X   z",", cx z ,

**Comment by captainbrosset** [comment]
Thanks for reaching out. Could you please re-open your issue on this feedback/support repository instead: https://github.com/MicrosoftEdge/EdgeWebDriver ?
That'd be great, thanks for your understanding!
