### ISSUE TITLE
Acer

### ISSUE THREAD

**Issue by tobiasheilmannn** [MicrosoftDocs/edge-developer#2346]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6314cab8-5f54-827b-d906-46f67dd0d0cf
[Document Details.txt](https://github.com/MicrosoftDocs/edge-developer/files/10147799/Document.Details.txt)

* Version Independent ID: fe69a922-b5b5-001b-5ef9-c0f44a693beb
* Content: [Sources tool overview - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/)
* Content Source: [microsoft-edge/devtools-guide-chromium/sources/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/sources/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
