### ISSUE TITLE
Still can't find the debugger, can't find my code, none of this matches anything

### ISSUE THREAD

**Issue by peteravila** [MicrosoftDocs/edge-developer#2350]
Why can't i find my js code where you say it is in the page tab??

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f215748-1d1e-6083-315b-0bf9b7c8f765
* Version Independent ID: 1e372759-3041-11cb-cb6c-5b6f427e9a74
* Content: [Get started debugging JavaScript - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/javascript/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. Could you please be a little bit more specific to help us understand the issue?
Do you have the URL to a website you can share so we can try on our end? What are you trying to do exactly? Are you looking for a specific file that you're not finding?

**Comment by peteravila** [comment]
Thank you for finally taking an interest. This msg sure is better than your msg 2 msgs ago:

"Hey, can you tell me where in this box I can find this thing I'm looking for?"
"Yeah, it's in the box-CASE CLOSED!"

Uninterested and dismissive, but not helpful

https://www.google.com/search?q=star+trek+four+alameda+scene&oq=star+trek+four+alameda+scene&aqs=edge..69i57j0i546l2.8278j0j4&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:47baed72,vid:MdSJFrhb-HM

I see this all the time in Microsoft documentation:

"HOW TO USE THE DEBUGGER: You can use the debugger to do this that and the other... if you can find it, that is! Good luck! CASE CLOSED! Let us know how we're doing!"

WHAT is not the same as HOW. Telling me what it does says nothing about how to use it to do what it does. The document does not fulfil the promise in the title.

And as for my question, by now it's a moot point. I found what I was looking for, though not from any help from your document, which gives me no pleasure to point out, btw.

I hope this helps. Best of luck.

**Comment by captainbrosset** [comment]
We have a "get started" article for the debugger here: https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/

I feel like it does a fairly good job at explaining how to use the debugger (how to open devtools, where to find the debugger, how to pause the code, etc.).
You are right that the "Sources tool overview" article is more of a WHAT than a HOW though: https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/

Does the first article I linked to help?

**Comment by captainbrosset** [comment]
Closing as this has become inactive. Let me know if you still have an issue here, and I can re-open this.
