### ISSUE TITLE
Use Anchor, don't resize manually

### ISSUE THREAD

**Issue by dhilgarth** [MicrosoftDocs/edge-developer#2357]
In Step 6, sub-point 6 it manually resizes and moves the controls. That's not clean.
The Anchor property of the controls should be used here instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48ba6a76-eb0b-e8f2-dfc9-d2c0df6261a4
* Version Independent ID: 8d62fdee-f44a-3d40-6800-04d7bd6193f8
* Content: [Get started with WebView2 in WinForms apps - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms)
* Content Source: [microsoft-edge/webview2/get-started/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#42583513

**Comment by captainbrosset** [comment]
Thank you, again, for the suggestion, however the webvewi2 team has not prioritized this documentation change, so I'll close this issue.
