### ISSUE TITLE
[DevTools Docs Feedback] Japanese translation of "Fixed Version Runtime".

### ISSUE THREAD

**Issue by fliedonion** [MicrosoftDocs/edge-developer#2366]
https://learn.microsoft.com/ja-jp/microsoft-edge/webview2/concepts/distribution
上記URLの日本語ページや、WebView2ランタイムダウンロードページの日本語ページで、"Fixed Version Runtime" の訳として「修正済みバージョンランタイム」という日本語が使われている。
WebView2 の "Fixed Version Runtime" の日本語訳として正しいのは「固定バージョンランタイム」ではないか。
"修正済み"という日本語は「問題を解消した」という意味であり、その点で未修正のバージョンというのもないと思うし不適切と思う。

---

https://learn.microsoft.com/ja-jp/microsoft-edge/webview2/concepts/distribution
In the Japanese page of the above URL and the Japanese page of the WebView2 Runtime Download Page, the Japanese term "修正済みバージョンランタイム" is used as a translation of "Fixed Version Runtime".
The correct Japanese translation of "Fixed Version Runtime" for WebView2 should be "固定バージョンランタイム".
The Japanese word "修正済み" means "the problem has been resolved," and in that respect, I don't think there is an unfixed version, and I think it is inappropriate.
(I used a translation software to translate the English text.)

note:
* The word "固定する" means something like "not to be changed" or "not to be moved. For example, a fixed fee is a "固定の料金”. not "修正済み料金".
* "修正" means "repair.

**Comment by captainbrosset** [comment]
Thank you very much for reporting this problem. I will forward it to our translation team and will update this page as soon as I know more.

<hr>

この問題を報告していただき、誠にありがとうございます。翻訳チームに転送し、詳細がわかり次第このページを更新します。

**Comment by captainbrosset** [comment]
I've been told this got fixed in the meantime, so closing this issue now.

**Comment by captainbrosset** [comment]
Thanks for your report. I'll pass this along to the right people.
