### ISSUE TITLE
3.

### ISSUE THREAD

**Issue by amusaber950** [MicrosoftDocs/edge-developer#2367]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 510619b0-1ad1-47e6-b199-0cb99025d54b
* Version Independent ID: 7d4432c8-45fa-7670-7b6b-1d9e289037b3
* Content: [The user experience of PWAs - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/ux)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/ux.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/ux.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
