### ISSUE TITLE
57878885yfghsh

### ISSUE THREAD

**Issue by tutururwtrwterye** [MicrosoftDocs/edge-developer#2379]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7819ec4-6bf9-b550-431b-07e5f7692150
* Version Independent ID: e3493b50-4f7a-b3a8-465a-6d494fecb3e0
* Content: [Microsoft Edge Add-ons store developer policies - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/store-policies/developer-policies?branch=user%2Fv-jomar7%2Fdocs%2Fextensions-chromium%2Fstore-policies%2F2019DEC09)
* Content Source: [microsoft-edge/extensions-chromium/store-policies/developer-policies.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/store-policies/developer-policies.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
