### ISSUE TITLE
hackers using cloud system for control of original user account 

### ISSUE THREAD

**Issue by CryproPolice** [MicrosoftDocs/edge-developer#2387]
https://vmuae.app.link/hs2D86D2lwb

someone is using console via GitHub to control my cloud state S a dev 
![Screenshot_2023-01-05-08-59-19-03](https://user-images.githubusercontent.com/118632709/210908078-873d3291-1cf1-47bc-a2c9-0bff62f04eee.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f04d8ef-d244-b231-dbe2-5e6e53a924c9
* Version Independent ID: 26afac6f-3aef-33d2-f492-6aa897e6a1c6
* Content: [Console overview - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/)
* Content Source: [microsoft-edge/devtools-guide-chromium/console/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/console/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
I'll close this now as this isn't a problem related to the Edge developer documentation. If you have a problem related to the browser itself, please go to **Settings and more** (`...`) > **Help and feedback** > **Send feedback** in Edge, directly.
