### ISSUE TITLE
Ok its nice

### ISSUE THREAD

**Issue by Harshk133** [MicrosoftDocs/edge-developer#2392]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e2efb18-3126-dc51-500f-c3e6b8b9d824
* Version Independent ID: 894a7544-0e73-3508-310c-bf9552bf864d
* Content: [Run JavaScript in the Console - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/console-javascript)
* Content Source: [microsoft-edge/devtools-guide-chromium/console/console-javascript.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/console/console-javascript.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
