### ISSUE TITLE
I have created Webview2 in MFC C++ in background and when i Open that tab in that Webview is not showing anything.

### ISSUE THREAD

**Issue by akhilpathania** [MicrosoftDocs/edge-developer#2401]
I have created Webview2 in MFC C++ in background and when i Open that tab in that Webview is not showing anything.

Looks like if we create Webview in background then we try to see it it does not show anything. But when i call` m_webView->OpenDevToolsWindow()`; it is properly showing the code and everything. Just page is not visible in view.

**Comment by captainbrosset** [comment]
Thanks for reporting this issue. Could you please report it on this specific WebView2 feedback repository instead though? https://github.com/MicrosoftEdge/WebView2Feedback
This will give you much higher chances of getting the right answer to your question. Thanks a lot for your understanding.
