### ISSUE TITLE
Opening source files in Visual Studio Code - Not work for less source file

### ISSUE THREAD

**Issue by wufeng87** [MicrosoftDocs/edge-developer#2407]
no link button shown:

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/1686808/212840374-83dd8e5f-8aaa-41cc-8b51-37279409e7f1.png">

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fda35f7f-7465-f440-5ae1-b119dc78e83e
* Version Independent ID: f9cf7424-9465-7b30-24db-5e02b6f2a8d5
* Content: [Opening source files in Visual Studio Code - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/opening-sources-in-vscode)
* Content Source: [microsoft-edge/devtools-guide-chromium/sources/opening-sources-in-vscode.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/sources/opening-sources-in-vscode.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for your feedback about this. Given that this is probably a problem with the tool itself, not the docs, could you please re-open your issue on the DevTools feedback repository instead: https://github.com/MicrosoftEdge/DevTools ?
Thank you for your understanding!
