### ISSUE TITLE
After "const copy = response.clone();" the variable copy is never used

### ISSUE THREAD

**Issue by WladimirWasilyev** [MicrosoftDocs/edge-developer#2408]
Looks like a bug: after "const copy = response.clone();" the variable copy is never used.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71d03146-4e21-71cc-6892-bb6d82c9ace3
* Version Independent ID: 6d9c64d5-6b34-71ef-9aaf-e038a7382b5b
* Content: [Offline and network connectivity support in Progressive Web Apps - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/offline)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/offline.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/offline.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks a lot for reporting this. You are right, this is a bug in this particular code snippet.
The issue will be fixed by #2334, which is being reviewed now and should be merged very very soon!
