### ISSUE TITLE
Navigating event

### ISSUE THREAD

**Issue by stephen56** [MicrosoftDocs/edge-developer#2415]
Hello, hope you can help. The old web browser had a "navigating" event which could intercept clicked links in a KML info window. Is it possible to get this event back? At the moment my kml info windows are not performing as designed. OR can you suggest a way to intercept these clicks, there is no recognition of navigation started, the links just open a new instance of edge which is not useful to me. I know kml is old but millions of people still use it. Cheers Steve

**Comment by captainbrosset** [comment]
Thanks for your message. Unfortunately I don't know what kml is. Could you help me by providing a bit more information about your use case? Is there any way to provide sample code as well, so I can try this locally too?

**Comment by stephen56** [comment]
HiThanks for quick reply.KML is Keyhole markup language, used to place points on maps along with information about the points. Was made by an independent company back in the day, but I think it is maintained by Google now, essentially for use with Google Maps and Google Earth. Most mapping apps na open a .kml or .kmz (the zipped version of kml).My app is for airstrips in outback australia.The image shows shows an example airstrip, Adeles Grove in Queensland.Under the old WebBrowser plug in, the blue underlined links could be captured by the "Navigating" event and then sent to a new webbrowser window (ie within the App) for specialist coding.In webview2 there is no Navigating event, only a "Navigation commenced" and a "Navigation completed". The clicks on the links in the KML information windows are not recognized by webview2, they just open a new instance of Edge.CheersStephen ***@***.***+61412 509172On 24 Jan 2023, at 01:33, Patrick Brosset ***@***.***> wrote:﻿
Thanks for your message. Unfortunately I don't know what kml is. Could you help me by providing a bit more information about your use case? Is there any way to provide sample code as well, so I can try this locally too?

**Comment by captainbrosset** [comment]
Thanks for your reply. I'll open a new issue for you on the WebView2Feedback repository instead then. I think that's the repo that will be best suited for this question.

Here it is: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3158

**Comment by RickStrahl** [comment]
Can't you use the `WebView.CoreWebView2.NavigationStarting` event? It has `e.Cancel` to abort requests at runtime.

**Comment by stephen56** [comment]
Hi Rick,Thanks for the info, I will give it a try.🤞CheersStephen ***@***.*** 509172On 28 Jan 2023, at 10:07, Rick Strahl ***@***.***> wrote:﻿
Can't you use the WebView.CoreWebView2.NavigationStarting event? It has e.Cancel to abort requests at runtime.
