### ISSUE TITLE
In edge 109.0.1518.61, ctrl + shift + f does not open source file search anymore.

### ISSUE THREAD

**Issue by tummalasujith** [MicrosoftDocs/edge-developer#2425]
After 109.0.1518.61 we are unable to open source file search using ctrl + shift +f. Multiple people in our team facing this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5074db57-7412-88c6-70a4-213f96ade8cb
* Version Independent ID: 5074db57-7412-88c6-70a4-213f96ade8cb
* Content: [Find source files for a page using the Search tool - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/search/search-tool)
* Content Source: [microsoft-edge/devtools-guide-chromium/search/search-tool.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/search/search-tool.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. Could you please post this issue on our DevTools feedback repository instead? Here: https://github.com/MicrosoftEdge/DevTools/issues

That would be super helpful, thank you!

**Comment by tummalasujith** [comment]
https://github.com/MicrosoftEdge/DevTools/issues/126
