### ISSUE TITLE
configuring javascript debugging in WebView2 / different panel on VS2022 Community?

### ISSUE THREAD

**Issue by diffent** [MicrosoftDocs/edge-developer#2428]
i managed to get past the install new components portion of these instructions,
but when it came to the part about 
"Enable script debugging for WebView2 apps"
my version of VS2022 community has a different menu; no option to set webview2 javascript debugging
as noted in this doc.

see attached.
do we need something beyond Community edition to use this feature?
or am i looking at the wrong panel?
or are the instructions different for Community?

i put a link to what i am seeing here:

https://www.dropbox.com/s/4424eiwc65mas8s/debugsettings.png?dl=0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5d323fb-5a95-107d-6f48-74071a581576
* Version Independent ID: c5d323fb-5a95-107d-6f48-74071a581576
* Content: [Debug WebView2 apps with Visual Studio - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug-visual-studio)
* Content Source: [microsoft-edge/webview2/how-to/debug-visual-studio.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/debug-visual-studio.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out with this question.
I don't have the answer, but let me ping @champnic who might be able to help you on this.

**Comment by champnic** [comment]
@diffent What options do you see if you expand the "Debugger Type > Application Process" dropdown?

This looks like the right panel, but the UI has been substantially changed between Visual Studio versions it seems.

**Comment by diffent** [comment]
hi, thanks for the response.  i found on another post somewhere that "ctrl shift i" opens the javascript dev tools for a running WebView2 app (running in debug / devel mode i presume) if anyone else finds this issue.  not sure if you have to be hovering your cursor over the WebView2 or not, but it got me what i needed!  you can close this.

**Comment by champnic** [comment]
Glad you got it working! You can also "Right click > Inspect" to open the devtools.
