### ISSUE TITLE
gaana

### ISSUE THREAD

**Issue by Ksheaflem** [MicrosoftDocs/edge-developer#2432]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7754210-02b0-6d3b-0405-e84b8b926c52
* Version Independent ID: 51551106-f219-09b0-5d6e-755115705f33
* Content: [Use DevTools in Internet Explorer mode (IE mode) - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/ie-mode/)
* Content Source: [microsoft-edge/devtools-guide-chromium/ie-mode/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/ie-mode/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
