### ISSUE TITLE
Interference of BlockExternalExtensions is unclear

### ISSUE THREAD

**Issue by joegoerlich** [MicrosoftDocs/edge-developer#2436]
It is not clear if BlockExternalExtensions has to be set to disabled or unconfigured as a prerequisite. Or if extensions and their origin configured in ExtensionInstallForcelist, ExtensionInstallSources, or ExtensionSettings take precedence over BlockExternalExtensions=Disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f290aba-5618-9b79-e3ac-243ec8cc4dd6
* Version Independent ID: 0cda1705-27db-4282-40e1-a2fbbd16ed2e
* Content: [Alternative ways to distribute extensions - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#43265320

**Comment by captainbrosset** [comment]
Thanks a lot for your question. I'm making sure this is tracked by the team so the docs can be made clearer.
In the meantime, you might be able to get a quick answer to your question by asking on this repository: https://github.com/microsoft/MicrosoftEdge-Extensions

**Comment by mikehoffms** [comment]
PR 2564 research so far:

Question:
It is not clear if `BlockExternalExtensions` has to be set to `disabled` or `unconfigured` as a prerequisite.  Or if extensions and their origin configured in `ExtensionInstallForcelist`, `ExtensionInstallSources`, or `ExtensionSettings` take precedence over `BlockExternalExtensions=Disabled`.

Answer: 
Setting the `BlockExternalExtensions` policy to `Not Configured` or `Disabled` won't have any effect.  If the `BlockExternalExtensions` policy is set to `enabled`, external extension installation (by third party software) won't be allowed. The policies for force install list, block list, and extension settings are used when enterprises want to install or block specific extensions on the client machines.

See [BlockExternalExtensions](http://learn.microsoft.com/deployedge/microsoft-edge-policies#blockexternalextensions) in _Microsoft Edge - Policies_.
