### ISSUE TITLE
Changes in manifest.json from V2 to V3 host permissions and permissions merged in to host_permissions?

### ISSUE THREAD

**Issue by yunshengyao** [MicrosoftDocs/edge-developer#2444]
It this right?
From the chrome side, it's the opposite
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fb3acda-9e0e-ced5-3f68-74f62fdb32d9
* Version Independent ID: c30c7d65-d50b-fd32-d65e-c8e27e9e39a3
* Content: [Manifest file format for extensions - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?tabs=v3)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/manifest-format.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#43357518

**Comment by captainbrosset** [comment]
Thanks for filing. I do not have the answer to this offhand, but I'll make sure this is added to our team's backlog so we can take a look and update the docs if they're incorrect.

**Comment by Reezaali** [comment]
Thanks for opening the issue. We updated the document. Much appreciated.
