### ISSUE TITLE
Device Emulation Missing in WebView2 Dev Tools

### ISSUE THREAD

**Issue by cartmouse** [MicrosoftDocs/edge-developer#2448]
When using the dev tools from a WebView2 window, the "device emulation" option is missing.

Is there any scope for adding this functionality or is this a hard limitation of using Edge as part of WebView2?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f45066d2-fb66-94fb-ff5e-138ee4e5b38a
* Version Independent ID: f45066d2-fb66-94fb-ff5e-138ee4e5b38a
* Content: [Debug WebView2 apps with Microsoft Edge DevTools - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug-devtools?tabs=dotnetcsharp)
* Content Source: [microsoft-edge/webview2/how-to/debug-devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/debug-devtools.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
I believe device emulation can only run in the context of the browser UI. A WebView2 control isn't a complete browser window. So I think there's a hard limitation here.

May I suggest the following next steps: please open a new issue on the [MicrosoftEdge/DevTools](https://github.com/MicrosoftEdge/DevTools/) repository and ask your question there again, but also please add information about why exactly do you need to use device emulation inside of a WebView2 control.

Thanks!
