### ISSUE TITLE
[DevTools Docs Feedback]

### ISSUE THREAD

**Issue by UL2MIT** [MicrosoftDocs/edge-developer#2453]
Someone has hacked my home security system and is editing my security video streams. The videos are being edited by creating a loop or repeat image and also deleted footage. It is then somehow presented as original. This has been going on for months now and it has driven us crazy. We knew something weird was happening with our security video but just didn't know what until I stumbled on an option with DevTools while viewing. I do not know a thing about coding. I'm hoping that somehow I can retrieve the original video footage from the edited code and that someone here would kindly help me to do so. We would be deeply appreciative. Thanks in advance. Link attached.

[https://www.dropbox.com/s/vqed4m2re0j6ex2/File%20Feb%2018%202023%2C%2010%2042%2016%20AM.jpeg?dl=0]

**Comment by captainbrosset** [comment]
Sorry to hear that you are facing issues with your home security system. However, Microsoft Edge DevTools is in no way related to this. DevTools is just a suite of useful tools for web developers to debug their own websites. It only runs inside the browser and cannot access any other parts of a system.
If you want to learn more about DevTools, please see https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/landing/
