### ISSUE TITLE
SPAIN - system webview2 have error with system resources in Edge 110 all versions [DevTools Docs Feedback]

### ISSUE THREAD

**Issue by Uranolibros** [MicrosoftDocs/edge-developer#2461]
Having version 109.0.1518.78, it started to go slow using maps, youtube and Edge customizations. But when installing Webview2 from system 109, the browser started to load super fast, with good cache, and the CPU resources were correct.

With the latest versions of Edge 110, until this last one from 02-24-2023, it is still just as slow, although it seems to saturate the CPU less. However something is undermining the system when Edge loads Webview2 latest version.

EXAMPLE
https://files.fm/u/ja2a2z88t
MORE INFO SISTEM EDGE-WEBVIEW-WINDOWS10
https://files.fm/u/pju2xgxwh
MY NAME IS JESUS FROM SPAIN
Not is a joke, is true. FROM 09-02-2023
 110.0.1587.41 UNTIL 23-02-2023 110.0.1587.56 HAVE have some conflict with the windows and webview2 system resources.

Greetings from Jesus from Madrid Spain (jesmar1973@gmail.com) IT and systems technician.

**Comment by Uranolibros** [comment]
I have verified that it may be something related to the Edge cache, and that Adblock Plus possibly influences something. But as I say, when I had the latest version of Edge 109.0.1518.78, and webview2 had the same version. Edge loaded everything super fast, and now it doesn't, it takes a long time, it's not normal.

**Comment by Uranolibros** [comment]
Hi.
A new update has been made, and the speed has improved but a lot. A lot of loading speed, a jitter of approx 45ms, and on the other hand, YouTube has loaded fast, video and thumbnails. But what I don't understand is why it loads the video first and then the rest of the web, I think this generates browser overload.

EXAMPLE NEW UPDATE EDGE
Versión 110.0.1587.57 (Compilación oficial) (64 bits)
https://files.fm/u/f4w3dejjg

**Comment by captainbrosset** [comment]
Thank you for reaching out about this. Unfortunately, this repository is dedicated to tracking documentation issues, not product issues. If you have a performance issue with Edge or WebView2, please raise feedback using one of these ways:

* For Edge: click on the `...` menu button in the top-right corner of the browser, then **Help and feedback**, then **Send feedback**.
* For WebView2: please create a new issue on [the WebView2Feedback repository](https://github.com/MicrosoftEdge/WebView2Feedback/issues).
