### ISSUE TITLE
perry issue

### ISSUE THREAD

**Issue by Kwapee** [MicrosoftDocs/edge-developer#2463]
[js.txt](https://github.com/MicrosoftDocs/edge-developer/files/10824140/js.txt)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2759d344-2139-2ca3-5d2b-e5a518c97365
* Version Independent ID: 4e854995-ffa1-accc-9090-1eaa1610b2f1
* Content: [Fix JavaScript errors that are reported in the Console - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/console-debug-javascript)
* Content Source: [microsoft-edge/devtools-guide-chromium/console/console-debug-javascript.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/console/console-debug-javascript.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.

**Comment by Kwapee** [comment]
how do i do it boss captainbrosset
