### ISSUE TITLE
Broken link to "Microsoft Edge (EdgeHTML) Virtual Machines"

### ISSUE THREAD

**Issue by remram44** [MicrosoftDocs/edge-developer#2468]
This page has a broken link to `https://developer.microsoft.com/microsoft-edge/tools/vms`:

> Microsoft Edge (EdgeHTML) Virtual Machines (VMs) enable you to access different versions of EdgeHTML and Internet Explorer on your computer through VirtualBox (or VMWare). Select a [virtual machine on the download page](https://developer.microsoft.com/microsoft-edge/tools/vms).

That link currently takes me back to the index at `https://developer.microsoft.com/en-us/microsoft-edge/`. If you have discontinued access to this VM, you should probably say so, or at least remove the broken link.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2959c6a-544c-395c-4bd9-07aaae2f56f9
* Version Independent ID: 2912f751-dab7-d0ae-5455-e9716b001103
* Content: [Emulate and test other browsers - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/testing-other-browsers)
* Content Source: [microsoft-edge/devtools-guide-chromium/device-mode/testing-other-browsers.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/device-mode/testing-other-browsers.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikehoffms** [comment]
Found some info in an archived copy of the page.  Will remove the broken link and possibly add a statement about using BrowserStack instead, which is the first item listed in the subsequent section.

https://web.archive.org/web/20230112030225/https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ -- "The Microsoft Edge team no longer offers VM image downloads for the testing of Microsoft Edge and Internet Explorer. If you need to test your website or app with Microsoft browsers and do not have the necessary versions of Windows to do so, you can use BrowserStack, which supports testing of many combinations of Microsoft browsers and operating systems both past and present. Testing of Microsoft Edge is free on BrowserStack. For more information see https://www.browserstack.com/test-on-microsoft-edge-browser"

**Comment by remram44** [comment]
That sucks for me, now I can't legally test my app on Edge or Windows. But at least the docs will be accurate, thanks.
