### ISSUE TITLE
Windows Hello employs a variety of ways to protect user credentials

### ISSUE THREAD

**Issue by psteniusubi** [MicrosoftDocs/edge-developer#247]
Hello,

Question about how Edge stores WebAuthn credentials

The _Web Authentication and Windows Hello_ article states

> Windows Hello employs a variety of ways to protect user credentials

I am interested in details. Does there exist a specification of what the various ways are and how they work?

In particular I would like to know how to manage WebAuthn credentials. For example how do I remove credentials I no longer need?

The _W3C WebAuthn_ specification is based on the _W3C Credential Management_ specification which states

https://w3c.github.io/webappsec-credential-management/#user-mediated-storage

> User agents MUST allow users to manually remove stored credentials. This functionality might be implemented as a settings page, or via interaction with a notification as described above.

Does this functionality exist in Microsoft Edge?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cabf96-7b2b-9eb6-c428-ff4b44a97312
* Version Independent ID: 922d390b-52b6-db2a-0aab-f338e8c21b85
* Content: [Dev guide - Web Authentication - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication)
* Content Source: [microsoft-edge/dev-guide/windows-integration/web-authentication.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/windows-integration/web-authentication.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @psteniusubi, We use this repo to track documentation related bugs. I'll go ahead and close out this issue now. You can send feedback using Alt + Shift + I. Thank you.
