### ISSUE TITLE
someone has got into my system help please

### ISSUE THREAD

**Issue by MONSTERMASH88** [MicrosoftDocs/edge-developer#2470]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc4cf6d-384c-09e4-f3c1-e8152e3b1302
* Version Independent ID: 1bc4cf6d-384c-09e4-f3c1-e8152e3b1302
* Content: [JavaScript Profiler tool - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript-profiler/javascript-profiler-tool)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript-profiler/javascript-profiler-tool.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/javascript-profiler/javascript-profiler-tool.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete.
