### ISSUE TITLE
No mention of <win32Dependencies:externalDependency>

### ISSUE THREAD

**Issue by DrusTheAxe** [MicrosoftDocs/edge-developer#2476]
[Enter feedback here]
Packaged apps can declare a dependency on WebView2 and it'll get installed if necessary. This page makes no mention of this option, despite it being a far simpler and more attractive option for many developers. No need to mess with the Evergreen Bootstrapper, Evergreen Standalone Installer or SelfContained (Fixed Version) distribution.

Update this page to include this option

See https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency

(that even has an example explicitly citing WebView2 :-) )

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute your app and the WebView2 Runtime - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution?source=docs)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#43627381

**Comment by captainbrosset** [comment]
Thanks for filing, I'll bring this back to the team for consideration and prioritization.
