### ISSUE TITLE
Set background-image (URL) in thead, When you print it, it's going to be split.

### ISSUE THREAD

**Issue by zcq1818** [MicrosoftDocs/edge-developer#2478]
Is it a problem with a plugin?    No - It's the browser itself

Does this work in other browsers?    Yes - This is just a Chromium problem

Steps to reproduce the problem:
1. Set background-image (URL) in thead,
2. When you print it, it's going to be split.

Problem Description:
When the page is printed,
Set the style background-image to be a LOGO image in thead.

For example, there are multiple pages.
When printing, the background-image image will be divided into a number of pages,  which will be displayed at each table head.

Expected:
The complete picture is displayed at the top of each page when printed

Note: This error has the same problem as Chorm. [Please check the feedback](https://bugs.chromium.org/p/chromium/issues/detail?id=1418818)

**Comment by captainbrosset** [comment]
Closing because this is a copy of a chromium bug that has nothing to do here.
