### ISSUE TITLE
Webview2 - Evergreen link to newest offline x64 version

### ISSUE THREAD

**Issue by dgiesselbach** [MicrosoftDocs/edge-developer#2479]
Hello folks,

we need an evergreen link to the latest webview2 offline x64 version. Could you create this link. We need this link for our automatic deployment.

Thanks very much!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute your app and the WebView2 Runtime - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Sorry if you have already checked this page, but https://developer.microsoft.com/en-us/microsoft-edge/webview2/ should contain what you need. Please let me know if it doesn't.

**Comment by dgiesselbach** [comment]
Hi @captainbrosset ,

through your link I find this url for the "Evergreen Standalone Installer x64 bit" https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/d602b474-c305-455f-86f3-49b09505ab2a/MicrosoftEdgeWebView2RuntimeInstallerX64.exe

But it seems that the hash value "d602b474-c305-455f-86f3-49b09505ab2a" would change with each new version.

Hence my question about an "evergreen link". For FSLogix, for example, it looks like this: https://aka.ms/fslogix_download . This link always points to the latest version.

Is it also possible to create something like this for webview2 Evergreen Standalone Installer x64 bit?

**Comment by captainbrosset** [comment]
@champnic are you able to help on this issue please?

**Comment by champnic** [comment]
@dgiesselbach Hello - I think you use the bootstrapper for this purpose. Here's the documentation: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#understanding-the-options-at-the-runtime-download-page

On the WebView2 Runtime page you use the "Get the link" button. Let me know if that doesn't work for you. Thanks!

**Comment by dgiesselbach** [comment]
@champnic yes "get the link" is the right feature, but we need this for the "Evergreen Standalone Installer offline installer x64".

Is this possible?

**Comment by champnic** [comment]
I don't think we have a link specifically for the full offline installer. In the online scenario you could use the bootstrapper, and in offline scenario you could use the version of the offline installer bundled with your app if needed. The installers will install the latest runtime version.

Additionally, the runtime has been distributed to nearly every Win10 device, and is inbox on Win11 devices. It should be unlikely that you are running on a machine without the runtime.

What's your scenario where you need the offline installer?

**Comment by dgiesselbach** [comment]
Currently we use "Evergreen Bootstrapper Online Installer" in our fully automated deployment of Azure Virtual Desktops (Windows 10 Enterprise Multi Session). This AVDs do not get Webview2 automatically! But from time to time the online installer fails to download sources from your servers during the setup process. For this reason we want to switch to the offline installer to eliminate the dependency on the download.

**Comment by champnic** [comment]
Gotcha - thanks for the info! I would recommend getting an offline installer but use it as a backup in case where the bootstrapper fails rather than a full replacement.

If you'd still like to see an evergreen offline installer link can you open an issue on our feedback repo? https://github.com/MicrosoftEdge/WebView2Feedback/issues/new?assignees=&labels=feature+request&template=feature---api-request.md&title=

**Comment by dgiesselbach** [comment]
@champnic ferature request is open :)
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3287

Thx!

**Comment by champnic** [comment]
Thanks! Sorry for the runaround here - I'm glad you got such a quick response and that it seems to solve the issue here :)
