### ISSUE TITLE
Confusing, incorrect documentation "Publish a Progressive Web App to the Microsoft Store"

### ISSUE THREAD

**Issue by zehawki** [MicrosoftDocs/edge-developer#2482]
This document is confusing and does not match anything on the actual so called "Windows partner center". Neither textually nor screenshots.

Referring to https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/microsoft-store#create-an-app-reservation

1. First of all, clicking on the link takes one to "Microsoft Partner Center" not "Windows partner center"
2. "Sign into Windows Partner Center with your Microsoft account" - what does "Microsoft account" mean? Does it mean a personal MS account, or is a MS 365 account considered a "Microsoft account".
3. Next "Navigate to Windows & Xbox." - there is no such thing. Anywhere.
4. "If Windows & Xbox isn't displayed, select Add program." - Again, nowhere do I see anything called "add program"
5. I go through "My access +", then finally a sidebar shows up on which I can select "Programs". Under that I see "Windows: Register as an app developer to submit apps and games to Microsoft marketplaces.", but no "Windows & Xbox" - is this what should be clicked on?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d7f49d04-dd9e-9d95-6bc3-f158e4eacada
* Version Independent ID: 5e3a5695-0978-7051-45d1-623dbb757f22
* Content: [Publish a Progressive Web App to the Microsoft Store - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/microsoft-store)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/microsoft-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/microsoft-store.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#43658570

**Comment by captainbrosset** [comment]
Thank you for reporting this, and sorry about the confusion. We will make sure to revisit this documentation article and update it.

**Comment by captainbrosset** [comment]
We'll do our best to prioritize this with other ongoing tasks and work on this asap.

**Comment by captainbrosset** [comment]
In the meantime, you might find better luck using the PWABuilder docs: https://docs.pwabuilder.com/#/builder/windows

**Comment by zehawki** [comment]
Thank you! Well, that resource also directly doesn't help, but I've made progress. Under [Prerequisites](https://docs.pwabuilder.com/#/builder/windows?id=prerequisites), it says 

* A Microsoft Developer account with Partner Center (which are available for a one-time fee of $19). Create one [here.](https://partner.microsoft.com/en-us/dashboard/account/v3/enrollment/introduction/partnership)

**But that link simply didnt work for me.** It kept taking me back to the same dashboard where I was.

What worked for me was the steps I mentioned above.

Here was my dashboard at start:

![image](https://user-images.githubusercontent.com/8095144/223391604-36e56494-485a-4ec0-a464-ad2d8cc6172b.png)

1. I clicked on "My access +", then finally a sidebar showed up on which I clicked on "Programs".
2. Then it showed me 2 tabs - "registered programs" & "other programs". I clicked on other programs.
3. From the choices, I clicked on "Windows: Register as an app developer to submit apps and games to Microsoft marketplaces."

![image](https://user-images.githubusercontent.com/8095144/223397978-58794d92-180c-426d-a01b-279cd4d9bce4.png)

4. Then it threw me to a screen where it said I can only register using a personal MS account, not MS 365, so I switched accounts

![image](https://user-images.githubusercontent.com/8095144/223398341-5dfa4a76-5aa3-4352-bf6b-4beb1666435c.png)

5. Then selected register as company, etc, entered details, made payment, etc etc
6. Finally I get a new "workspace" in my personal account dashboard called "Apps and games"

![image](https://user-images.githubusercontent.com/8095144/223396984-f0d44e2f-3398-4052-a13d-cf14ea1b9fec.png)

Presumably I should be able to proceed with this part [Reserve Your App](https://docs.pwabuilder.com/#/builder/windows?id=reserve-your-app)

-----

I'm still having an issue with verifying the email ID for the partner center - keeps giving me an error, but of course that's not related to this issue here. Just that its very difficult dealing with MS in general 🙄

**Comment by zateutsch** [comment]
@zehawki Hey there! I'm working on updating this documentation based on your feedback.

Could you check one thing for me? 

If you click on the top left hamburger menu (to the left of Microsoft Partner Center) - does that show the Nav options of "Apps and Games"?

**Comment by zehawki** [comment]
Yup.

![image](https://user-images.githubusercontent.com/8095144/230215241-f67ac6f4-e9d5-43d3-b280-ef0635e24a84.png)

**Comment by zateutsch** [comment]
Do you remember if that was there before you went through the process of registering that new workspace? No worries if not.

**Comment by zehawki** [comment]
> if that was there before you went through the process of registering that new workspace?

No it wasnt. Came into the dashboard and nav only after going thru the steps.

**Comment by zateutsch** [comment]
Thanks for the clarification.
