### ISSUE TITLE
EdgeOptions addArguments is not supported

### ISSUE THREAD

**Issue by MichaelOdumosu57** [MicrosoftDocs/edge-developer#2483]
[Enter feedback here]
The method addArguments(String) is undefined for the type EdgeOptions
![image](https://user-images.githubusercontent.com/21322737/222925718-80a0c45e-2f49-4428-9b75-fcb8846bbd8e.png)

## Environment
|property|value|data|
|:------|:------:|------|
|OS |Windows 10 pro||
|java| java version "17.0.4.1" 2022-08-18 LTS Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2) Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing) openjdk1.7 i believe||
|testng|7.7.1||
|selenium-java|3.14.0||
|vscode version|1.76.0 92da9481c0904c6adfe372c12da3b7748d74bdcb x64||
||||

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver to automate Microsoft Edge - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
The documentation you reported this feedback on mentions `addArgument` (singular), not `addArguments` (plural).
Could it just be a typo in your code? Please let me know if this fixes it for you.

**Comment by MichaelOdumosu57** [comment]
close it I think I fugured it out althogu
