### ISSUE TITLE
Incorrect screenshot to display differences for Focus Mode in DevTools

### ISSUE THREAD

**Issue by aryanprince** [MicrosoftDocs/edge-developer#2486]
> If DevTools is undocked or docked to the bottom of the browser, the **Activity Bar will be horizontal**. If DevTools is docked to the side of the browser, the **Activity Bar will be vertical**, and tool names will not be visible.

In the screenshot shown below, Activity Bar should be shown vertically when docked to right and horizontally when docked below or popped out in a separate window yes?

Is this intended - to show Activity Bar top-aligned for both scenarios (to showcase the collapsible title names for DevTools categories) or an oversight?

![image](https://user-images.githubusercontent.com/45622345/223179672-2fba0e5c-0ebd-47de-9eca-a38c9a948551.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb8172aa-183f-6821-f7a3-1a1f838d671c
* Version Independent ID: fb8172aa-183f-6821-f7a3-1a1f838d671c
* Content: [Simplify DevTools using Focus Mode - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/experimental-features/focus-mode)
* Content Source: [microsoft-edge/devtools-guide-chromium/experimental-features/focus-mode.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/experimental-features/focus-mode.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#43674575

**Comment by captainbrosset** [comment]
You're very right, it feels weird talking about the fact that the Activity Bar is vertical when docked to the side, and then show a screenshot that does not demonstrate this.
In reality, you can customize the position of the Activity Bar, so the screenshot is not incorrect at least, but it is confusing and we should change it.
Thanks for reaching out and filing this issue. I'll add this to our list of things to fix.

**Comment by aryanprince** [comment]
Awesome! Quick question btw, what's the ADO label? Azure DevOps?

**Comment by captainbrosset** [comment]
Yes, ADO stands for Azure DevOps in this context. We're just using it here to track the issues that are in our internal backlog.

**Comment by captainbrosset** [comment]
The new docs should be live in a few minutes. Thanks for the issue!

**Comment by aryanprince** [comment]
New Edge Dev + the red boxes are a good touch, looks great! Much easier to see what Focus mode does to DevTools now
