### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by JasonEades** [MicrosoftDocs/edge-developer#249]
The two links to: https://www.pwabuilder.com/serviceworker are no longer valid.  Server errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcef5936-232e-1ab0-c1c4-77026c79e277
* Version Independent ID: b6ec450d-ead9-ffcf-0d5b-7a408bf0e13d
* Content: [Get started with Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/get-started#feedback)
* Content Source: [microsoft-edge/progressive-web-apps/get-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/get-started.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by rikgarner** [comment]
and https://www.pwabuilder.com/imageGenerator too

**Comment by marcoleitl** [comment]
Found the files here (change the constant "offlineFallbackPage" in pwabuilder-sw.js to "offline.html") :

https://github.com/pwa-builder/pwabuilder-serviceworkers/tree/master/serviceWorker1

**Comment by aajala** [comment]
thanks @marcoleitl
