### ISSUE TITLE
incorrect behavior on DevTools

### ISSUE THREAD

**Issue by Thenewchicken55** [MicrosoftDocs/edge-developer#2491]
The documentation says 
> "For JavaScript changes to take effect, press Ctrl+S"

However even after they're saved, they don't take effect on edge. If I do the same changes on Opera GX, they take effect. I confirmed they are in a function.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6314cab8-5f54-827b-d906-46f67dd0d0cf
* Version Independent ID: fe69a922-b5b5-001b-5ef9-c0f44a693beb
* Content: [Sources tool overview - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/)
* Content Source: [microsoft-edge/devtools-guide-chromium/sources/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/sources/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for sending this feedback. Would you be so kind and please report it on our DevTools feedback repository here instead: https://github.com/MicrosoftEdge/DevTools/ ?
That'd be great! This repo here is only for the documentation. And it seems like what you're seeing is a bug of the product itself, not its documentation.
