### ISSUE TITLE
Win32/C++ API Reference

### ISSUE THREAD

**Issue by kczx3** [MicrosoftDocs/edge-developer#2495]
The WebView2 API Reference page has tabs near the top for links to documentation on different languages/runtimes for API documentation.  Clicking on the Win32/C++ tab shows one hyperlink that points to https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32 however that page has a banner at the top stating:

> This reference is no longer being maintained. For the latest API reference, see [WebView2 API Reference](https://learn.microsoft.com/en-us/microsoft-edge/webview2/webview2-api-reference).

The hyperlink in that banner just leads back to the API Reference page that had just been navigated from.  Seems off to me.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 959795d0-fc31-eee2-8730-ab47d8cca845
* Version Independent ID: 39dd3adf-eb28-3de5-1d26-210775209efd
* Content: [WebView2 API Reference - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/webview2-api-reference?tabs=dotnetcsharp)
* Content Source: [microsoft-edge/webview2/webview2-api-reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/webview2-api-reference.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#43762627

**Comment by Reezaali** [comment]
Thanks for reporting the issue, which is no longer showing up. I'll go ahead and close this issue. Thanks!
