### ISSUE TITLE
options.add_argument("headless")

### ISSUE THREAD

**Issue by yaohongfenglove** [MicrosoftDocs/edge-developer#2496]
[Enter feedback here]

In the 111.0.1661.44 version of Edge, when headless mode is enabled, the actual browser opened is Chrome instead of Edge. For example, the following image shows an edge in headless mode with bind.com open. Obviously, the enabled browser is not edge, but Chrome
![image](https://user-images.githubusercontent.com/71106576/225802061-9c3b53e9-69b9-4eee-af5d-be94b2ed510c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver to automate Microsoft Edge - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=python)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for your feedback. Could you please re-create a new issue on this repository instead: https://github.com/MicrosoftEdge/EdgeWebDriver ?

We only use issues here for tracking documentation issues. But what you are describing feels more like a product bug, and it will get more chances of getting correctly addressed on the EdgeWebDriver repo instead.

Thank you for your understanding.
