### ISSUE TITLE
Include information on how to diagnose when things didn't work

### ISSUE THREAD

**Issue by fiksen99** [MicrosoftDocs/edge-developer#2498]
Currently, step 4 of the Windows section, and step 6 of the macOS steps indicate:

> 6. In Microsoft Edge, go to edge://extensions, and then verify that your extension is listed.

This is great. But if the extension *is not* listed after following these steps, there are no troubleshooting steps, e.g. system logs that we could read to see why the lookup failed - incorrect file placement, incorrect location, invalid update url etc.

Currently when the extension doesn't install, it's a guessing game to figure out what went wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f290aba-5618-9b79-e3ac-243ec8cc4dd6
* Version Independent ID: 0cda1705-27db-4282-40e1-a2fbbd16ed2e
* Content: [Alternative ways to distribute extensions - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#43831315

**Comment by captainbrosset** [comment]
Great suggestion. I'll make sure this is tracked and on our radar for prioritization. 
Quick question though: in your experience, what is the most probable cause for an extension _not_ to get listed? There may be many different reasons why this may not work, and we should make sure to documentate the most common.

**Comment by captainbrosset** [comment]
Closing as I don't think this is actionable as is. Please comment here if you have specific things that would be worth adding. We can always re-open the issue.
