### ISSUE TITLE
Missing contact info / way to resolve the current status.

### ISSUE THREAD

**Issue by guidobouman** [MicrosoftDocs/edge-developer#2511]
There's no way provided to contact the Edge team about getting my domain removed from the Edge compatibility list.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77e7cee1-a4cc-cb21-abf9-19e7eb1333ed
* Version Independent ID: 67677a5d-e51c-5aff-d5fc-b2effddb8fe2
* Content: [Detecting Microsoft Edge from your website - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-guidance)
* Content Source: [microsoft-edge/web-platform/user-agent-guidance.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/user-agent-guidance.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Please take a look at this section: https://learn.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#request-an-update-to-the-internet-explorer-compatibility-list which contains an email address to add or remove your site from the compatibility list.
I hope this helps.
