### ISSUE TITLE
Missing information about the Discover feature

### ISSUE THREAD

**Issue by TheBaban** [MicrosoftDocs/edge-developer#2517]
Discover button has been added in the latest build.
Need to document how DISCOVER pull the data.
https://blogs.windows.com/msedgedev/2022/09/01/microsoft-edge-sidebar-multitask-smarter
"Discover in the sidebar boosts your browsing experience and provides more relevant information as you search the web. Jump to a web page and with a simple click on the Discover button, you’ll get page-related facts, articles, and videos, designed to help you find more of the knowledge and inspiration you’re looking for, all at a quick glance."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1311289-0892-7fa5-3540-96fc823fc8cd
* Version Independent ID: 1c69b077-dbd1-7105-9cc8-d11c99d1495d
* Content: [Microsoft Edge Privacy Whitepaper - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/)
* Content Source: [microsoft-edge/privacy-whitepaper/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/privacy-whitepaper/index.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#43959943

**Comment by captainbrosset** [comment]
Thanks for reaching out. The Discover button has changed since the blog post you mentioned. My understanding is that, now, the same feature is available from the Bing button that's displayed in the top-right corner of the browser, and then under the Insights tab.
I'll bring this issue to the team's attention for evaluation and prioritization.

**Comment by shekhar-chauhan** [comment]
Hey @captainbrosset, i had a better suggestion for the 'Discover' icon. Am I allowed to raise a PR for that? If yes, can you please point me to the repository/branch_name against which I can do that.

**Comment by shekhar-chauhan** [comment]
![image](https://user-images.githubusercontent.com/48454925/233948885-06bb771c-6b66-4894-a0a1-b7a7b53d7640.png)

it really does look awkward, and out of order as well, given the other icons are all "Outline" themed, and this is just a picture of Bing.
Can we change it to something of an outline design to match the other icons.

**Comment by captainbrosset** [comment]
Thanks for the feedback. The best way to report this is via the browser's feedback mechanism:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

I believe this feedback is known by the Edge team already, but sending your own point of view and perspective on it always helps.
You can't, however, open a PR to change this.

Thanks for your understanding.

**Comment by shekhar-chauhan** [comment]
No issues, but I've already sent a feedback for this. Let's see if they decide to fix it.

**Comment by shekhar-chauhan** [comment]
![Screenshot (17)](https://github.com/MicrosoftDocs/edge-developer/assets/48454925/52d5e2d4-d093-42b0-a227-0236806c38b8)

It still does look weird !

**Comment by captainbrosset** [comment]
The way the button looks has nothing to do with this issue however. This issue was specifically on the topic of updating the privacy whitepaper with information about Bing Chat and other AI-related features. This has been done, hence the issue now closed.

**Comment by shekhar-chauhan** [comment]
I get it that this has nothing to do with that issue, but just raised it as an FYI cause i didn't wanna raise a new issue for a simple gui thing.
