### ISSUE TITLE
[DevTools Docs Feedback]

### ISSUE THREAD

**Issue by xiakan** [MicrosoftDocs/edge-developer#2522]
描述：
频繁close、open webview2偶现空白页面或页面显示error。
环境：
SDK:1.0.1248-prerelease
Microsoft.UI.Xaml: 2.8.0-prerelease.220413001
代码调用如下：
private async void Init()
{
 webView = new WebView2();
await webView?.EnsureCoreWebView2Async();
}
private void Navigate()
{
if (webView?.CoreWebView2 != null)
            {
                webView.CoreWebView2.Navigate("");
}
private void CloseWebView2()
{
webView?.Close();
.webView = null;
}

private  void Button_Click(object sender, RoutedEventArgs e)
{
    Init();
}
private  void ButtonClose_Click(object sender, RoutedEventArgs e)
{
    CloseWebView2();
}
问题：
1.调用await webView?.EnsureCoreWebView2Async() 后，有时候不返回CoreWebView2对象，为什么？如何去解决？
2.调用webView.CoreWebView2.Navigate("");后，出现error或白屏现象，这里代码块已经走完。
3.如何去根据上面操作去修复白屏和error的问题？希望得到webview2团队大佬的答复，谢谢~

**Comment by captainbrosset** [comment]
I used Google translate to translate the above description into English:

describe:
Frequent close, open webview2 occasional blank page or page display error.
environment:
SDK: 1.0.1248-prerelease
Microsoft.UI.Xaml: 2.8.0-prerelease.220413001
The code call is as follows:
private async void Init()
{
webView = new WebView2();
await webView?.EnsureCoreWebView2Async();
}
private void Navigate()
{
if (webView?. CoreWebView2 != null)
{
webView.CoreWebView2.Navigate("");
}
private void CloseWebView2()
{
webView?.Close();
.webView = null;
}

private void Button_Click(object sender, RoutedEventArgs e)
{
Init();
}
private void ButtonClose_Click(object sender, RoutedEventArgs e)
{
CloseWebView2();
}
question:
1. After calling await webView?.EnsureCoreWebView2Async(), sometimes the CoreWebView2 object is not returned, why? How to solve it?
2. After calling webView.CoreWebView2.Navigate("");, an error or a white screen appears, and the code block here has been completed.
3. How to fix the white screen and error problems according to the above operations? I hope to get an answer from the webview2 team leader, thank you~

**Comment by captainbrosset** [comment]
Based on the above, can you please re-open this issue on the WebView2Feedback repository instead? You will likely get better answers to your question there.
Here is the link: https://github.com/MicrosoftEdge/WebView2Feedback/issues/new

---

Translation to Chinese:

基于以上所述，您能否改为在 WebView2Feedback 存储库上重新打开此问题？您可能会在那里得到更好的问题答案。
这是链接：https://github.com/MicrosoftEdge/WebView2Feedback/issues/new
