### ISSUE TITLE
No Support for Mac/non-Windows?

### ISSUE THREAD

**Issue by TonyGorman** [MicrosoftDocs/edge-developer#2523]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Introduction to Microsoft Edge WebView2 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by TonyGorman** [comment]
> [Enter feedback here]

What are the plans to make this cross platform?

**Comment by captainbrosset** [comment]
Thank you for reaching out. This question is specific to the WebView2 product, not its documentation. Therefore, could you please open a new issue for this over on the dedicated WebView2Feedback repository?

Here is the link: https://github.com/MicrosoftEdge/WebView2Feedback/issues/new

Thanks for your understanding.
