### ISSUE TITLE
Two feedback headers in some pages

### ISSUE THREAD

**Issue by liminzhu** [MicrosoftDocs/edge-developer#253]
There are 2 `Feedback` headers in some of the pages, and the 2nd one at the bottom of the page is probably autogenerated. This is a bit confusing and I'm not sure if the bottom Feedback has the right links. @zoherghadyali 

Example - 
https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide

**Comment by Reezaali** [comment]
Thanks for the feedback. This has been fixed. Closing this issue now.
