### ISSUE TITLE
PrintAsync not working properly

### ISSUE THREAD

**Issue by subash7038** [MicrosoftDocs/edge-developer#2530]
I tried to print a HTML file using Webview2's PrintAsync method. The document is sent to the printer queue but didn't print in the printer. Is there any way to silently print my HTML file to printer in WPF. I can able to print it manually through browser. I tried converting it to a pdf file as well and print it but still couldn't print.
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5508b9cf-0802-8e6e-3f88-3c482efd1a8f
* Version Independent ID: 5508b9cf-0802-8e6e-3f88-3c482efd1a8f
* Content: [Printing from WebView2 apps - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/print?tabs=dotnetcsharp)
* Content Source: [microsoft-edge/webview2/how-to/print.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/print.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out. This question is specific to the WebView2 product, not its documentation. Therefore, could you please open a new issue for this over on the dedicated WebView2Feedback repository?

Here is the link: https://github.com/MicrosoftEdge/WebView2Feedback/issues/new

Thanks for your understanding.
