### ISSUE TITLE
MS case 35808789 - redirected to here - WebView2

### ISSUE THREAD

**Issue by MCSSinc** [MicrosoftDocs/edge-developer#2531]
Our network has O365 web based email disabled for security purposes. 

I understand WV2 is the cause Outlook trying to open a web browser either with multiple email accounts or just switching to calendar. We do not use WV2, users only use desktop products for O365. 

WV2 auto install has been disabled in O365 Apps Admin, box is unchecked, but it's not working. Have confirmed auto re-install of WV2 a while later, leading back to the problem of Outlook and the browser login. A GPO was applied using the Edge/WV2 admx files, can confirm they work using edge://policy, but they are not helping either. 

What is the method to remove WV2 from all computers and disable auto-reinstall?

**Comment by MCSSinc** [comment]
Ok, thank you. I did run into that link earlier. Tried disabling update tasks in scheduler, registry changes, various powershell commands, domain GPOs, etc.

This thread covers Outlook opening a web browser for a meeting creation or when Outlook feels like it, opening a browser while trying to navigate through Outlook accounts.
https://answers.microsoft.com/en-us/outlook_com/forum/all/how-to-stop-outlook-from-opening-a-browser-every/44daf8f7-4168-4726-8dc8-e580d1a8580e?page=7

A suggestion for a temp fix until MS releases the update is –

C:\Windows\System32\Drivers\etc\hosts
127.0.0.1 outlook.office.com

Have to verify this AM with a few users, but yesterday this change was working, doesn’t seem to break Outlook. For a user that has had a persistent problem with this, after putting in the loopback, you could see Outlook putting the spinner on the mouse pointer like it wanted to connect to MS, didn’t, then kept working along.

From: Patrick Brosset ***@***.***>
Reply-To: MicrosoftDocs/edge-developer ***@***.***>
Date: Wednesday, April 5, 2023 at 12:21 AM
To: MicrosoftDocs/edge-developer ***@***.***>
Cc: Merlin Johnson ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/edge-developer] MS case 35808789 - redirected to here - WebView2 (Issue #2531)


This related FAQ was recently added to the WebView2 docs: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/end-user-faq#why-was-webview2-re-installed-after-i-uninstalled-it

That being said, it doesn't seem like this is the answer you were expecting. Let me ping @champnic<https://github.com/champnic> here as he might be able to provide a better reply.

**Comment by champnic** [comment]
@MCSSinc Have you confirmed that Outlook is the source of the WebView2 install? Lots of apps these days are using WebView2 and may deploy it to the machine.

Even if you aren't using the web for email, the desktop Outlook app uses WebView2 for other purposes and will attempt to install it if it's not there. I can't speak to the Office admin setting for disabling auto-install and whether or not that works. I believe the Edge/WebView2 group policy only disables updates, not initial installs.

**Comment by MCSSinc** [comment]
I looked into that and have tried to remove all extra MS apps I could, also realizing other apps could trigger a reinstall. Thing is even after explicitly turning off WV2 auto update via local and domain GPO, task scheduler and via O365 Apps Admin, it still reinstalls. Once it reinstalls Outlook tries to open a web browser for O365 login (that’s the main user disruption) or if you move between email accounts and calendars.

From: "Nic Champagne Williamson [MSFT]" ***@***.***>
Reply-To: MicrosoftDocs/edge-developer ***@***.***>
Date: Wednesday, April 5, 2023 at 12:04 PM
To: MicrosoftDocs/edge-developer ***@***.***>
Cc: Merlin Johnson ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/edge-developer] MS case 35808789 - redirected to here - WebView2 (Issue #2531)


@MCSSinc<https://github.com/MCSSinc> Have you confirmed that Outlook is the source of the WebView2 install? Lots of apps these days are using WebView2 and may deploy it to the machine.

Even if you aren't using the web for email, the desktop Outlook app uses WebView2 for other purposes and will attempt to install it if it's not there. I can't speak to the Office admin setting for disabling auto-install and whether or not that works. I believe the Edge/WebView2 group policy only disables updates, not initial installs.

**Comment by champnic** [comment]
Oh gotcha - this is just a workaround for a bug in Office, not the main thing you are trying to accomplish. It looks like the Outlook team is aware of the issue and working on a fix which should be available soon:
https://support.microsoft.com/en-us/office/outlook-unexpectedly-opens-a-browser-window-if-owa-is-disabled-4c915e88-0654-4f77-8daa-a624600dc718

**Comment by MCSSinc** [comment]
Just found that one, yes eagerly awaiting a fix.

From: "Nic Champagne Williamson [MSFT]" ***@***.***>
Reply-To: MicrosoftDocs/edge-developer ***@***.***>
Date: Wednesday, April 5, 2023 at 12:22 PM
To: MicrosoftDocs/edge-developer ***@***.***>
Cc: Merlin Johnson ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/edge-developer] MS case 35808789 - redirected to here - WebView2 (Issue #2531)


Oh gotcha - this is just a workaround for a bug in Office, not the main thing you are trying to accomplish. It looks like the Outlook team is aware of the issue and working on a fix which should be available soon:
https://support.microsoft.com/en-us/office/outlook-unexpectedly-opens-a-browser-window-if-owa-is-disabled-4c915e88-0654-4f77-8daa-a624600dc718
