### ISSUE TITLE
Is the Canary Channel of Edge necessary for remote debugging of WebView2 on UWP?

### ISSUE THREAD

**Issue by sparkrod** [MicrosoftDocs/edge-developer#2532]
This documentation recommends that you download the canary channel of Microsoft Edge in step 1. Is this really necessary to be able to follow the rest of the steps? It seems to work fine with the version I have-- 111.0.1661.62 (Official build) (64-bit)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c27cd959-ebbb-089e-2b4c-ac1548a09093
* Version Independent ID: c27cd959-ebbb-089e-2b4c-ac1548a09093
* Content: [Remote debugging WebView2 WinUI 2 (UWP) apps with Remote Tools for Microsoft Edge - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/remote-debugging)
* Content Source: [microsoft-edge/webview2/how-to/remote-debugging.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/remote-debugging.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out about this. 
My intuition is that, at the time the doc was written, Canary was needed. But perhaps the feature that was needed in Edge is now also available in the normal Release version.

@mikehoffms would you be able to answer the question?

**Comment by sparkrod** [comment]
Yes that was my feeling as well. I would like to give clear direction to our developers and IT team about this, since it involves installing extra software-- please let us know!

**Comment by mikehoffms** [comment]
The PR also removes steps about setting the release channel preference to 1 (WEBVIEW2_RELEASE_CHANNEL_PREFERENCE=1); this is no longer needed.
