### ISSUE TITLE
Headless

### ISSUE THREAD

**Issue by marcelogrsp** [MicrosoftDocs/edge-developer#254]
How do I open it on headless mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c06efc-3188-86bb-4f73-f171b67df210
* Version Independent ID: 4859f651-74ee-4bbb-33c7-d999d4933070
* Content: [Webdriver - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver#feedback)
* Content Source: [microsoft-edge/webdriver.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi there, there's a new document with the information available at: https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium?tabs=c-sharp.

I'll go ahead and close out this issue now. Thanks.
