### ISSUE TITLE
Warning error re lazy loading iframes

### ISSUE THREAD

**Issue by Scrabble96** [MicrosoftDocs/edge-developer#2550]
[Enter feedback here]
Re a warning saying "iframe[loading]' is not supported by Firefox, Firefox for Android, Safari, Safari on iOS."

This is not true for Firefox (I haven't tested the others). See https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f96b9489-8f01-cb4e-4a61-f1817303c287
* Version Independent ID: f96b9489-8f01-cb4e-4a61-f1817303c287
* Content: [Overview of DevTools - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/overview)
* Content Source: [microsoft-edge/devtools-guide-chromium/overview.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/overview.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Looking at [the iframe's documentation on MDN](https://developer.mozilla.org/en-US/docs/web/html/element/iframe#browser_compatibility), it says that the `loading` attribute is not supported on Firefox and Firefox and Android yet, and points to this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1622090 which is still open. So I do not think that `iframe[loading]` is supported.
It does seem to be supported on Safari though.

However, this isn't a documentation bug (which this repository is about). I believe this is a webhint bug. Webhint uses the [mdn/browser-compat-data](https://github.com/mdn/browser-compat-data/) dataset to get this information, same as what MDN uses. So this issue should resolve itself as soon as webhint updates to a more recent version of BCD.
