### ISSUE TITLE
Method to check if WebView Runtime installed already outdated.

### ISSUE THREAD

**Issue by valuator18** [MicrosoftDocs/edge-developer#2569]
No HKLM\SOFTWARE\Microsoft\EdgeUpdate key in the registry despite having the WebView2 installed.

![image](https://user-images.githubusercontent.com/45210657/235797530-adbc2094-9505-4298-b7b6-005ea7569446.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e34a272-7809-e90f-e677-deceb6b3a90d
* Version Independent ID: 3e34a272-7809-e90f-e677-deceb6b3a90d
* Content: [WiX Custom Action to deploy the WebView2 Runtime - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/samples/wv2deploymentwixcustomactionsample)
* Content Source: [microsoft-edge/webview2/samples/wv2deploymentwixcustomactionsample.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/samples/wv2deploymentwixcustomactionsample.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out. This question is specific to the WebView2 product, not its documentation. Therefore, could you please open a new issue for this over on the dedicated WebView2Feedback repository?

Here is the link: https://github.com/MicrosoftEdge/WebView2Feedback/issues/new

Thanks for your understanding.

**Comment by valuator18** [comment]
Ok, just FYI the feedback button on https://learn.microsoft.com/en-us/microsoft-edge/webview2/samples/wv2deploymentwixcustomactionsample links to this repository, not the one you provided.
