### ISSUE TITLE
PWA, WinRT, and Visual Studio 2019?

### ISSUE THREAD

**Issue by brodybits** [MicrosoftDocs/edge-developer#257]
The referenced content describes how it would be possible to make a PWA work with WinRT, and lists Visual Studio 2017 as a prerequisite.

It is not 100% clear to me whether or not this would be possible with Visual Studio 2019.

I think this kind of functionality would be useful for a number of Windows apps in 2019 and beyond. It is also needed for the Apache Cordova Windows platform support to work without some kind of a rewrite. (They already had to do a rewrite to go from WP8 to UWP.)

This comment is triggered by <https://github.com/apache/cordova-windows/issues/327#issuecomment-488505446>. I tweeted this question in <https://twitter.com/brodybits/status/1123769634514264065> before I realized I could raise this question on GitHub.

May be related to the following issues:
- #252
- #220
- #177

I was also wondering if the following pages are relevant for Visual Studio 2019, would be happy to raise separate issues if needed:

- https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/get-started
- https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba583c8-c78b-49de-a68a-4fbc7a2bb568
* Version Independent ID: e71db58c-e513-eefd-3f4d-2644b88f405d
* Content: [Progressive Web Apps in the Microsoft Store - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/microsoft-store)
* Content Source: [microsoft-edge/progressive-web-apps/microsoft-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/microsoft-store.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
This unfortunately hasn't been updated in a long time. Marking as stale and planning to close this soon unless this becomes active again.
