### ISSUE TITLE
CMake instructions

### ISSUE THREAD

**Issue by olilarkin** [MicrosoftDocs/edge-developer#2577]
It would be great if you could also provide instructions for how to do this via Cmake, since there you can't manually tweak your .vcxproj each time

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31b9c394-df9a-b0fd-5710-6c49f0354c0a
* Version Independent ID: a8c05336-1d5c-8fdc-0a47-aa99a927e6c1
* Content: [Distribute a WebView2 app as a single executable file - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/static)
* Content Source: [microsoft-edge/webview2/how-to/static.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/static.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#44527569

**Comment by captainbrosset** [comment]
Thanks for reporting this. I'll make sure this is tracked on our team's radar for evaluation and prioritization.

**Comment by captainbrosset** [comment]
After evaluation, we decided not to prioritize this particular request at this time in this repository.
If you need help on this, please check the https://github.com/MicrosoftEdge/WebView2Feedback repository where you can discuss with the team and other WebView2 users.
Thank you for your input.
