### ISSUE TITLE
Suggestions for additional information

### ISSUE THREAD

**Issue by Coarist** [MicrosoftDocs/edge-developer#2578]
There are many types of code that use WebView2. Examples are WPF and .NET Framework. Specific to writing Windows Desktop application using .NET (.NET Core), it is fairly straightforward to embed WebView2. In Visual Studio 2022, pull the package into our project using NuGet Package Manger. However, when our app target is deployed, there is one thing to consider as described below. 

For Windows Desktop target using WebView2 **Fixed Runtime**, the setup program (or installer) would put the app into the **Program Files** or the **Program Files(x86)** folder together with WebView2 executables. By default, browser data such as cookies, cache, etc. are also written to this directory. Since WebView2 user does not have access rights to the folder, the operation will fail. Browser will not be able to display content. 

The following code line demonstrates a solution to this problem. 

`var p = Path.Combine(Application.UserAppDataPath, "MyWebView2AppName"); Environment.SetEnvironmentVariable("WEBVIEW2_USER_DATA_FOLDER", p);`

The above code gave instruction to WebView2 to place browser data to the designated user space on harddisk outside of the app install folder. Add this line to our source code, place it immediately after WebView2 is loaded (instantiated), to complete adoption of WebView2 in our app. With this change, our app will be able to display Internet contents.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribute your app and the WebView2 Runtime - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out. I am not sure what you are requesting however. This repository is to track documentation changes only. Can you explain what documentation changes you think we should be making exactly?

**Comment by Coarist** [comment]
In order to assist other WebView2 users in saving time and confusion, I would like some additional information placed in appropriate section in documentation. The additional information regards WebView2 application deployment. That is, after the programmer is satisfied with his/her program that utilizes WebView2, he/she will deploy the program. He/she will find out that the program used to work in debugging mode now cease to function properly when run standalone. This is because the programmer needs to be aware of the settings:

`var p = Path.Combine(Application.UserAppDataPath, "MyWebView2AppName"); Environment.SetEnvironmentVariable("WEBVIEW2_USER_DATA_FOLDER", p);`
