### ISSUE TITLE
MSWebViewWebResourceRequested not able to capture all resource requests.

### ISSUE THREAD

**Issue by DexterWoo** [MicrosoftDocs/edge-developer#258]
Hi, I am trying to use MSWebViewWebResourceRequested to capture all request from my site, and I found that 1. svg resource won't be rendered, 2. font request won't be captured.
I will try to pack my site to inline all svg/font resources in the html it self, but is it possible to know what else limitation this event has?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb816db-330e-da9a-4ae8-43107365f42a
* Version Independent ID: 727a6adc-35e4-bbeb-dd37-c20badc66af8
* Content: [Microsoft Edge WebView for Windows 10 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview)
* Content Source: [microsoft-edge/hosting/webview.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/hosting/webview.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by pagoe-msft** [comment]
Moved to our feedback repo over here: https://github.com/MicrosoftEdge/WebViewFeedback/issues/153
