### ISSUE TITLE
Is there any code sample explaining how to add a Microsoft Edge extension in the web view?

### ISSUE THREAD

**Issue by lucasvinicode** [MicrosoftDocs/edge-developer#2580]
Is there any code sample explaining how to add a Microsoft Edge extension in the web view?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6747d603-e773-dec7-7580-f18f4365cec9
* Version Independent ID: 5f7cd45b-5739-ad85-4b61-c9f94921df98
* Content: [Get started with WebView2 in WinUI 3 (Windows App SDK) apps - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui)
* Content Source: [microsoft-edge/webview2/get-started/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/winui.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
My understanding is that Microsoft Edge WebView2 does not support extensions. But please feel free to ask your question again on the dedicated WebView2Feedback repository?

Here is the link: https://github.com/MicrosoftEdge/WebView2Feedback/issues/new

Thanks for your understanding.
