### ISSUE TITLE
Re-title and/or split notifications, badges, and push page?

### ISSUE THREAD

**Issue by aluhrs13** [MicrosoftDocs/edge-developer#2591]
**Link to the documentation page**: https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/notifications-badges

**Description of the issue**: These three concepts are loosely related, but combining them makes it difficult to find details on push. I always end up looking at the background sync doc trying to find it. Also the title is much more verbose than other similar pages.

AB#44676504

**Comment by captainbrosset** [comment]
Thanks Andy, this makes a lot of sense. I agree that Push (at least) should be split into its own article.
Let me make sure this is tracked on our backlog.
