### ISSUE TITLE
Conditional breakpoints should have a different color

### ISSUE THREAD

**Issue by harith1996** [MicrosoftDocs/edge-developer#2595]
Hello,
It would be good to make conditional breakpoints look different than the normal red-colored breakpoints. This is a feature that is implemented in almost all Chromium-based browsers and Firefox, for examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a900399-43f6-f787-17b1-426e26eec4a1
* Version Independent ID: 97d60945-0048-78f6-cc47-0e4202c9817d
* Content: [Pause code with breakpoints - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/breakpoints)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript/breakpoints.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/javascript/breakpoints.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out about this. 
I think this is a great feature request, but unfortunately it's not on the right repository. This repository here is for tracking **documentation** issues, not product issues.
Could you please create a new issue for this over on the DevTools repo instead? Here is the address: https://github.com/MicrosoftEdge/DevTools

Thanks for your understanding!

**Comment by harith1996** [comment]
Whoops! Thanks for pointing that out.

I've opened the a [new issue](https://github.com/MicrosoftEdge/DevTools/issues/155) on the DevTools repo :)
