### ISSUE TITLE
amjad

### ISSUE THREAD

**Issue by amjadkofahi** [MicrosoftDocs/edge-developer#2601]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93731a26-d409-9e68-78f8-09a06658e5ed
* Version Independent ID: d352bba6-17ec-ae4c-921b-2a6aa16f8eab
* Content: [Remotely debug Windows devices - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/windows#activate-developer-mode-and-enable-device-portal)
* Content Source: [microsoft-edge/devtools-guide-chromium/remote-debugging/windows.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/remote-debugging/windows.md)
* Product: **microsoft-edge**
[README.md](https://github.com/MicrosoftDocs/edge-developer/files/11521186/README.md)

* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by amjadkofahi** [comment]
> [Enter feedback here]
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 93731a26-d409-9e68-78f8-09a06658e5ed
> * Version Independent ID: d352bba6-17ec-ae4c-921b-2a6aa16f8eab
> * Content: [Remotely debug Windows devices - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/windows#activate-developer-mode-and-enable-device-portal)
> * Content Source: [microsoft-edge/devtools-guide-chromium/remote-debugging/windows.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/remote-debugging/windows.md)
> * Product: **microsoft-edge**
>   [README.md](https://github.com/MicrosoftDocs/edge-developer/files/11521186/README.md)
> * Technology: **devtools**
> * GitHub Login: @MSEdgeTeam
> * Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
