### ISSUE TITLE
AA

### ISSUE THREAD

**Issue by leader195** [MicrosoftDocs/edge-developer#2602]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5074db57-7412-88c6-70a4-213f96ade8cb
* Version Independent ID: 5074db57-7412-88c6-70a4-213f96ade8cb
* Content: [Find source files for a page using the Search tool - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/search/search-tool)
* Content Source: [microsoft-edge/devtools-guide-chromium/search/search-tool.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/search/search-tool.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
