### ISSUE TITLE
無法發佈擴充功能。您的開發人員帳戶驗證擱置中或遭到拒絕。在您開始發佈之前，請先在 [帳戶設定頁面完成帳戶驗證。 深入了解

### ISSUE THREAD

**Issue by new4u** [MicrosoftDocs/edge-developer#2606]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e46faf3-c5bc-3872-ff77-f5056ac88704
* Version Independent ID: 35ea3906-7ea2-159b-75d9-490b9e4f4d5a
* Content: [Register as a Microsoft Edge extension developer - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/create-dev-account#account-type)
* Content Source: [microsoft-edge/extensions-chromium/publish/create-dev-account.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/publish/create-dev-account.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. However, I'm not sure how to best help you. Here is the translation of this issue's title into English:

"Unable to publish extension. Your developer account verification is on hold or declined. Before you can start posting, please complete account verification on the Account Settings page. understand deeper"

There appears to be an issue with your developer account. This repository is specifically focused on the Edge developer documentation only. Please provide more information about your issue and we will try to direct you to the right place.

**Comment by captainbrosset** [comment]
Closing as stale. Feel free to comment with more information and I can re-open the issue.
