### ISSUE TITLE
Tracking 

### ISSUE THREAD

**Issue by manishaarya9899359346** [MicrosoftDocs/edge-developer#2609]
/
#1996  feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f54bc635-cbe9-0a10-0936-fd97ef878a39
* Version Independent ID: 793467bb-69e0-4093-6761-ce443318751e
* Content: [Tracking prevention in Microsoft Edge - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/tracking-prevention)
* Content Source: [microsoft-edge/web-platform/tracking-prevention.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/tracking-prevention.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
