### ISSUE TITLE
[DevTools Docs Feedback]fody&webview2

### ISSUE THREAD

**Issue by jemmy2556a** [MicrosoftDocs/edge-developer#2610]
Hello, when I use fody to package, I cannot package the webview2-related dll files into a single executable file, and after I package it, the webview2 program cannot be used in the program, and there is no error report directly. 

When i double-clicking the event My program cannot call webview2. 

I have tried to embed the necessary program directly into the program and then package it, but the result is that an error is reported directly. 

I have read a lot of relevant information, but there is no corresponding solution

**Comment by jemmy2556a** [comment]
does anyone have an answer for me?

**Comment by captainbrosset** [comment]
Thank you for reaching out. This question is specific to the WebView2 product, not its documentation. Therefore, could you please open a new issue for this over on the dedicated WebView2Feedback repository?

Here is the link: https://github.com/MicrosoftEdge/WebView2Feedback/issues/new

Thanks for your understanding.
