### ISSUE TITLE
关于扩展应用的审核太慢了

### ISSUE THREAD

**Issue by Crucialm** [MicrosoftDocs/edge-developer#2611]
[Enter feedback here]

关于扩展应用的审核太慢了，可以加快吗？
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6bdbaf0-1a39-c369-deca-d22e0d4e6ec0
* Version Independent ID: 7ec272a7-8291-5d33-f320-ef7f1bcd9648
* Content: [Contact Microsoft Edge extensions support - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team)
* Content Source: [microsoft-edge/extensions-chromium/publish/contact-extensions-team.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/publish/contact-extensions-team.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out. Unfortunately this isn't the right place to enquire about extension reviews. I'm sorry you are experiencing slow reviews, but this repository is specific to the Edge platform documentation. I would suggest using the support resources on Partner Center instead. 
Thanks for your understanding.
