### ISSUE TITLE
[Add-ons API] Status Not Updating After Publishing

### ISSUE THREAD

**Issue by DannyBedard** [MicrosoftDocs/edge-developer#2612]
I am facing an issue with the Microsoft Edge Add-ons API while attempting to publish my Edge extension using GitHub Actions' Ubuntu runners. Despite receiving a successful HTTP 202 response after publishing the app, the status of the submission does not update in the UI as expected.

So far:

- I can successfully fetch the authentication token using the API.
- I can update the zip files of the existing draft submission using the API, and I can observe the changes in the UI.
- However, when I use the API to publish the app for review, the status in the UI remains unchanged even though I receive a HTTP 202 response.

I can see that my package has been verified. I can also publish my extension using the UI button and I can see the status change from "in draft" to "in review", which is what I expect to see when I publish with the API.

My API request :

```
curl \
	-H "Authorization: Bearer ${{ steps.token.outputs.token }}" \
	-H "Content-Length: 0" \
	-X POST \
	-i \
https://api.addons.microsoftedge.microsoft.com/v1/products/${{ secrets.DWL_EDGE_PRODUCT_ID }}/submissions
```

This is the response :

```
HTTP/1.1 202 Accepted
Content-Length: 0
Location: <value>
Request-Context: appId=<value>
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Fri, 26 May 2023 13:50:39 GMT
```

When I try to fetch the status using the API, I receive this

```
  "id": <value> ,
  "createdTime": "2023-05-29T17:33:33.[82]",
  "lastUpdatedTime": "2023-05-29T17:33:34.6130653Z",
  "status": "Failed",
  "message": "Can't create new extension.",
  "errorCode": "CreateNotAllowed",
  "errors": null
```

Which in the documentation it says `Response when a new product is published`

https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference#response-when-a-new-product-is-published

Maybe there is a missing step?

AB#45606331

**Comment by captainbrosset** [comment]
Thanks for reaching out and providing those details.
Let me try to get somebody to help you with this particular problem. I'll also keep this issue opened in case there is a change that needs to be made to the documentation too.

**Comment by DannyBedard** [comment]
The tags `needs-more-info` as been assigned to this issue, can you please tell me the information I need to provide?

**Comment by captainbrosset** [comment]
Sorry @DannyBedard, this tag isn't meant for you to provide information, but rather for someone who knows more about the AI than I do to comment here.

**Comment by captainbrosset** [comment]
I realize it's been some time and nothing has happened here. I'll try to get someone to comment here again. But this might be useful for you too: there's now a new extension-specific repository on GitHub too, where people can come and ask questions about APIs. So you might want to ask your question over there too: https://github.com/microsoft/MicrosoftEdge-Extensions/issues

**Comment by captainbrosset** [comment]
Our team looked into this particular issue and, based on the error message provided, it looks like you are trying to publish a new extension to the Edge Add Ons Store.

The Publish API currently only supports updates to existing extensions. Publishing of a new extension has to be done through Partner Centre ([docs](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension)).

I'll make sure this is documented on the Publish API docs.

Let us know if you have any other questions.

**Comment by DannyBedard** [comment]
Thank you for your answer, since then, I've tried with an existing extension and the result is similar, I'm able to put a new submission `in draft`, publish it, but the status of the submission stay in draft and it doesn't change to `in review`

**Comment by captainbrosset** [comment]
My PR has been merged, but given your last comment, this issue shouldn't be fixed.
I'll check with the team and we'll get back to you here.

**Comment by DannyBedard** [comment]
I up this issue since it's been a while

**Comment by captainbrosset** [comment]
Thanks for the ping. I'll check again.

**Comment by Gurjeet-msft** [comment]
Hello @DannyBedard ,

I request you to please provide us with more details about this issue, including your account, extension and the submissions details you are referring to @[[ext_dev_support@microsoft.com](mailto:ext_dev_support@microsoft.com)] and our team will review it. 

Thanks,
Gurjeet Singh.

**Comment by captainbrosset** [comment]
Thank you @Gurjeet-msft for helping. Closing this issue since this is now a support request.
