### ISSUE TITLE
Jan Buřil +420606339626

### ISSUE THREAD

**Issue by Buriljan1** [MicrosoftDocs/edge-developer#2615]
[Sem napište váš názor.]
nic moc teda , nefunguje to a je to složitě to vůbec dělat a celkově není v tom přehled a EU a ČR to zakazují dělat 
takže je to k ničemu nevadí aspoň trochu jinak vylepšit změnu nastavení změn k vytváření vlastních věcí na webu a kontrola 

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů learn.microsoft.com ➟ GitHub.*

* ID: 6314cab8-5f54-827b-d906-46f67dd0d0cf
* Version Independent ID: fe69a922-b5b5-001b-5ef9-c0f44a693beb
* Content: [Sources tool overview - Microsoft Edge Development](https://learn.microsoft.com/cs-cz/microsoft-edge/devtools-guide-chromium/sources/)
* Content Source: [microsoft-edge/devtools-guide-chromium/sources/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/sources/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
