### ISSUE TITLE
I Cant see the Microsoft.Web.WebView2 after searched

### ISSUE THREAD

**Issue by aviv-pzProjects** [MicrosoftDocs/edge-developer#2622]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d071ad3-e3b9-4a21-72c8-ca9c2ae27a40
* Version Independent ID: 1d071ad3-e3b9-4a21-72c8-ca9c2ae27a40
* Content: [Set up your Dev environment for WebView2 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/machine-setup)
* Content Source: [microsoft-edge/webview2/how-to/machine-setup.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/machine-setup.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. Could you please enter more feedback in this issue explaining where you were expecting to see Microsoft.Web.WebView2, and where you searched?
The article you refer to is long, and I'm trying to understand exactly which step led to a problem when you tried to follow the docs.

**Comment by mikehoffms** [comment]
In VS, in NuGet Package Manager, to search for "Microsoft.Web.WebView2", click the **Browse** tab.  If you instead are looking at the **Installed** tab or the **Updates** tab, and the package isn't installed yet, it won't be found.

https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/machine-setup#install-or-update-the-webview2-sdk
that section includes screenshot showing the Browse tab where "Microsoft.Web.WebView2" is found:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/media/nuget.png

**Comment by captainbrosset** [comment]
Closing this issue which has become stale. Feel free to keep commenting here and we can re-open the issue if needed.
