### ISSUE TITLE
Your message to ietoedge@microsoft.com couldn't be delivered.

### ISSUE THREAD

**Issue by nattrass** [MicrosoftDocs/edge-developer#2632]
Getting an error message when using the email address ietoedge@microsoft.com <ietoedge@microsoft.com> defined in the documentation.  The address doesn't exist on the Microsoft domain??

> Your message to ietoedge@microsoft.com couldn't be delivered.
> --
> ietoedge wasn't found at microsoft.com.

<html>
<body>

Original Message Details
--
Created Date:08/06/2023 18:44:11Sender Address:paul@##########Recipient Address:ietoedge@microsoft.comSubject:Add to Internet Explorer compatibility list | Created Date: | 08/06/2023 18:44:11 | Sender Address: | ****@****** | Recipient Address: | ietoedge@microsoft.com | Subject: | Add to Internet Explorer compatibility list
Created Date: | 08/06/2023 18:44:11
Sender Address: | paul@*********
Recipient Address: | ietoedge@microsoft.com
Subject: | Add to Internet Explorer compatibility list
Error Details
Error:550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [DM3NAM06FT006.Eop-nam06.prod.protection.outlook.com 2023-06-08T18:44:14.562Z 08DB683D48AB36FA]Message rejected by:DM3NAM06FT006.mail.protection.outlook.com | Error: | 550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [DM3NAM06FT006.Eop-nam06.prod.protection.outlook.com 2023-06-08T18:44:14.562Z 08DB683D48AB36FA] | Message rejected by: | DM3NAM06FT006.mail.protection.outlook.com
Error: | 550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [DM3NAM06FT006.Eop-nam06.prod.protection.outlook.com 2023-06-08T18:44:14.562Z 08DB683D48AB36FA]
Message rejected by: | DM3NAM06FT006.mail.protection.outlook.com

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe5c21b-2296-8b5c-208a-f41eb967c24e
* Version Independent ID: c3722063-7455-5ba9-a78d-102823dfd474
* Content: [Move users to Microsoft Edge from Internet Explorer - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#why-is-a-website-added-to-the-ie-compatibility-list)
* Content Source: [microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#44981501

**Comment by captainbrosset** [comment]
Thanks for filing this. Let me make sure this goes onto our team's roadmap for investigation and fixing.

**Comment by Reezaali** [comment]
Hi @nattrass - the email address is up and running again. Thanks so much for reporting this issue.
