### ISSUE TITLE
Missing information for "Emulates Microsoft-recommended hardware and network performance presets."

### ISSUE THREAD

**Issue by wiolsen** [MicrosoftDocs/edge-developer#2634]
The documentation mentions "Emulates Microsoft-recommended hardware and network performance presets."

But it does not describe what those are, or provide any links to further information.

I have been using this feature in my development, and I notice a significant slow down on certain pages.  How should I interpret this, if I do not know the actual hardware and network performance preset that are in being emulated?  Would these performance issues affect a small percentage of users?  A large percentage of users?  Only mobile users?  etc.

Here is the specific section of the page I am refering to:
https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/experimental-features/#emulate-microsoft-recommended-hardware-and-network-performance-presets

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01833e0f-3c21-f31c-dc62-531dc2fc25a0
* Version Independent ID: 18503934-9175-e4f5-5135-e0dc1953a896
* Content: [Experimental features - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/experimental-features/#emulate-microsoft-recommended-hardware-and-network-performance-presets)
* Content Source: [microsoft-edge/devtools-guide-chromium/experimental-features/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/experimental-features/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#45008815

**Comment by captainbrosset** [comment]
Thanks for the question. I'll flag this up for the team to improve the documentation based on your feedback.

**Comment by captainbrosset** [comment]
This experiment was added by mistake and has now been removed.
