### ISSUE TITLE
The email address on this website doesn't work

### ISSUE THREAD

**Issue by spurimpact** [MicrosoftDocs/edge-developer#2646]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe5c21b-2296-8b5c-208a-f41eb967c24e
* Version Independent ID: c3722063-7455-5ba9-a78d-102823dfd474
* Content: [Move users to Microsoft Edge from Internet Explorer - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#why-is-a-website-added-to-the-ie-compatibility-list)
* Content Source: [microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for your message. We are aware of this issue and are tracking it already via issue #2632.
I'll close this one as a duplicate for now.
Thanks again.
