### ISSUE TITLE
can you add PWA application Link Handling for bing chat website?

### ISSUE THREAD

**Issue by bigplayer-ai** [MicrosoftDocs/edge-developer#2647]
can you add PWA application Link Handling for bing chat website?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9788272c-700b-9e60-d419-0f845a1ff644
* Version Independent ID: 4e4fbf06-2d8e-bb66-ee1b-07f9d32a940e
* Content: [Handle links to your Progressive Web Apps - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-urls)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/handle-urls.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/handle-urls.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Sorry if I'm misunderstanding this, but it feels to me like this is feedback about Bing. I think the Bing team would be interested in hearing about it. This repository here is about the documentation of various Microsoft Edge developer features only. Not about Bing.

I would advise giving the Bing team your feedback by doing the following: Go to bing.com > Find the **Feedback** link at the bottom of the web page by scrolling down > Click the link > Fill in your feedback and press **Send**.
