### ISSUE TITLE
_manifest.json should not have the underscore

### ISSUE THREAD

**Issue by clemens-tolboom** [MicrosoftDocs/edge-developer#2651]
```
└── part1
    ├── _manifest.json <====== has an underscore
    ├── icons
    │   ├── nasapod16x16.png
    │   ├── nasapod32x32.png
    │   ├── nasapod48x48.png
    │   └── nasapod128x128.png
    ├── images
    │   └── stars.jpeg
    └── popup
        └── popup.html
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d70c4902-5246-ea94-a95f-f4ac94611c4c
* Version Independent ID: c7f1c45d-32ad-90f7-bfd6-d44ecd2bc941
* Content: [Create an extension tutorial, part 1 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension?tabs=v3)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#45117000

**Comment by captainbrosset** [comment]
Thanks for filing this. Looks like @mikehoffms is already on it in #2653.

**Comment by captainbrosset** [comment]
The PR mentioned previously has now been merged. The fix should be live any minute now.

**Comment by clemens-tolboom** [comment]
👍
