### ISSUE TITLE
No '\' needed after $(SolutionDir) as it already has it. 

### ISSUE THREAD

**Issue by namar0x0309** [MicrosoftDocs/edge-developer#266]
No '\' needed after $(SolutionDir) as it already has it. 

so it should be:

copy "$(SolutionDir)packages\Microsoft.Web.WebView2.2.0.8.149\build\native\$(PlatformTarget)\WebView2Loader.*" "$(OutDir)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c3ae57-a8c8-4615-7dcf-855e006a4043
* Version Independent ID: 39480ab3-700f-9151-cd72-a12aba59c63d
* Content: [Microsoft Edge WebView 2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/gettingstarted#feedback)
* Content Source: [microsoft-edge/hosting/webview2/GettingStarted.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/hosting/webview2/GettingStarted.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by liminzhu** [comment]
Thanks for reporting this! I've lumped a fix for this in another PR. https://github.com/MicrosoftDocs/edge-developer/pull/268

**Comment by liminzhu** [comment]
Resolved by https://github.com/MicrosoftDocs/edge-developer/pull/268
