### ISSUE TITLE
Invalid Email Address

### ISSUE THREAD

**Issue by winstonfwilliams** [MicrosoftDocs/edge-developer#2667]
The email address (mailto:ietoedge@microsoft.com) to add domains to the "Internet Explorer compatibility list" is invalid.  We have attempted to email our list multiple times.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe5c21b-2296-8b5c-208a-f41eb967c24e
* Version Independent ID: c3722063-7455-5ba9-a78d-102823dfd474
* Content: [Move users to Microsoft Edge from Internet Explorer - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#why-is-a-website-added-to-the-ie-compatibility-list)
* Content Source: [microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out, and sorry about the inconvenience. This issue is known and tracked at #2632. We're working on it and will make sure to update that other issue as soon as we can.
