### ISSUE TITLE
Emulate mobile devices (Device Emulation) not work 

### ISSUE THREAD

**Issue by KaratLee** [MicrosoftDocs/edge-developer#2673]
[Enter feedback here]
Enter the mobile emulator mode according to the following document, the result prompts 'Hmm, your browser version is not support'.
I've tried both Chrome and Microsoft Teams, same result. Not just me, many colleagues like this.

MacOS version: 13.4 (22F66)
Chrome version: 114.0.5735.133 (Official Build) (arm64)
Microsoft Edge version: 114.0.1823.41 (Official build) (arm64)

https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/
![image](https://github.com/MicrosoftDocs/edge-developer/assets/37133480/19de370f-d06c-43a2-9dba-7fac21e487eb)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b9be124-0391-f845-4998-5a4d195db34b
* Version Independent ID: 07f3fe21-5c70-ae77-d992-7ada8b24df06
* Content: [Emulate mobile devices (Device Emulation) - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/)
* Content Source: [microsoft-edge/devtools-guide-chromium/device-mode/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/device-mode/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by KaratLee** [comment]
@captainbrosset I want to use the mobile development mode on Teams. I remember that there was no download prompt before.

**Comment by captainbrosset** [comment]
In that case, I think the right next step would be to get in touch with the Teams team instead. The mobile emulation tool isn't causing the download prompt, Teams is doing this.
It appears you came here after reporting the issue with them already: https://github.com/MicrosoftDocs/msteams-docs/issues/8920
I'm so sorry for ping-pong'ing you around like this, but I think there's a chance your issue wasn't correctly understood on that repo. Let me drop a comment there to try and help.
