### ISSUE TITLE
Edge Sidebar PWA documentation not working

### ISSUE THREAD

**Issue by sandrohanea** [MicrosoftDocs/edge-developer#2675]
**Link to the documentation page**: [The URL to the page.](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/sidebar.md)

**Description of the issue**: Followed this documentation using all insider edge browsers. 
For the Canary (the one specified in the instructions) , there is no "Add Current page" as in the documentation but this view:
![image](https://github.com/MicrosoftDocs/edge-developer/assets/40202887/1d408ea6-e685-4a6d-8130-27ea5365fc9a)

I chose "Open in sidebar" button but couldn't manage to install it as a PWA in the edge browser, it just installs as a site:
![image](https://github.com/MicrosoftDocs/edge-developer/assets/40202887/359c5a69-cf7e-4409-8e04-ddea897b8fb3)

Same behavior was also with edge dev and edge beta, the only difference was that I had the "Add current page" button => but still install it as a site, not as an App.

I confirm I started all these versions using: ` .\msedge.exe --enable-features=msWebAppManifestSidePanel,msAddEdgeSidePaneBrandUA`

Also, if I navigate to edge://settings/sidebar I can see that pwamp is a site, not an app:
![image](https://github.com/MicrosoftDocs/edge-developer/assets/40202887/7a3e4079-53b4-4ffc-a3ae-4c23cab2228b)

AB#45386588

**Comment by captainbrosset** [comment]
Thanks for the feedback, and sorry about the delay. I've marked this as part of our backlog, and we'll make sure to investigate and fix the app and/or docs accordingly.
