### ISSUE TITLE
Add documentation link to the Repo page

### ISSUE THREAD

**Issue by pankajparashar** [MicrosoftDocs/edge-developer#2685]
I find myself switching between this Github repo page and the documentation page often. It would be nice to have the link to the documentation added to this Github repository page.

Like this,
<img width="688" alt="github com_MicrosoftDocs_edge-developer" src="https://github.com/MicrosoftDocs/edge-developer/assets/38640616/796a484c-c45b-460b-bbce-d72bf777a3a7">

**Comment by captainbrosset** [comment]
Excellent suggestion Pankaj. I'll add it now.
