### ISSUE TITLE
Like in firefox please implement in in edge console so that when we type console.log the parenthesis automatically come after typing log in console.log

### ISSUE THREAD

**Issue by RudrangsuChoudhury** [MicrosoftDocs/edge-developer#2687]
Like in firefox please implement in in edge console so that when we type console.log the parenthesis automatically come after typing log in console.log

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c6cd94a-404d-5ce5-91da-575d7af01b8c
* Version Independent ID: 1fc9a95f-6db4-77bf-048f-52903f62cc4f
* Content: [Keyboard shortcuts - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/shortcuts/)
* Content Source: [microsoft-edge/devtools-guide-chromium/shortcuts/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/shortcuts/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for your feedback. This repository, however, is only for the documentation of DevTools, not for DevTools itself.
Could you please, re-submit your feedback over on the DevTools repository here instead: https://github.com/MicrosoftEdge/DevTools ?

That would be fantastic! Thanks, and sorry about the inconvenience.
