### ISSUE TITLE
64 bit Edge Chromium installs to x86 Program Files

### ISSUE THREAD

**Issue by teetime514** [MicrosoftDocs/edge-developer#269]
The 64 bit Edge Chromium installs to

C:\Program Files (x86)\Microsoft\Edge Dev\Application

instead of

C:\Program Files\Microsoft\Edge Dev\Application

**Comment by Reezaali** [comment]
Hi @teetime514 I'll go ahead and close this issue now. You can leave feedback using Alt+Shift+I. Thank you.
