### ISSUE TITLE
can we automate the login for a msft authenticated website through this?

### ISSUE THREAD

**Issue by Akpandita** [MicrosoftDocs/edge-developer#2708]
Hey Team,

wanted to know if we can use selenium to automate the login process for this website?
https://partner.microsoft.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2db99e-eee9-7078-5955-c955696cc75d
* Version Independent ID: 2b2db99e-eee9-7078-5955-c955696cc75d
* Content: [Contact the Microsoft Edge WebDriver team - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/contact)
* Content Source: [microsoft-edge/webdriver-chromium/contact.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/contact.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out. However, this repository is only about the documentation, not how the product works. Therefore, could you please open a new issue for this over on the dedicated Microsoft Edge WebDriver repository?

Here is the link: https://github.com/MicrosoftEdge/EdgeWebDriver/issues/new

Thanks for your understanding.
