### ISSUE TITLE
WebView2 Stopped working after installing some NuGet packages

### ISSUE THREAD

**Issue by EvilYtGuy** [MicrosoftDocs/edge-developer#2710]
WebView2 Stopped working after installing some NuGet packages. 
I don't know which package triggered it, but I have the following installed:
-Costura.Fody
-Newtonsoft.Json
(-WebView2)
I have also updated all of them.

The error:
Severity Code Description Project File Line Suppression State
Error XDG0003 The file or assembly "Microsoft.Web.WebView2.Wpf, Version=1.0.1823.32, Culture=neutral, PublicKeyToken=2a8ab48044d2601e" or one of its dependencies was not found. The system cannot find the specified file. Program D:\VS2022\Program\MainWindow.xaml 11

Everything is present and up to date. Therefore, I request assistance.

**Comment by captainbrosset** [comment]
Thank you for reaching out. This question is specific to the WebView2 product, not its documentation. Therefore, could you please open a new issue for this over on the dedicated WebView2Feedback repository?

Here is the link: https://github.com/MicrosoftEdge/WebView2Feedback/issues/new

Thanks for your understanding.
