### ISSUE TITLE
contributing guidelines and code of conduct

### ISSUE THREAD

**Issue by Kova36** [MicrosoftDocs/edge-developer#2711]
[msedgedevrel]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9046489c-0435-15c2-114f-1bd99ac3a58e
* Version Independent ID: a6f1022e-0029-75d4-6c9b-b1f2c145d791
* Content: [Port a Chrome extension to Microsoft Edge - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension?source=recommendations)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
