### ISSUE TITLE
Page seems to contradict itself

### ISSUE THREAD

**Issue by chrissyast** [MicrosoftDocs/edge-developer#2716]
> If you're a GitHub user, you don't need to create a new Microsoft account (MSA) and remember extra passwords. You can use GitHub authentication to sign into Partner Center and publish your Microsoft Edge extensions to the [Microsoft Edge](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home/)

then later...

> You'll need to link your GitHub account to a Microsoft account (MSA), as described in the following steps. The Microsoft account (MSA) will be created for you if necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63070130-9155-88e0-f4c6-9fce27abf81d
* Version Independent ID: 4b770fca-c029-c3c1-da2a-8a9cfe961e53
* Content: [Publish a Microsoft Edge extension by using a GitHub account - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/github)
* Content Source: [microsoft-edge/extensions-chromium/publish/github.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/publish/github.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#45589353

**Comment by captainbrosset** [comment]
Thanks for reaching out. I'll try to find someone to help understand this in more details (and potentially update the docs).

**Comment by captainbrosset** [comment]
I got a bit more information about this. You shouldn't need to do any linking from your end. MSA is mandatory for the Edge extensions program. When registering through GitHub, an MSA is automatically created and linked for you in the backend. From your perspective, you should just need to register using your GitHub credentials.

I hope this helps.

I'll try to clarify the docs too, so keeping this issue open until I do.
