### ISSUE TITLE
Autenticador 

### ISSUE THREAD

**Issue by feccruz** [MicrosoftDocs/edge-developer#2723]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4edd411d-e52a-32ef-e539-fb4ed709c86c
* Version Independent ID: 9b96eeb9-accc-7230-20b1-b704d9f9a79e
* Content: [Overview of Microsoft Edge extensions - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/#the-featured-badge)
* Content Source: [microsoft-edge/extensions-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
