### ISSUE TITLE
[DevTools Docs Feedback]

### ISSUE THREAD

**Issue by Teamwolf9Nlsnightcore9** [MicrosoftDocs/edge-developer#2727]
Is it possible to use this for Roblox studio if you can’t get a hold of your Apple ID because it one day just wasn’t there anymore and you didn’t have it put in a password on paper and you didn’t remember it

**Comment by captainbrosset** [comment]
I'm sorry but your issue doesn't contain enough information for us to help. What specific article in our docs is this about?
