### ISSUE TITLE
This template does not work

### ISSUE THREAD

**Issue by sethreidnz** [MicrosoftDocs/edge-developer#273]
I am using Visual Studio 2017 and I have tried the steps above. When I try to build the project, with a valid website as a url it doesn't work and give me the error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project must have a reference to an application. Please add a reference under the 'Applications' node in the Solution Explorer.	PatternBlockDemo.Uwp1	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets	173	

Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c306f3b9-d287-beba-eb3b-513e58df2440
* Version Independent ID: 787855c5-24d2-b772-e4c3-ce43118e5adb
* Content: [Tailor your PWA for Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/windows-features)
* Content Source: [microsoft-edge/progressive-web-apps/windows-features.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/windows-features.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Ramakrishna44** [comment]
I am getting the same error

**Comment by AlRosenthal** [comment]
I'm getting the same issue on build.

**Comment by lworkman** [comment]
If you're on an older version of Visual Studio, you need to use a different project template. It's confusing since they have the same name.

For instance, I'm on Visual Studio 2017, and I needed to use the "Hosted Web App (Universal Windows)" project template.

**Comment by sethreidnz** [comment]
While that might be true, the new version doesn't even have the type that we are talking about. The "Hosted Web App (Universal Windows)" appears to now be depreciated. Even though this article says to use it. So it's pretty unclear what you are supposed to do.

**Comment by davidtimovski** [comment]
There appears to be only one template where this error doesn't happen:
Other Languages -> JavaScript -> Progressive Web App (Universal Windows).

**Comment by mwalol** [comment]
is there any work around to by pass this error?
i'm using the last Visual Studio 2019

**Comment by davrous** [comment]
Hi! The Hosted Web App / Progressive Web App template is only available with Visual Studio 2017, we removed support for it in Visual Studio 2019. We renamed it from Hosted Web App (HWA) to Progressive Web App (PWA) during the life of VS2017 but it is the exact same template.

Regarding the error you have, I've not sure exactly when you have it. Is it right after creating the project in VS2017? After running the solution? Did you create a JavaScript -> Windows Universal -> Progressive Web App (Universal Windows) project?

![image](https://user-images.githubusercontent.com/933018/78659241-8b5c5600-78cb-11ea-81a8-9eed90980133.png)

**Comment by mwalol** [comment]
i have fixed the issue using this solution : 

https://github.com/MicrosoftDocs/edge-developer/issues/252#issuecomment-598139288

**Comment by captainbrosset** [comment]
Apologies for this issue having gotten stale. I have read through the comments, and I don't think there is something actionable to do here anymore. So I will be closing this issue, but please feel free to re-open a new one if there is still an issue with the Edge documentation site regarding the above discussion.
