### ISSUE TITLE
Experimental Edge Features

### ISSUE THREAD

**Issue by DigitalTherapy** [MicrosoftDocs/edge-developer#2732]
I'd like to enroll in the Origin trials for edge browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd0c252f-0ce0-55f8-480e-27dbed99ec16
* Version Independent ID: f64a4dac-d25d-30ac-1188-4184b1e8239f
* Content: [Experimental features and origin trials - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/origin-trials#enroll-your-site-in-an-origin-trial)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/origin-trials.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/origin-trials.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Here is our documentation about Origin Trials in Microsoft Edge: https://learn.microsoft.com/en-us/microsoft-edge/origin-trials/
Closing this issue now. Let me know if this article isn't helpful enough.
