### ISSUE TITLE
Where is "To enable widget support in Microsoft Edge for users of your production PWA, enroll your site in the Web App Widgets origin trial."  ?

### ISSUE THREAD

**Issue by tanmay-veer** [MicrosoftDocs/edge-developer#2749]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a0e6a65-5e0a-55cc-d3c8-b4fdd37a2d2b
* Version Independent ID: 1a0e6a65-5e0a-55cc-d3c8-b4fdd37a2d2b
* Content: [Build PWA-driven widgets - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/widgets#enable-widgets-for-your-users)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/widgets.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/widgets.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#45803802

**Comment by captainbrosset** [comment]
Thanks a lot for reporting this. I'll make sure this issue is part of our backlog so we can prioritize it and fix it.

**Comment by captainbrosset** [comment]
The origin trial ended in Edge 114 and the feature was enabled in Edge 115, so the flag is no longer needed. I'll make sure to remove it from the documentation (sorry we missed this).

**Comment by captainbrosset** [comment]
Oh you can certainly contribute to the docs! We very much welcome external contributions via this GitHub repo.
Now, for this particular issue, I've already opened a PR (#2753) to remove the experimental flag and origin trial from the Widgets doc.

But, if you want to contribute to other pages, please feel free to do so. We have a contribution guide here which should be helpful: https://github.com/MicrosoftDocs/edge-developer/blob/main/CONTRIBUTING.md

**Comment by captainbrosset** [comment]
PWAs can create their own widgets for the Windows widgets board. So if devdocs.io created its own widget, then you'd be able to pin it to the widgets board in Windows.
So you can't have widget for just any PWA, just for those that created a widget (by using their manifest file).
