### ISSUE TITLE
Fix in "Example: Monitoring the requests and responses via the WebResourceResponseReceived event"

### ISSUE THREAD

**Issue by EDeLeon9** [MicrosoftDocs/edge-developer#2752]
In the example of the section **Example: Monitoring the requests and responses via the WebResourceResponseReceived event** there is the first line: _WebView.WebResourceResponseReceived += WebView_WebResourceResponseReceived;_ and it should be **_WebView.CoreWebView2.WebResourceResponseReceived += CoreWebView2_WebResourceResponseReceived;_**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9acfedb-38dd-88a1-3c87-f9109eebbd2b
* Version Independent ID: b9acfedb-38dd-88a1-3c87-f9109eebbd2b
* Content: [Custom management of network requests - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webresourcerequested?tabs=dotnet#example-monitoring-the-requests-and-responses-via-the-webresourceresponsereceived-event)
* Content Source: [microsoft-edge/webview2/how-to/webresourcerequested.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/webresourcerequested.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#45821031

**Comment by captainbrosset** [comment]
Thanks for filing this and suggesting a fix. I'll flag this for our team to review and fix the docs.
