### ISSUE TITLE
journey begin

### ISSUE THREAD

**Issue by shaff0** [MicrosoftDocs/edge-developer#2757]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd1b8fb-2741-3867-b865-c1d02b2d197d
* Version Independent ID: 6185c1db-6124-1966-7f92-cd24d349f08c
* Content: [Inspect and modify CSS animation effects - Microsoft Edge Development](https://learn.microsoft.com/en-gb/microsoft-edge/devtools-guide-chromium/inspect-styles/animations)
* Content Source: [microsoft-edge/devtools-guide-chromium/inspect-styles/animations.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/inspect-styles/animations.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikehoffms** [comment]
Thanks for test issue.  Closing.
