### ISSUE TITLE
test

### ISSUE THREAD

**Issue by ichalibrahim** [MicrosoftDocs/edge-developer#2759]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 028bc212-b336-c856-d96a-23316e54f8a6
* Version Independent ID: 0cd83087-5264-1c5a-2164-543751a3594a
* Content: [Automatically test a webpage for accessibility issues - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/accessibility/test-issues-tool#verify-that-images-have-alt-text)
* Content Source: [microsoft-edge/devtools-guide-chromium/accessibility/test-issues-tool.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/accessibility/test-issues-tool.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikehoffms** [comment]
Thanks for test.  Closing.
