### ISSUE TITLE
ExecuteScript method invocation prevents rendering

### ISSUE THREAD

**Issue by OllieJones** [MicrosoftDocs/edge-developer#276]
Following your instructions (on VS2017), if this line is in my app : `webviewWindow-&gt;ExecuteScript(L"alert(\'foo\');", nullptr);`
the webpage fails to render.  I don't see any exception thrown.

I get the same failure to render if I try to use AddScriptToExecuteOnDocumentCreated to show an alert.

Is there, possibly, some race condition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c3ae57-a8c8-4615-7dcf-855e006a4043
* Version Independent ID: 39480ab3-700f-9151-cd72-a12aba59c63d
* Content: [Microsoft Edge WebView 2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/gettingstarted#feedback)
* Content Source: [microsoft-edge/hosting/webview2/GettingStarted.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/hosting/webview2/GettingStarted.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by liminzhu** [comment]
Thanks for reporting the issue and sorry for seeing it just now @OllieJones. Yes this is due to a race condition where alert is being executed before the first page navigation happens, and that alert somehow requires user interaction before first navigation to another page, which causes the page to hang.

I've changed the sample to remove alert since then.

**Comment by tholp** [comment]
I have also found this issue (without seeing this report).
If you move the ExecuteScript call into a NavigationCompleted event handler then it will work.
(The opposite is the case for the AddScriptToExecureOnDocumentCreated calls).

**Comment by pagoe-msft** [comment]
Moved issue to our WebView feedback repo here: https://github.com/MicrosoftEdge/WebViewFeedback/issues/154
