### ISSUE TITLE
Unity 2020.3.40 - Webview preview 0.17.1-pre.5 compilation problem

### ISSUE THREAD

**Issue by RubenGarcia** [MicrosoftDocs/edge-developer#2762]
The tutorial screenshot indicates Webview 0.19.0 is available, but on Unity 2020.3.40, only version 0.17.1-pre.3 and 5 are shown.
Installing version 0.17.1-pre.5 gives me
```
Library\PackageCache\com.microsoft.mixedreality.webview.unity@dc3360005667\Runtime\Editor\EditorWebView.cs(19,70): error CS8124: Tuple must contain at least two elements.
Library\PackageCache\com.microsoft.mixedreality.webview.unity@dc3360005667\Runtime\Editor\EditorWebView.cs(19,71): error CS1526: A new expression requires (), [], or {} after type
```

Please create a 0.17.1-pre.6 which fixes this issue, or ensure that 0.19.0 is compatible with Unity 2020.3.40

FYI, 0.17.1.pre3 compiles.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76a8da9c-3c3c-bc28-5c70-7e5e5c7a9409
* Version Independent ID: 76a8da9c-3c3c-bc28-5c70-7e5e5c7a9409
* Content: [Get started with WebView2 in HoloLens 2 Unity apps (Preview) - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/hololens2)
* Content Source: [microsoft-edge/webview2/get-started/hololens2.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/hololens2.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#45928861

**Comment by mikehoffms** [comment]
Related Issue: https://github.com/MicrosoftDocs/edge-developer/issues/2772

**Comment by GLARKI** [comment]
Is there a Unity version where we can use the Webview 0.19.0 and Prefab WebView2 ?

My question would be: Is there a good tutorial/example on how to create an input system to navigate on the webpage itself (i.e. scroll the page) for the HL2? 

Based on https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/hololens2 I assume I have to make this myself, I still consider myself a novice programmer, I wonder if anyone has advice regarding the input system to interact with the webpage?

<img width="610" alt="image" src="https://github.com/MicrosoftDocs/edge-developer/assets/115214302/8fdb1f08-3060-4984-a9b5-6ffe003186eb">

**Comment by michaelfarnsworth** [comment]
@GLARKI improving documentation and samples around input is definitely on our radar. We've recently--earlier this week--push a small update to the GettingStarted sample app, which implements some basic pointer-up/down handling. Hopefully, that will help get you started.

**Comment by GLARKI** [comment]
Thanks for all the kind replies! I will definitely give it a try over the following weeks.

**Comment by mikehoffms** [comment]
[PR 2773](https://github.com/MicrosoftDocs/edge-developer/pull/2773) that fixes this Issue is live (Change "WebView2 prefab" to "WebView prefab" for HoloLens/Unity).  
eg:
* [https://learn.microsoft.com/microsoft-edge/webview2/get-started/hololens2#step-4---install-the-webview-plugin-for-unity-by-using-the-mixed-reality-feature-tool](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/hololens2#step-4---install-the-webview-plugin-for-unity-by-using-the-mixed-reality-feature-tool) -- png now shows 0.17, not 0.19.
* https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/hololens2#step-5---set-up-the-webview-prefab-in-unity-scene - Heading now reads "Step 5 - Set up the WebView prefab in Unity scene" not "Step 5 - Set up the WebView2 prefab in Unity scene".

**Comment by RubenGarcia** [comment]
@mikehoffms Hello, your patch only fixes half of the issue.
The second half (and arguably the most important) is that 0.17.1-pre.5 does not compile. 
I understand that the second part should be a new issue in a different repository; do you know where the source code for WebView2 is located?

**Comment by GLARKI** [comment]
Webview example compiles fine for uwp on my laptop. Prefab webview2 is non
existing, and the input is tricky. But the example works. Maybe retry the
steps one more time?

What is the compile error?

Kind regards

**Comment by RubenGarcia** [comment]
Compile error is
```
Library\PackageCache\com.microsoft.mixedreality.webview.unity@dc3360005667\Runtime\Editor\EditorWebView.cs(19,70): error CS8124: Tuple must contain at least two elements.
Library\PackageCache\com.microsoft.mixedreality.webview.unity@dc3360005667\Runtime\Editor\EditorWebView.cs(19,71): error CS1526: A new expression requires (), [], or {} after type
```
for version 0.17.1-pre.5

**Comment by mikehoffms** [comment]
"the second part should be a new issue in a different repository"
@RubenGarcia - the article
https://learn.microsoft.com/microsoft-edge/webview2/contact
links to the repo:
https://github.com/MicrosoftEdge/WebViewFeedback
where you can open an issue or search the issues.

**Comment by RubenGarcia** [comment]
Done
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3726
