### ISSUE TITLE
Wrong screenshot

### ISSUE THREAD

**Issue by HO-COOH** [MicrosoftDocs/edge-developer#2775]
[This section](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug-visual-studio#open-devtools-using-an-approach-other-than-f12) posted a wrong screenshot from visual studio code, which is supposed to be visual studio. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

AB#45948351

**Comment by mikehoffms** [comment]
Notes:
The linked article section is:
"Open DevTools using an approach other than F12" in "Debug WebView2 apps with Visual Studio".
https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug-visual-studio#open-devtools-using-an-approach-other-than-f12

There's no screenshot in that linked section.

@HO-COOH - What is the .png filename?

**Comment by HO-COOH** [comment]
@mikehoffms 
![image](https://github.com/MicrosoftDocs/edge-developer/assets/42881734/74b1ee4f-76a0-48c4-96dd-f332377bcafb)

https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug-visual-studio-images/console.png

**Comment by mikehoffms** [comment]
Public preview of article section from PR 3233: bottom screenshot (Visual Studio 2022, not VS Code), along with the specific steps and screenshots that produce it:
https://github.com/MicrosoftDocs/edge-developer/blob/user/mikehoffms/png-wv2-debug-vs/microsoft-edge/webview2/how-to/debug-visual-studio.md#debug-your-webview2-app
@HO-COOH @captainbrosset

**Comment by captainbrosset** [comment]
Fixed by #3233.
