### ISSUE TITLE
Error in code sample: error CS0103: The name 'PointerEvent' does not exist in the current context

### ISSUE THREAD

**Issue by RubenGarcia** [MicrosoftDocs/edge-developer#2777]
There is probably a missing using directive; please fix.
```
error CS0103: The name 'PointerEvent' does not exist in the current context
error CS0103:  The name 'PointerButton' does not exist in the current context
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76a8da9c-3c3c-bc28-5c70-7e5e5c7a9409
* Version Independent ID: 76a8da9c-3c3c-bc28-5c70-7e5e5c7a9409
* Content: [Get started with WebView2 in HoloLens 2 Unity apps (Preview) - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/hololens2)
* Content Source: [microsoft-edge/webview2/get-started/hololens2.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/hololens2.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#45948334

**Comment by mikehoffms** [comment]
@RubenGarcia - which section of the article has the related code listing, is it the following code listing? 

https://learn.microsoft.com/microsoft-edge/webview2/get-started/hololens2#add-code-to-hook-up-the-buttons

**Comment by RubenGarcia** [comment]
No, quite below that,
https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/hololens2#input
this code:
```
using Microsoft.MixedReality.WebView;

public class WebViewExample : MonoBehaviour, IPointerDownHandler
{
    // WebView setup steps skipped for brevity

    public void OnPointerDown(PointerEventData eventData)
    {
        IWithMouseEvents mouseEventsWebView = webView as IWithMouseEvents;

        // Call hypothetical function which converts the event's x, y into the WebView2's coordinate space.
        var hitCoord = ConvertToWebViewSpace(eventData.position.x, eventData.position.y);

        WebViewMouseEventData mouseEvent = new WebViewMouseEventData
        {
            X = hitCoord.x,
            Y = hitCoord.y,
            Type = PointerEvent.PointerDown,
            Button = PointerButton.Left,
            TertiaryAxisDeviceType = WebViewMouseEventData.TertiaryAxisDevice.PointingDevice
        };

        // Propagate the event to the WebView plugin.
        mouseEventsWebView.MouseEvent(mouseEvent);
    }
}
```

**Comment by RubenGarcia** [comment]
This is the correct code
```
            Type = WebViewMouseEventData.EventType.MouseDown,
            Button = WebViewMouseEventData.MouseButton.ButtonLeft,
```
derived from the documentation at
https://learn.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/webview2-plugin-mouse-event-data-class

**Comment by mikehoffms** [comment]
@RubenGarcia - thanks.
https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/hololens2#input now reads:
Type = WebViewMouseEventData.EventType.MouseDown,
Button = WebViewMouseEventData.MouseButton.ButtonLeft,
