### ISSUE TITLE
canva

### ISSUE THREAD

**Issue by Dex-Lab27** [MicrosoftDocs/edge-developer#2779]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 742f11d6-f1b0-e63e-ec19-7f9bf39ff885
* Version Independent ID: 742f11d6-f1b0-e63e-ec19-7f9bf39ff885
* Content: [Debug DOM memory leaks with the Detached Elements tool - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks?source=recommendations)
* Content Source: [microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#45950171

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
