### ISSUE TITLE
Error after Click the "Display" Button

### ISSUE THREAD

**Issue by eviluess** [MicrosoftDocs/edge-developer#2781]
[Enter feedback here]
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
extension://oefnhlajdgnmdobknobmbnpnjmnigcck/popup/popup.html
Trace Stack: popup/popup.html:0
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec889040-6707-74fd-9086-d838c15a9172
* Version Independent ID: 73d6355a-b256-c8ab-9889-c51603d3052b
* Content: [Create an extension tutorial, part 2 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts?tabs=v3)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
