### ISSUE TITLE
Double Title for "general shortcuts"

### ISSUE THREAD

**Issue by fschoenfeldt** [MicrosoftDocs/edge-developer#279]
The Title "General Shortcuts" Appears twice with the same text. Screenshot: https://imgur.com/a/C5UxPIa 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7708ebf-b89b-168e-de02-bb00e9223318
* Version Independent ID: 48a20484-21fe-cbd3-7b84-f1992002eb63
* Content: [Microsoft Edge (EdgeHTML) Developer Tools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide#feedback)
* Content Source: [microsoft-edge/devtools-guide.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by jm-trd-ms** [comment]
Closed. https://github.com/MicrosoftDocs/edge-developer/pull/499
