### ISSUE TITLE
stackoverflow on Redstone4 10.0.17134

### ISSUE THREAD

**Issue by DexterWoo** [MicrosoftDocs/edge-developer#280]
this event is causing stackoverflow issue on RS4 system with external webview process.
but working on RS5, any idea to workaround this issue on RS4 systems?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c41a6a0e-7655-e936-fbac-f2c33e3372f2
* Version Independent ID: 9024b5a7-96bf-2d2e-be33-b9956f663939
* Content: [WebResourceRequestedEvent object - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview/webresourcerequestedevent)
* Content Source: [microsoft-edge/hosting/webview/WebResourceRequestedEvent.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/hosting/webview/WebResourceRequestedEvent.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by pagoe-msft** [comment]
@DexterWoo, Moving this issue to our specific WebView feedback repo over here:

https://github.com/MicrosoftEdge/WebViewFeedback/issues/152
