### ISSUE TITLE
Guidance on how to write the chrome_native_messaging_host.exe would be very helpful.

### ISSUE THREAD

**Issue by BenKey** [MicrosoftDocs/edge-developer#2802]
This is an excellent and well written document. It answers most of the questions about native messaging. Unfortunately, like so many other resources on this subject, it leaves the most important question unanswered. How do you actually write the chrome_native_messaging_host.exe application?

This document makes it clear that `stdin` and `stdout` are used to communicate with the host. However some vital information is left out.

* How is the information sent from the extension encoded? I have some information that suggests the first four bytes is a number that specifies packet length and the rest may be the packet data encoded as JSON but I am not certain of this.
* How to encode the information that is sent back to the extension?
* How does the chrome_native_messaging_host.exe application know when to exit?

A brief section on writing the chrome_native_messaging_host.exe application with a few code examples in different programming languages would be very useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6baf3ba3-2850-707d-fdfc-9b65f88655c7
* Version Independent ID: 661b537b-bba6-cb07-9979-cddcc35421e3
* Content: [Native messaging - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging?tabs=v3%2Cwindows&source=docs)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/native-messaging.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#46170218

**Comment by captainbrosset** [comment]
Thanks for the detailed request. Adding it to our team's backlog for internal discussions/prioritization.
We'll keep you posted on this issue of any progress.
