### ISSUE TITLE
This topic was very helpful.

### ISSUE THREAD

**Issue by jimgilliam** [MicrosoftDocs/edge-developer#2805]
Thank you for this help topic. The side-by-side comparison of the two technologies really helped me understand which direction works better for my projects.

Off to learn some more!

Jim

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0cf4bb86-b9fc-b4b2-4135-6e3b43587551
* Version Independent ID: 0cf4bb86-b9fc-b4b2-4135-6e3b43587551
* Content: [Develop for the sidebar - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/sidebar)
* Content Source: [microsoft-edge/web-platform/sidebar.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/sidebar.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Glad this was helpful! Thank you for the kind words. Let us know if anything is unclear, and we will try to improve the docs.
