### ISSUE TITLE
Not Found 404

### ISSUE THREAD

**Issue by pixcubeanim** [MicrosoftDocs/edge-developer#281]
When following those steps, i get the message Not Found 404. Basically when Debugging the Code via local host, the Message is: 
The Server has not found matches for the URI (Uniform Resource Identifier). 

GET - http://localhost:1337/

Can someone help me out how to solve this? I cant figure it out, where there could be a mistake happend. 

Ive just followed the steps on: 
https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/get-started
up to the part with including serviceworker files. Everything should be fine.

**Comment by Reezaali** [comment]
Hi @pixcubeanim, I'm sorry it's taken so long for someone to get back to you on this issue. We've updated our getting started content [here ](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/get-started)which may solve your issue. We've also published a service worker topic [here](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/serviceworker). I'll go ahead and close this issue now. Thanks.
