### ISSUE TITLE
SAFA DESIGN STUDIO

### ISSUE THREAD

**Issue by nurersafa007** [MicrosoftDocs/edge-developer#2815]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8701d20e-292e-e12e-5505-91b2b906c64d
* Version Independent ID: 8701d20e-292e-e12e-5505-91b2b906c64d
* Content: [What's new in DevTools (Microsoft Edge 115) - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2023/07/devtools-115#profiling-improvements-for-the-performance-tool)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2023/07/devtools-115.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/whats-new/2023/07/devtools-115.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
