### ISSUE TITLE
Explain when you need to update a PWA in the store

### ISSUE THREAD

**Issue by danielcompton** [MicrosoftDocs/edge-developer#2828]
I've read through https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/microsoft-store and understand how to generate an app from a PWA and publish it to the store.

What I don't understand is when I would need to regenerate the PWA to update it. Looking at the generated app packages, it seems like it is mostly images. I couldn't find much from the actual manifest except from the start-url.

I think it could be good to add a section explaining when you need to update your app. My guess would be that you need to do this:

1. When you want to update assets in the store, or your app icon
2. When you want to update your start-url

Is this correct? Are there more reasons to update a PWA app in the store?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d7f49d04-dd9e-9d95-6bc3-f158e4eacada
* Version Independent ID: 5e3a5695-0978-7051-45d1-623dbb757f22
* Content: [Publish a Progressive Web App to the Microsoft Store - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/microsoft-store)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/microsoft-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/microsoft-store.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#46441487

**Comment by captainbrosset** [comment]
This is a very good point @danielcompton. Let me make sure this issue is tracked on our backlog so we can prioritize it and update the docs.
I think your assumption about when you'd need to update the package in the store is correct, but we'll need to double-check internally with the right team before updating the docs.
