### ISSUE TITLE
tautan

### ISSUE THREAD

**Issue by Johnfrandess** [MicrosoftDocs/edge-developer#2831]
[Ketikkan umpan balik di sini]

---
#### Detail Dokumen

⚠ *Jangan edit bagian ini. Memerlukan penautan masalah learn.microsoft.com ➟ GitHub.*

* ID: 6c1ef1bb-91a3-db70-2e06-b38c1a494bed
* Version Independent ID: 1b4e4189-04a9-f818-32ca-b3056e5fae3f
* Content: [Microsoft Edge DevTools extension for Visual Studio Code - Microsoft Edge Development](https://learn.microsoft.com/id-id/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension)
* Content Source: [microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
