### ISSUE TITLE
Update spec links to OpenSearch

### ISSUE THREAD

**Issue by Malvoz** [MicrosoftDocs/edge-developer#284]
Dev guide: https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/browser-features/search-provider-discovery

In the guide, the link(s): http://go.microsoft.com/fwlink/p/?LinkID=208582 point to http://www.opensearch.org/Specifications/OpenSearch/1.1, however new spec URL is https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md

**Comment by captainbrosset** [comment]
Apologies for this issue having gotten stale. The dev guide mentioned above has been retired and is not available anymore. So I will be closing this issue.
