### ISSUE TITLE
https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider

### ISSUE THREAD

**Issue by FHuq** [MicrosoftDocs/edge-developer#2850]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2ecc9a-c883-9097-bcdc-9f812cbe5d53
* Version Independent ID: 0b2ecc9a-c883-9097-bcdc-9f812cbe5d53
* Content: [Securely debug original code by using Azure Artifacts symbol server source maps - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/consume-source-maps-from-azure)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript/consume-source-maps-from-azure.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/javascript/consume-source-maps-from-azure.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
