### ISSUE TITLE
Improve memory leak examples for modern V8

### ISSUE THREAD

**Issue by victor-homyakov** [MicrosoftDocs/edge-developer#2851]
Documentation page https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots has a few examples of memory leaks:
- here https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots#naming-functions-to-differentiate-between-closures-in-the-snapshot
- and here https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots#demo-webpage-example-7-eval-is-evil

The code to demonstrate easily detectable memory leak looks like

```js
function createLargeClosure() {
    var largeStr = new Array(1000000).join('x');
    var lC = function() {
        return largeStr;
    };
    return lC;
}
```

The problem is that this code does not create large closures anymore.

On modern versions of V8 the code `var largeStr = new Array(1000000).join('x')` creates a string of type `CONS_ONE_BYTE_STRING_TYPE`, which takes only about 600 bytes in memory (concatenation of concatenations of concatenations etc. of a single small string chunk like 'xxxxxxxx') instead of desired million bytes. In order to create really large closure you should use one of methods on string, which convert string into its plain form `ONE_BYTE_STRING_TYPE`. Right now some of those methods are `indexOf('something')`, `slice(1)`, `substring(1)`, `toLowerCase()` (situation may change with the next versions of V8).

The large memory leak example should look like

```js
function createLargeClosure() {
    var largeStr = 'x'.repeat(1000000).toLowerCase(); // ONE_BYTE_STRING_TYPE, takes 1000012 bytes on my machine
    var lC = function() {
        return largeStr;
    };
    return lC;
}
```

Also don't forget to fix similar code on the example page https://microsoftedge.github.io/Demos/devtools-memory-heap-snapshot/example-07.html.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b145f7a-6722-5840-340c-f0b6310f598b
* Version Independent ID: 8aae8eac-9736-b537-b24d-f06fc5a9e27b
* Content: [Record heap snapshots using the Memory tool - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots)
* Content Source: [microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#46865090

**Comment by captainbrosset** [comment]
Thank you for the very detailed report and solution. I will mark this as tracked on our backlog so we can fix the docs soon.
