### ISSUE TITLE
Missing What's New in Devtools pages for Edge 116 & 117

### ISSUE THREAD

**Issue by pankajparashar** [MicrosoftDocs/edge-developer#2853]
**Link to the documentation page**:
https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/whats-new

**Description of the issue**:
I reckon Edge is currently on 117. I was hoping to see What's new in Edge DevTools 116 & 117, which doesn't seem to exist.

**Screenshots**:
<img width="846" alt="image" src="https://github.com/MicrosoftDocs/edge-developer/assets/38640616/01bcb0c8-22ba-4b39-a9d9-c05556d3851d">

**Comment by captainbrosset** [comment]
Correct, we're still working on them. 116 is being drafted in https://github.com/MicrosoftDocs/edge-developer/pull/2803
And we don't yet have a PR for 117.

**Comment by captainbrosset** [comment]
This is not an issue per say. We didn't forget to add them, we just need more time. But this is tracked already. So I'll go ahead and close this issue for now.
