### ISSUE TITLE
WebView2 Tooltips are not displaying in correct location in multi-monitor display

### ISSUE THREAD

**Issue by brigilvincent** [MicrosoftDocs/edge-developer#2861]
Description
When WebView2 window stretched across two monitors, tooltips of DIV displayed in first monitor gets displayed in left edge of second monitor.

Version
WebView2 SDK: 1.0.1901.177
WebView2 Runtime: 115.0.1901.203
Framework: Win32
OS: Win11/Win10

Regression
Was this working before but has regressed? no
If yes, what version did this last work on? na

Repro Steps

Host WebView2 on a Win32 window
Navigate to a page having DIV tooltips based on DIV's "title" attribute
Resize the window to stretch it across two display monitors and try to hover over the DIV to confirm display location of the tooltip
Expected behavior: Tooltip will display in the same position as the corresponding DIV is displayed.

Actual behavior: When the window is positioned based on first monitor, tooltip location is good (i.e. same location as the DIV location). But as soon as the second monitor takes over the window as it's major portion moved over to second monitor (eg: ::MonitorFromWindow starts to return handle to second monitor or the window starts to honor DPI of second monitor), the tooltip displayed in left-most edge of the second monitor even though the DIV is still in first monitor.

Additional Info
![image](https://github.com/MicrosoftDocs/edge-developer/assets/75496442/b18bf386-7034-43ce-92ee-56e0ed719cab)

**Comment by brigilvincent** [comment]
@captainbrosset Thank you for the suggestion. Actually, I opened the issue in WebView2Feedback repository two weeks ago (https://github.com/MicrosoftEdge/WebView2Feedback/issues/3826). As there were no updates there, when reaching out to Microsoft support, received suggestion to open issue here along with the link (https://github.com/MicrosoftDocs/edge-developer/issues/new?title=%5BDevTools%20Docs%20Feedback%5D). 

Any suggestion for getting updates on the bug quicker will be greatly appreciated, as the tooltips of existing web pages broken in multi-monitor displays. Thank you very much for your understanding and help!

**Comment by captainbrosset** [comment]
Apologies about this. The WebView2Feedback repository is the right place for your bug report. The present repo is only for docs, and I'm sorry you got redirected here.

The WebView2Feedback repo does get a log of new issues on a daily basis, and it can take some time for an issue to be worked on. I see your issue was assigned 2 weeks ago to @johna-ms, so that's a sign that it's moving along at least.
