### ISSUE TITLE
Setting DefaultBackgroundColor method for WinUI2&WebView2 seems like needs to be updated

### ISSUE THREAD

**Issue by SnowNooDLe** [MicrosoftDocs/edge-developer#2862]
Hey MS,

Based on the Environment file, I can see within the VS2022 Assembly System.Runtime.Extensions, Version=4.2.1.0

The `Environment` class doesn't seem to have `SetVariable` method. Instead, it now has a method called `SetEnvironmentVariable`

![image](https://github.com/MicrosoftDocs/edge-developer/assets/7849113/9b2f5e0d-6430-4b50-b3af-274acddd459f)

So I think the document needs to be updated from

```scharp
Environment.SetVariable("WEBVIEW2_DEFAULT_BACKGROUND_COLOR", "FF000000");
```

to

```scharp
Environment.SetEnvironmentVariable("WEBVIEW2_DEFAULT_BACKGROUND_COLOR", "FF000000");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0042c10-cb18-e543-95ed-983f62afa37f
* Version Independent ID: 6bc76779-2539-5538-241e-2a9727f52398
* Content: [Get started with WebView2 in WinUI 2 (UWP) apps - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2)
* Content Source: [microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/winui2.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#46971236

**Comment by captainbrosset** [comment]
Thanks so much for reporting this and providing a PR to fix it!

**Comment by SnowNooDLe** [comment]
Thanks for the opportunity 😁
