### ISSUE TITLE
MSWebViewProcess constructor missing description of options parameter

### ISSUE THREAD

**Issue by david-risney** [MicrosoftDocs/edge-developer#288]
The MSWebViewProcess constructor takes an optional MSWebViewProcessOptions

dictionary MSWebViewProcessOptions
{
    DOMString enterpriseId;
    MSWebViewProcessCapabilityState privateNetworkClientServerCapability = "default";
};

enum MSWebViewProcessCapabilityState
{
    "default",
    "disabled",
    "inherited"
};

**Comment by Reezaali** [comment]
@david-risney I'll go ahead and close this issue now. If it should be reopened, please let me know.
