### ISSUE TITLE
kratin.co.in

### ISSUE THREAD

**Issue by suhasinichintalwar123** [MicrosoftDocs/edge-developer#2880]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7d6245e-cf05-572b-fe3b-a76141f4c9d4
* Version Independent ID: b7d6245e-cf05-572b-fe3b-a76141f4c9d4
* Content: [Lighthouse tool - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/lighthouse/lighthouse-tool)
* Content Source: [microsoft-edge/devtools-guide-chromium/lighthouse/lighthouse-tool.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/lighthouse/lighthouse-tool.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
