### ISSUE TITLE
Missing docs for "Add device pixel ratio"

### ISSUE THREAD

**Issue by pankajparashar** [MicrosoftDocs/edge-developer#2887]
**Link to the documentation page**:
https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/

**Description of the issue**:
The device emulation page has no docs about the **Add device pixel ratio** option available under **More options**. Docs for other options like, **Show media queries**, **Set the device type**, etc., are available on the page.

Equivalent docs from the Chrome Devtools documentation,
https://developer.chrome.com/docs/devtools/device-mode/#dpr

**Screenshot:**
<img width="469" alt="Screenshot 2023-10-21 at 23 35 31" src="https://github.com/MicrosoftDocs/edge-developer/assets/38640616/7f725dd7-08e0-4071-8e87-8e8796f781c4">

AB#47199716

**Comment by captainbrosset** [comment]
Thanks a lot for the report Pankaj. Adding to our backlog.
