### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by davidtimovski** [MicrosoftDocs/edge-developer#289]
Small thing but in this section: 
https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/microsoft-store#submitting-your-pwa-manually
You have "wrappper" instead of "wrapper".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba583c8-c78b-49de-a68a-4fbc7a2bb568
* Version Independent ID: e71db58c-e513-eefd-3f4d-2644b88f405d
* Content: [Progressive Web Apps in the Microsoft Store - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/microsoft-store#submitting-your-pwa-manually)
* Content Source: [microsoft-edge/progressive-web-apps/microsoft-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/microsoft-store.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by dplotnikov** [comment]
@MSEdgeTeam please merge the PR and feel free to close this issue

**Comment by jm-trd-ms** [comment]
Closed. https://github.com/MicrosoftDocs/edge-developer/pull/294
