### ISSUE TITLE
Device not visible to inspect

### ISSUE THREAD

**Issue by hiteshnayak** [MicrosoftDocs/edge-developer#2893]
[Enter feedback here]

After updating to 118 version, Android Local devices are not showing to see Stetho NetworkInterceptor Logs.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 423e15ae-4f85-e6b4-05a0-e1c3a1c2d448
* Version Independent ID: e8d1d135-b095-dbf7-f3b2-28feace8934e
* Content: [Remotely debug Android devices - Microsoft Edge Development](https://learn.microsoft.com/en-in/microsoft-edge/devtools-guide-chromium/remote-debugging/)
* Content Source: [microsoft-edge/devtools-guide-chromium/remote-debugging/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/remote-debugging/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for the report. I'm not familiar with Stetho, but if I understand correctly, it's a way to connect an Android device to the chromium DevTools UI. However, Stetho's github repository seems to be archived, and I can't find a homepage for the project online. Are you sure the tool is still supported?

In any case, this issue has to do with DevTools, not with its documentation. So, could you please report the issue again on the DevTools repo instead? That'd be great, thank you! ➡️ https://github.com/MicrosoftEdge/DevTools
