### ISSUE TITLE
Open DevTools with a new Tab

### ISSUE THREAD

**Issue by pankajparashar** [MicrosoftDocs/edge-developer#2895]
**Link to the documentation page**:
https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/overview#have-devtools-automatically-open-when-you-open-a-new-tab

**Description of the issue**:
The command to open devtools with a new tab for macOS uses Microsoft Edge Beta, whereas the Windows command uses Microsoft Edge. It took me a few seconds to figure out why my command failed; because I did not have the Beta version installed.

1. Should the command point to the main app? If yes then I can submit a PR.
2. As a side-note, the default shell in macOS is Zsh. Probably it's not necessary to mention the type of the shell, instead using "Terminal" app should be fine, similar to Windows Command Prompt or Windows PowerShell.
3. Even though the title mentions "new tab", the same command also works for a "new window", and all subsequent New windows, open with devtools open by default.

**Screenshots**:
<img width="788" alt="image" src="https://github.com/MicrosoftDocs/edge-developer/assets/38640616/780d3086-36f1-4409-8c7b-430f834bcb33">

AB#47279283

**Comment by captainbrosset** [comment]
Thanks for catching this. I agree that we don't need to use Beta specifically on macOS for this command. If you're ok submitting a PR, then by all means, please do :)
