### ISSUE TITLE
learning to make tab extension.

### ISSUE THREAD

**Issue by whiplash696** [MicrosoftDocs/edge-developer#2903]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd37dada-0845-5f1a-7f99-495fe06882cd
* Version Independent ID: 1bbb4d2e-dabb-3d68-de2b-12fb808f86ca
* Content: [Sideload an extension - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/extension-sideloading)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/extension-sideloading.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/extension-sideloading.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
