### ISSUE TITLE
How to enable only Finger ID without Screen lock (PIN Code) option?

### ISSUE THREAD

**Issue by ido-lempert** [MicrosoftDocs/edge-developer#292]
I add code:
authenticatorAttachment: "platform"

On Android device it's open Finger ID authentication UI with Screen lock option (PIN code).
There is away to disable "Screen lock" feature? 
Or maybe knowing when the user authenticate with PIN instead of Finger ID?

I'm only interested to enable Finger ID :\

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cabf96-7b2b-9eb6-c428-ff4b44a97312
* Version Independent ID: 922d390b-52b6-db2a-0aab-f338e8c21b85
* Content: [Dev guide - Web Authentication - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication#feedback)
* Content Source: [microsoft-edge/dev-guide/windows-integration/web-authentication.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/windows-integration/web-authentication.md)
* Product: **microsoft-edge**
* Technology: **windows-integration**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @ido-lempert, since this is related to the previous version of Edge, I'll go ahead and close this issue now. You can use the feedback option (Alt+Shift+I) to leave feedback. Thank you.
