### ISSUE TITLE
Application Tab Completely Blank

### ISSUE THREAD

**Issue by TJohnsonSE** [MicrosoftDocs/edge-developer#2922]
When viewing the 'Application' tab in the Edge DevTools, the tab is completely blank.  Prior to the latest update, this tab showed items such as the session and local storage.  However, now, the tab shows as empty and is not interactable.

Screenshot for reference:

![image](https://github.com/MicrosoftDocs/edge-developer/assets/79184128/be2aec52-62ed-446b-82b2-5e2502d4626c)

I've tested this on web applications I'm developing, which I know for sure utilize session storage, generic webpages, and other web apps that I'm not working on myself.  All result in the same blank Application tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa670af-d081-4ffd-a78f-017621c3ac26
* Version Independent ID: 2fa670af-d081-4ffd-a78f-017621c3ac26
* Content: [What's New in Microsoft Edge DevTools - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/whats-new)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/whats-new.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/whats-new/whats-new.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for the report. This is a known bug which has already been fixed. If you're still seeing the bug, please file a new issue on our DevTools feedback repository instead, here: https://github.com/MicrosoftEdge/DevTools and let us know the Edge version and OS you are using.
Thanks!

**Comment by UyCode** [comment]
same issue with chromium version 120.0.2210.22 (Official build) beta (64-bit)

**Comment by captainbrosset** [comment]
Thanks for the comment. 120 is the last version where this bug persists, but the team is working on fixing it there too.
Please follow the status of this bug here: https://github.com/MicrosoftEdge/DevTools/issues/199
