### ISSUE TITLE
genesis johnytran23

### ISSUE THREAD

**Issue by johnnytran143** [MicrosoftDocs/edge-developer#2924]
__1*1 {ID:}
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 742f11d6-f1b0-e63e-ec19-7f9bf39ff885
* Version Independent ID: 742f11d6-f1b0-e63e-ec19-7f9bf39ff885
* Content: [Debug DOM memory leaks with the Detached Elements tool - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks)
* Content Source: [microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel** 
* Copyright: //Austindgk23//Johnytran143// ==={N}

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
