### ISSUE TITLE
[DevTools Docs Feedback]

### ISSUE THREAD

**Issue by xodfba7** [MicrosoftDocs/edge-developer#2927]
I'm having trouble accessing one of my class videos; all other videos work fine.

This content appeared on the page that was not functioning properly:

<embed id="plugin" type="application/x-google-chrome-pdf" original-url="file:///C:/Users/Yve%20Forthman/Downloads/PowerPoint%202019%20(Modified).pdf" src="chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/20ac9f8c-4e40-4435-b1f4-e8592eb7d07a" background-color="0xFFE6E6E6" first-page-separator="4" style="position: relative !important; top: 41px; min-height: calc(100% - 41px);" javascript="allow" stream_timestamp="7439186027" embed-top-offset="41" width="826" height="228980" full-frame="" pdfviewrecoveryenabled="" pdffreetextenabled="" data-docheight="228976" data-docwidth="826">

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
