### ISSUE TITLE
Older Version of web driver

### ISSUE THREAD

**Issue by jonil3400** [MicrosoftDocs/edge-developer#2935]
Where Can I find older versions for edge web driver? the oldest I can find on the directory is version 100.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver to automate Microsoft Edge - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp&form=MT00IS)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out. This question is specific to the EdgeWebDriver product, not its documentation. Therefore, could you please open a new issue for this over on the dedicated EdgeWebDriver repository?

Here is the link: https://github.com/MicrosoftEdge/EdgeWebDriver/issues/new

Thanks for your understanding.
