### ISSUE TITLE
Rabbit007$

### ISSUE THREAD

**Issue by thug51932** [MicrosoftDocs/edge-developer#2943]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa670af-d081-4ffd-a78f-017621c3ac26
* Version Independent ID: 2fa670af-d081-4ffd-a78f-017621c3ac26
* Content: [What's New in Microsoft Edge DevTools - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/whats-new)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/whats-new.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/whats-new/whats-new.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
