### ISSUE TITLE
ID i77GO7D SAI AUNG 475020 TB2907 AUNG SAI 115145 5826458 00342971 

### ISSUE THREAD

**Issue by ALEXSAIAUNG88** [MicrosoftDocs/edge-developer#2949]
**Link to the documentation page**: The URL to the page.

**Description of the issue**: A clear and concise description of what the issue is.

**Screenshots**: If applicable, add screenshots to help explain the issue.

**Microsoft Edge version**: If the issue occurs with a specific version of Microsoft Edge.

**Comment by ALEXSAIAUNG88** [comment]
O
E
R
C
D

**Comment by ALEXSAIAUNG88** [comment]
K
M
N
G
N

**Comment by ALEXSAIAUNG88** [comment]
I
V
R
S
A

**Comment by ALEXSAIAUNG88** [comment]
X
Z
F
T
Q

**Comment by ALEXSAIAUNG88** [comment]
Y
U
J
L
K
B

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
