### ISSUE TITLE
Blazor PWA

### ISSUE THREAD

**Issue by marqdouj** [MicrosoftDocs/edge-developer#295]
How about a PWA article using the latest Blazor Client template?

I've tried doing this based on what is described in this article, and have got it working (sort of) as I do see the service worker registered in the debugger and the offline page does get displayed when I shutdown IIS Express and try and reload the page. I'm not sure what to do next to turn my blazor client into a true PWA that I can use on Windows 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcef5936-232e-1ab0-c1c4-77026c79e277
* Version Independent ID: b6ec450d-ead9-ffcf-0d5b-7a408bf0e13d
* Content: [Get started with Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/get-started)
* Content Source: [microsoft-edge/progressive-web-apps/get-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/get-started.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @marqdouj, here are a couple of links that may help. 
https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&tabs=visual-studio 
https://wellsb.com/csharp/aspnet/create-pwa-from-blazor-app/
