### ISSUE TITLE
Extension manifest confusing on short description

### ISSUE THREAD

**Issue by erik-lance** [MicrosoftDocs/edge-developer#2958]
As someone who's posting their extension for the first time, it was a bit unclear what the `short description` field is supposed to be or if it even IS a field. It would be nice to get a hyperlink to a page that discusses the parameters briefly or perhaps provide a sample  on this page how to supply these parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 303075ec-ed9b-7ba4-15c5-242f93d53eb2
* Version Independent ID: 15d3653d-af25-8ee7-2e94-01057a734de4
* Content: [Publish a Microsoft Edge extension - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension)
* Content Source: [microsoft-edge/extensions-chromium/publish/publish-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/publish/publish-extension.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#48042656

**Comment by captainbrosset** [comment]
Thank you for your feedback. It's very useful. I'll make sure this issue is tracked on our backlog, so that our team can prioritize it and eventually clarify the docs.

**Comment by Bhuvana-Priya** [comment]
Hi @erik-lance,

Here is the page that details the parameters briefly: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension#before-you-begin

When it comes to the "short description", it is the first few lines displayed about your extension in our store listing. Whereas, "description" is the paragraph displayed when anyone opens your extension.
