### ISSUE TITLE
Auto Parry

### ISSUE THREAD

**Issue by mahamoud12109** [MicrosoftDocs/edge-developer#2964]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb8172aa-183f-6821-f7a3-1a1f838d671c
* Version Independent ID: fb8172aa-183f-6821-f7a3-1a1f838d671c
* Content: [Simplify DevTools using Focus Mode - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/experimental-features/focus-mode)
* Content Source: [microsoft-edge/devtools-guide-chromium/experimental-features/focus-mode.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/experimental-features/focus-mode.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
