### ISSUE TITLE
Edge Manifest V2 support timeline update

### ISSUE THREAD

**Issue by mztse** [MicrosoftDocs/edge-developer#2970]
[Enter feedback here]
Currently the doc says: "Manifest V2 extensions will continue to be supported through Enterprise policies at least until Chromium Manifest V2 support timeline (which is currently January 2024)."

However Chrome side has recently updated the timeline in November 2023 here: https://developer.chrome.com/blog/resuming-the-transition-to-mv3

Please update the doc about the Edge Manifest V2 support timeline accordingly. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 815c941b-4a07-481a-9bb5-f8ef3d6b1118
* Version Independent ID: 815c941b-4a07-481a-9bb5-f8ef3d6b1118
* Content: [Overview and timelines for migrating to Manifest V3 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/manifest-v3?source=docs)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#48121066

**Comment by captainbrosset** [comment]
Thanks so much for noticing this discrepency and filing an issue about it.
I'll take this back to the team and we'll update the docs accordingly, asap.

**Comment by captainbrosset** [comment]
Hi @mztse. For info, the dates displayed in [our timeline](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/manifest-v3) are still TBD. We are still working on finalizing the dates and will share an update as soon as we can over the coming months.

We will update the docs as soon as we've finalized the date. Until then, I'll close this issue. 

Thanks again!
