### ISSUE TITLE
How to calculate Sec-CH-UA-Platform-Version like Edge

### ISSUE THREAD

**Issue by daniel-lerch** [MicrosoftDocs/edge-developer#2981]
**Link to the documentation page**: [Detect Windows 11 and CPU architecture using User-Agent Client Hints](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11)

**Description of the issue**:

I want to send `Sec-CH-UA-Platform-Version` headers in my own app that follow Microsoft's official version pattern. Unfortunately, the table of versions in the documentation only states that Windows 11 uses version _13+_ without exact version numbers. The documentation also says that the versioning pattern follows the API contract version of `Windows.Foundation.UniversalApiContract` documented [here](https://learn.microsoft.com/en-us/windows/uwp/debug-test-perf/version-adaptive-apps#api-contracts).

However, it seems these API contract versions are not meant to be looked up. In the documentation about version adaptive apps there is only the method [`ApiInformation.IsApiContractPresent`](https://learn.microsoft.com/en-us/uwp/api/windows.foundation.metadata.apiinformation.isapicontractpresent) mentioned but no elegant way to get the current version.

This C# code counts versions up and reports the highest supported version. Is this the really the best way to do it?

```csharp
public static int GetCHUAPlatformVersion()
{
    for (int version = 0; ; version++)
    {
        if (!Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent(
            "Windows.Foundation.UniversalApiContract",
            (ushort)(version + 1))
        )
            return version;
    }
}
```

**Screenshots**: N/A.

**Microsoft Edge version**: N/A.

**Comment by captainbrosset** [comment]
Thanks for the question. Let me check internally and report any findings.

**Comment by captainbrosset** [comment]
While the Edge team owns these headers, they're normally added by the browser. It looks like your question isn't so much about the `CH-UA` header itself, but rather about `Windows.Foundation.UniversalApiContract`, which our team doesn't own.
I think the best way forward here is to contact the team who owns the https://learn.microsoft.com/en-us/windows/uwp/debug-test-perf/version-adaptive-apps docs.

Go to that page, scroll down to the bottom, and click the **This page** button under **Feedback**.

This should put you in touch with the right set of people. Thanks for your understanding.
