### ISSUE TITLE
TTS & tts_engine API's

### ISSUE THREAD

**Issue by skechboy** [MicrosoftDocs/edge-developer#299]
Hi,

I've noticed TTS and TTS_engine API's available in chromium are missing in the current Edge-developer build.

Are there any plans for these API's to be supported in Edge or? 

Thanks

**Comment by Reezaali** [comment]
Hi @skechboy, I think this link has the information you're asking about: https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/api-support

I'll go ahead and close this issue now.
