### ISSUE TITLE
Not all tabs persisted in order between sessions

### ISSUE THREAD

**Issue by CalvinQuark** [MicrosoftDocs/edge-developer#2998]
The claim on this page that "Your custom tool order persists across DevTools sessions" apparently does not apply to _Extension_-provided tabs. I am encountering with the _GraphQL Network Inspector_ extension sourced from the Chrome web store that this extension's tab is always positioned after the standard DevTools native tabs.

If this behavior is intentional, then it would be helpful if it were noted down on this page. However, it would be more useful if the positions of extension tabs were likewise persisted between sessions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40b9fb83-7f94-b1e8-dabf-31bc0faca815
* Version Independent ID: 511435aa-e29b-9798-9e5d-2945ea12d302
* Content: [Customize DevTools - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/customize/)
* Content Source: [microsoft-edge/devtools-guide-chromium/customize/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/customize/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#48368746

**Comment by captainbrosset** [comment]
I agree that it would be more helpful if extension-provided tabs would also get their position persisted, and I would advise you to file this as a feature request on the DevTools feedback repository instead, here: https://github.com/MicrosoftEdge/DevTools.

In the meantime, we can also make a change to the documentation, something like "For the time being, extension-provided tabs are always positioned after the built-in tabs".
