### ISSUE TITLE
More guides should be added on how to build extension

### ISSUE THREAD

**Issue by samsonmobisa** [MicrosoftDocs/edge-developer#3001]
More guides should be added on how to build extension

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4edd411d-e52a-32ef-e539-fb4ed709c86c
* Version Independent ID: 9b96eeb9-accc-7230-20b1-b704d9f9a79e
* Content: [Overview of Microsoft Edge extensions - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/?form=MA13FJ)
* Content Source: [microsoft-edge/extensions-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for filing. We have a two-parts tutorial here: https://learn.microsoft.com/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.
Can you explain in which way(s) is this tutorial not enough for your needs? It would be very helpful if you could provide more detail about the kind of guides you're looking for.

**Comment by samsonmobisa** [comment]
Just had some doubt since the download folder i installed in my machine is 5gb

**Comment by samsonmobisa** [comment]
the tutorial will help I guess i was missing it

**Comment by captainbrosset** [comment]
Great to hear that the tutorial will be helpful. Feel free to file another issue if you identify specific areas that would benefit from more documentation.
