### ISSUE TITLE
[Edge WebDriver Docs Feedback] XML file downloads are blocked

### ISSUE THREAD

**Issue by RajeshPoola** [MicrosoftDocs/edge-developer#3005]
While using InPrivate mode, downloading XML files triggers a security pop-up showing the file download blocked message.

I used the following options but they didn't work. I didn't find any documentation regarding this.
```
var options = new EdgeOptions();
options.AddArgument("--safebrowsing-disable-download-protection");
options.AddUserProfilePreference("download.prompt_for_download", false);
options.AddUserProfilePreference("savefile.default_directory", OutputFilePath);
options.AddUserProfilePreference("savefile.prompt_for_download", false);
```

I would appreciate any help you can give me
![Screenshot 2024-01-05 110535](https://github.com/MicrosoftDocs/edge-developer/assets/82456213/49dfd5d7-d650-4b4b-b186-4bba2930a728)
.

**Comment by captainbrosset** [comment]
Thanks for your feedback. Since this is an issue with Edge WebDriver directly (instead of with its documentation), I advise creating a new issue over on the Edge WebDriver feedback repository. Here is the link: https://github.com/MicrosoftEdge/EdgeWebDriver/issues

Thanks for your understanding.
