### ISSUE TITLE
msedgewebview2 crashes before even login.

### ISSUE THREAD

**Issue by Bcuzeau** [MicrosoftDocs/edge-developer#3007]
[Enter feedback here]

msedgewebview2 crashes before even login.
Can't get rid of it, uninstalling doesn't help.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de4d5de5-6690-7c62-6ed8-9b839a01b670
* Version Independent ID: 01abbd67-1b51-39e5-96dc-e1a7bbc0ae70
* Content: [Contact the WebView2 Team - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/contact)
* Content Source: [microsoft-edge/webview2/contact.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/contact.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. However this repository is related to the documentation of webview2, not to the webview2 library itself.
For anything technical, please get in touch with our webview2 team on this repository:

https://github.com/MicrosoftEdge/WebView2Feedback/issues/

Thanks for your understanding.
