### ISSUE TITLE
Missing semi colon in document 

### ISSUE THREAD

**Issue by jbp199** [MicrosoftDocs/edge-developer#3008]
Example shown here missing a semicolon on second to last closure:

webView.CoreWebView2.ContextMenuRequested += delegate (object sender, 
                                    CoreWebView2ContextMenuRequestedEventArgs args)
{
    // add new item to end of collection
    CoreWebView2ContextMenuItem newItem = 
                        webView.CoreWebView2.Environment.CreateContextMenuItem(
        "Display Page Uri", null, CoreWebView2ContextMenuItemKind.Command);
        newItem.CustomItemSelected += delegate (object send, Object ex)
        {
            string pageUri = args.ContextMenuTarget.PageUri;
            System.Threading.SynchronizationContext.Current.Post((_) =>
            {
                MessageBox.Show(pageUri, "Page Uri", MessageBoxButton.OK);
            }, null);
        }**;  <<---- semi colon missing** 
    menuList.Insert(menuList.Count, newItem);
};

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4d963f2-c098-e1b5-74cb-22219ce7c751
* Version Independent ID: a4d963f2-c098-e1b5-74cb-22219ce7c751
* Content: [Customize context menus in WebView2 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/context-menus?tabs=csharp)
* Content Source: [microsoft-edge/webview2/how-to/context-menus.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/context-menus.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#48412524

**Comment by captainbrosset** [comment]
Thanks for filing this issue. I've opened a PR to fix it.
