### ISSUE TITLE
Disgusting it is not working now I have install Chrome. Edge is stupid 

### ISSUE THREAD

**Issue by harshchokshi** [MicrosoftDocs/edge-developer#3015]
[RemoteTestNG] detected TestNG version 7.4.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting Microsoft Edge WebDriver 120.0.2210.133 (5a3825c4628d0bef4e9a1ceca8987a524bbd379a) on port 57198
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
Jan 14, 2024 12:05:07 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Jan 14, 2024 12:05:07 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 120, so returning the closest version found: a no-op implementation
Jan 14, 2024 12:05:07 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Unable to find CDP implementation matching 120.
Jan 14, 2024 12:05:07 AM org.openqa.selenium.chromium.ChromiumDriver lambda$new$3
WARNING: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.1.4` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
Starting ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}) on port 50472
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver to automate Microsoft Edge - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by harshchokshi** [comment]
@BeforeTest
  public void browserlaunch() 
  {
	  spark.config().setTheme(Theme.DARK);
	  spark.config().setDocumentTitle("MyReport");
	  extent.attachReporter(spark);       
	  //System.setProperty(EdgeDriverService.EDGE_DRIVER_LOG_PROPERTY, "true");
	  EdgeOptions options = new EdgeOptions();
	  options.addArguments("--remote-allow-origins=*");
	//  System.setProperty("webdriver.edge.driver","C:\\edgedriver_win64\\msedgedriver.exe");
	//  WebDriverManager.edgedriver().setup();
	  driver = new EdgeDriver(options);
	  driver.get("https://www.google.com/");
  }

**Comment by captainbrosset** [comment]
If you have technical issues with Edge WebDriver, please file issues on the corresponding repository here: https://github.com/MicrosoftEdge/EdgeWebDriver

Also note that this repository has adopted the [Microsoft code of conduct](https://opensource.microsoft.com/codeofconduct/). Please be respectful and avoid insulting or derogatory comments.

**Comment by harshchokshi** [comment]
Sir, change the subject now could you able to provide me solution. I mean, my issue is not solved and it has been closed???
