### ISSUE TITLE
The Screenshot and text for Step 1 is now out of date

### ISSUE THREAD

**Issue by BPapp-MS** [MicrosoftDocs/edge-developer#3019]
There is now, importantly, an option for "Allow DevTools to load resources, such as source maps, from remote file paths" which must also be enabled in the DevTools Settings > Preferences screen

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2ecc9a-c883-9097-bcdc-9f812cbe5d53
* Version Independent ID: 0b2ecc9a-c883-9097-bcdc-9f812cbe5d53
* Content: [Securely debug original code by using Azure Artifacts symbol server source maps - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/consume-source-maps-from-azure)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript/consume-source-maps-from-azure.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/javascript/consume-source-maps-from-azure.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#48531703

**Comment by captainbrosset** [comment]
Thanks for reporting this. I'll make sure this is on our backlog so we can prioritize and fix the issue.

**Comment by captainbrosset** [comment]
After a deeper investigation, I realized that the **Allow DevTools to load resources, such as source maps, from remote file paths** option really only applies when the source map is loaded from a `file://` URL.

**Comment by captainbrosset** [comment]
With this in mind, I think it would make more sense to document this option under this more general source map section: https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/source-maps#enable-source-maps-in-settings
