### ISSUE TITLE
Edge third party cookie blocking

### ISSUE THREAD

**Issue by gkratkin-menlo** [MicrosoftDocs/edge-developer#3021]
Does Edge plan something analogous to Chrome's third party cookie blocking rollout (https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2024jan)?

If so, can you comment on the schedule and whether the rollout will be accompanied by a deprecation trial like Chrome's (https://developers.google.com/privacy-sandbox/3pcd/temporary-exceptions/preserving-critical-user-experiences#third-party_deprecation_trial_for_non-advertising_use_cases)?

Thank you,
Gary Kratkin  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e08a40c-6a79-a8f1-64e6-8befc952684f
* Version Independent ID: e1ab6543-67eb-bc78-8466-2315d3906d2c
* Content: [Site compatibility-impacting changes coming to Microsoft Edge - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/site-impacting-changes?tabs=latest)
* Content Source: [microsoft-edge/web-platform/site-impacting-changes.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/site-impacting-changes.md)
* Service: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
The Microsoft Edge Product Group is aware of the changes announced by Google Chrome to third party cookies. As this work evolves, we will continue to support solutions that maintain consumer choice and control while balancing a healthy ecosystem for all. Microsoft Edge already provides customers with built-in tracking prevention and additional settings to block 3P cookies if they choose. We will publish timelines for any site compatibility-impacting changes in Edge here: [Site compatibility-impacting changes coming to Microsoft Edge](https://learn.microsoft.com/microsoft-edge/web-platform/site-impacting-changes).
