### ISSUE TITLE
Redefinition Error in Sample Code

### ISSUE THREAD

**Issue by haowxums** [MicrosoftDocs/edge-developer#3034]
[Enter feedback here]
The sample code for the method based on `WebResourceRequested` contains duplicated definition for `stream` leading to a build error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4cd0457-26bf-0123-6f03-35bc1fd5dcdc
* Version Independent ID: c4cd0457-26bf-0123-6f03-35bc1fd5dcdc
* Content: [Working with local content in WebView2 apps - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/working-with-local-content?tabs=win32cpp)
* Content Source: [microsoft-edge/webview2/concepts/working-with-local-content.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/concepts/working-with-local-content.md)
* Service: **microsoft-edge**
* Sub-service: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#48669424

**Comment by captainbrosset** [comment]
Thank you for reporting this. Adding to our list of tracked webview2 docs issues, and will try to get to it soon.

**Comment by captainbrosset** [comment]
Fixed by #3208.
