### ISSUE TITLE
CONTRIBUTING.md instructs to use non-existent develop branch

### ISSUE THREAD

**Issue by alesandroortiz** [MicrosoftDocs/edge-developer#305]
[CONTRIBUTING.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/CONTRIBUTING.md) file references a `develop` branch, however, that branch does not exist: https://github.com/MicrosoftDocs/edge-developer/tree/develop

The file instructs contributors to use the non-existent branch. Not clear if we should be using `master` now or another branch.

Happy to submit PR to fix, but need to know which branch contributors should be directed to.

**Comment by Reezaali** [comment]
The doc has been updated. Thank you.

**Comment by alesandroortiz** [comment]
Thanks for the info. Can confirm it was updated in https://github.com/MicrosoftDocs/edge-developer/pull/585.
