### ISSUE TITLE
Page does work

### ISSUE THREAD

**Issue by ray-burger** [MicrosoftDocs/edge-developer#3054]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebb3961c-ee29-d589-71a4-04ab454472b0
* Version Independent ID: 802d2dbe-c716-c901-882c-fe7f08f7eead
* Content: [Override the user agent string - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/override-user-agent)
* Content Source: [microsoft-edge/devtools-guide-chromium/device-mode/override-user-agent.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/device-mode/override-user-agent.md)
* Service: **microsoft-edge**
* Sub-service: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing this issue, but feel free to comment here if you're still having an issue.
