### ISSUE TITLE
This isn't correct anymore

### ISSUE THREAD

**Issue by jimgilliam** [MicrosoftDocs/edge-developer#3055]
The window overlay feature **does not hide** the title bar as in the instructions say. Has Microsoft changed this and forgot to update the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a244fe70-67b5-97c9-9bf5-ee88daa3cf2a
* Version Independent ID: 39a6ad7c-1dba-f87b-ded0-4236a80caa55
* Content: [Display content in the title bar - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay.md)
* Service: **microsoft-edge**
* Sub-service: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
From what I know, nothing should have changed. If the feature doesn't work for you, could you please provide a way for us to reproduce the problem and investigate?

**Comment by jimgilliam** [comment]
Thank you, @captainbrosset. Yes, I will gather it and post it here. Thank you so much for the kind offer.

**Comment by jimgilliam** [comment]
@captainbrosset Captain, it's working now after adjustments to my manifest. Thank you. Do you know if there's a way to customize the Search button? I'd like it to open my help documentation associated with my app.
![image](https://github.com/MicrosoftDocs/edge-developer/assets/4622040/e25b58c2-0566-4442-9928-aef18435d8d1)

**Comment by captainbrosset** [comment]
@jimgilliam great to hear that the feature is working for you now.
No, there currently is no way to customize the Search button unfortunately. If this is a feature you would enjoy using, please send feedback to the Edge team via the Edge feedback mechanism:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Somewhat related to this, there's also the Edge Sidepanel API that might be of interest to you: https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/sidebar
