### ISSUE TITLE
No Privacy or Developer contact info for Edge Addon?

### ISSUE THREAD

**Issue by soniariv** [MicrosoftDocs/edge-developer#3061]
[Enter feedback here]

Good morning,

What does it mean when there is no information about the Privacy or Developer contact info at an Add-on page?
There is no Privacy contents disclaimer and no reference to any 'Contact' / email /website of the Software Developer for this Edge Add-on:
https://microsoftedge.microsoft.com/addons/detail/auto-refresher/lnehigejbkdlcjiocfndnbmigdfbegpb?hl=en

Anyone could publish an addon this way?  How to trust such addons?

Thanks
soniariv

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6bdbaf0-1a39-c369-deca-d22e0d4e6ec0
* Version Independent ID: 7ec272a7-8291-5d33-f320-ef7f1bcd9648
* Content: [Contact Microsoft Edge extensions support - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team)
* Content Source: [microsoft-edge/extensions-chromium/publish/contact-extensions-team.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/publish/contact-extensions-team.md)
* Service: **microsoft-edge**
* Sub-service: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out. I suggest posting this question again on the dedicated Microsoft Edge Extensions discussion repo: https://github.com/microsoft/MicrosoftEdge-Extensions/discussions

Thank you for your understanding.

**Comment by soniariv** [comment]
Thank you! Done.
