### ISSUE TITLE
The email address is not working and returning errors when you send an email ext_dev_support@microsoft.com

### ISSUE THREAD

**Issue by hansvangent** [MicrosoftDocs/edge-developer#3064]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 303075ec-ed9b-7ba4-15c5-242f93d53eb2
* Version Independent ID: 15d3653d-af25-8ee7-2e94-01057a734de4
* Content: [Publish a Microsoft Edge extension - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension)
* Content Source: [microsoft-edge/extensions-chromium/publish/publish-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/publish/publish-extension.md)
* Service: **microsoft-edge**
* Sub-service: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#49073986

**Comment by captainbrosset** [comment]
Thank you for reporting this issue, I'll bring it to the right people to get it fixed as soon as we can.

**Comment by captainbrosset** [comment]
Our team is currently working on fixing this issue. So it's a temporary bug that will get resolved soon. I'll update this issue again once I know this has been fixed.

**Comment by captainbrosset** [comment]
The email should be working again. Closing this issue. Feel free to get in touch again if you see another issue.
