### ISSUE TITLE
Image generator does not work

### ISSUE THREAD

**Issue by MarianoCurros** [MicrosoftDocs/edge-developer#308]
https://www.pwabuilder.com/imageGenerator does not work. It gives http error 500. Also the buttons can't be seen, it displays awfully in edge and any browser. Shame.

**Comment by jm-trd-ms** [comment]
Hi [MarianoCurros](https://github.com/MarianoCurros),
Sorry to hear about your negative experience. 
Please confirm that this issue is valid.  
The link for Image Generator is live.  

Live: https://www.pwabuilder.com/imageGenerator

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.
