### ISSUE TITLE
Selenium tool uses IE Edge Mode forces the infobar flags for security , causing issue in overall application usage.

### ISSUE THREAD

**Issue by niravbha2016** [MicrosoftDocs/edge-developer#3080]
Utilizing automation tools such as Selenium may inadvertently trigger IE Edge Mode, leading to the enforcement of infobar flags for security. This, in turn, can result in issues affecting the overall application usage. Two specific infobars, namely 'You are using an unsupported command line flag --ie-mode-force. This causes stability and security risk.' and 'Sites in this tab will open in Internet Explorer mode,' are particularly problematic. Unfortunately, these flags cannot be turned off, raising the question: Is there a registry setting available to disable them?

how to turn these off?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Version Independent ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Content: [Use Internet Explorer Driver to automate IE mode in Microsoft Edge - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp#known-limitations)
* Content Source: [microsoft-edge/webdriver-chromium/ie-mode.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/ie-mode.md)
* Service: **microsoft-edge**
* Sub-service: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out about this. @bwalderman can you help answer the above please?

**Comment by captainbrosset** [comment]
Closing this since we didn't hear back.
