### ISSUE TITLE
https://www.pwabuilder.com/generate does not display correctly in edge

### ISSUE THREAD

**Issue by MarianoCurros** [MicrosoftDocs/edge-developer#309]
Please, seriously? See the image:

![image](https://user-images.githubusercontent.com/54580279/63765227-fb6b1e00-c89e-11e9-9900-9a92c2f91643.png)

My display is 4K scaled, Dell XPS 15, Windows 10 1903...

**Comment by Reezaali** [comment]
Hi there, can you retry as the team has made several improvements. I'll go ahead and close this issue now. Thanks.
