### ISSUE TITLE
https://www.pwabuilder.com/serviceworker copy button does not work.

### ISSUE THREAD

**Issue by MarianoCurros** [MicrosoftDocs/edge-developer#310]
The copy button in https://www.pwabuilder.com/serviceworker does not work.

0: Unable to get property 'define' of undefined or null reference, CopyButton.js line 115,1

Please hit F12 and check all the errors you got in the page.

**Comment by Reezaali** [comment]
Hi there, can you retry as the team has made several improvements. I'll go ahead and close this issue now. Thanks.
