### ISSUE TITLE
WinUI 3 WebView2 now supports custom environments

### ISSUE THREAD

**Issue by krschau** [MicrosoftDocs/edge-developer#3101]
WinAppSDK now supports custom WebView2 environments 🎉 (see https://github.com/microsoft/microsoft-ui-xaml/issues/6150). The "API Limitations" section of this page should be updated.

@DmitriyKomin 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6747d603-e773-dec7-7580-f18f4365cec9
* Version Independent ID: 5f7cd45b-5739-ad85-4b61-c9f94921df98
* Content: [Get started with WebView2 in WinUI 3 (Windows App SDK) apps - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui)
* Content Source: [microsoft-edge/webview2/get-started/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/winui.md)
* Service: **microsoft-edge**
* Sub-service: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#49459391

**Comment by captainbrosset** [comment]
Thanks for filing!
