### ISSUE TITLE
learn.microsoft.com ➟

### ISSUE THREAD

**Issue by AyeshaSattar2116** [MicrosoftDocs/edge-developer#3103]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dec166ea-3192-50ac-a930-f2185226801f
* Version Independent ID: a7055048-1b57-b2dc-78ae-6786d8765467
* Content: [WebView2 Roadmap - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/webview2/roadmap)
* Content Source: [microsoft-edge/webview2/roadmap.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/roadmap.md)
* Service: **microsoft-edge**
* Sub-service: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Closing as incomplete. Please feel free to add more information if you have any and we can re-open the issue.
