### ISSUE TITLE
Detached element tool, Only the quantity is displayed, without showing detailed information about the list.

### ISSUE THREAD

**Issue by Chrisyjs** [MicrosoftDocs/edge-developer#3145]
https://learn.microsoft.com/zh-cn/microsoft-edge/devtools-guide-chromium/contact

The latest version of Edge has been installed.
when I use Detached element tool, Only the quantity is displayed, without showing detailed information about the list.
![image](https://github.com/MicrosoftDocs/edge-developer/assets/22340685/044f2df8-5f38-403b-aa91-f9cedabaa3a9)

**Comment by captainbrosset** [comment]
Thanks for filing, and sorry about the inconvenience. We're aware of this bug and are currently tracking it in this existing issue: https://github.com/MicrosoftEdge/DevTools/issues/233
