### ISSUE TITLE
I couldn't find any non-5-star reviews

### ISSUE THREAD

**Issue by bu6030** [MicrosoftDocs/edge-developer#3149]
[Enter feedback here]
![image](https://github.com/MicrosoftDocs/edge-developer/assets/11482988/740b4b2f-62e9-4428-a954-a7cf46976759)
![image](https://github.com/MicrosoftDocs/edge-developer/assets/11482988/2669c943-2610-4126-86e9-2aaeb56377c0)

My extension has a rating of 4.3, but after checking all the ratings, they are all 5-stars. I couldn't find any non-5-star reviews. Could you please look into what might be going on?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6bdbaf0-1a39-c369-deca-d22e0d4e6ec0
* Version Independent ID: 7ec272a7-8291-5d33-f320-ef7f1bcd9648
* Content: [Contact Microsoft Edge extensions support - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team#request-help-or-submit-feedback)
* Content Source: [microsoft-edge/extensions-chromium/publish/contact-extensions-team.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/publish/contact-extensions-team.md)
* Service: **microsoft-edge**
* Sub-service: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Apologies about the confusion here. However, this repo is for maintaining the documentation of Edge developer features, not about resolving Edge extension issues.
Could you please reach out to the extensions team on this repo instead: https://github.com/microsoft/MicrosoftEdge-Extensions/discussions?
Thank you for your understanding.
