### ISSUE TITLE
Native apps docs stop short: no information on how to package a native extension in a real visual studio project

### ISSUE THREAD

**Issue by minfrin** [MicrosoftDocs/edge-developer#3155]
In the docs, we learn that files need to be copied into specific locations, and the registry keys are to be updated.

Obviously the average user isn't going to be copying files or updating registry keys, this will be the job of an application installer. There is however no next steps describing how you would turn a manually installed native extension into a proper package for installation.

The docs stop short of being practically useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6baf3ba3-2850-707d-fdfc-9b65f88655c7
* Version Independent ID: 661b537b-bba6-cb07-9979-cddcc35421e3
* Content: [Native messaging - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging?tabs=v3%2Cmacos)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/native-messaging.md)
* Service: **microsoft-edge**
* Sub-service: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#50891956

**Comment by captainbrosset** [comment]
Thanks for filing this request. I'm marking it up so it shows up on our backlog for evaluation and prioritization.

**Comment by Markimark956** [comment]
na

**Comment by Markimark956** [comment]
na

**Comment by Markimark956** [comment]
na

**Comment by minfrin** [comment]
Further info - in the world of MSIX, applications are sandboxed from one another.

With MSIX being the way forward, there needs to be docs on how to package a native extension as an MSIX in such a way that a browser will find it.

**Comment by minfrin** [comment]
After a host of false starts, it's become apparent that MSIX and browser extensions are fundamentally incompatible with each other with no workaround.

Raised this to make sure the docs are clear: https://github.com/MicrosoftDocs/edge-developer/issues/3191

**Comment by captainbrosset** [comment]
Thanks for capturing the confusion in the new issue. I think the need here is to rework the article to make it clear that it's the job of the native app installer to update the required registry keys, and to say how this can be done.
I think both issues can be solved with this. So I'll close this one.
