### ISSUE TITLE
Can I save the log (to a file)? Or copy the log to paste and save?

### ISSUE THREAD

**Issue by chipbite** [MicrosoftDocs/edge-developer#316]
Can I save the log (to a file)? Or copy the log to paste and save?

I cant seem to find a way to move the information in the log elsewhere, in any way - except for screenshots, which is impractical. Tips?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462f093f-9486-8086-da81-c689b7ef7d9e
* Version Independent ID: 0424a5af-15a6-1ccd-5732-12edb757838a
* Content: [DevTools - Console - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console#feedback)
* Content Source: [microsoft-edge/devtools-guide/console.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/console.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Apologies for this issue having gotten stale. Yes, you can save the logs to a file in the more recent versions of Microsoft Edge. Just right-click anywhere in the console and choose "Save as...".

Note that this repository is about the Microsoft Edge **documentation**. If you want to report an issue about DevTools itself, you can do so by following the instructions here: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/contact
