### ISSUE TITLE
I cant watch youtube

### ISSUE THREAD

**Issue by RBanks29** [MicrosoftDocs/edge-developer#3163]
[Enter feedback here] I cant watch youtube because they say its blocked😒 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0dff9d4-34da-5563-4b34-ca5ef03ade06
* Version Independent ID: 55519333-e802-ec65-1b49-8fe64fe04825
* Content: [Change DevTools placement (Undock, Dock to bottom, Dock to left) - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/customize/placement)
* Content Source: [microsoft-edge/devtools-guide-chromium/customize/placement.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/customize/placement.md)
* Service: **microsoft-edge**
* Sub-service: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by RBanks29** [comment]
plsssswsxs

**Comment by captainbrosset** [comment]
This repository is specific to Edge developer documentation.
Can you please send your feedback again by using the browser's feedback mechanism? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
