### ISSUE TITLE
Node js connect with oracle database data crud operaion SELECT QUERY issuse

### ISSUE THREAD

**Issue by ManojbabuV** [MicrosoftDocs/edge-developer#3172]
[ oracle database data crud operaion SELECT QUERY issuse]

---
#### I connect with oracle database with help of node js  that data passing to api axios api that api get the data to display the front end component but without error to fetching  data but space is allocated but not value display how network connection also workhow can i solve help to resolve it and then give a solution.

⚠ *THIS MY ISSUES  see this image better understanding::***
![Screenshot (96)](https://github.com/MicrosoftDocs/edge-developer/assets/168261760/14fb36ab-fd3e-4866-82dc-743e9083e899)
![Screenshot (97)](https://github.com/MicrosoftDocs/edge-developer/assets/168261760/4f06d6c8-b937-4eeb-9d55-593c1b0739b3)
))

* ID: 6c1ef1bb-91a3-db70-2e06-b38c1a494bed
* Version Independent ID: 1b4e4189-04a9-f818-32ca-b3056e5fae3f
* Content: [Microsoft Edge DevTools extension for Visual Studio Code - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension)
* Content Source: [microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/visual-studio-code/microsoft-edge-devtools-extension.md)
* Service: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
This repository is specific to maintaining the edge developer docs at https://learn.microsoft.com/en-us/microsoft-edge/
I don't really understand your question here, but it doesn't seem related to our docs, so I will close this issue.
If you suspect that there's an issue with Edge DevTools, then you can reach out about this at https://github.com/MicrosoftEdge/DevTools.
If you think this is a browser issue instead, then please send feedback by using the browser feedback tool:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
