### ISSUE TITLE
Copilot fails to consume errors in DevTools console

### ISSUE THREAD

**Issue by gavinayling** [MicrosoftDocs/edge-developer#3173]
[Enter feedback here]
When I click the icon in the Console, Copilot instantly responds "What do you want to do with the text?" then "You" says "Explain the error message from DevTools console" and then Copilot complains it doesn't have the error message.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba6dfeb3-8baf-0405-2a5b-2a7eb9bcc272
* Version Independent ID: ba6dfeb3-8baf-0405-2a5b-2a7eb9bcc272
* Content: [Explain Console errors and warnings using Copilot in Edge - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/copilot-explain-console#the-explain-this-error-feature)
* Content Source: [microsoft-edge/devtools-guide-chromium/console/copilot-explain-console.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/console/copilot-explain-console.md)
* Service: **microsoft-edge**
* Sub-service: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gavinayling** [comment]
![2024-05-22_11-05-03](https://github.com/MicrosoftDocs/edge-developer/assets/30932750/fe519a03-0330-440a-b1a7-0b28b5405eac)

**Comment by captainbrosset** [comment]
Sorry about this, and thanks so much for filing this. This repository is focused on developer docs, not on the implementation of the feature itself. So, to help us track this issue better, could you please re-open it in this other repo instead: https://github.com/MicrosoftEdge/DevTools/issues ?

That would be very helpful. Thank you!

**Comment by gavinayling** [comment]
If this isn’t the right place, why does Edge bring me here to provide feedback?Gavin Aylinghttps://ayling.tech/gavinOn May 22, 2024, at 13:04, Patrick Brosset ***@***.***> wrote:﻿
Closed #3173 as completed.
