### ISSUE TITLE
Link to symbol.exe doesn't lead to download page

### ISSUE THREAD

**Issue by mauron85** [MicrosoftDocs/edge-developer#3179]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3efb02b4-e5e3-7b6a-542a-1f588383acae
* Version Independent ID: 3efb02b4-e5e3-7b6a-542a-1f588383acae
* Content: [Securely debug original code by publishing source maps to the Azure Artifacts symbol server - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/publish-source-maps-to-azure#step-3-publish-source-maps-to-the-azure-artifacts-symbol-server)
* Content Source: [microsoft-edge/devtools-guide-chromium/javascript/publish-source-maps-to-azure.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/javascript/publish-source-maps-to-azure.md)
* Service: **microsoft-edge**
* Sub-service: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#51533227

**Comment by captainbrosset** [comment]
Thank you for filing this issue. Will add this to our backlog for prioritization.

**Comment by captainbrosset** [comment]
Fixed in PR #3200, which improved the wording around the fact that the linked page describes a REST API endpoint that developers can use to acquire the symbol.exe file.
