### ISSUE TITLE
My name is Margaret B---- you have been going into my account for what i don't know

### ISSUE THREAD

**Issue by Margieb2007** [MicrosoftDocs/edge-developer#32]
I need help my phone number is 9177499649 if you can please help me.

**Comment by mattwojo** [comment]
Hi Margaret, I've removed your last name and phone number for your own privacy and can assure you that we have not been going in to your account. You have stumbled on to the Microsoft Edge Browser documentation for developers who create websites. Possibly by pressing the F12 key and then clicking the ? icon ...? I'm closing this issue, but if you need help with something on your computer running Windows, you might try https://support.microsoft.com. Have a blessed day!

**Comment by GrantMeStrength** [comment]
Did anyone feed the fish?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mattwojo** [comment]
I did. 😊

**Comment by GrantMeStrength** [comment]
Thanks!

**Comment by Margieb2007** [comment]
U fuck

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by GrantMeStrength** [comment]
LOLs

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Margieb2007** [comment]
Who the fuck told u to go on my account



Sent from myMail for iOS


Friday, 2 June 2560 BE, 5:47 PM -0400 from Matt Wojciakowski <notifications@github.com>:
I did. 😊

**Comment by Margieb2007** [comment]
U are all in trouble now. My job computer broke and I had to tell them



Sent from myMail for iOS


Friday, 2 June 2560 BE, 5:47 PM -0400 from Matt Wojciakowski <notifications@github.com>:
I did. 😊

**Comment by GrantMeStrength** [comment]
Let’s end this thread now. I’m unclear as to where it is being published, and a few other threads got crossed and confused.

MargieB, if you are reading this, please email me directly – jken@microsoft.com<mailto:jken@microsoft.com> – and we can discuss your problem directly. I’m certain this is just a misunderstanding and we can clear things up very quickly.

Thanks,

John Kennedy
Senior Content Publishing Manager

**Comment by Margieb2007** [comment]
Get the fuck off im calling the cops



Sent from myMail for iOS


Monday, 5 June 2560 BE, 4:41 PM -0400 from Margieb2007 <notifications@github.com>:
U are all in trouble now. My job computer broke and I had to tell them



Sent from myMail for iOS


Friday, 2 June 2560 BE, 5:47 PM -0400 from Matt Wojciakowski <notifications@github.com>:
I did. 😊
