### ISSUE TITLE
Are those extentions compatible with the new Edge Browser? (Edge Insider?)

### ISSUE THREAD

**Issue by jhueppauff** [MicrosoftDocs/edge-developer#321]
Hi,

I am wondering if this is also the documentation to create extentions for the Chrome Base Edge (https://www.microsoftedgeinsider.com/en-us/)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1037a28d-7cd5-66dc-9826-1e626fa6e74b
* Version Independent ID: f90b56a3-db51-eeea-707c-0c30e81b4749
* Content: [Extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions)
* Content Source: [microsoft-edge/extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by WesselKroos** [comment]
No that's the documentation for the EdgeHTML based browser.
The documentation for the Chromium based browser extensions can be found here:
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/

**Comment by gebansal** [comment]
@jhueppauff I am hoping your concern has been addressed, hence closing the issue. If not, please feel free to either open this issue or create a new one.
