### ISSUE TITLE
🧡💜🕉♋🆔♾https://accounts.google.com/gsi/select?client_id=49625052041-kgt0hghf445lmcmhijv46b715m2mpbct.apps.googleusercontent.com&ux_mode=popup&ui_mode=card&as=QfDsuZ1ZnpceQoR0vo58oQ&channel_id=68b420298c5189368b58356c53ac5a4da6e3b89a7c2835e906c046217d221eb8&origin=https%3A%2F%2Fx.com

### ISSUE THREAD

**Issue by 8848devil** [MicrosoftDocs/edge-developer#3222]
**Link to the documentation page**: The URL to the page.

**Description of the issue**: A clear and concise description of what the issue is.

**Screenshots**: If applicable, add screenshots to help explain the issue.

**Microsoft Edge version**: If the issue occurs with a specific version of Microsoft Edge.

**Comment by victoralves1275-del** [comment]
/victoralves1275@gmail.com

**Comment by alahaske-lang** [comment]
https://accounts.google.com/gsi/select?client_id=49625052041-kgt0hghf445lmcmhijv46b715m2mpbct.apps.googleusercontent.com&ux_mode=popup&ui_mode=bottom_sheet&as=b7ItDJhrGRtEMW602ztNZw&channel_id=747ff869aa62e4928a7709ef37e4160a22a8052a6652fc3ab8cf6ca0e8a09a45&origin=https://mobile.twitter.com&pli=1&authuser=0
