### ISSUE TITLE
Issue with Webview2 for opening Office documents from sharepoint server

### ISSUE THREAD

**Issue by bkimp** [MicrosoftDocs/edge-developer#3223]
Sharepoint 2016 server is now unable to utilize Webview2.
As documents are opened with Webview2, Sharepoint 2016 server is unable to use it as there is redirection loop to Identity Provider.
But identity provider page cannot be loaded.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de4d5de5-6690-7c62-6ed8-9b839a01b670
* Version Independent ID: 01abbd67-1b51-39e5-96dc-e1a7bbc0ae70
* Content: [Contact the WebView2 Team - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/webview2/contact)
* Content Source: [microsoft-edge/webview2/contact.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/contact.md)
* Service: **microsoft-edge**
* Sub-service: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out. This question is specific to the WebView2 product, not its documentation. Therefore, could you please open a new issue for this over on the dedicated WebView2Feedback repository?

Here is the link: https://github.com/MicrosoftEdge/WebView2Feedback/issues/new

Thanks for your understanding.
