### ISSUE TITLE
Shortcut not accurate

### ISSUE THREAD

**Issue by jgraff-esi** [MicrosoftDocs/edge-developer#323]
The dev console help page has:
Open file    Ctrl + P, Ctrl + O
...but Ctrl + P actually changes the console's docking behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7708ebf-b89b-168e-de02-bb00e9223318
* Version Independent ID: 48a20484-21fe-cbd3-7b84-f1992002eb63
* Content: [Microsoft Edge (EdgeHTML) Developer Tools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide?source=f12help#feedback)
* Content Source: [microsoft-edge/devtools-guide.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by GiovanniHD201E** [comment]
2019_12_26- In meine Kopie von Anwendung die Tastenkombination geklapt!
In my copie of this app the shortcut works. Using directly in Edge too.

**Comment by jgraff-esi** [comment]
Maybe I'm not explaining this right.  In the F12 help page :
https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide?source=f12help

the chord for "open file" is described as "Ctrl + P, Ctrl + O" but it is just Ctrl + O that does the action. Ctrl + P is not a part of it.  The help page should be updated.

**Comment by jm-trd-ms** [comment]
@jgraff-esi 
Can you please clarify whether you are using Microsoft Edge (EdgeHTML) or Microsoft Edge (Chromium) browser?

**Comment by jgraff-esi** [comment]
Help guide for EdgeHTML is the inaccurate one.  Can confirm either Ctrl + P or Ctrl + O works to open file in Chromium Edge as documented on that devtools help page.

**Comment by jm-trd-ms** [comment]
Your feedback resulted in changes to the documentation.
#645

**Comment by jm-trd-ms** [comment]
@jgraff-esi  
Per discussion with subject matter expert, the shortcuts represent the most recent version of Windows.  
Your requested changes to the content have not resulted in changes to the public content.  
Thank you for your feedback.
