### ISSUE TITLE
EULA Link for Microsoft Edge WebDriver Returns 404 Error

### ISSUE THREAD

**Issue by futuremaze** [MicrosoftDocs/edge-developer#3247]
**Link to the documentation page**: https://msedgedriver.azureedge.net/EULA

**Description of the issue**: On August 13, 2024, around 3:00 PM JST, I attempted to access the [EULA link](https://msedgedriver.azureedge.net/EULA) on the official [Microsoft Edge WebDriver page](https://developer.microsoft.com/ja-jp/microsoft-edge/tools/webdriver/?form=MA13LH), but encountered a 404 error. Multiple attempts yielded the same result.

**Screenshots**: <img width="1344" alt="スクリーンショット 2024-08-13 23 01 40" src="https://github.com/user-attachments/assets/cb4866de-3d65-49c9-a4a7-6a9341393fb7">

**Microsoft Edge version**: Occurs regardless of the version.

AB#53184357

**Comment by captainbrosset** [comment]
Thank you for filing this issue. I will raise it with the team and we'll start looking into it.

**Comment by captainbrosset** [comment]
The 404 issue has now been resolved. Closing this issue. Thank you for your patience.
