### ISSUE TITLE
Documentation Typo - Commerical

### ISSUE THREAD

**Issue by tgiphil** [MicrosoftDocs/edge-developer#3249]
**Commerical** should be spelled **commercial** in the following documentation:

Control Copilot with **Commerical** Data Protection access to browser context for Microsoft Entra ID profiles

This policy controls access to page contents, browser history, and user preferences for Copilot with **Commerical** Data Protection in the Edge sidebar. This policy applies only to Microsoft Entra ID profiles. To summarize pages and interact with text selections, it needs to be able to access the page contents. This policy does not apply to MSA profiles. This policy doesn't control access for Copilot without Commercial Data Protection. Access for Copilot without Commercial Data Protection is controlled by the policy CopilotPageContext. If you enable this policy, Copilot with **Commerical** Data Protection will have access to browser context. If you don't configure this policy, a user can enable access to browser context for Copilot with **Commerical** Data Protection using the setting toggle in Edge. If you disable this policy, Copilot with **Commerical** Data Protection will not be able to access browser context.

**Comment by captainbrosset** [comment]
@tgiphil Thank you for filing this. Can you please help understand where is the document that contains this typo located? I'm not finding the typo on our edge-developer documentation.

**Comment by captainbrosset** [comment]
Closing for now. Feel free to comment with an answer to my previous question and I can re-open the issue.
