### ISSUE TITLE
How to Add a Custom Add-in to the Sidebar?

### ISSUE THREAD

**Issue by CodeCube0** [MicrosoftDocs/edge-developer#3257]
![image](https://github.com/user-attachments/assets/0557798c-b49b-4596-8688-391904c4f7ca)

How can I add my own custom page in this position?

Can it also be added from Admin Center?

Can I prevent removal?

**Comment by captainbrosset** [comment]
Please refer to the documentation about the Edge sidebar here: https://www.microsoft.com/en-us/edge/features/sidebar?form=MA13FJ
You can add any site to the sidebar by clicking **Close Customize pane** and then **Open in sidebar**.

You can also create apps and browser extensions that appear in the sidebar, as documented here https://learn.microsoft.com/en-us/microsoft-edge/web-platform/sidebar

**Comment by CodeCube0** [comment]
> Please refer to the documentation about the Edge sidebar here: https://www.microsoft.com/en-us/edge/features/sidebar?form=MA13FJ
> 
> You can add any site to the sidebar by clicking **Close Customize pane** and then **Open in sidebar**.
> 
> 
> 
> You can also create apps and browser extensions that appear in the sidebar, as documented here https://learn.microsoft.com/en-us/microsoft-edge/web-platform/sidebar

can I control it through Admin Center?

**Comment by captainbrosset** [comment]
I don't think so. But you will find more answers to your questions at https://support.microsoft.com/en-us/microsoft-edge, and the ability to ask new questions at https://answers.microsoft.com/en-us/microsoftedge/forum
