### ISSUE TITLE
Sidebar Configuration

### ISSUE THREAD

**Issue by CodeCube0** [MicrosoftDocs/edge-developer#3259]
How can I configure the sidebar on the system side? Are there any policies that allow me to disable some functions and set a default Site List? Would it be possible to modify this configuration JSON that I find here "edge://sidebar-internals/"?

**Comment by captainbrosset** [comment]
Thanks for reaching out. However, this repository is for collecting issues and changes relative to the Edge developer documentation. Your questions are more specific to using Microsoft Edge. Can you please ask them again at https://support.microsoft.com/en-us/microsoft-edge ?
Thanks so much for your understanding.
