### ISSUE TITLE
PWA Builder Image Generator not working

### ISSUE THREAD

**Issue by elizsbarnes** [MicrosoftDocs/edge-developer#327]
After going to https://www.pwabuilder.com/imageGenerator per the tutorial instructions, I am unable to download any images, since what I assume is the download button self references to the same webpage URL. Attempted in both Chrome and Edge. Any advice on how to continue with this tutorial would be much appreciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcef5936-232e-1ab0-c1c4-77026c79e277
* Version Independent ID: b6ec450d-ead9-ffcf-0d5b-7a408bf0e13d
* Content: [Get started with Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/get-started#feedback)
* Content Source: [microsoft-edge/progressive-web-apps/get-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/get-started.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Backus125** [comment]
I ended up using http://cthedot.de/icongen/ to generate my icons.  You then have to manually type the array containing your images in the manifest.json file.  See https://developer.mozilla.org/en-US/docs/Web/Manifest for what that looks like.

**Comment by JasonBrown2K13** [comment]
Use https://app-manifest.firebaseapp.com/

**Comment by nkaredia** [comment]
Clone this -> https://github.com/pwa-builder/pwabuilder-Image-Generator
Run on Visual Studio 2017 or 2019. 
Open https://www.pwabuilder.com/imageGenerator
Submit form with the data you want.
Open dev tools and check network tab.
Open Postman and POST http request with same POST data, headers and multipart form data. Be sure send this data on localhost:{port} where your app is running.
This will take a while if you're using .svg files.
After success you'll receive a link. press Ctrl+Click to download the zip file.

**Comment by Reezaali** [comment]
We've updated the document [here](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/get-started). I'll go ahead and close this issue now. Thanks.
