### ISSUE TITLE
[Edge WebDriver Docs Feedback] Version Match between Browser Version and Webdriver Version

### ISSUE THREAD

**Issue by helfried-behrendt** [MicrosoftDocs/edge-developer#3270]
I missed the Information on how exact must the Version match between WebDriver and Browser be. That means, would a Browser with Version 128.0.2739.79 work with a WebDriver with Version 128.0.2739.84 or 128.0.2739.50? Must the main Match follow the first 3 Fields of the Version Number or Not?

AB#54011245

**Comment by captainbrosset** [comment]
I asked internally and got the following answer: only the 3 first components of the version number need to match.
For example:

Browser version 128.0.2739.79

would work with:

WebDriver version 128.0.2739.84

**Comment by helfried-behrendt** [comment]
Hi Patrick,
Thanks für clarifying that.

Kind regards
Helfried
Von: Patrick Brosset ***@***.***>
Gesendet: Dienstag, 24. September 2024 09:47
An: MicrosoftDocs/edge-developer ***@***.***>
Cc: Helfried Behrendt - IPG ***@***.***>; Author ***@***.***>
Betreff: Re: [MicrosoftDocs/edge-developer] [Edge WebDriver Docs Feedback] Version Match between Browser Version and Webdriver Version (Issue #3270)

Sie erhalten nicht oft eine E-Mail von ***@***.******@***.***>. Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

I asked internally and got the following answer: only the 3 first components of the version number need to match.
For example:

Browser version 128.0.2739.79

would work with:

WebDriver version 128.0.2739.84
