### ISSUE TITLE
[DevTools Docs Feedback]

### ISSUE THREAD

**Issue by carol706** [MicrosoftDocs/edge-developer#3273]
I do not work for anyone i want back my Administrator rights & my UAC I have never purchased any type of OFFICE this is my home computer all my rights have been taken away by some Administrator & password & taken over UAC no matter what I try my updates are blocked Troubleshooting The Wizard all blocked on 10/03/2022 I got a new motherboard Windows 10 22H2 version OS I had Malwarebytes installed but windows firewall security infiltrated evidently put my Lenovo &  WIN-QM1NE1H1PGP to sleep & returned my pc back to 2019 it says i have S version but microsoft store says i do not have S Malwarebytes blocks everything windows tells them I think a trogon has taken over & by-passed my security what happened to microsoft regular security it was great with my other security I do not want to do a clean install i'm 78 & not to savvy but i do know my pc is not fun anymore WiFi is blocked so is my att router I only have one domain yours no file & printer sharing no public it says everything is controlled by you administrator who ever the hell that is I do not know I tried blocking javascript that does not work eithor just said i could not sign-in to MicrosoftEdge!

**Comment by captainbrosset** [comment]
Sorry about the inconvenience, but this repository is specific to documentation issues related to Edge web development technologies. Your issues seem unrelated to that. So I'm going to close this. Thanks for your understanding.
