### ISSUE TITLE
IUnknown args?

### ISSUE THREAD

**Issue by tholp** [MicrosoftDocs/edge-developer#328]
Why is the args type IUnknown?

Is the interface not completed, or is it just dummy args, or ...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 478d9cc5-dba4-7449-7128-204a51ac719c
* Version Independent ID: 140f284c-98a1-adad-ce33-585b1f5ee18f
* Content: [Microsoft Edge WebView2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2focuschangedeventhandler#feedback)
* Content Source: [microsoft-edge/hosting/webview2/reference/IWebView2FocusChangedEventHandler.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/hosting/webview2/reference/IWebView2FocusChangedEventHandler.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by ewok-janitor** [comment]
https://en.wikipedia.org/wiki/IUnknown ?

**Comment by david-risney** [comment]
Thanks for checking out our preview interfaces! Yes the event args are IUnknown and nullptr here because there are no event arg properties to communicate. I've opened https://github.com/MicrosoftEdge/WebViewFeedback/issues/53
