### ISSUE TITLE
No continuation Result

### ISSUE THREAD

**Issue by tholp** [MicrosoftDocs/edge-developer#329]
Is it deliberate that this CompletedHandler have an Invoke that only takes one arguments?  (All other CompletedHandler's have two arguments).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f79802-c07c-022e-09b8-1248df125fb5
* Version Independent ID: 647f2fe0-405f-5ea3-85d6-f7ecc6a9492d
* Content: [Microsoft Edge WebView2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2capturepreviewcompletedhandler)
* Content Source: [microsoft-edge/hosting/webview2/reference/IWebView2CapturePreviewCompletedHandler.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/hosting/webview2/reference/IWebView2CapturePreviewCompletedHandler.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by david-risney** [comment]
Thanks! The sort of boilerplate text that is set for every async method's completed handler interface's Invoke method says you get the status and result but in this case you only get the status. The result is written to the stream provided in the CapturePreview method call. I've opened a doc issue for this: https://github.com/MicrosoftEdge/WebViewFeedback/issues/54
