### ISSUE TITLE
How to obtain IWebView2WebView3

### ISSUE THREAD

**Issue by tholp** [MicrosoftDocs/edge-developer#330]
IWebView2Environment::CreateWebView result in a IWebView2WebView object, where does an IWebView2WebView3 object come from.
Should we QueryInterface for it?

(Also isn't it a bit early to reach iXxxx3 before the first release?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ee94b40-dc6e-f3ce-099f-1e71489a08eb
* Version Independent ID: 9a166020-1f43-7c84-c0ce-71c7633d02d8
* Content: [Microsoft Edge WebView2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview3)
* Content Source: [microsoft-edge/hosting/webview2/reference/IWebView2WebView3.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/hosting/webview2/reference/IWebView2WebView3.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by david-risney** [comment]
Thanks for the feedback! We'll get back to your feedback faster if you file it on our https://github.com/MicrosoftEdge/WebViewFeedback/issues page. 

Yes you QueryInterface for it. I've opened https://github.com/MicrosoftEdge/WebViewFeedback/issues/52 to update our documentation.

For the first release we'll have a breaking change and squash all the versioned interfaces down to one interface. Eg. Everything in IWebView2WebViewN will be moved into IWebView2WebView.

**Comment by tholp** [comment]
OK, thank you.
