### ISSUE TITLE
[Edge WebDriver Docs Feedback] Mirroring Edge Driver

### ISSUE THREAD

**Issue by gitissuepost** [MicrosoftDocs/edge-developer#3316]
Hi Team,

As part my my company security policy, all external files should be accessed through our enterprise artifactory (jfrog).

Can you pleaase help me with the dteails to set up a remote for edge webdrivers. So we can leverage that to mirror teh required drivers in runtime.

Thanks

**Comment by captainbrosset** [comment]
Sorry about the delay here. I had missed this issue.
Can you please open the issue again on the https://github.com/MicrosoftEdge/EdgeWebDriver repository instead. That's where questions and feedback about _using_ Edge WebDriver need to go.
Thanks for your understanding.

**Comment by gitissuepost** [comment]
@captainbrosset - https://github.com/MicrosoftEdge/EdgeWebDriver/issues/179 has been logged for your reference.
