### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mapalko** [MicrosoftDocs/edge-developer#333]
The Windows Hello Test Drive demo leads to a page that is currently broken. The web app is failing with error 403. The web app should be fixed or this link should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 821eda1f-9154-4229-e023-83df97117a9d
* Version Independent ID: c7d27a3f-dc27-4bca-faa9-ccddbf3e61ce
* Content: [Dev guide - Web authentication - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/device/web-authentication#feedback)
* Content Source: [microsoft-edge/dev-guide/device/web-authentication.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/device/web-authentication.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jm-trd-ms** [comment]
@mapalko
Thank you for providing this feedback.

**Comment by jm-trd-ms** [comment]
Your feedback resulted in changes to the documentation. 
#628
