### ISSUE TITLE
[DevTools Docs Feedback]

### ISSUE THREAD

**Issue by ksayershoag** [MicrosoftDocs/edge-developer#3331]
Need to understand how to throttle or optimize the WebView2 processes on our VDI sessions. We have VDI sessions that are using 15/16 WebView2 processes on each session and the Memory associated with Microsoft Teams ranges from 200MB 900MB +
![msedgewebviewer2](https://github.com/user-attachments/assets/7ea05925-eb5e-437f-af9b-f70458f15f5d)
![msedgewebviewer2-memfromteams](https://github.com/user-attachments/assets/ff6b372b-9eb6-4b15-8c8e-b156b17f2349)

Need to understand how to optomize the webView 2 process in a Citrix VDI session

**Comment by captainbrosset** [comment]
Thank you for reaching out. This question is specific to using WebView2, not specific to its documentation. Therefore, could you please open a new issue for this over on the dedicated WebView2Feedback repository?

Here is the link: https://github.com/MicrosoftEdge/WebView2Feedback/issues/new

Thanks for your understanding.
