### ISSUE TITLE
How to disables it 

### ISSUE THREAD

**Issue by he1986yuan** [MicrosoftDocs/edge-developer#340]
When I update my Win10 Sys,and I press F12 in my own Browser(core chrome),this dev tools will show .and just for the vue page will show this tools.I prefer to use the original dev tools with the browser  ,please tell me how to disabled it !  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7708ebf-b89b-168e-de02-bb00e9223318
* Version Independent ID: 48a20484-21fe-cbd3-7b84-f1992002eb63
* Content: [Microsoft Edge (EdgeHTML) Developer Tools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide#feedback)
* Content Source: [microsoft-edge/devtools-guide.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by Reezaali** [comment]
@he1986yuan are you having the same issue in the new Microsoft Edge?

**Comment by Reezaali** [comment]
I'll go ahead and close this issue. Thanks!
