### ISSUE TITLE
Missing code sample

### ISSUE THREAD

**Issue by JudahGabriel** [MicrosoftDocs/edge-developer#354]
We're missing a sample here. The doc says, "For example, suppose you have a COM object with the following interface", then the code sample is blank.

![image](https://user-images.githubusercontent.com/312936/67820420-57f0e200-fa76-11e9-8747-a5a42b3f2c8f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea9f905-2f7a-c907-5fa1-d9d055b7fc7c
* Version Independent ID: 18bb72ed-c55d-a44b-844d-66f5109de217
* Content: [Microsoft Edge WebView2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview4#feedback)
* Content Source: [microsoft-edge/hosting/webview2/reference/IWebView2WebView4.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/hosting/webview2/reference/IWebView2WebView4.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by david-risney** [comment]
Oops. Thanks, we'll fix this!

**Comment by liminzhu** [comment]
@pagoe-msft helped patch the docs yesterday 😃 . https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview4#addremoteobject should be correct now.
