### ISSUE TITLE
Does not work because of incompatible version

### ISSUE THREAD

**Issue by mariusbancila** [MicrosoftDocs/edge-developer#362]
I followed the steps described in the article but the web view is not created because the callback is never called. I have Edge Beta (from [here](https://www.microsoftedgeinsider.com/en-us/download/)) **Version 78.0.276.24 (Official build) beta (64-bit)**. This is greater than the minimum requirement of **78.0.270.0**. I also set this browser as the default one in Windows.

The only thing that I see in the output window when debugging is the following:

> Loader skipped an incompatible version: C:\Program Files (x86)\Microsoft\Edge Beta\Application\78.0.276.24

Why is my version incompatible and how do I get this working?

**Comment by Reezaali** [comment]
Hi @mariusbancila, sorry to hear that this isn't working as expected. Have you tried using the new Microsoft Edge?

**Comment by Reezaali** [comment]
I'll proceed to close out this issue now. Thank you.
