### ISSUE TITLE
Microsoft

### ISSUE THREAD

**Issue by audas** [MicrosoftDocs/edge-developer#37]
Honestly - what are you doing ?

Where is the service worker ? Where is the code ?

The code in the video is entirely different from the code in code pen ?

Why are we using code pen and not Github ?

There is a reason your browser is failing - it boggles the mind that you are still behaving like this.

Dropping all support of Microsoft. The lack of compliance is just too costly.

Just want to add that I went to Code Pen - and code has absolutely no similarity to the code in video or the code presented in the Edge Docs.

This is absurdity on the most basic level. 

Fed up.

**Comment by erikadoyle** [comment]
Could you please provide more details on what particular video and code examples that you found confusing and/or frustrating? You could either reply back to this or leave a comment at the bottom of the specific doc.

For now I'm going to close this issue until we can make it more actionable.

**Comment by audas** [comment]
Web Push Notifications with service workers.

These are available now - for TWO YEARS in Chrome, Firefox, Safari, Opera.

Still no service workers in Microsoft. Mind blown. Literally the most important feature in web browsers in the last two years.

From the docs -
https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/device/web-notifications-api

Which links to here and codepen and is COMPLETELY different code to the video presented. There is literally no option offered anywhere at all by Microsoft to offer users the ability to copy the code in the video for testing either. To try it - users must pause the video and type it out by hand.

Honestly - wast this put together by someone who has never used the internet ?

https://codepen.io/MicrosoftEdgeDocumentation/pen/RGbxWW/

**Comment by abbycar** [comment]
Thanks for the thorough response! :)

The doc you're referring to is about the Web Notifications API. This API doesn't require Service Worker support. It seems you might be looking for documentation about the [Push API](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/serviceworker/) which does require Service Worker.

In regards to the Web Notifications API doc though, I just updated the CodePen to reflect the code in the video.

At this point, the [Push API](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/pushapi/?q=push%20api) and [Service Worker](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/serviceworker/) are is still in development. However, you can still try out their current state in Microsoft Edge by enabling them in [about:flags](https://docs.microsoft.com/en-us/microsoft-edge/f12-devtools-guide/settings) on the latest [Windows Insider Preview](https://insider.windows.com/en-us/) builds.

The Microsoft Edge team will be sharing the latest details of Service Worker and PWA support at next month's [Microsoft Edge Web Summit](https://summit.microsoftedge.com/#schedule).
