### ISSUE TITLE
developer toolbar broken

### ISSUE THREAD

**Issue by jwisener** [MicrosoftDocs/edge-developer#377]
broken toolbar, at least offer a way to get it open opening instead of just a blank area.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7708ebf-b89b-168e-de02-bb00e9223318
* Version Independent ID: 48a20484-21fe-cbd3-7b84-f1992002eb63
* Content: [Microsoft Edge (EdgeHTML) Developer Tools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide#microsoft-store-app)
* Content Source: [microsoft-edge/devtools-guide.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by Reezaali** [comment]
@jwisener I'm sorry to hear about this issue. Have you tried using the new Microsoft Edge, and does it resolve your issue?

**Comment by jwisener** [comment]
I stopped using this, and just continue to use chrome instead

**Comment by Reezaali** [comment]
Ok thanks for the reply. I'll go ahead and close the issue now.

**Comment by jwisener** [comment]
Thanks
