### ISSUE TITLE
The publishing process is already working?

### ISSUE THREAD

**Issue by felipepessoto** [MicrosoftDocs/edge-developer#397]
I tried to upload the ZIP file several times and it hangs. After minutes it retunred this error:

The following checks failed:
Package acceptance validation error: ValidationFatal UnsuccessfulHttpRequestException thrown with message: Unsuccessful status code of InternalServerError returned by https://general-a-eus2.falconprod-sf.trafficmanager.net/extensionassetvalidator/v1/validate. Content: Code: PAC-ValidationFatal

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 303075ec-ed9b-7ba4-15c5-242f93d53eb2
* Version Independent ID: 15d3653d-af25-8ee7-2e94-01057a734de4
* Content: [Publish An Extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension#feedback)
* Content Source: [microsoft-edge/extensions-chromium/publish/publish-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/publish/publish-extension.md)
* Product: **microsoft-edge-chromium**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by WesselKroos** [comment]
I was able to upload my extension today. Although it failed on the first upload. So you might have to retry it a few times.

**Comment by felipepessoto** [comment]
Still not working for me

**Comment by Unumpuer** [comment]
Same error

`ValidationFatal UnsuccessfulHttpRequestException thrown with message: Unsuccessful status code of InternalServerError returned by https://general-a-eus2.falconprod-sf.trafficmanager.net/extensionassetvalidator/v1/validate. Content: Code: PAC-ValidationFatal`

**Comment by WesselKroos** [comment]
Have you tried it in some other browsers as well? I'm not sure in which browser I've uploaded it in the end.

**Comment by Unumpuer** [comment]
Lets me check some other _Chromium_

**Comment by Unumpuer** [comment]
Unsuccessful 

![Screenshot_1](https://user-images.githubusercontent.com/59127962/72500869-bdfb3300-3835-11ea-8953-2df31039d5ec.jpg)

**Comment by WesselKroos** [comment]
There might be a better way to contact Microsoft. Because I've seen no one from Microsoft here.

**Comment by patuwwy** [comment]
Do You have manifest.json in zip? or folder with manifest.json in zip?

**Comment by Unumpuer** [comment]
Hello @patuwwy, tested with both. it works in the Chrome developer dashboard.

**Comment by WesselKroos** [comment]
Can you post a link to the zip you are trying to upload? Maybe there is something missing or invalid.

**Comment by Unumpuer** [comment]
I don't know why, all data are correct

![Screenshot_1](https://user-images.githubusercontent.com/59127962/73242808-3b179800-41a6-11ea-8c93-ad72b08b28da.jpg)

**Comment by savies** [comment]
I have the same issue as felipepessoto, the uploading process hangs without any outcome. I have tried few times, even with the extension which attached to "Getting Started Tutorial". I have a company account that was authorized.

**Comment by WesselKroos** [comment]
> I have the same issue as felipepessoto, the uploading process hangs without any outcome. I have tried few times, even with the extension which attached to "Getting Started Tutorial". I have a company account that was authorized.

It may sound strange, but can you try uploading it from another ip address/network.

Another thing no one tried yet is uploading it from another device. You may try it from your phone, laptop, desktop or tablet.

Since it's a server error it could also be Azure related. Because I think the website is hosted in Azure. There are multiple Azure server parks in the world. You may try to connect with another server park by uploading it via a VPN in another continent.

Those are just some guesses, but the 3 things we haven't tried yet.

**Comment by savies** [comment]
> > I have the same issue as felipepessoto, the uploading process hangs without any outcome. I have tried few times, even with the extension which attached to "Getting Started Tutorial". I have a company account that was authorized.
> 
> It may sound strange, but can you try uploading it from another ip address/network.
> 
> Another thing no one tried yet is uploading it from another device. You may try it from your phone, laptop, desktop or tablet.
> 
> Since it's a server error it could also be Azure related. Because I think the website is hosted in Azure. There are multiple Azure server parks in the world. You may try to connect with another server park by uploading it via a VPN in another continent.
> 
> Those are just some guesses, but the 3 things we haven't tried yet.

I tried to upload it via another network, and it works fine. Thanks:)

**Comment by WesselKroos** [comment]
Aha, then we have finally found an issue!

My guess would be that the server remembers something per ip address that blocks the upload process. Or the connection itself can become corrupt per ip address.

**Comment by JNavas2** [comment]
Disable any ad blocker you might be running.
I had to disable uBlock Origin.

**Comment by gebansal** [comment]
If you are facing any issues with respect to the publishing process, please feel free to write to us at ext_dev_support@microsoft.com. We'll try our best to resolve the issue.
