### ISSUE TITLE
Canary & Dev do receive UA overrides

### ISSUE THREAD

**Issue by mgol** [MicrosoftDocs/edge-developer#398]
Hi, the text says:

> Our Canary and Dev channels do not currently receive UA overrides

but I checked Edge Beta, Dev & Canary on macOS Catalina 10.15.2 (19C57) and all 3 receive UA overrides. I checked edge://compat/useragent - all 3 versions receive similar entries. Also, I opened one of the entries in all 3: namely, https://play.google.com/store and checked `navigator.userAgent` in the DevTools console and the overrides did get applied.

It looks like the docs are incorrect. Which behavior is intended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0130ae-2318-e95c-a77d-669d2c5dc8b8
* Version Independent ID: 3fcc0df5-94ed-6a3d-5c3f-78229329288c
* Content: [Microsoft Edge User Agent String - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string#feedback)
* Content Source: [microsoft-edge/web-platform/user-agent-string.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/user-agent-string.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by scottlow** [comment]
@mgol Thanks for letting us know! The behavior the docs specifies is correct. I'll investigate this morning to see if I can figure out what's going on.

**Comment by scottlow** [comment]
This was caused by the fact that we weren't sending the proper "clear" signal to macOS clients. We pushed a change to do this and verified that UA overrides are no longer present in Canary and Dev channels on any platform.

**Comment by mgol** [comment]
I confirm it works as documented now, thanks!
