### ISSUE TITLE
Translate page titles

### ISSUE THREAD

**Issue by GiovanniHD201E** [MicrosoftDocs/edge-developer#402]
I like to see text in German, in spite of I am Brasilian und can read in English.
I ask to translate only title pages I use to access whenever the message warning: (not literal) "This page is not available in selected language. Here is the English version". I intend to mantain the original title as a subtitle in this way: 
                                 Title (in German)
Original Title (in English)

**Comment by G-Couvert** [comment]
Imperialism.

**Comment by Reezaali** [comment]
Hi @GiovanniHD201E and @G-Couvert, thanks for your feedback. I wanted to let you know that we published localized versions of the topics. I'll go ahead and close this issue now. Thanks again.
