### ISSUE TITLE
Will be there an API to publish new versions?

### ISSUE THREAD

**Issue by stefanbuck** [MicrosoftDocs/edge-developer#406]
Are there any plans to allow publishing of new versions using an API like https://developer.chrome.com/webstore/using_webstore_api?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 303075ec-ed9b-7ba4-15c5-242f93d53eb2
* Version Independent ID: 15d3653d-af25-8ee7-2e94-01057a734de4
* Content: [Publish An Extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension#feedback)
* Content Source: [microsoft-edge/extensions-chromium/publish/publish-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/publish/publish-extension.md)
* Product: **microsoft-edge-chromium**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by ClementVidal** [comment]
I'm joining @stefanbuck regarding his question.
Having to manually push update on store is a real bottleneck here.

At least having just one api to push new update from our CI chain will be really nice.

Is there any plan on that or is it just out of scope for the moment ?

**Comment by gebansal** [comment]
This scenario is in our backlog and will be picked up soon.

**Comment by Reezaali** [comment]
I'll proceed to close out this issue. You can also add and upvote your feature requests on [UserVoice](https://microsoftedge.uservoice.com/). Thank you.

**Comment by larry-xu** [comment]
@gebansal are there any updates on this issue? Google and Mozilla both support API's for publishing Chrome and Firefox extensions, respectively. It would be very useful to support similar API's for Edge extensions as well.
