### ISSUE TITLE
Your package failed certification. Make corrections and certify again.

### ISSUE THREAD

**Issue by vrgomes** [MicrosoftDocs/edge-developer#407]
Hi, I'm having this error uploading a .zip file to the Developer console.
Please see the image:
![1](https://user-images.githubusercontent.com/3107574/71787664-b310f900-3012-11ea-8cf7-43f3d0e4ebff.png)

It says:
The following checks failed: Error
And don't say anything else... It should say what is the error.

Can you please say what is happening?
Greetings.

**Comment by WesselKroos** [comment]
I also got this error the first time I uploaded my extension. Then I re-uploaded the zip and it succeeded. So my guess would be that it got aborted somewhere in the uploaded process on the server.

You might have to retry it a few times.

**Comment by Reezaali** [comment]
@vrgomes were you able to get past the error?

**Comment by vrgomes** [comment]
Hi, now the error is not happening any more.
Greetings.

**Comment by Reezaali** [comment]
Thanks for replying. I'll go ahead and close the issue. Thanks.
