### ISSUE TITLE
WebView2 sample app does not work

### ISSUE THREAD

**Issue by mariusbancila** [MicrosoftDocs/edge-developer#415]
Hi,

I have followed all the instructions from [Getting Started with WebView2 (developer preview)](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/gettingstarted) to create an app that is using Microsoft Edge (Chromium). However, it is not able to find the Edge browser. I also tried the [sample app](https://github.com/MicrosoftEdge/WebView2Browser) but with the same results. I have built the app both for 32- and 64-bit. 

What I get from calling `CreateWebView2EnvironmentWithDetails()` is 0x80070002, which is `ERROR_FILE_NOT_FOUND` (The system cannot find the file specified.)

I have:
- Edge Version 79.0.309.60 (Official build) beta (64-bit)
- Windows 10.0.17134
- Visual Studio 2019 16.4.2

Why isn't it able to find the Edge installation?

**Comment by Reezaali** [comment]
@mariusbancila I've copied the issue to: https://github.com/MicrosoftEdge/WebViewFeedback/issues/164.

I'll go ahead and close this issue. Thanks.
