### ISSUE TITLE
Is this list of issues read by anyone at Microsoft?

### ISSUE THREAD

**Issue by WesselKroos** [MicrosoftDocs/edge-developer#417]
I've just answered some issues that have been open for a month without a response. Is there anyone at Microsoft that reads these issues? Because I see ~50 issues without any response.

Or should I see this list of issues like a forum for developers on which they can answer each other's questions?

**Comment by gergelyszabo94** [comment]
Since 12 days have passed without a reaction I think we got our answer.

**Comment by Reezaali** [comment]
@WesselKroos and @gergelyszabo94 - I apologize for the lack of communication, and thank you for the feedback.
