### ISSUE TITLE
Certification time

### ISSUE THREAD

**Issue by Pheil** [MicrosoftDocs/edge-developer#429]
My extension has the status "Microsoft is reviewing your submission right now" for 31 days so the "up to 7 business days" line should be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 303075ec-ed9b-7ba4-15c5-242f93d53eb2
* Version Independent ID: 15d3653d-af25-8ee7-2e94-01057a734de4
* Content: [Publish An Extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension?branch=extensions-documentation#feedback)
* Content Source: [microsoft-edge/extensions-chromium/publish/publish-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/publish/publish-extension.md)
* Product: **microsoft-edge-chromium**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by WesselKroos** [comment]
My extension got approved within 7 days. So it might not get approved unless you contact Microsoft.

**Comment by Pheil** [comment]
Hmm.  I found "ExtensionPartnerOps@microsoft.com", but not sure if that's the correct contact.  There should be something on the partner page that makes contacting easier.

**Comment by JNavas2** [comment]
"Microsoft is reviewing your submission right now" in Extension Overview
is likewise misleading, and should be changed! My experience:

- Approval in Google (Chrome): prompt
- Approval by Mozilla (Firefox): very fast
- Approval by Microsoft (Edge): the check is in the mail

Makes me question why I did an Edge version of my extension.

**Comment by JNavas2** [comment]
**UPDATE**: Not as bad as I expected.
Took 2 days to get a rejection.
The reasons were silly, easily fixed, and I've resubmitted.
Will be interesting to see how long it takes this time,
and if I'll have to go through any more cycles.
