### ISSUE TITLE
Option to use the same media (screenshots, logos, tiles) for multiple/all locales?

### ISSUE THREAD

**Issue by gergelyszabo94** [MicrosoftDocs/edge-developer#440]
It would be nice if I did not have to manually upload the same images for every single locale.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 303075ec-ed9b-7ba4-15c5-242f93d53eb2
* Version Independent ID: 15d3653d-af25-8ee7-2e94-01057a734de4
* Content: [Publish An Extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension#feedback)
* Content Source: [microsoft-edge/extensions-chromium/publish/publish-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/publish/publish-extension.md)
* Product: **microsoft-edge-chromium**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by alexanderby** [comment]
I have 30 locales and submitting a logo, tiles and screenshots for each is ridiculous.

**Comment by gergelyszabo94** [comment]
@alexanderby yes it absolutely is, I guess at least I don't feel dumb now for not seeing any option to work around that.

**Comment by muzuiget** [comment]
Yes, this shock me I found out I have to upload images and fill the forms for each locales.

So, we can sure Edge Store developers didn't try their own dog food.

**Comment by gebansal** [comment]
We understand your concern. The work being done for this is in progress and should be rolled out soon. I am hoping the new design should address all these concerns and more.

**Comment by gebansal** [comment]
The feature is now live. 
1. You can choose to duplicate or copy your assets across all languages without having to manually upload for all languages.
2. You can choose to remove languages from store details page if you do not have the details localized for a language.

Write to us at ext_dev_support@microsoft.com if you have any more feedback, we would love to put it in our backlog and work on it.
