### ISSUE TITLE
End result does not work

### ISSUE THREAD

**Issue by stejmurphy** [MicrosoftDocs/edge-developer#443]
New to extension writing and thought I would give this a go on the new Chromium Edge (79, stable channel)

From walking through this tutorial I was met with an error at the very end and I've not been able to resolve it.

I reverted to the supplied completed version and this also does not work out of the box on fresh install of the extension.

Can we get someone to review this content? 

Error:
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
Stack Trace
popup/popup.html:0 (anonymous function)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec889040-6707-74fd-9086-d838c15a9172
* Version Independent ID: 73d6355a-b256-c8ab-9889-c51603d3052b
* Content: [Dynamically Insert NASA Picture Below The Page Body Tag Using Content Scripts - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts#feedback)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md)
* Product: **microsoft-edge-chromium**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by sturdeac** [comment]
Why did you close this? I am also getting this error.

**Comment by stejmurphy** [comment]
Hey @sturdeac, I figured it out just after reporting this. The supplied code and my own is working as designed but they forgot one key point.

Your active tab needs to be on an actual website for it to work. 

EG, Open Google.com and it should work

**Comment by Unkind-Chris** [comment]
Doesn't work properly even if on a website. The download version neither works in chrome or edge properly either.
Does display an image placeholder in the active (online) tab that is approx 10x10 but that is it and it errors
