### ISSUE TITLE
regarding Paths.

### ISSUE THREAD

**Issue by shirshak55** [MicrosoftDocs/edge-developer#445]
As puppeteer is used in linux/macos too and memorizing those paths are usually not necessary I have made a package to assist it. Please find it here https://github.com/shirshak55/edge-paths.

we can use it like this:
```
const edgePaths = require("edge-paths");


// On Windows

edgePaths.edge; // 'C:\\Program Files (x86)\\Microsoft\\Edge Dev\\Application\\msedge.exe'


```
Currently supports windows. Once underlying package support macs and linux i will add support asap :)

Thanks Microsoft for making fastest browser in the universe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa0e4d86-12ac-7f7e-1c06-66377987487e
* Version Independent ID: 52fa943b-5a87-0d35-1d89-a2a627486061
* Content: [Puppeteer - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/puppeteer#feedback)
* Content Source: [microsoft-edge/puppeteer.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/puppeteer.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @zoherghadyali
* Microsoft Alias: **zoghadya**

**Comment by ststimac** [comment]
This is for @zoherghadyali to weigh in on. This is beyond my technical knowledge.

**Comment by zoherghadyali** [comment]
Hi @shirshak55! Thank you for creating the edge-paths package on npm and making it easier to get the executable path to Edge! I tried it out on Windows with this snippet: 

```js
const edgePaths = require("edge-paths");
console.log("Windows Edge path", edgePaths.edge);
```
but what I see logged is: `Windows Edge path C:\Users\zoghadya\Documents\My_Apps\DevTools-todomvc\node_modules\edge-launcher\dist\x86\MicrosoftEdgeLauncher.exe` which isn't what I expected. I expected edgePaths.edge to point to my installation of stable Microsoft Edge: `C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe`. 

Please let me know if this is a bug and I'm happy to try again! I would also like to request a way to provide the paths to Edge Canary, Dev, and Beta as well as the Stable Edge channel. Thanks!

**Comment by shirshak55** [comment]
@zoherghadyali hey there can u give me list of all paths. I don't have windows so it is abit hard for me to figure it out

Windows
Edge Stable: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Edge Canary: C:\Program Files (x86)\Microsoft\Edge SxS\Application\msedge.exe
others (Confirm edge canary path)


On OSX the path i receive are 
```
Beta: /Applications/Microsoft Edge Beta.app/Contents/MacOS/Microsoft Edge Beta
Canary: /Applications/Microsoft Edge Canary.app/Contents/MacOS/Microsoft Edge Canary
Dev: /Applications/Microsoft Edge Beta.app/Contents/MacOS/Microsoft Edge Dev
Stable: /Applications/Microsoft Edge Beta.app/Contents/MacOS/Microsoft Edge
```

**Comment by shirshak55** [comment]
I have tried to check windows paths currently it returns 

```
C:\Program Files (x86)\Microsoft\Edge Beta\Application\msedge.exe
C:\Program Files (x86)\Microsoft\Edge Canary\Application\msedge.exe
C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe
C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
```

I hope its correct.

**Comment by shirshak55** [comment]
Would you mind reconfirming

Typescript
```
import { getEdgeBetaPath, getEdgeCanaryPath, getEdgeDevPath, getEdgePath } from "edge-paths"

console.log(getEdgeBetaPath())
console.log(getEdgeCanaryPath())
console.log(getEdgeDevPath())
console.log(getEdgePath())
```

Or Javascript
```
let { getEdgeBetaPath, getEdgeCanaryPath, getEdgeDevPath, getEdgePath } = require("edge-paths") // Replace with require("edge-paths")

console.log(getEdgeBetaPath())
console.log(getEdgeCanaryPath())
console.log(getEdgeDevPath())
console.log(getEdgePath())
```
