### ISSUE TITLE
Edge extension toolkit changes chrome_url_overrides property to browser__ and breaks

### ISSUE THREAD

**Issue by dChin84** [MicrosoftDocs/edge-developer#452]
Currently using chrome_url_overrides property in the manifest.json to utilise url/page overrides for display of a custom page when a new tab is opened. When using the edge extension toolkit it changes the property to browser_url_overrides and stops the new tab from working correctly. If i change it back to chrome_url_overrides it seems to work ok. Is this feature supported? also Is it possible to submit the extension to the store with a chrome property in the manifest?

**Comment by gebansal** [comment]
@dChin84 We believe there is some confusion with respect to the old edge and new edge browser extension submission experience. 
For old edge extension submissions, we had this toolkit to convert Chrome extensions into edge extensions. For the new edge browser, an extension can be submitted without any changes.
The support for the old edge browser is soon going to be replaced on users' machines and we are not accepting any new extension submissions for the same. We recommend submitting your extensions for the new edge browser instead.
Please let us know if you need any help with that by either reopening this issue or creating a new one.
