### ISSUE TITLE
ReferenceError: browser is not defined

### ISSUE THREAD

**Issue by CreedsCode** [MicrosoftDocs/edge-developer#463]
**The page is a little bit out to date!**
If you get the same reference error and are using the chromium based edge browser.
The solution is to replace the "browser" to "chrome"

before:
reset.onclick = () => {
  browser.tabs.insertCSS({code: "body { background: none !important; }"});
};

after:
reset.onclick = () => {
  chrome.tabs.insertCSS({code: "body { background: none !important; }"});
};

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e322d0db-8a91-6fff-7510-a5ec18fa4a65
* Version Independent ID: 0c60d518-08f5-3b4e-0f4b-b7cd71455951
* Content: [Creating an extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/creating-an-extension#feedback)
* Content Source: [microsoft-edge/extensions/guides/creating-an-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/creating-an-extension.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@CreedsCode - I've edited the note at the top of the article to link to the Chromium documentation, where the correct code samples can be found. This update should go live soon. Thank you.
