### ISSUE TITLE
Chrome 80 changes

### ISSUE THREAD

**Issue by ShadowSharmon** [MicrosoftDocs/edge-developer#468]
This page conflicts with this one &lt;that says MS Edge will not be adopting the change: https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/chrome-behavior-affects-applications

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e08a40c-6a79-a8f1-64e6-8befc952684f
* Version Independent ID: e1ab6543-67eb-bc78-8466-2315d3906d2c
* Content: [Site compatibility-impacting changes coming to Microsoft Edge - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/site-impacting-changes#feedback)
* Content Source: [microsoft-edge/web-platform/site-impacting-changes.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/site-impacting-changes.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by ericlaw1979** [comment]
The text of the chrome-behavior-affects-application page notes: "Microsoft Edge browser on Chromium (**version 80**) will not be affected by these SameSite changes. You can read the Edge documentation to see the current plan for adapting this change."

**Comment by Reezaali** [comment]
@ShadowSharmon - I'm closing the issue as it appears to have been resolved. Thank you!
