### ISSUE TITLE
Send feedback about this product link broken on bottom of Edge docs

### ISSUE THREAD

**Issue by stevennyman** [MicrosoftDocs/edge-developer#473]
At the bottom of docs for the new Microsoft Edge, the send feedback about this product link goes to https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer, which no longer exists and returns a 404 error code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f290aba-5618-9b79-e3ac-243ec8cc4dd6
* Version Independent ID: 0cda1705-27db-4282-40e1-a2fbbd16ed2e
* Content: [Alternate Method of Distributing Extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md)
* Product: **microsoft-edge-chromium**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@stevennyman thanks for reporting this issue. The issue has now been fixed.
