### ISSUE TITLE
Use of DesiredCapabilities has been deprecated in favor of browser-specific Options classes

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/edge-developer#478]
Using DesiredCapabilities is deprecated. Driver built by this approach is not so ideal for long time. Documentation has to mention that its relying either on unstable alpha releases or using deprecated APIs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107ce527-7b9c-ff4e-e524-a8ebbc1a6714
* Version Independent ID: 6c8de68a-01bf-3426-8427-6daa5dca5f03
* Content: [WebDriver (Chromium) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium#feedback)
* Content Source: [microsoft-edge/webdriver-chromium.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @zoherghadyali
* Microsoft Alias: **zoghadya**

**Comment by zoherghadyali** [comment]
I'm closing this issue as we've removed our samples using `DesiredCapabilities`. The latest [Selenium alpha](https://www.selenium.dev/downloads/) now has a `useChromium` property. You can refer to the provided samples in our [WebDriver guide](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium#selenium-400-alpha05-and-newer).

For developers who want to stay on Selenium 3, we've released the [Selenium Tools for Microsoft Edge](https://github.com/microsoft/edge-selenium-tools) which extends Selenium 3 to add support for the new Chromium-based Microsoft Edge. You can read more about getting started with the Selenium Tools for Microsoft Edge in our [WebDriver guide](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium#selenium-3).
