### ISSUE TITLE
Documentation for some old IE specific API's redirects to unhelpful MDN page

### ISSUE THREAD

**Issue by kimmccoy** [MicrosoftDocs/edge-developer#48]
I am trying to update an old website to work without compatibility mode. In the code I am working on there are numerous references to IE specific methods and properties going back to IE5

When I google/bing them I get a link to the helpful MSDN page which redirects to the unhelpful MDN web api directory page.

Eg)
"replaceNode method (Internet Explorer) - msdn.microsoft.com"
https://msdn.microsoft.com/en-us/library/ms536719(v=vs.85).aspx
![image](https://user-images.githubusercontent.com/6612899/32581395-c8025ecc-c524-11e7-8e8a-66e6837d451f.png)

Redirects to:
https://developer.mozilla.org/en-US/docs/Web/API

Also:
Element.removeNode(bool) can't be found on MDN as it is ancient IE stuff (that I still have to work with today).

It would be much better if I could see the old pages if there is no matching page in MDN rather than a redirect to a A-Z directory page which is of zero help.

I was using the pages cached by google/bing but they are now disappearing.

**Comment by erikadoyle** [comment]
Apologies for the inconvenience @kimmccoy. I had suspended the redirects for most of the proprietary APIs while we're porting the content to MDN, however I obviously missed some. The MSDN doc for Element.removeNode(bool) is still available here:  https://msdn.microsoft.com/en-us/library/ms536708

Besides replaceNode(), what other API docs are you missing? If you can reply with a list, I'll make sure to reinstate them asap. Thanks!

If it helps, replaceNode() is intended to be called upon the node to be replaced, which is also returned:

var replacedObject = objectToBeReplaced.replaceNode(replacementObject);

**Comment by kimmccoy** [comment]
Hi Erika, thank you very much for the help. I don’t really have a list of api’s as I just come across these old bits of IE as I’m porting a very old web site to work with Edge/Chrome etc. 

I’m now tacking some .htc files and have found that docs for that so that is fantastic.

Many Thanks
Kim

Sent from Mail for Windows 10

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.
