### ISSUE TITLE
Not able to load extensions using EdgeOptions.

### ISSUE THREAD

**Issue by Shandilyatanay** [MicrosoftDocs/edge-developer#482]
I am trying to load extension to the edge browser when the browser is launched. The extension is a .crx file and I don't see addExtensions method in EdgeOptions class. What is the other way around. Please help.

**Comment by gebansal** [comment]
You can try side-loading your extension on the browser launch. Please find the steps for the same here: https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension#run-your-extension-locally-in-your-browser-while-developing-it-side-loading

Please let us know if this addresses your concern.
