### ISSUE TITLE
This is broken in the latest edge.

### ISSUE THREAD

**Issue by rlynch99** [MicrosoftDocs/edge-developer#488]
As a developer it was always nice to be able to easily change and set the browser emulation. I can no longer find this feature. It seems like a giant step backwards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9455f5ae-148e-a255-4f24-6109e30e3568
* Version Independent ID: c26cff0e-9087-bada-54ef-2a78abd3eff2
* Content: [DevTools - Emulation - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/emulation#feedback)
* Content Source: [microsoft-edge/devtools-guide/emulation.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/emulation.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by ststimac** [comment]
@rlynch99 are you referring to the latest version of EdgeHTML or Edge on Chromium?

**Comment by rlynch99** [comment]
Edge on Chromium

**Comment by zoherghadyali** [comment]
Hi @rlynch99! Thank you for sending us your feedback. I wanted to let you know that there is a way to simulate mobile devices in the Edge DevTools. With the DevTools open, press `Ctrl`+`Shift`+`M` or click ![image](https://user-images.githubusercontent.com/34316555/80178566-60ece700-85b3-11ea-94c7-129a72996d17.png) to toggle the Device Toolbar. This modifies the viewport to either be in a responsive state or to match the selected device. 

You can learn more about simulating mobile devices in [our documentation](https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/device-mode/).

**Comment by KoenigseggRS** [comment]
I would like to simulate other browsers, such as Chrome, or IE, but I do not see a way to do so.

**Comment by rlynch99** [comment]
KoenigseggRS… totally with you there.. I guess we cant get rid of the old version of Edge.. fortunately the co-exist on the same system quite effectively.
(I still really miss the ruler that existed on IE10?)

**Comment by KoenigseggRS** [comment]
I only used the new Edge for video calls, but I enjoyed the old developer panel since it was more clear where everything was. Hoping if they update this so they can do what the old developer tools for Edge did.

**Comment by hxlnt** [comment]
Hi, @KoenigseggRS @rlynch99. In the new Edge DevTools, you are able to simulate other browsers by changing the user agent string in the Network conditions tab.

![image](https://user-images.githubusercontent.com/9647195/83185732-0afaea00-a0f1-11ea-9876-aa579fcb8174.png)

Does this address your concern?

P.S. You can also enable rulers in DevTools Settings. Look for the "Show rulers" checkbox under the Elements heading.
