### ISSUE TITLE
webauthn, excludeCredentials, and Windows

### ISSUE THREAD

**Issue by ctro** [MicrosoftDocs/edge-developer#493]
👋 Hi, I have a webauthn example that works on various OSes and many different browsers.
We make use of the `excludeCredentials` option. 
We've been getting reports of webauth not working for Windows customers.  I can reproduce this in Windows 10 with many browsers (Edge, Chrome, FF).

If I disable our use of `excludeCredentials` things work in Windows (but the same hardware key can be added multiple times). When I set `excludeCredentials` things stop working in Windows, but continue working as expected in all other OS/browser combos.

In Windows while using the `excludeCredentials` option I always get the following error returned on the client-side:

```
NotAllowedError
The operation either timed out or was not allowed. See: https://w3c.github.io/webauthn/#sec-assertion-privacy
```

Are there any working examples of using `excludeCredentials` in Windows?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cabf96-7b2b-9eb6-c428-ff4b44a97312
* Version Independent ID: 922d390b-52b6-db2a-0aab-f338e8c21b85
* Content: [Dev guide - Web Authentication - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication)
* Content Source: [microsoft-edge/dev-guide/windows-integration/web-authentication.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/windows-integration/web-authentication.md)
* Product: **microsoft-edge**
* Technology: **windows-integration**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Apologies for long delay here. Unfortunately, the link provided above does not work anymore as it is about some legacy documentation that got retired.
Also, please note that this repository is about the documentation of Microsoft Edge developer features, not about the features themselves.
I'm therefore closing this issue. Feel free to open a new one if there is a documentation problem with WebAuthn. Also note that we have some documentation about debugging WebAuthn issues with DevTools here: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/webauthn/
