### ISSUE TITLE
Porting CWebView to WebView2 

### ISSUE THREAD

**Issue by Tobias8048** [MicrosoftDocs/edge-developer#505]
I am using the CHtmlView in my application and there, I use a handler for getting Json data from the host when the user presses a Select button.

How can I implement such a handler with the WebView2?

// Handler used in CHtmlView
class CExternalHandler : public CCmdTarget
{
public:
  CExternalHandler()
  {
    EnableAutomation();
  }

  void BuildupSelect(LPCWSTR str)
  {
     CHelpers::StoreData(str);
  }

private:
  DECLARE_DISPATCH_MAP()
};
BEGIN_DISPATCH_MAP(CExternalHandler, CCmdTarget)
  DISP_FUNCTION(CExternalHandler, "BuildupSelect", BuildupSelect, VT_EMPTY, VTS_WBSTR)
END_DISPATCH_MAP()

**Comment by Reezaali** [comment]
@Tobias8048 I've copied the issue to https://github.com/MicrosoftEdge/WebViewFeedback/issues/166

I'll go ahead and close this issue. Thanks.
