### ISSUE TITLE
Finding Executable Path

### ISSUE THREAD

**Issue by HansUXdev** [MicrosoftDocs/edge-developer#508]
So the executable path should be changed.
Users open the desired browser then goto `edge://version/` to find the executable path. 
It works regardless of windows or mac and regardless of the chromium-based browser...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa0e4d86-12ac-7f7e-1c06-66377987487e
* Version Independent ID: 52fa943b-5a87-0d35-1d89-a2a627486061
* Content: [Puppeteer - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/puppeteer#feedback)
* Content Source: [microsoft-edge/puppeteer.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/puppeteer.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @zoherghadyali
* Microsoft Alias: **zoghadya**

**Comment by Reezaali** [comment]
@HansUXdev I've made a pull request with your suggestion. Thank you. 
#605
