### ISSUE TITLE
Time to live

### ISSUE THREAD

**Issue by ndbills** [MicrosoftDocs/edge-developer#527]
After an extension has been submitted and becomes published "in the store", how long does it take for the browser to pick up the latest version of the extension and install it? I noticed that when in developer mode, I can force an update of all extensions by clicking the "update" button, but how often does the browser poll naturally? Is it only on browser startup? Is it once every hour? Once a day?

Thanks for the insight, it would be nice to have this info here in the docs somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5d9185-ba64-51ed-4d7f-fbf2161e93d9
* Version Independent ID: 1c79c547-44b6-9436-676b-baf49ea8daa2
* Content: [Update An Extension Listing - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/update#feedback)
* Content Source: [microsoft-edge/extensions-chromium/publish/update.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/publish/update.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by ndbills** [comment]
Also, does the version number have anything to do with how things are auto-updated? For example, using the format {major.minor.build.revision}, if v1.2003.1.0 is currently published, and now I make a bug fix and publish v1.2003.1.1, does that change in revision number affect the clients auto updating? or do I need to change a major, minor, or build number instead? Thanks for any clarity you can provide on the subject :)

**Comment by gebansal** [comment]
Extensions are updated when the browser is started and every 5 hours after that till the browser is running.
