### ISSUE TITLE
Hide video control panel in full screen mode

### ISSUE THREAD

**Issue by vaszol** [MicrosoftDocs/edge-developer#53]
Please tell me how to hide native video controls in MS Edge in full screen mode.
On my page there is a video element that should show my control buttons, but when I call "video.msRequestFullscreen ();" it is overlapped with the wrong buttons.
In alternative browsers, everything works as it should.

**Comment by erikadoyle** [comment]
Hi @vaszol, could you please file a ticket with repro steps on the [Edge issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/) so someone can take a look? Thanks!
