### ISSUE TITLE
No highlight option in PDF viewing mode.

### ISSUE THREAD

**Issue by abhimanyu-bitsgoa** [MicrosoftDocs/edge-developer#532]
New Edge doesn't have a highlighting feature for documents.

**Comment by Reezaali** [comment]
@abhimanyu-bitsgoa thank you for your feedback. This repo is used for documentation. To submit feature requests, please see https://microsoftedge.uservoice.com/.

Thank you.

**Comment by abhimanyu-bitsgoa** [comment]
Thanks for the information. I will try to submit a patch myself if time permits :)
