### ISSUE TITLE
Possible error in registry key path instructions

### ISSUE THREAD

**Issue by jfarleyx** [MicrosoftDocs/edge-developer#533]
This document states a user should add the following registry key, but note that it references Google Chrome and not Microsoft Edge: "HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.my_company.my_application". Is Edge going to rely on a Google Chrome registry key or should this be "HKCU\Software\Microsoft\Edge\NativeMessagingHosts\com.my_company.my_application"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6baf3ba3-2850-707d-fdfc-9b65f88655c7
* Version Independent ID: 661b537b-bba6-cb07-9979-cddcc35421e3
* Content: [Native Messaging - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging#feedback)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/native-messaging.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by asamuzaK** [comment]
As far as I know, any Chromium-based browser references the Google Chrome registry key.
See [asamuzaK/webExtNativeMsg: Helper modules for WebExtensions native messaging host](https://github.com/asamuzaK/webExtNativeMsg#supported-browsers)

**Comment by gebansal** [comment]
Thank you for pointing it out. We'll modify the documentation accordingly. To add the registry key, the path should be "HKCU\Software\Microsoft\Edge\NativeMessagingHosts\com.my_company.my_application".
