### ISSUE TITLE
Why is there no requirement to require people publishing non-official versions of popular extensions to explicitly state so (or not be allowed to do it)?

### ISSUE THREAD

**Issue by keeganwitt** [MicrosoftDocs/edge-developer#544]
It's hard to know whether to trust an extension in the Microsoft store.  The publisher name may or may not match the Chrome Store publisher name, and it may or may not have been published by the original extension author.  It may be just the original extension re-published, or it may be modified.  There's no way to know, unless you lookup the official extension website and see if it appears to be mentioned there.

I'm concerned not having a policy on this will allow bad actors to squat on names, or pretend to be the official extension until they have a large install base, then get up to mischief.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7819ec4-6bf9-b550-431b-07e5f7692150
* Version Independent ID: e3493b50-4f7a-b3a8-465a-6d494fecb3e0
* Content: [Microsoft Edge Addons Catalog Developer Policies - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/store-policies/developer-policies?branch=user%2Fv-jomar7%2Fdocs%2Fextensions-chromium%2Fstore-policies%2F2019DEC09#feedback)
* Content Source: [microsoft-edge/extensions-chromium/store-policies/developer-policies.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/store-policies/developer-policies.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
@keeganwitt thank you for raising this concern. As a part of the extension submission process, we have a thorough review process. We have a requirement to state explicitly that they are not officially sponsored/supported by the original company/developer.
If you find any extension violating this, you can report to us at ext_dev_support@microsoft.com or through report abuse on the store and we will make sure to review them again.

**Comment by keeganwitt** [comment]
Where is that stated on the store page?  Are they just required to mention that in the description somewhere?  It might be nice if there were a section for that (maybe next to the version/updated/terms sections).

**Comment by gebansal** [comment]
If an extension doesn't pass the certification process, it's not published to the store. The extensions that have been published to the store, from our review process, are trusted.
Again, if you do find any extension violating this, you can report to us at ext_dev_support@microsoft.com or through report abuse on the store and we will make sure to review them again.

**Comment by gebansal** [comment]
The concern you have raised is completely valid and to address this we are in the process of redesigning our product page on the store to provide more information such as publisher website/ support details etc which can help the end-users evaluate the publisher's authenticity.

**Comment by gebansal** [comment]
Closing this thread for now. If you have any concerns, please feel free to reopen this thread or start a new one.
