### ISSUE TITLE
Doc issue: Add document of localization in docs of dev tool of MS Edge

### ISSUE THREAD

**Issue by zhouyuZY** [MicrosoftDocs/edge-developer#551]
In docs of dev tool of MS Edge: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium, there is no document of localization: https://blogs.windows.com/msedgedev/2020/02/04/localizing-edge-devtools/. Please add it in the doc.

**Comment by ststimac** [comment]
@zhouyuZY is there something specific you're looking for with the documentation that the blog post doesn't cover for localization?

**Comment by zhouyuZY** [comment]
No. I think the blog is detailed in localization. This part should also be included in the documentation.

**Comment by jm-trd-ms** [comment]
Thank you for your feedback.  
Your feedback has resulted in changes to the documentation.
#615
