### ISSUE TITLE
Crash using GetCoreWebView2BrowserVersionInfo

### ISSUE THREAD

**Issue by KeesvanHeerden** [MicrosoftDocs/edge-developer#558]
Before creating a webview2 environment (CreateCoreWebView2EnvironmentWithDetails), I check if the Edge version is suitable via the GetCoreWebView2BrowserVersionInfo and CompareBrowserVersions functions.
Using these functions on a server with Windows Server 2012 R2, it crashes on the function GetCoreWebView2BrowserVersionInfo. I know that Webview2 is yet not supported on that server version, but I expected the method to return a not S_OK value, or an emtpy string with version info. Not a crash.
I hope this can be changed, that a function will be added to check if the windows version is supported, because it is still not clear yet which windows versions will be supported in the future.
Thanks for reading.

**Comment by liminzhu** [comment]
Thanks for reporting the issue! I copied the bug to our WebView feedback repo and let's go from there :).
