### ISSUE TITLE
Any way to propose a new API?

### ISSUE THREAD

**Issue by Happy-Ferret** [MicrosoftDocs/edge-developer#56]
Is there any way to propose a new API, similar to Mozilla's [Webextension Experiments](https://github.com/web-ext-experiments/about) repository or Google's API proposal process outlined [here](https://www.chromium.org/developers/design-documents/extensions/proposed-changes/apis-under-development)?

I recognise that Edge itself is closed source, however I'm sure there would be a way to propose a new API without presenting the actual implementation. In fact, a ``schema.json`` and a thorough ``README.md`` outlining the API's intentions should be all that is needed.

**Comment by erikadoyle** [comment]
Good question @Happy-Ferret! I checked with our Edge extensions team and they said to please post API proposals (along with any other suggestions) in the[ extensions section](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/filters/hot?category_id=87962) of our Edge UserVoice forum.  You could host your spec (json, readme, etc) from your own Github, then post the link to it. 

FWIW you might want to check out the [W3C Browser Extension Community Group](https://www.w3.org/community/browserext/), if you're not already a member of that.
