### ISSUE TITLE
میشه یکی منو راهنمایی کنه 

### ISSUE THREAD

**Issue by betnews** [MicrosoftDocs/edge-developer#569]
اگر میشه استفاده از github رو ب من توضیح مختصری بدین واقعا ممنونتون میشم

**Comment by betnews** [comment]
> @betnews 
ایدیم

**Comment by Reezaali** [comment]
Hello,
I ran the text through a translator and it translated as follows: If I'm using GitHub, I don't really give a brief explanation.
Would [this ](https://github.com/MicrosoftDocs/edge-developer/blob/master/CONTRIBUTING.md) document be helpful?
I'll go ahead and close the issue for now.
Thanks.
