### ISSUE TITLE
[Core feature request] Make the Immersive Reader APIs available

### ISSUE THREAD

**Issue by yassinebridi** [MicrosoftDocs/edge-developer#570]
[Enter feedback here]
I want to develop an Edge extension that make working with the **Immersive Reader** feature easy.
Like keyword mapping for pausing, skipping lines and, skipping paragraphs, reTTS a paragraph or a line etc..
I don't know if such APIs exists, but if they do, is it possible that it can be made accessible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4edd411d-e52a-32ef-e539-fb4ed709c86c
* Version Independent ID: 9b96eeb9-accc-7230-20b1-b704d9f9a79e
* Content: [Microsoft Edge (Chromium) Extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/)
* Content Source: [microsoft-edge/extensions-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@yassinebridi I've checked with the Engineering team and they confirmed that no API exists today. They are interested in understanding more about your scenarios if you'd like to connect with them. I'll go ahead and close this issue now. Have a great day.

**Comment by Ayanmullick** [comment]
@Reezaali , I would like to be able to place the `Play` button for the screen reader at a specific place on a web page. However, I couldn't locate any documentation on how one could the screen reader for one's web page.
