### ISSUE TITLE
Where or how does one get a Microsoft-Catalog-extensionID?

### ISSUE THREAD

**Issue by shripathi-kamath** [MicrosoftDocs/edge-developer#571]
"To enable your Native Application identify and communicate with Microsoft Edge Addons Extension, set allowedorigins to extension://[Microsoft-Catalog-extensionID] in your native messaging host manifest file"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6baf3ba3-2850-707d-fdfc-9b65f88655c7
* Version Independent ID: 661b537b-bba6-cb07-9979-cddcc35421e3
* Content: [Native Messaging - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging#feedback)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/native-messaging.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
You can obtain the extension ID from the store's extension page URL. If the URL to the extension on Microsoft edge addons store is "https://microsoftedge.microsoft.com/addons/detail/pagamfblajcameemhhhklnlcnfp", "pagamfblajcameemhhhklnlcnfp" will be the extension ID

**Comment by shripathi-kamath** [comment]
I apologize, but I do not understand the response.

If I'm developing an extension, how do I get an extension ID?  The response seems to how to get the extension ID of an installed extension.

Step 1 of https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/native-messaging.md shows:

_"chrome-extension://knldjmfmopnpolahpmmgbagdohdnhkik/"_

Where do I get "knldjmfmopnpolahpmmgbagdohdnhkik"?

**Comment by gebansal** [comment]
While you are developing the native messaging host and extension, you can sideload the extension to test native messaging. Go to edge://extensions page and enable the “Developer mode” toggle button. Then, load your extension by clicking on the “Load unpacked” button. Once, you load the extension, you will be able to see the extension id on the same page. You can use this id to specify in “allowed_origins” when you install the host manifest file. Then you can test your native messaging host and extension.

**Comment by shripathi-kamath** [comment]
Seems like a Catch-22.

I want to write a native messaging extension.  Before I can even test it, I have to create one.  The documentation says I have to create a manifest file.  In that manifest file, I have to enter an extension-id.

Where do I get this extension id?

Without it, what does it even mean to sideload the extension?

Suppose you were developing one, can you give me a sample manifest file, and show me HOW you added this extension id to the file.  Before you even load it.

I really need no help in how to look at the extension id of an extension already created and installed.  Twice now, you have provided great instructions on how to do that.

Just give me a sample manifest file, and tell me where you got the extension id to put into it.

**Comment by shripathi-kamath** [comment]
Any other forum I can get an answer to my query?  Please let me know.

**Comment by gebansal** [comment]
@shripathi-kamath Can you send an email as a follow-up to this issue at ext_dev_support@microsoft.com.

**Comment by gebansal** [comment]
@shripathi-kamath Meanwhile we'd request you to refer to this documentation as well https://developer.chrome.com/extensions/manifest/key.
We'd be able to share a sample manifest file over email, request you to reach out at ext_dev_support@microsoft.com.

**Comment by shripathi-kamath** [comment]
That documentatuon is useless for my question.  Surely you see that?

I have posed the question to the email you sent me.

Please close this question, it is a waste of time.

**Comment by Reezaali** [comment]
Closing the issue as requested. Thanks.
