### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by jona888** [MicrosoftDocs/edge-developer#574]
With Progressive Web Apps (or simply PWAs) you do ot have
--&gt;
With Progressive Web Apps (or simply PWAs) you do not have

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3263f88a-8279-75bc-1985-355339ae540f
* Version Independent ID: 5cf75ba7-6666-181f-ec00-dd4968a629ef
* Content: [Progressive Web Apps on Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/#feedback)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Thanks for sharing this typo @jona888. Would you like to submit a PR with the fix to get the contribution on your profile?

**Comment by Reezaali** [comment]
Closing as fixed in #588
