### ISSUE TITLE
Confusion for Microsoft Account

### ISSUE THREAD

**Issue by ackava** [MicrosoftDocs/edge-developer#582]
For existing Partners, Partner portal no longer accepts any other account apart from Work Email, after transferring account to Work Email, I cannot access edge extension marketplace, because this  page says that you need to have Microsoft Account. Can you please clarify this?

Contacting Partner support redirects us to this page saying this issue is out of their scope.

Partner accounts are already verified, but there is no way to publish an extension through existing partner account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e46faf3-c5bc-3872-ff77-f5056ac88704
* Version Independent ID: 35ea3906-7ea2-159b-75d9-490b9e4f4d5a
* Content: [Open A New Developer Account - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/create-dev-account)
* Content Source: [microsoft-edge/extensions-chromium/publish/create-dev-account.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/publish/create-dev-account.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by shemseddine** [comment]
We are currently having a similar issue. Did you get around this some how?

**Comment by balajek** [comment]
@ackava, @shemseddine - yes, you need to have a Microsoft Account (i.e. outlook.com/live.com etc.) in order to sign up for the Microsoft Edge program in Partner Center. Unfortunately we do not yet support work accounts for Microsoft Edge program.

**Comment by shemseddine** [comment]
@balajek But we want it to be associated with our Partner account. How can we do that? I invited an external account (an Microsoft outlook.com account) to my partner account and tried to get started with the Microsoft Edge program, and again I just get it redirecting me back to the dashboard.

**Comment by balajek** [comment]
@shemseddine - support for associating a Partner account is not yet available. It is in our roadmap. You will need to register with an outlook.com account first & later once support/capability is added to associate work accounts, you will be be able to associate the Partner account with outlook.com ID.
