### ISSUE TITLE
Budaksarawa

### ISSUE THREAD

**Issue by Budaksarawakgamer** [MicrosoftDocs/edge-developer#591]
my page studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aac3ac4-1558-8bbf-ae33-ef0df46468b5
* Version Independent ID: 56d39fa0-be1a-db58-4ef0-d6d68dcecbd4
* Content: [Runtime Domain - DevTools Protocol Version 0.2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-protocol/0.2/domains/runtime#feedback)
* Content Source: [microsoft-edge/devtools-protocol/0.2/domains/runtime.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-protocol/0.2/domains/runtime.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @pelavall
* Microsoft Alias: **pelavall**

**Comment by Reezaali** [comment]
Hi @Budaksarawakgamer. It seems that some of the text in the issue may be missing. I'm not sure how to proceed with this issue, so I'll go ahead and close it for now. Feel free to open a new issue as needed. Thank you.
