### ISSUE TITLE
Steps missing from how-to

### ISSUE THREAD

**Issue by stuartluscombe** [MicrosoftDocs/edge-developer#595]
Going through the steps for 'Getting started with Progressive Web Apps' the project will fail to run as-is.

I had to additionally install nodejs (even though I'd selected the nodejs development part in VS installation) and then also either right-click on the npm folder in Solution Explorer and install the npm packages, or run .npm install from the interactive NodeJS window.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcef5936-232e-1ab0-c1c4-77026c79e277
* Version Independent ID: b6ec450d-ead9-ffcf-0d5b-7a408bf0e13d
* Content: [Get started with Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-edgehtml/get-started#feedback)
* Content Source: [microsoft-edge/progressive-web-apps-edgehtml/get-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-edgehtml/get-started.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
I'm sorry to hear about this issue. Please note that we just updated our documentation [here](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/get-started). Please see if that helps. I'll go ahead and close this issue now. Thanks.
