### ISSUE TITLE
Unable to dock right

### ISSUE THREAD

**Issue by rwarford** [MicrosoftDocs/edge-developer#596]
There is no dock right button for IE 11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7708ebf-b89b-168e-de02-bb00e9223318
* Version Independent ID: 48a20484-21fe-cbd3-7b84-f1992002eb63
* Content: [Microsoft Edge (EdgeHTML) Developer Tools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide#feedback)
* Content Source: [microsoft-edge/devtools-guide.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by ststimac** [comment]
@rwarford Correct, the documentation in questions shows the developer tools for Microsoft Edge (EdgeHTML) which are different from the IE 11 developer tools. There is no dock right option in IE 11.
