### ISSUE TITLE
Visual Studio Project template?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/edge-developer#607]
Where is the Visual Studio Project template for Edge Extensions projects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d70c4902-5246-ea94-a95f-f4ac94611c4c
* Version Independent ID: c7f1c45d-32ad-90f7-bfd6-d44ecd2bc941
* Content: [Build A Simple Extension That Pops Up NASA Picture Of The Day - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
The visual studio project template exists for the old legacy edge browser. For the new chromium based browser, we wouldn't need one.
