### ISSUE TITLE
c#?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/edge-developer#608]
How do you use this api from c#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa0e4d86-12ac-7f7e-1c06-66377987487e
* Version Independent ID: 52fa943b-5a87-0d35-1d89-a2a627486061
* Content: [Puppeteer - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/puppeteer)
* Content Source: [microsoft-edge/puppeteer.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/puppeteer.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @zoherghadyali
* Microsoft Alias: **zoghadya**

**Comment by zoherghadyali** [comment]
[Puppeteer](https://pptr.dev/) is a Node library that is currently only available for JavaScript. You can check out [Puppeteer Sharp](https://github.com/hardkoded/puppeteer-sharp), a .NET port of Puppeteer. With Puppeteer Sharp, you can refer to this sample: 
```cs
var options = new LaunchOptions { Headless = true, ExecutablePath = executablePath };

using (var browser = await Puppeteer.LaunchAsync(options))
using (var page = await browser.NewPageAsync())
{
    // use page
}
```
which I pulled from here: https://www.puppeteersharp.com/examples/ReuseChrome.html and then provide the executable path to your installation of Microsoft Edge (Chromium).

Another option is to use Selenium WebDriver. Please check out our guide to getting started with [WebDriver (Chromium)](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium) and definitely let us know how that goes for you!

**Comment by Bartolomeus-649** [comment]
I have several issues with this...
1. First you say it's only available for JavaScript, and then in the very next sentence say the opposite, that it is available for c#.
2. It seem like Microsoft no longer consider C# and .NET to be their primary development language and development platform. If this is the case then be clear about it and say so.

**Comment by zoherghadyali** [comment]
Sorry about that! I can be clearer. [Puppeteer](https://pptr.dev/) is an open source project that is built by Chromium developers. The project itself is a Node library that is only available in JavaScript. Other members of the OSS community have ported it to other languages like [Python](https://github.com/miyakogi/pyppeteer) and [C#](https://github.com/hardkoded/puppeteer-sharp).

You can choose to use these ports of Puppeteer or you can use Selenium WebDriver, which is an implementation of the [W3C WebDriver standard](https://www.w3.org/TR/webdriver2/). This is available for .NET via [NuGet packages](https://www.nuget.org/packages/Selenium.WebDriver/4.0.0-alpha05) and we include C# samples in [our documentation](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium).
