### ISSUE TITLE
Way to little info on Native Messaging

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/edge-developer#609]
Way to little info on Native Messaging. 
* How do you create one in Visual Studio?
* What APIs are available, client side and server side?
* Which problem is Native Messaging a solution to?
* Links to other pages relevant to this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6baf3ba3-2850-707d-fdfc-9b65f88655c7
* Version Independent ID: 661b537b-bba6-cb07-9979-cddcc35421e3
* Content: [Native Messaging - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/native-messaging.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
Thank you @Bartolomeus-649 for giving the feedback, we'll incorporate it and update our documentation accordingly.

**Comment by gebansal** [comment]
I am closing this issue for now and the feedback will be taken up as part of the document improvement.
