### ISSUE TITLE
WASM-based extension in c#

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/edge-developer#610]
Where is the documentation on how to write a WASM-based extension in c#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4edd411d-e52a-32ef-e539-fb4ed709c86c
* Version Independent ID: 9b96eeb9-accc-7230-20b1-b704d9f9a79e
* Content: [Microsoft Edge (Chromium) Extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/)
* Content Source: [microsoft-edge/extensions-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
@Bartolomeus-649  We'd request you to please reach out to the Microsoft Edge extensions team at ext_dev_support@microsoft.com for the above issue.

**Comment by Bartolomeus-649** [comment]
@gebansal I "reached out", didn't get any reply.

**Comment by gebansal** [comment]
@Bartolomeus-649  can you help me with the date of the email here? I can follow up on that to see why it got missed from our end. Thank you!

**Comment by Bartolomeus-649** [comment]
@gebansal sent a new email just now.
