### ISSUE TITLE
Grrr... issing files

### ISSUE THREAD

**Issue by G-Couvert** [MicrosoftDocs/edge-developer#623]
Before the complete procedure the "stdafx.cpp', "stdafx.h" and "resource.h are missing.
The path for com.h is vrong, and is dificul to find "WebView2.h" ...

**Comment by Reezaali** [comment]
@G-Couvert sorry to hear that you are having difficulty. To get support for WebViews, please open an issue on this repo: https://github.com/MicrosoftEdge/WebViewFeedback
Thank you.
