### ISSUE TITLE
uploading my photo with a cost/price added

### ISSUE THREAD

**Issue by jabidahscreationssystems** [MicrosoftDocs/edge-developer#63]
I want to have a purchase price/cost first and place for deposit like Paypal, for every photo or pictures which 100% belong to me on my facebook  site. If peoples want purchase and claim there photo's only the one's that I will release to buy..  how do I create these links and payments 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7708ebf-b89b-168e-de02-bb00e9223318
* Version Independent ID: 48a20484-21fe-cbd3-7b84-f1992002eb63
* Content: [Microsoft Edge Developer Tools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide)
* Content Source: [microsoft-edge/devtools-guide.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide.md)
* Service: **unspecified**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
Hi @jabidahscreationssystems, unless I'm misunderstanding your question, it sounds like you're looking for developer info for Facebook. Our content here is limited to Windows / Microsoft Edge stuff, and for everything web standards we recommend [MDN web docs](https://developer.mozilla.org/en-US/).

**Comment by erikadoyle** [comment]
Hopefully the Facebook developer docs have what you're looking for.
