### ISSUE TITLE
Kayce Basques 

### ISSUE THREAD

**Issue by christian7877** [MicrosoftDocs/edge-developer#631]
Teile dieser Seite sind Änderungen, die auf Von Google erstellten und geteilten Arbeiten basieren und gemäß den in der Creative Commons Attribution 4.0 International Licensebeschriebenen Bedingungen verwendet werden.
Die Originalseite finden Sie hier und wurde von Kayce Basques (Technical Writer, Chrome DevTools & Lighthouse) verfasst.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: dfe13e34-3525-cc2b-b6cc-e445f676749a
* Version Independent ID: 69f4a92e-525c-2abc-3ecf-5cc69717dd1a
* Content: [Get Started With Analyzing Runtime Performance - Microsoft Edge Development](https://docs.microsoft.com/de-de/microsoft-edge/devtools-guide-chromium/evaluate-performance/#feedback)
* Content Source: [microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@christian7877 thank you for suggesting the change. Since that is a standard note that we're required to include, I'll go ahead and close out the issue. Thanks.
