### ISSUE TITLE
Bitterly Dissapointed. Does not work in Chrome or Chromium Edge

### ISSUE THREAD

**Issue by Unkind-Chris** [MicrosoftDocs/edge-developer#634]
The title says it all really. Followed all step and even tried the download versions. They do n ot work in either Chrome or Edge.

We get as far as seeing in IMG placeholder that is approx. 10x10px in an active (online) tab but it errors thereafter,

**Comment by Unkind-Chris** [comment]
Now that's interesting. It does work - without me changing or reloading anything... Potential bug in chromium!

**Comment by Reezaali** [comment]
@Unkind-Chris since it looks like the issue was resolved, I'll go ahead and close this issue. Thanks.

**Comment by Unkind-Chris** [comment]
Thanks @Reezaali
