### ISSUE TITLE
DevTools What's New landing page

### ISSUE THREAD

**Issue by hxlnt** [MicrosoftDocs/edge-developer#639]
Should this be a landing page for collecting What's New entries? This page isn't tied to a release, and the content may become outdated while appearing to be the latest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4394c584-0299-9b4c-5e5e-077d95551b3c
* Version Independent ID: 1276e848-bced-213b-aa1d-cdc750352765
* Content: [What's new in the Microsoft Edge (Chromium) DevTools in March 2019 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new#feedback)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/whats-new.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @zoherghadyali
* Microsoft Alias: **zoghadya**

**Comment by jm-trd-ms** [comment]
Reusable text may aid this, but investigation is needed to retain SEO benefits.

**Comment by jm-trd-ms** [comment]
Related pull merged, closed bug.
