### ISSUE TITLE
Fluent Design into Extention

### ISSUE THREAD

**Issue by dwm1909** [MicrosoftDocs/edge-developer#64]
Has try to build CSS or even with SCSS format for update my privat extention to look more like fluent design but with no luck. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1037a28d-7cd5-66dc-9826-1e626fa6e74b
* Version Independent ID: f90b56a3-db51-eeea-707c-0c30e81b4749
* Content: [Extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions)
* Content Source: [microsoft-edge/extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions.md)
* Service: **unspecified**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by libbymc** [comment]
Hi @dwm1909 - sorry, there are no resources for web developers at this time.
