### ISSUE TITLE
Edge Chromium Maximum instances

### ISSUE THREAD

**Issue by JamieBenson** [MicrosoftDocs/edge-developer#644]
I've managed to get this working on Selenium 3.14 using the package above (https://www.nuget.org/packages/Microsoft.Edge.SeleniumTools), but I can't seem to find any documentation anywhere indicating what the maximum number of concurrent instances can be run on a given machine. I know the earlier EdgeHTML version was only 1, but given this version is based of Chromium I was hoping this was more than 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107ce527-7b9c-ff4e-e524-a8ebbc1a6714
* Version Independent ID: 6c8de68a-01bf-3426-8427-6daa5dca5f03
* Content: [WebDriver (Chromium) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium#feedback)
* Content Source: [microsoft-edge/webdriver-chromium.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by zoherghadyali** [comment]
Hi @JamieBenson! Thank you for using Microsoft Edge and sending us your feedback. You are correct that Microsoft WebDriver for Microsoft Edge (EdgeHTML) (aka Microsoft Edge Legacy) only supported 1 session at a time. The new Microsoft Edge (Chromium) and the new Microsoft Edge Driver do not have that restriction. There is no limit on the number of sessions of Microsoft Edge (Chromium) that can be run on a given machine. 

Please keep sending us feedback! You can use the **Feedback** icon in the [Microsoft Edge Developer Tools](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium)

![image](https://user-images.githubusercontent.com/34316555/83720903-dc987580-a5ee-11ea-876a-8312f2cf83be.png)
or tweet at us/DM us on Twitter [@EdgeDevTools](https://twitter.com/edgedevtools) as well!
