### ISSUE TITLE
Pressing Send Feedback "On this product" ends up at closed uservoice

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/edge-developer#646]
_From @birbilis on Thursday, April 16, 2020 4:05:32 AM_

**Describe the bug**
the send feedback > On this product doesn't work (sends you to a close UserVoice site)

**To Reproduce**
near the end of the page 
https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-manifest-keys
one can select to send feedback and then pick On this product

this takes them to a page that says that UserVoice page is now closed
 

_Copied from original issue: MicrosoftDocs/feedback#2673_

**Comment by Reezaali** [comment]
@gewarren the fix is now live. Thank you.

**Comment by gewarren** [comment]
Thank you for reporting this @birbilis!
