### ISSUE TITLE
Demo Links Broken

### ISSUE THREAD

**Issue by germanfortiz** [MicrosoftDocs/edge-developer#647]
At the beginning of the article, the links for the three demos are broken:

SimpleWebRTC
ORTC phone call
ORTC demo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a565ddff-a57c-b6de-ca2e-c03ddd171ae4
* Version Independent ID: 9156f42f-ad6c-46dd-7de9-fac155e3fb31
* Content: [Dev guide - Object RTC API - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/realtime-communication/object-rtc-api#feedback)
* Content Source: [microsoft-edge/dev-guide/realtime-communication/object-rtc-api.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/realtime-communication/object-rtc-api.md)
* Product: **microsoft-edge**
* Technology: **edgehtml**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jm-trd-ms** [comment]
Your issue has resulted in changes to the content.
PR #649 

Please follow the changes in the PR.
