### ISSUE TITLE
"Get the add-on" badge for edge extensions

### ISSUE THREAD

**Issue by sienori** [MicrosoftDocs/edge-developer#659]
I think add-on developers need a "Get the add-on" badge to promote the Edge extension.
The following badges are available in Chrome, Firefox and Microsoft store:

![Chrome](https://developer.chrome.com/webstore/images/ChromeWebStore_BadgeWBorder_v2_206x58.png)
https://developer.chrome.com/webstore/branding

![Firefox](https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/addons/files/2015/11/get-the-addon.png)
https://blog.mozilla.org/addons/2015/11/10/promote-your-add-ons-with-the-get-the-add-on-button/

![Microsoft](https://user-images.githubusercontent.com/29514424/81471744-490d9800-922e-11ea-98fb-bceaf60d9c3d.png)
https://developer.microsoft.com/en-US/store/badges/

**Comment by gebansal** [comment]
@sienori thank you for your feedback. We have created a work item in our backlog for the same and should be picked up soon.

**Comment by foooomio** [comment]
@gebansal Hi. How's it going? Is the item still on the backlog?

**Comment by Liozon** [comment]
I made a custom Edge badge, while waiting for an official one. You can see it and download it here: https://gist.github.com/Liozon/cf898c47628bfecd9896f79e6c9a8db8

**Comment by sienori** [comment]
@Liozon  Awesome! I will use this until the official one is released.

**Comment by foooomio** [comment]
It's been two years...

@mikehoffms I guess you are the manager of this repository. Could you please take a look at this issue?

**Comment by Araxeus** [comment]
![image](https://user-images.githubusercontent.com/78568641/212470539-dd4d22a0-3af8-4fa7-9671-6df5b2e26a70.png)

**Comment by Moustachauve** [comment]
Any updates on this?

**Comment by arnav-kr** [comment]
Here's My version, edited from Firefox one


![add_to_edge](https://user-images.githubusercontent.com/72879799/229780441-610f727a-edb4-41e0-a1fb-6593af3d4485.svg)
