### ISSUE TITLE
@media queries

### ISSUE THREAD

**Issue by davidslight** [MicrosoftDocs/edge-developer#660]
Where can I adjust and work with @media queries - not firing correctly so I need to debug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f4e719c-edd9-95fc-6b62-66f1a172f21d
* Version Independent ID: 0b55c280-1b8b-a84a-49a1-9f86c4aa85ed
* Content: [CSS Reference - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/css/reference#feedback)
* Content Source: [microsoft-edge/devtools-guide-chromium/css/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/css/reference.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by codepo8** [comment]
Hey there David, 
Media Queries are part of the device toolbar. So if you open devtools and the toolbar, you can select and edit the queries and jump directly from them to your code. 
You can see this in this GIF: 

![mediaqueries gid](https://user-images.githubusercontent.com/13508/82695207-ed4b0200-9c64-11ea-813c-7bb03faa8a54.gif)

**Comment by davidslight** [comment]
Yes thanks for your help.
David
