### ISSUE TITLE
Rectangle box goes up, and down when I am scrolling on Twitter (canary)

### ISSUE THREAD

**Issue by bplasmeijer** [MicrosoftDocs/edge-developer#664]
Version 84.0.512.0 (Official build) canary (64-bit)

![image](https://user-images.githubusercontent.com/116467/81646575-c6522c00-942b-11ea-912b-961b2cb4417a.png)

**Comment by Reezaali** [comment]
Thanks for reporting this issue. This repo is used for documentation. If this is still an issue and hasn't been updated in a more recent version of Edge, please report the issue by submitting the issue in Edge - select Alt+Shift+I on Windows. I'll go ahead and close out this issue now. Thanks.
