### ISSUE TITLE
Current availability

### ISSUE THREAD

**Issue by SteveALee** [MicrosoftDocs/edge-developer#667]
The 1st para in the Current Availability section makes almost no sense to me having only read the current page :( What are you trying to say? I can only use Fetch not other services in WinRT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3263f88a-8279-75bc-1985-355339ae540f
* Version Independent ID: 5cf75ba7-6666-181f-ec00-dd4968a629ef
* Content: [Progressive Web Apps on Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/#feedback)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by SteveALee** [comment]
So exp;loring a bit more and having previous learnt PWAs on Windows could access WinRT APIs I see why this is now confusing.

You should spell out on this page that That there are 2 edges and the Chromium one provides standard PWAs, ie only features common to a PWA on on browser. YOu mention platform sepcifcs but that DOES NOT mean winAPI,

The old messaging about WinRT access is only for the old Edge.

Given this I think you are missing an explanation of what the Windows specific experience is for users when using a PWA in new Edge? The PWA community was originally very weak on describing how user can install and what platform integration there is if any. Can you clarify at least for WIndows users. What happens when they install. WHen are they offer to install, can they force an install after a single use. Can developers still offer new Edge PWAs in the store? etc etc

thanks

**Comment by SteveALee** [comment]
Also how does this fit in with the Hosted App Model in general and with Edge specifically?

**Comment by Maggers** [comment]
Hello, thanks for your comments here. We went through and refreshed the content mid May to better call out the two different PWA approaches - EdgeHTML based WWAHost PWAs pre the switch to Chromium web platform and then following it. We separated out the content along those lines. Hopefully this is more clear now. Closing this issue as it relates to the old content structure.
