### ISSUE TITLE
VS2019 are not synchrone with WebView2 development !

### ISSUE THREAD

**Issue by schlebe** [MicrosoftDocs/edge-developer#671]
I use WebView (old version) in a VB.Net program but when I build my project, I have following message

Warning BC40000	'WebView' is deprecated : 'The WebView control will be replaced by WebView2 in the future. Read more here to provide early feedback: https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2'.

But when I go to this URL, I see that WebView2 is not a final product that can only be used in C++ !

There are 2 things todo

1. remove warning in Visual Studio 2019 or 2020 that says that WebView is deprecated
2. or, this is the best solution, release a final WebView2 control for .Net (VB et C#) as soon as possible ;-)	

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c82b4fb3-b1bd-ea62-5f3d-335caf143497
* Version Independent ID: a0d2d661-8d09-126b-c60f-6a3fd36a4a03
* Content: [Microsoft Edge WebView 2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2#feedback)
* Content Source: [microsoft-edge/hosting/WebView2.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/hosting/WebView2.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by pagoe-msft** [comment]
We have just released a preview for WebView2 on .NET! 
Check out: https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#09515-prerelease
