### ISSUE TITLE
Webview2 not works on winform

### ISSUE THREAD

**Issue by PaulYBChiang** [MicrosoftDocs/edge-developer#686]
Glad to see that Microsoft is moving fast now. I follow the Url https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms and get null exception at this line:
this.Controls.Add(this.webView21).

System.NullReferenceException
  HResult=0x80004003
  Message=未将对象引用设置到对象的实例。
  Source=Microsoft.Web.WebView2.WinForms
  StackTrace:
   at 
   at System.Windows.Forms.Control.AssignParent(Control value)
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at WindowsFormsApp1.Form1.InitializeComponent() in C:\Users\paul\source\repos\WindowsFormsApp1\WindowsFormsApp1\Form1.Designer.cs:line 50
   at WindowsFormsApp1.Form1..ctor() in C:\Users\paul\source\repos\WindowsFormsApp1\WindowsFormsApp1\Form1.cs:line 17
   at WindowsFormsApp1.Program.Main() in C:\Users\paul\source\repos\WindowsFormsApp1\WindowsFormsApp1\Program.cs:line 19

target framework:
	.NET Framework 4.7

vs.net version: 
	Microsoft Visual Studio Community 2019  Version 16.4.3

webview2 version: 
	0.9.515-prerelease

Edge version:  
	81.0.416.72  (64-bit)

Windows version: 
	10.0.18363.836

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Microsoft Edge WebView 2 for Windows Forms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by torgeirf** [comment]
Have you tried running it in 32-bit mode? I had to check "prefer 32-bit" or choose x86 platform to make it run, or else I got a NullReferenceException.

**Comment by PaulYBChiang** [comment]
> Have you tried running it in 32-bit mode? I had to check "prefer 32-bit" or choose x86 platform to make it run, or else I got a NullReferenceException.

Thanks. your suggestion is making sense as msedge.exe file is located in the C:\Program Files (x86) folder. but the result is sad:(

I also tried the sample WinFrom solution from Microsoft, no luck either. Maybe I should switch to the C++ version:((

**Comment by torgeirf** [comment]
It does work, I have just tested both in VB and C#. No code required, just set the Source property in designer. Only issue is what I said above (which actually is due to the 32-bit version of WebViewLoader.dll being used even in 64-bit mode. This bug has already been reported though, see https://github.com/MicrosoftEdge/WebViewFeedback/issues/182

PS! I had to download the Canary version of Edge, as v81 would not work. This is also mentioned somewhere in the documentation...

**Comment by PaulYBChiang** [comment]
> Have you tried running it in 32-bit mode? I had to check "prefer 32-bit" or choose x86 platform to make it run, or else I got a NullReferenceException.

Many thanks, friend. With the Canary Edge, It works like charm!

**Comment by CWCWOOD** [comment]
I did change to x86 mode and I still get the same exception. Running VB.NET 4.6.2 VS 2017.

Where is the "Canary" version? I was told to go here for Canary...

https://www.microsoftedgeinsider.com/en-us/

But it just installed Microsoft Edge. Where can I get the Canary version?

**Comment by Reezaali** [comment]
@CWCWOOD can you try [https://www.microsoftedgeinsider.com/en-us/download/](https://www.microsoftedgeinsider.com/en-us/download/)?

**Comment by CWCWOOD** [comment]
OK, now it is working once I installed the Canary Version of the Edge Browser. Success!!!

Can one develop applications for testing the new WebView2 and distribute it? Will a VS 2017 setup application pick up all the proper dependencies? Will users have to install the Canary Version of Edge? I have a group of friends that test my applications if I can distribute it to them...non-commercial use.
