### ISSUE TITLE
CoreWebView2 is null and doesn't load content in WPF window

### ISSUE THREAD

**Issue by dk511** [MicrosoftDocs/edge-developer#693]
Installed nuget package 

![image](https://user-images.githubusercontent.com/58889061/82392899-d81e6b00-99f9-11ea-8f3e-684eae4d8617.png)

 &lt;wv2:WebView2 Name="webView"
                          Source="https://www.microsoft.com" /&gt; 
Any workaround for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9dc9d2-795c-9612-3585-408b4621c080
* Version Independent ID: f73fc16d-d842-4507-9fdb-b42856720355
* Content: [Microsoft Edge WebView 2 for WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf)
* Content Source: [microsoft-edge/webview2/gettingstarted/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by chrisluna** [comment]
I am facing similar issues - BTW first, the documented sample code has an extra closing tag in there that had to be remove.   After removing the extra closing tag, solution builds, window pops up on debug but website not loading.
![image](https://user-images.githubusercontent.com/44534203/82469872-3bf07480-9a8a-11ea-8f9b-3fa4ec64ca12.png)

**Comment by BastienEscaich** [comment]
I'm having the same issue. CoreWebView2 is null when trying to navigate to any URL. Hardcoded Source doesn't load either.

**Comment by chrisluna** [comment]
could it be already captured in this bug?
https://github.com/MicrosoftEdge/WebViewFeedback/issues/179

**Comment by dk511** [comment]
What is the fix for this? Are the hints from here work for you guys?MicrosoftEdge/WebViewFeedback#179

**Comment by BastienEscaich** [comment]
@dk511 Haven't tried yet. This is more a workaround than anything. So I will be waiting for a stable release as I have a bit of time for now.

**Comment by chrisluna** [comment]
I was able to get the Getting Started app to work after installing the Canary version of edge -
which can be found here - https://www.microsoftedgeinsider.com/en-us/download

**Comment by Reezaali** [comment]
Looks like the issue was resolved. I'll go ahead and close out this issue now. Thanks.

**Comment by priyasgs** [comment]
@dk511 is this fixed for you? I created a new VSIX project in VS 2017, unchecked "Sign the assembly" in the project (https://github.com/MicrosoftEdge/WebViewFeedback/issues/181), added a tool window, and included the WebView2 as per https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf, but just see a gray box in the tool window.

Calling methods like Reload() on the WebView2 results in an exception:
'Attempted to use WebView2 functionality which requires its CoreWebView2 prior to the CoreWebView2 being initialized.  Call EnsureCoreWebView2Async or set the Source property first.'

**Comment by priyasgs** [comment]
Doesn't look like this is resolved https://github.com/MicrosoftEdge/WebViewFeedback/issues/195#issuecomment-645066820
