### ISSUE TITLE
Order of precedence/merged access controls?

### ISSUE THREAD

**Issue by GregDomjan** [MicrosoftDocs/edge-developer#699]
When there is an entry with the same host id under both these registry keys - such as having a Chrome extension also

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\com.my_company.my_application
or
HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.my_company.my_application,`

then it seems to be taking the access control list from the chrome file and not the access controls from edge file
adding the access control with the MS store id to the Chrome file allows access even though the same in the edge config did not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6baf3ba3-2850-707d-fdfc-9b65f88655c7
* Version Independent ID: 661b537b-bba6-cb07-9979-cddcc35421e3
* Content: [Native Messaging - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/native-messaging.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
Edge tries to search both the Edge registry location and the Chrome registry location in that order. If an extension needs to be granted access for native messaging and it is not present (specified using “allowed_origins”) in the host’s json specified in the Edge registry location, we look for the host’s json specified in the Chrome registry location.

**Comment by GregDomjan** [comment]
Thanks @gebansal that is what I had expected.

Edge in testing our extension and native messaging was behaving differently for us.
I had registry present for edge, and extension was working with native messaging
I added registry for chrome that didn't include the id for edge,  edge stopped working, access was denied for native messaging.

When time presents I will test again with latest version to verify if it's changed.

**Comment by gebansal** [comment]
Sure, please let us know if you face any further concerns with it.

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thank you.

**Comment by GregDomjan** [comment]
Re investigated to see if we can remove the MS Store id `hobnnehemnjllfddjaeiniapbfjfonog` from the chrome version of access file, and still find it failing to read the Edge config while Chrome config is present.

Edge Version 84.0.522.63 (Official build) (64-bit)

Any other details needed?

# Working inclusion of ms store id in google chrome file and in it's own file
Registry
```
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost]
@="C:\\Program Files\\NetIQ\\SecureLogin\\Win32\\com.netiq.slNativeHost.chrome.json"
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost]
@="C:\\Program Files\\NetIQ\\SecureLogin\\Win32\\com.netiq.slNativeHost.edge.json"
```
com.netiq.slNativeHost.chrome.json
```
{
  "name": "com.netiq.slchromehost",
  "description": "SecureLogin Chrome native messaging host",
  "path": "slNativeHost.exe",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://abjopieldicnknjgiplcjgepeijbealm/",
    "chrome-extension://jkhicjgpbeiijonckbnnljpdpceijbbi/",
    "chrome-extension://gfgmejjjdncfgdoldimlnpoioepkkafi/",
    "chrome-extension://hobnnehemnjllfddjaeiniapbfjfonog/",
    "chrome-extension://alfldkommhkckjgodadfeidkbgmccpod/"
  ]
}
```
com.netiq.slNativeHost.edge.json
```
{
  "name": "com.netiq.slchromehost",
  "description": "SecureLogin Edge native messaging host",
  "path": "slNativeHost.exe",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://hobnnehemnjllfddjaeiniapbfjfonog/",
    "chrome-extension://gfgmejjjdncfgdoldimlnpoioepkkafi/"
  ]
}
```

# Failing - remove Edge store id from Google chrome file
Change only com.netiq.slNativeHost.chrome.json  to remove ms store id `hobnnehemnjllfddjaeiniapbfjfonog`
```
{
  "name": "com.netiq.slchromehost",
  "description": "SecureLogin Chrome native messaging host",
  "path": "slNativeHost.exe",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://abjopieldicnknjgiplcjgepeijbealm/",
    "chrome-extension://jkhicjgpbeiijonckbnnljpdpceijbbi/",
    "chrome-extension://gfgmejjjdncfgdoldimlnpoioepkkafi/",
    "chrome-extension://alfldkommhkckjgodadfeidkbgmccpod/"
  ]
}
```
Edge is no longer able to interact with native messaging host

> chrome.runtime.lastError
> {}
> message: "Access to the specified native messaging host is forbidden."
> get message: ƒ ()
> __proto__: Object

# Working - Hide chrome config so Edge can't find it
Registry
```
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost**-badid**]
@="C:\\Program Files\\NetIQ\\SecureLogin\\Win32\\com.netiq.slNativeHost.chrome.json"
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost]
@="C:\\Program Files\\NetIQ\\SecureLogin\\Win32\\com.netiq.slNativeHost.edge.json"
```
config com.netiq.slNativeHost.chrome.json still has `hobnnehemnjllfddjaeiniapbfjfonog` remove but no longer found by edge (or chrome)  edge is able to interact properly with native messaging host
