### ISSUE TITLE
Component doesn't show in embeded wpf pages

### ISSUE THREAD

**Issue by maliakkas** [MicrosoftDocs/edge-developer#700]
I am writting custom dlls for an erp suite. In order to show my customizations, I use wpf Pages and inject them to the erp panels. If my component starts as an embeded window in the main erp window, it is not displaying anything. If my component start as a pop up window, then the webview2 shows the webpage. In all cases when I close the component, the app crashes.

Also what about the "external" object in javascript. Can't it be implemented as in ie, in order for older customizations to work with webview2 as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9dc9d2-795c-9612-3585-408b4621c080
* Version Independent ID: f73fc16d-d842-4507-9fdb-b42856720355
* Content: [Microsoft Edge WebView 2 for WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf#feedback)
* Content Source: [microsoft-edge/webview2/gettingstarted/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @maliakkas, the engineering team asked for more information on your scenario. Please comment on the linked issue on the WebViewFeedback repo, or you can open your own issue if you prefer that. I'll go ahead and close this issue now. Thanks.
