### ISSUE TITLE
WebView2 incompatible with low-integrity processes

### ISSUE THREAD

**Issue by forderud** [MicrosoftDocs/edge-developer#703]
I'm unable to add a WebView2 control in my C# WinForms or WPF applications if the process is running in low integrity mode. This makes me unable to display web content with a more modern browser than IE in a security sandboxed .Net application.

## Steps to Reproduce
1. Clone & build https://github.com/MicrosoftEdge/WebView2Samples
2. For the WebView2WindowsFormsBrowser & WebView2WpfBrowser projects:
   - Start command prompt with admin permissions and run "`icacls <appname>.exe /setintegritylevel Low`" so that it will run in low integrity.
   - Start the application
   - Observe that the webpage loading fails silently _if_ the process is running in low integrity.

[Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) can be used to check if a process runs under the low, medium or high integrity.

## Expected behavior
The WebView2 control should start normally, as for medium or high-integrity processes.
The legacy `System.Windows.Forms.WebBrowser` have always supported low-integrity.

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: c82b4fb3-b1bd-ea62-5f3d-335caf143497
* Version Independent ID: a0d2d661-8d09-126b-c60f-6a3fd36a4a03
* Content: [Microsoft Edge WebView2 Control - Microsoft Edge Development](https://docs.microsoft.com/nb-no/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @forderud, thanks for your interest in WebView2. The issues in this repo are intended to track errors in documentation. For technical support, can you open an issue on [https://github.com/MicrosoftEdge/WebViewFeedback](https://github.com/MicrosoftEdge/WebViewFeedback)? 
Thanks.

**Comment by forderud** [comment]
Ok. I've now moved the issue over to https://github.com/MicrosoftEdge/WebViewFeedback/issues/198
