### ISSUE TITLE
Grammar nitpick

### ISSUE THREAD

**Issue by arktronic** [MicrosoftDocs/edge-developer#71]
"you're extension will be packaged in no time" should be "your extension will be packaged in no time".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e606632-9492-a033-f5cd-763143ab90f7
* Version Independent ID: a37bced5-fe53-6182-9a08-1fa2080889a3
* Content: [Extensions - Packaging - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/packaging)
* Content Source: [microsoft-edge/extensions/guides/packaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/packaging.md)
* Service: **unspecified**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by libbymc** [comment]
Thanks, @arktronic! All fixed!
