### ISSUE TITLE
when more of WebView2's events are coming ?

### ISSUE THREAD

**Issue by FRsyesCD** [MicrosoftDocs/edge-developer#712]
webview2 has few useless/casual events when will u add containsfullscreenelement or newWindow and clicked element .... events ?

Microsoft webview has these events and more :
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.containsfullscreenelementchanged?view=winrt-19041

**Comment by Reezaali** [comment]
Hi @FRsyesCD, thanks for sharing this issue with us. Can you log the issue on the WebView2 engineering repo where the team can respond to your request? 
https://github.com/MicrosoftEdge/WebViewFeedback
Thanks.

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now.
