### ISSUE TITLE
How to use WebView2 with UWP docs needed

### ISSUE THREAD

**Issue by tauheedul** [MicrosoftDocs/edge-developer#713]
Can you demonstrate a way to use WebView2 as the browsing component of a UWP application - instead of the default?

So it can use the old WebView where UWP still has dependencies on it but allow the browser control to be WebView2 so pages render smoother (giving it the best of both worlds).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Microsoft Edge WebView 2 for Windows Forms apps - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/webview2/gettingstarted/winforms)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jasonstephen15** [comment]
Thank you for opening this issue @tauheedul ! Our team recently released a Webview2 for WinUI3 (UWP) Getting Started doc linked below. I am tagging @adambarlow for more information on using WebView on prior versions of UWP.

 https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.
