### ISSUE TITLE
Missing a crucial component...

### ISSUE THREAD

**Issue by shaareable** [MicrosoftDocs/edge-developer#715]
Greetings from Sunny Vancouver :)

I'm writing a C# Windows Forms app with the webview2 in order to save my wife from struggling with a 90's website she has to waste hours a day on (its the Usborne Consultant website, they sell children books). I hope to automate the drudgery...

It appears a very useful feature is not documented in the page... how to wait until the page's loaded.

`        private void btnStart_Click(object sender, EventArgs e){
            if (webView != null && webView.CoreWebView2 != null) {
                webView.CoreWebView2.Navigate("https://www.usbornebooksathome.ca/");
                //now how do I tell it to wait until it's completely loaded??????}
        }`

Thank you !

Antoine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Microsoft Edge WebView 2 for Windows Forms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@shaareable I’m sorry to hear that you’re having an issue. I’ve created an [issue](https://github.com/MicrosoftEdge/WebViewFeedback/issues/237) in the [WebView2 Feedback GitHub repo](https://github.com/MicrosoftEdge/WebViewFeedback) for you, which is where our engineering team engages with the community. You may want to watch the repo to get notifications going forward. Thanks.

**Comment by mikemeinz** [comment]
Can't you use the [NavigationCompleted](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/winforms/0-9-515/microsoft-web-webview2-winforms-webview2#navigationcompleted) event to do that?

**Comment by mqudsi** [comment]
```csharp
// Copyright Mahmoud Al-Qudsi, NeoSmart Technologies. All rights reserved.
// Licensed under the MIT License.

namespace NeoSmart.Extensions
{
    public static class WebView2Extensions
    {
        public static void Navigate(this WebView2 webview, Uri url)
        {
            webview.Source = url;
        }

        public static async Task NavigateAndWaitAsync(WebView2 webview, Uri uri)
        {
            var navigationComplete = new TaskCompletionSource<bool>();
            void RequestedUrlLoaded(WebView2 webview, WebView2NavigationCompletedEventArgs e)
            {
                navigationComplete.SetResult(true);
                webview.NavigationCompleted -= RequestedUrlLoaded;
            }
            webview.NavigationCompleted += RequestedUrlLoaded;
            webview.Navigate(uri);

            await navigationComplete.Task;
        }
    }
}
```

**Comment by mikemeinz** [comment]
Example of how to enable the **NavigationCompleted** event handler. The **NavigationCompleted**  event handler is called after the WebView2 control has finished rendering the web page.

```
using System;
using System.Diagnostics;
using System.Windows.Forms;
using Microsoft.Web.WebView2.Core;
namespace WebView2
{
    public partial class WebView : Form
    {
        public WebView()
        {
            InitializeComponent();
            this.Load += WebView2Test_Load;
        }
        private void WebView2Test_Load(object sender, EventArgs e)
        {
            InitializeAsync();
        }
        async private void InitializeAsync()
        { 
            await webview.EnsureCoreWebView2Async(); // Wait for coreWebView2 initialization
            webview.NavigationCompleted += browser_NavigationCompleted;
            webview.Source = new System.Uri("https://microsoft.com/", UriKind.Absolute);
        }
        private void browser_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            Debug.Print ("Navigation Completed");
        }
   }
}
```

**Comment by ShaareableApps** [comment]
> ```cs
> // Copyright Mahmoud Al-Qudsi, NeoSmart Technologies. All rights reserved.
> // Licensed under the MIT License.
> 
> namespace NeoSmart.Extensions
> {
>     public static class WebView2Extensions
>     {
>         public static void Navigate(this WebView2 webview, Uri url)
>         {
>             webview.Source = url;
>         }
> 
>         public static async Task NavigateAndWaitAsync(this WebView2 webview, Uri uri)
>         {
>             var navigationComplete = new TaskCompletionSource<bool>();
>             void RequestedUrlLoaded(WebView2 webview, WebView2NavigationCompletedEventArgs e)
>             {
>                 navigationComplete.SetResult(true);
>                 webview.NavigationCompleted -= RequestedUrlLoaded;
>             }
>             webview.NavigationCompleted += RequestedUrlLoaded;
>             webview.Navigate(uri);
> 
>             await navigationComplete.Task;
>         }
>     }
> }
> ```

Hi Mqudsi,

Could I ask you what version you are using and what the using statements at the top?

Thanks,

Antoine

**Comment by ShaareableApps** [comment]
Isn't there a way to simply do a if(browser.navigationCompleted == true){ etc. } ?
How do I do this with WebView2?

**Comment by Reezaali** [comment]
@ShaareableApps would you mind opening an issue on the following repo where the Engineering team responds to customer questions:
https://github.com/MicrosoftEdge/WebViewFeedback

I'll go ahead and close this issue now. Thanks.
