### ISSUE TITLE
DevTools standalone, non-store link

### ISSUE THREAD

**Issue by TheJaredWilcurt** [MicrosoftDocs/edge-developer#723]
Is there currently (and if not, can we get), a link to the Edge DevTools to download them *without* having to go through the Windows store?

* https://www.microsoft.com/store/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj

I understand that this is meant to make it easier to download/install, but it actually just makes it almost impossible to build tooling around Edge. I'd much prefer just a Node module package that could download/install a versioned release of the dev tools. Similar to how Puppeteer or `ndb` or Cypress, etc all download parts of chromium for use in other tooling.

But at the very least having an official link to direct-download the file would simplify tooling a lot more.

**Comment by zoherghadyali** [comment]
Hi @TheJaredWilcurt! Thank you for using Microsoft Edge and sending us your feedback. As you may already know, [Microsoft Edge has shifted from the EdgeHTML web platform to adopt the Chromium web platform](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/). The new Chromium-based Microsoft Edge is available for download [here](https://www.microsoft.com/edge).

As a result, this version of Microsoft Edge now comes with new-and-improved DevTools. You can learn more about the new DevTools in [our documentation](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium). The old EdgeHTML-based DevTools, that are packaged in the [Microsoft Edge DevTools Preview app](https://www.microsoft.com/en-us/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj), are no longer receiving major updates or new features. To learn about the latest and greatest features available in the Microsoft Edge (Chromium) DevTools, check out [What's New in the DevTools](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2020/03/devtools).
