### ISSUE TITLE
I can't reference this namespace on xaml

### ISSUE THREAD

**Issue by AzuresSunday** [MicrosoftDocs/edge-developer#724]
I'm following this tutorial coding.
but I found it unusable.
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ba9dc9d2-795c-9612-3585-408b4621c080
* Version Independent ID: f73fc16d-d842-4507-9fdb-b42856720355
* Content: [适用于 WPF 应用的 Microsoft Edge Web 视图2 - Microsoft Edge Development](https://docs.microsoft.com/zh-cn/microsoft-edge/webview2/gettingstarted/wpf)
* Content Source: [microsoft-edge/webview2/gettingstarted/wpf.md](https://github.com/MicrosoftDocs/edge-developer.zh-cn/blob/master/microsoft-edge/webview2/gettingstarted/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by magnogtsouza** [comment]
I also tried and it gave error.

**Comment by Reezaali** [comment]
Hi @AzuresSunday and @magnogtsouza. I’m sorry to hear that you’re having an issue. I’ve created an [issue](https://github.com/MicrosoftEdge/WebViewFeedback/issues/234) in the [WebView2 Feedback GitHub repo](https://github.com/MicrosoftEdge/WebViewFeedback) for you, and the team has responded. Please feel free to check out the response and engage with the team there. I’ll go ahead and close this issue now. You may want to watch the repo to get notifications going forward. Thanks.
