### ISSUE TITLE
s/index/mobile.png) 

### ISSUE THREAD

**Issue by oyyunttt** [MicrosoftDocs/edge-developer#725]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 196d2a77-99b7-78c6-e392-f5cd2c89aa54
* Version Independent ID: ca07d8cb-b643-d0de-a6b8-bd1e4bf771ee
* Content: [DevTools 中的新增功能（Microsoft Edge 83） - Microsoft Edge Development](https://docs.microsoft.com/zh-cn/microsoft-edge/devtools-guide-chromium/whats-new/2020/03/devtools#view-network-requests-that-set-a-specific-cookie-path)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2020/03/devtools.md](https://github.com/MicrosoftDocs/edge-developer.zh-cn/blob/master/microsoft-edge/devtools-guide-chromium/whats-new/2020/03/devtools.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by TinaMcN** [comment]
@oyyunttt 感谢您报告此问题。 这似乎是我们的机器翻译工具的问题。 我们将进行调查。(Thank you for reporting this issue.  It appears to be a problem with our machine translation tool.  We will investigate it.)

**Comment by OfficeGlobal** [comment]
Hello @oyyunttt , the article was updated and images are displayed properly at live page
