### ISSUE TITLE
webview2 assembly reference error

### ISSUE THREAD

**Issue by tmblog** [MicrosoftDocs/edge-developer#729]
I followe the tutorial and created, I didn't have the pre-release option but did get a stable version to install from nuget. But I got the following error.

`The tag 'WebView2' does not exist in XML namespace 'clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf'.`

`XLS0414	The type 'wv2:WebView2' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built. webview2app MainWindow.xaml	11	`

This is my mainwindow.xaml:

```
<Window x:Class="webview2app.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:webview2app"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <DockPanel>
        <wv2:WebView2 Name="webView"
                  Source="https://www.microsoft.com"
    />
    </DockPanel>
</Window>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9dc9d2-795c-9612-3585-408b4621c080
* Version Independent ID: f73fc16d-d842-4507-9fdb-b42856720355
* Content: [Microsoft Edge WebView 2 for WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf)
* Content Source: [microsoft-edge/webview2/gettingstarted/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by emailajay21** [comment]
I am also facing same issue.

**Comment by bakkar89** [comment]
I had to change the package reference to pre-release in .csproj to make it work

<PackageReference Include="Microsoft.Web.WebView2" Version="0.9.538-prerelease" />

**Comment by alamathe1** [comment]
@bakkar89 Can you post the exact change is possible?

This is what I have in my .csproj file.

```
  <Import Project="..\packages\Microsoft.Web.WebView2.0.9.538\build\Microsoft.Web.WebView2.targets" Condition="Exists('..\packages\Microsoft.Web.WebView2.0.9.538\build\Microsoft.Web.WebView2.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Microsoft.Web.WebView2.0.9.538\build\Microsoft.Web.WebView2.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.Web.WebView2.0.9.538\build\Microsoft.Web.WebView2.targets'))" />
  </Target>
```

**Comment by emailajay21** [comment]
By using [Install-Package Microsoft.Web.WebView2 -Version 0.9.538-prerelease] command, it got installed. but still below mention code piece is not working.

`<DockPanel>
    <wv2:WebView2 Name="webView"
                  Source="https://www.microsoft.com"
    />
</DockPanel>`

I have also try from code behind but that too is also not working 

`private void Button_Click(object sender, RoutedEventArgs e)
        {
            webView.CoreWebView2.Navigate("https://www.google.com");
        }
`

**Comment by saipravatkumar1996** [comment]
Is it mandatory to install any Microsoft edge channel when developed Web View2 ?I have install Beta channel  its working fine but when install Stable channel then i have gated error null object .When Beta  channel updated new release then previous Media link not working.Is it any stable version available where all old version and new version working.

**Comment by vmeganathan81** [comment]
We need to compile your project in version 4.6.2 and above, for this error to go away. Since they have compiled those dll in 4.6.2.
Let me know if this resolves the issue

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.
