### ISSUE TITLE
Missing info for global methods like CreateWebView2Environment

### ISSUE THREAD

**Issue by dd8** [MicrosoftDocs/edge-developer#730]
The global methods like `CreateWebView2Environment` appear to have been engineered to avoid a load-time dependency on WebView2Loader.dll, and apps using WebView2 will start even if WebView2Loader.dll is missing.

That's a very good thing, but it would be good to document this. It look me a few hours using `dumpbin` and testing on VMs without Edge to confirm this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6517b911-1bf3-f658-cda8-7a666dc46aa3
* Version Independent ID: 4d079038-4cfb-7f7f-f716-87ab0e0f50a2
* Content: [Microsoft Edge WebView2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-430/webview2-idl)
* Content Source: [microsoft-edge/webview2/reference/win32/0-9-430/webview2-idl.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/reference/win32/0-9-430/webview2-idl.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.
