### ISSUE TITLE
Flag --auto-open-devtools-for-tabs does not work

### ISSUE THREAD

**Issue by Londovir** [MicrosoftDocs/edge-developer#732]
As of version 83.0.478.37 (64-bit), the flag --auto-open-devtools-for-tabs does not appear to work when launching MSEdge at a command prompt. The same flag does correctly work in Chrome and presumably Chromium (have not tested Chromium yet, but have tested latest Chrome), but will not work in Edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a30dd02-f9c7-852e-337c-ef604a38ab8f
* Version Independent ID: 11f3c055-0f28-52ab-ab6b-0d6f6b95c640
* Content: [Open Microsoft Edge DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/open)
* Content Source: [microsoft-edge/devtools-guide-chromium/open.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/open.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by zoherghadyali** [comment]
Hi @Londovir! I just ran: `"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --auto-open-devtools-for-tabs` and I'm seeing on Version 83.0.478.56 (Official build) (64-bit) that the DevTools are opening for every tab:

![image](https://user-images.githubusercontent.com/34316555/85824095-d7cd6a00-b733-11ea-9157-d16fcf168b54.png)

If you continue to encounter this issue, there may be some helpful diagnostic info in Microsoft Edge's logs. Can you click the **Feedback** button in the DevTools and ensure "Send diagnostic data" is checked when you observe this behavior?

![image](https://user-images.githubusercontent.com/34316555/85824184-064b4500-b734-11ea-98eb-ac3c4635a476.png)

Thanks!

**Comment by Londovir** [comment]
Agree. Even version 83.0.478.45 is now working (I haven't yet updated to the newest.) In the build I mentioned above, the flag **would** work, but only if no other Edge instances/windows were running at the time of launch. Since I like to use Edge as my daily driver browser, that was often the case, and trying to launch a new instance of Edge using this flag would not open the developer panel as desired when launched from command line, VS Code, or Visual Studio. I would have to close all other Edge instances first, then it would work. Thankfully, it works now without having to close other instances. Many thanks to the dev team!

**Comment by jurijsk** [comment]
As of  now It looks like this is not working anymore. I've tried to run: `msedge --auto-open-devtools-for-tabs` both with instance running and without one immediately after Windows restart, and after killing all instances. 

version:
119.0.2151.44 (Official build) (64-bit)

**Comment by thkuberlin** [comment]
With current version 119.0.2151.58 it doesn't work for me either.

**Comment by captainbrosset** [comment]
Thanks for sharing. This is being tracked in this other issue: https://github.com/MicrosoftEdge/DevTools/issues/197
It seems like the issue has been resolved in version 120. Are you able to test whether it works for you there?
