### ISSUE TITLE
No VB.Net Examples?

### ISSUE THREAD

**Issue by AlanBurkhart** [MicrosoftDocs/edge-developer#734]
Do you plan to add examples for VB.Net?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Microsoft Edge WebView 2 for Windows Forms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@AlanBurkhart I created the following issue on the engineering repo and they replied there. I'll go ahead and close this issue for now: 

https://github.com/MicrosoftEdge/WebViewFeedback/issues/265

**Comment by DDSGuy** [comment]
I see there are examples for the MS Edge WebView2 using C# and C++.... How about VB.Net and/or VBA???  Thanks
