### ISSUE TITLE
feature Request -> if(browser.navCompleted == true)

### ISSUE THREAD

**Issue by ShaareableApps** [MicrosoftDocs/edge-developer#744]
Greetings,

I'm still struggling just to figure out how to implement in C# something that was dead simple in excel vba: checking if the browser had finished loading.  C# is like heaven compared to that cage I was in (excel vba) hahaha but I really need to be able to quickly and easily check if the page has loaded as I code a sequence of automation events and right now it appears the simplest form, 
browser.navigationCompleted == true 

for example, isn't there.

And to me that's kind of odd since that'd be the simplest way to check.

I can't even find working documentation on how to actually check from within my code if the page has loaded to enable the next line of code to run.

Thanks for your time,

Antoine

**Comment by Reezaali** [comment]
Hi @ShaareableApps, I'm sorry to hear about your issue. Are you trying to do this task using WebView2?

**Comment by ShaareableApps** [comment]
Hi Reezeaali!

Yes. I was thinking that webview2 was an evolution of what I was using in Excel VBA.

Cheers,

Antoine

**Comment by Reezaali** [comment]
Hi @ShaareableApps thanks for the clarification. For this type of question, I think it'll be better suited for the following repo which is where the engineering team responds to issues: https://github.com/MicrosoftEdge/WebViewFeedback
Can you close this issue, and re-open it at the above repo?

**Comment by Reezaali** [comment]
I'll proceed to close out this issue now. Thank you.

**Comment by ShaareableApps** [comment]
Thank you for your time. I will follow your recommendation. Cheers from Vancouver! :)
