### ISSUE TITLE
This is hardly believable

### ISSUE THREAD

**Issue by markweatherill1966** [MicrosoftDocs/edge-developer#75]
I'd prefer to see a guide to creating extensions for Edge, and not a guide to how to port extensions from other browsers.
I realise this is how most Edge extensions are going to be made, but what if I wanted to create one from scratch? Microsoft is telling me not to start here!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e322d0db-8a91-6fff-7510-a5ec18fa4a65
* Version Independent ID: 0c60d518-08f5-3b4e-0f4b-b7cd71455951
* Content: [Extensions - Creating an extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/creating-an-extension)
* Content Source: [microsoft-edge/extensions/guides/creating-an-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/creating-an-extension.md)
* Service: **unspecified**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by someniatko** [comment]
@libbymc also the statement "Microsoft Edge does not support `browser.tabs.reload()` seems not true. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/reload

**Comment by libbymc** [comment]
@someniatko - Yes, correct. As of EdgeHTML 17, `browser.tabs.reload()` is supported. This page will be updated shortly.

**Comment by libbymc** [comment]
Hi @markweatherill1966 - check out the new [Creating a Microsoft Edge extension](https://docs.microsoft.com/microsoft-edge/extensions/guides/creating-an-extension) topic. This guide now walks you through creating an extension specifically for Microsoft Edge, start to finish. Thanks for reaching out!
