### ISSUE TITLE
When adding Microsoft.Extensions.Hosting WebView2 reports Microsoft.Web could not be found

### ISSUE THREAD

**Issue by ChrisPulman** [MicrosoftDocs/edge-developer#752]
Using a WPF application, net48 / netcoreapp3.1
When adding Microsoft.Extensions.Hosting WebView2 reports Microsoft.Web could not be found.

**Comment by Reezaali** [comment]
Hi @ChrisPulman, sorry to hear about this issue. Would you mind closing this issue, and opening an issue on the following repo, which is where the Engineering team responds?
https://github.com/MicrosoftEdge/WebViewFeedback

**Comment by Reezaali** [comment]
@ChrisPulman I'll go ahead and close this issue. Please let us know if you are still having the issue. Thanks.
