### ISSUE TITLE
External Resources with xlink:href require viewBox

### ISSUE THREAD

**Issue by jt-github** [MicrosoftDocs/edge-developer#76]
When using the `<use>` element to include SVG files, Edge ignores any `viewBox` defined within the SVG file and requires that a `viewBox` is defined on the parent SVG element instead.

Example "snazzy.svg" file:
```
<svg id="svg" viewBox="0 0 80 80">
  <circle cx="40" cy="40" r="40" stroke="black" stroke-width="3" fill="red" />
</svg> 
```

Examples of file being referenced from within an HTML document...

This won't work in Edge (but works fine in Chrome, Firefox, etc.):
`<svg><use xlink:href="snazzy.svg#svg"></use></svg>`
(Edge will render nothing at all)

But this _will_:
`<svg viewBox="0 0 400 400"><use xlink:href="snazzy.svg#svg"></use></svg>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad9adcff-dd65-a70e-1984-5d264995cb05
* Version Independent ID: 62643b2d-89a3-ec59-81a5-5de47763da5b
* Content: [Dev guide - SVG - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/graphics/svg#xlinkhref)
* Content Source: [microsoft-edge/dev-guide/graphics/svg.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/graphics/svg.md)
* Service: **unspecified**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by erikadoyle** [comment]
Hi @jt-github, thanks for the detailed bug writeup! Would you mind posting it to our Edge bug db:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

There are some known issues with our viewBox implementation that are being investigated, so additional bug reports are always useful. Thanks!

**Comment by erikadoyle** [comment]
Fair enough :) We recently updated our docs feedback mechanism to be more explicit about where to file product bugs vs. doc bugs, though sometimes its hard to know if its an issue with the sample code or EdgeHTML engine itself without further triage by a human.
