### ISSUE TITLE
WebDriver Status and Commands reference link

### ISSUE THREAD

**Issue by pizzafacemo** [MicrosoftDocs/edge-developer#77]
I'm getting a 404 when I click the WebDriver Status and Commands (reference) link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c06efc-3188-86bb-4f73-f171b67df210
* Version Independent ID: 4859f651-74ee-4bbb-33c7-d999d4933070
* Content: [Dev guide - WebDriver - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/tools/webdriver)
* Content Source: [microsoft-edge/dev-guide/tools/webdriver.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/tools/webdriver.md)
* Service: **unspecified**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by libbymc** [comment]
Hi -  Which page are you trying to find? The Status command is here: [Status](https://w3c.github.io/webdriver/#dfn-status).

**Comment by pizzafacemo** [comment]
I was browsing your Microsoft Edge developer website and https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ and received a 404 when clicking the

WebDriver Status and Commands reference link.  I'm unable to find the link now.  Maybe the link has been removed.  You can close this ticket if the link can't be found.


Thank you. <https://docs.microsoft.com/en-us/microsoft-edge/webdriver#>




WebDriver - Microsoft Edge Development<https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/>
developer.microsoft.com
Close the loop on your developer cycle by automating testing of your website in Microsoft Edge with Microsoft WebDriver




________________________________

**Comment by libbymc** [comment]
Yep, it looks like the link was removed. Thanks for reaching out!
