### ISSUE TITLE
Documentation is unclear and possibly incorrect 

### ISSUE THREAD

**Issue by nick-acquaviva** [MicrosoftDocs/edge-developer#770]
```
{
    "update_url": "https://edge.microsoft.com/extensionwebstorebase/v1/crx"
}
```
This snippet is labeled _JavaScript_ but json is mentioned later in the article.

This statement, "In your Extension key, create a property, **update_url**, and set it to the value: https://edge.microsoft.com/extensionwebstorebase/v1/crx" is not clear. Does property mean a REG_SZ value named "update_url"? Or does or is the json stored as a REG_MULTI_SZ value?

This statement, "To uninstall your extension (for example, if your software is uninstalled), remove your preference file (aaaaaaaaaabbbbbbbbbbcccccccccc.json) or the metadata from the registry." is not clear. Where is the "preference file" stored? What is the "metadata" in the registry? Is the "metadata" a REG_SZ value such as "update_url"?

A few examples of the registry keys and values would be very helpful.

I am trying to install an extension using this method on 64-bit Windows 10. I tried all of these registry values:

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Edge\Extensions\gggmmkjegpiggikcnhidnjjhmicpibll]
"update_url"="https://edge.microsoft.com/extensionwebstorebase/v1/crx"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\Extensions\gggmmkjegpiggikcnhidnjjhmicpibll]
"update_url"="https://edge.microsoft.com/extensionwebstorebase/v1/crx"

[HKEY_CURRENT_USER\SOFTWARE\WOW6432Node\Microsoft\Edge\Extensions\gggmmkjegpiggikcnhidnjjhmicpibll]
"update_url"="https://edge.microsoft.com/extensionwebstorebase/v1/crx"

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Edge\Extensions\gggmmkjegpiggikcnhidnjjhmicpibll]
"update_url"="https://edge.microsoft.com/extensionwebstorebase/v1/crx"

Only the last registry value HKCU\SOFTWARE\Microsoft\Edge\Extension
had any effect. According to the documentation, HKLM\SOFTWARE\WOW6432Node\Microsoft\Edge\Extensions should have been to registry value to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f290aba-5618-9b79-e3ac-243ec8cc4dd6
* Version Independent ID: 0cda1705-27db-4282-40e1-a2fbbd16ed2e
* Content: [Alternate Method of Distributing Extension - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by d4rk0de** [comment]
any updates on this? How I deploy for example an extension which is hosted in my environment? I just point the url to my network path? 
None of the reg keys above works.

**Comment by gebansal** [comment]
@d4rk0de I'd request you to please reach out to the Microsoft Edge extensions team at ext_dev_support@microsoft.com for the above issue.

**Comment by ashishnirvana1** [comment]
> any updates on this? How I deploy for example an extension which is hosted in my environment? I just point the url to my network path?
> None of the reg keys above works.

**Steps to host a package locally and install it.** 

1. Host the package locally: Create CRX file of extension and host it at a shared directory/location 

    - Do not host the file at a location that requires authentication 
    - The manifest.json file of extension should not contain key attribute and should have update_url attribute pointing to the location of the updates.xml file (details in point number 2 below).  
    - [Read more here ](https://docs.google.com/document/d/1pT0ZSbGdrbGvuCsVD2jjxrw-GVz-80rMS2dgkkquhTY/edit#heading=h.gb2ntk6856ld) 

2. Create updates.xml file with the URL pointing to the CRX file, the version number of the extension and extension id ([Read more here ](https://developer.chrome.com/apps/autoupdate#update_manifest)) 
3. Whitelist the URL where the CRX and updates.xml is hosted using the ExtensionInstallSources policy ([Read more here ](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#extensioninstallsources)) 
4. [Optional] Use the ExtensionInstallForcelist policy to force install the extension on selected desktops or security groups ([Read more here ](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#extensioninstallforcelist))

**Comment by gebansal** [comment]
@d4rk0de We'll go ahead and close this for now. If you feel that the issue has not been addressed and there are more open questions, please feel free to either reopen this issue or a create a new one.
