### ISSUE TITLE
Support Web API WebAuthn uvi, uvm & authnSel extension

### ISSUE THREAD

**Issue by letrthang** [MicrosoftDocs/edge-developer#773]
[Enter feedback here]
These extensions were designed in the Web API spec. However until now it has not implemented yet.

Same request i submitted to chromium.org:
https://bugs.chromium.org/p/chromium/issues/detail?id=1097972

---
#### Document Details
Details about Web API spec for uvi & uvm extension:
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialRequestOptions/extensions
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/extensions
https://w3c.github.io/webauthn/#sctn-uvm-extension

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 821eda1f-9154-4229-e023-83df97117a9d
* Version Independent ID: c7d27a3f-dc27-4bca-faa9-ccddbf3e61ce
* Content: [Dev guide - Web Authentication - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication#api-surface)
* Content Source: [microsoft-edge/dev-guide/windows-integration/web-authentication.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/dev-guide/windows-integration/web-authentication.md)
* Product: **microsoft-edge**
* Technology: **windows-integration**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @letrthang - have you tried using the new Microsoft Edge? You can send feedback using the Send Feedback option from within Microsoft Edge. I'll go ahead and close this issue now. Thanks.
