### ISSUE TITLE
Picture is missing

### ISSUE THREAD

**Issue by leevare** [MicrosoftDocs/edge-developer#777]
There are many pictures missing in the document

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: dfe13e34-3525-cc2b-b6cc-e445f676749a
* Version Independent ID: 69f4a92e-525c-2abc-3ecf-5cc69717dd1a
* Content: [分析运行时性能入门 - Microsoft Edge Development](https://docs.microsoft.com/zh-cn/microsoft-edge/devtools-guide-chromium/evaluate-performance/)
* Content Source: [microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md](https://github.com/MicrosoftDocs/edge-developer.zh-cn/blob/master/microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by OfficeGlobal** [comment]
Hello @leevare  , the article was updated and images are displayed properly at live page
