### ISSUE TITLE
translation flaw

### ISSUE THREAD

**Issue by abwesendf** [MicrosoftDocs/edge-developer#778]
Translation:
German "Durchwahl" means phone extension. The direct number to call to get someone at a desk in a company.
Extension is typically translated with "Extension" or "Erweiterung", but never with Durchwahl
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4edd411d-e52a-32ef-e539-fb4ed709c86c
* Version Independent ID: 9b96eeb9-accc-7230-20b1-b704d9f9a79e
* Content: [Microsoft Edge (Chrom)-Erweiterungen - Microsoft Edge Development](https://docs.microsoft.com/de-de/microsoft-edge/extensions-chromium/)
* Content Source: [microsoft-edge/extensions-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer.de-de/blob/master/microsoft-edge/extensions-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Thanks for reporting this issue. We've fixed the issue.
