### ISSUE TITLE
Add dates to releases

### ISSUE THREAD

**Issue by LyalinDotCom** [MicrosoftDocs/edge-developer#781]
It would be very helpful if each release had not just the version but also the date when the update became available. Right now its hard to understand for example if there is something new since roughly a month ago when I last looked. This would also better match how we do release notes in other parts of the company.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af2b9c25-cf58-71cb-9046-acd2cdfd84d4
* Version Independent ID: 8515f71e-5ca1-530a-7c63-9de565eb368d
* Content: [Release Notes for Microsoft Edge WebView2 for Win32, WPF, and WinForms - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#feedback)
* Content Source: [microsoft-edge/webview2/releasenotes.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/releasenotes.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by lkamazaezuzemedium** [comment]
26/6/2020

**Comment by Reezaali** [comment]
@LyalinDotCom - thanks for logging the issue. Can you share an example of what you had in mind please? Thanks!

**Comment by LyalinDotCom** [comment]
Sure example below:

-

0.9.538 [**Add Date Of This Release Here**]
NuGet package | minimum Microsoft Edge version 85.0.538.0.

**Comment by Reezaali** [comment]
Thanks for your suggestion. We've started including release dates in our release notes.
