### ISSUE TITLE
Unchecked runtime.lasterror: Could not establish connection. Receiving end does not exist

### ISSUE THREAD

**Issue by jimweegar** [MicrosoftDocs/edge-developer#790]
Please advise on how-to fix this issue. Thank you.

The issue occurs in code provided by:
Microsoft Edge Documentation - Extensions (Chromium) - Doc Date: 05/08/2020.

Getting Started Tutorial: "Dynamically Insert NASA Picture Below The Page Body Tag Using Content Scripts". - "NASA Picture of the day viewer - Part 2".

*** BEGIN ERROR ***
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

Context
extension://aaliggndnkipnpgpnglkgaejjjmngheo/popup/popup.html

Stack Trace
popup/popup.html:0 (anonymous function)
*** END ERROR ***

Steps to Duplicate Error:
1) Download extension code included in tutorial.
2) Load extension into Edge Chromium Browser: "Version 83.0.478.56 (Official build) (64-bit)".
3) Click extension icon to display popup dialog.
4) Click "Display" button on the popup dialog to send message to Edge tab. ***ERROR OCCURS HERE IN STEP 4***
5) Review error details by viewing Edge extensions page and clicking the "Errors" link on "NASA Picture of the day viewer 0.0.0.1".

**Comment by jimweegar** [comment]
Okay, so now the issue no longer appears to be a problem. Not exactly sure why. I did notice that Edge Chromium Browser updated to: Version 83.0.478.58 (Official build) (64-bit). After that I removed this extension and rebooted my PC. After that, the extension appears to be working. In any case, I'm closing the issue. Thank you.

**Comment by zakoxxk1998** [comment]
https://codapi.org/embed/?sandbox=cpp&code=data%3A%3Bbase64%2CPY1BCsMwDATveoXqQEmgL0hMzv1Bz8EWQWBLYCu9lPy9xKY9zuyyO7CEdERCz1qt0JZXGP6uWmHZV4C3csS9ENkYVKphtTjPPb6jbJkm%2FAAi9iDoYeg9uielpA90F1ytJm8NW5EkpgVOABbDvLGMv51%2B5l5aUnTTAucX
