### ISSUE TITLE
Document that CoTaskMemFree is necessary after GetAvailableCoreWebView2BrowserVersionString

### ISSUE THREAD

**Issue by Urmeli0815** [MicrosoftDocs/edge-developer#791]
GetAvailableCoreWebView2BrowserVersionString returns a string that (according to the sample) needs to be freed with CoTaskMemFree. This should be explicity stated in the API-Documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47deb796-74a5-eaf6-668e-ea9dd928b622
* Version Independent ID: 4ffbd156-1b73-6c42-7ab1-bae094dbad66
* Content: [Microsoft Edge WebView2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-488/webview2-idl)
* Content Source: [microsoft-edge/webview2/reference/win32/0-9-488/webview2-idl.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/reference/win32/0-9-488/webview2-idl.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Closing this issue because I opened an issue on the engineering team's feedback repo. Thanks.
