### ISSUE TITLE
Why not write a full update list?

### ISSUE THREAD

**Issue by newpost** [MicrosoftDocs/edge-developer#798]
https://developers.google.com/web/updates/2020/03/devtools

There is a function above that is not mentioned in the update document.For example,New icons for breakpoints, conditional breakpoints, and logpoints.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 196d2a77-99b7-78c6-e392-f5cd2c89aa54
* Version Independent ID: ca07d8cb-b643-d0de-a6b8-bd1e4bf771ee
* Content: [What's new in DevTools (Microsoft Edge 83) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2020/03/devtools)
* Content Source: [microsoft-edge/devtools-guide-chromium/whats-new/2020/03/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/whats-new/2020/03/devtools.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Thanks for the feedback @newpost. We've updated the article.
