### ISSUE TITLE
Unable to connect to AD

### ISSUE THREAD

**Issue by Adrianotiger** [MicrosoftDocs/edge-developer#80]
I don't know where to report it, I write it here.
Yesterday I tried to pack my PWA as APPX. Everything seems to work, but the login to a Microsoft Account doesn't work inside an App (works perfectly as PWA). Once I try to login in the Microsoft account and after inserting my email I get the message: "Technical problems for the Microsoft account, try again later".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcef5936-232e-1ab0-c1c4-77026c79e277
* Version Independent ID: b6ec450d-ead9-ffcf-0d5b-7a408bf0e13d
* Content: [Get started with Progressive Web Apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/get-started)
* Content Source: [microsoft-edge/progressive-web-apps/get-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/get-started.md)
* Service: **unspecified**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
Hi @Adrianotiger, would you mind posting this and your repro steps to our Edge bug database so someone can further investigate?

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

...or alternately, if you're on Windows 10 you can use the _Feedback _Hub__ app to submit a bug report (and even capture a video of the repro steps, if you choose to do so). Either way, both feedback mechanisms funnel into our central bug db. Thanks!
