### ISSUE TITLE
Selenium Edge Driver Automation with pre-launched WebView2 application

### ISSUE THREAD

**Issue by Arthanarieaswaran** [MicrosoftDocs/edge-developer#805]
I have complex windows application with WebView2 (chromium) embedded edge browser implementation.
My windows application will launch using some part windows screen automation, during the automatoin follow, one of the step will launch the WebView2 embedded browser windows screen. So I would like to know, how to get hold of automation for already launched WebView2 Screens.

I have seen [Automating and testing WebView2 with Microsoft Edge Driver](https://docs.microsoft.com/en-us/microsoft-edge/webview2/howto/webdriver), will launch the application and controlling the webpage using selenium.

Kindly let me know, how to do the webpage automation on pre-launched (not launched by selenium webdriver) application using selenium for WebView2 application.

Artha

**Comment by SIvanskoi** [comment]
Hi,

I have the same question. Another question is how do I connect to a specific window showing web content in WebView2 control. There are different dialogs in the application showing web content in different conditions. For example, the application starts and users may add Dropbox account, then do some stuff and then add Box account etc.

**Comment by Arthanarieaswaran** [comment]
I got answered for my question like below and it worked for me

**Answer 1**
______________________________________________________________
Thank you for your interest in building and automating your application using WebView2 (Chromium). It is certainly possible to connect Selenium WebDriver to a pre-launched Webview2 instance. To do this, you will first need to configure WebView2 to enable remote debugging, and then you can configure WebDriver to connect to the remote debugging port instead of launching a new process.

To enable remote debugging for WebView2, set the following environment variable before launching your application:

WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS="--remote-debugging-port=9222"

This will tell WebView2 to listen for remote debugging connections on port 9222. You can substitute 9222 with a port of your choice. If you'd prefer, you may also set the additionalBrowserArguments property in C++ when you create the WebView2Environment. See https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/webview2-idl for more information about setting additionalBrowserArguments.

Next, launch the WebView2 embedded browser window and wait for the WebView2 browser to load. Finally, use the following Selenium code to connect to the WebView2 instance that was just launched:

var options = new EdgeOptions();
options.UseChromium = true;
options.UseWebView = true;
options.DebuggerAddress = "localhost:9222";
var driver = new EdgeDriver(options);

The important property here is 'DebuggerAddress'. This tells Selenium to connect to a running browser instead of launching a new one. Note, you may need to adjust the above Selenium code to your exact Selenium version and language. The above sample is for Selenium 4 alpha 06 or later, using C#.

Good luck and I hope this helps!
_______________________________________________________________

**Answer 2** - For your second question
_____________________________________________________
I am able to switch between the windows based on the windows title, title I can get from window handles, please see the code sample below
var listOfBrowsers = driver.WindowHandles;
foreach (var browser in listOfBrowsers)
{
	driver.SwitchTo().Window(browser);
	if (remoteEdgeWebDriver.Title.Contains(title))
	{
		break;
	}
}
____________________________________________________

I hope this will help you!!!

**Comment by SIvanskoi** [comment]
@Arthanarieaswaran Thank you very very very much for this answer.  This works well.

**Comment by sramssh** [comment]
@Arthanarieaswaran thank you so much for the solution! Worked for me

**Comment by SIvanskoi** [comment]
@csharsha As far as I know there is no way to do that for standalone IE or IE embedded browser control.

**Comment by SIvanskoi** [comment]
@csharsha For MS Edge window this works the same way as for WebView2: you would need to start MS Edge with --remote-debugging-port=NNNN command line where NNNN is any open port you would need to connect to the browser. Then you will be able to connect to the existing browser instance.

**Comment by Arthanarieaswaran** [comment]
Yes, as of now latest EdgeDriver supports attaching existing browser instance or embedded browser. If we customize the IEDriverServer source code (https://github.com/SeleniumHQ/selenium/tree/trunk/cpp), then we can able to attach already opened IE browser.

**Comment by csharsha** [comment]
Thank you very much @SIvanskoi and @Arthanarieaswaran as you said this option is working for MS edge. Can you please confirm whether this is possible for MS Edge in IE Mode?

**Comment by Arthanarieaswaran** [comment]
I think, it should work.

**Comment by MarcelGa** [comment]
@Arthanarieaswaran do you know how to setup EdgeOptions If I need to connect to webview browser running on remote machine? my tests access local webview browser without any problem.

**Comment by Arthanarieaswaran** [comment]
I haven't work this scenario, but code may be something similar below

--------------------------------------------------------
EdgeDriverService driverService = EdgeDriverService.CreateChromiumService("[EdgeDriverPath]");
  driverService.HideCommandPromptWindow = false;

  EdgeOptions edgeOptions = new EdgeOptions();

  edgeOptions.BinaryLocation = **"\\\MachineName\path\app.exe";**

  edgeOptions.UseChromium = true;

  edgeOptions.DebuggerAddress = **"MachineName:9200";** // Bascially machinename may be 'localhost' if it is running same machine and port may be different for you

  EdgeDriver remoteEdgeWebDriver = new EdgeDriver(driverService, edgeOptions);

  remoteEdgeWebDriver.Navigate();

-----------------------------------------------

**Comment by MarcelGa** [comment]
@Arthanarieaswaran should I replace "[EdgeDriverPath]" by path to edgedriver on each remote machine? or it should be path to edgedriver on test agent which executes tests? or its only constat which should not be changed. thank you

**Comment by Arthanarieaswaran** [comment]
This is not a constant, it should be edgedriver path, i am not sure what will this path, please try with remote driver machine edgedriver path.

**Comment by captainbrosset** [comment]
I believe this can be closed as the internal backlog task that was opened for this got closed last year. There is guidance in the docs related to attaching to running instances: https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver#step-4-choosing-whether-microsoft-edge-driver-should-launch-your-app-or-attach-to-it
