### ISSUE TITLE
Manfifest examlple refers Chrome extension for allowed origins

### ISSUE THREAD

**Issue by ejurinsky** [MicrosoftDocs/edge-developer#807]
**Wrong?**

<img width="826" alt="Screen Shot 2020-07-09 at 9 21 51 AM" src="https://user-images.githubusercontent.com/12001715/87065764-56abb380-c1c6-11ea-80ab-24a73119463e.png">

**Should be like this?**

<img width="933" alt="Screen Shot 2020-07-09 at 9 26 09 AM" src="https://user-images.githubusercontent.com/12001715/87065803-60cdb200-c1c6-11ea-97b8-7ede854b3e2f.png">

**Comment by ejurinsky** [comment]
extension:// does not work
chrtome-extension:// works 

documentation needs to be updated as it is confusing (see https://github.com/MicrosoftDocs/edge-developer/issues/812)

**Comment by gebansal** [comment]
@ejurinsky thank you for pointing out the error in the documentation. We are working on improving the documentation and we'll incorporate the above pointed out error at the same time.
"extension://[Microsoft-Catalog-extensionID]" should be changed to "chrome-extension://[Microsoft-Catalog-extensionID]"
