### ISSUE TITLE
This tool is rated 2.8 on your own store

### ISSUE THREAD

**Issue by ScottRFrost** [MicrosoftDocs/edge-developer#81]
Of the 8 reviews, 4 of them are 1 star saying the tool crashes.  Please release updates or at least the source for the tool so the community can take it over.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d4a026a-a501-3be9-3974-8f9095fbe7bd
* Version Independent ID: 43ed16fa-9d96-36f8-86c0-517f86b831d2
* Content: [Extensions - Porting Chrome extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions)
* Content Source: [microsoft-edge/extensions/guides/porting-chrome-extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/porting-chrome-extensions.md)
* Service: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by libbymc** [comment]
Hi, thanks for reaching out. However, this is not a documentation issue. Please leave your feedback on the [Microsoft Edge Extension Toolkit](https://www.microsoft.com/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb?rtc=1) page.
