### ISSUE TITLE
native message host manifest.json with "extension://crxid..." will not lunched by chrome

### ISSUE THREAD

**Issue by cuiliang** [MicrosoftDocs/edge-developer#812]
Hi,
I Want to write a Native message host that works for both Chrome and Edge.
By following the document: https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging
I added the following code to native message host program's manifest file:
```json
{
  "name": "com.getquicker.chromeagent",
  "description": "Chrome native message host for Quicker application",
  "path": "C:/Users/cuili/AppData/Local/Quicker/bin/NativeMessageHost/ChromeAgent.exe",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://jbpfafjlamdkljgeihnddjaldoihhbka/",
    "chrome-extension://klggbkjfmbonefdcfkiidhcmfjdfnepa/",
    "extension://hcnknmobjnlekfkbcllhcoldbppkgpda"  <----------------Added this line for edge
  ] 
}
```

after that, Chrome will not load the native message host application any more.
By change "extension://....." to "chrome-extension://....." it will work again.

And another problem:
There is no "[Microsoft-Catalog-extensionID]" in "patern center", only  "CRX ID":
![image](https://user-images.githubusercontent.com/1972649/87226476-904b0d00-c3c6-11ea-8d54-0735c9a37867.png)

**Comment by ejurinsky** [comment]
we also found that extension:// does not work for edge. need to use chrome-extension:// b

i opened issue about it as documentation is confusing: https://github.com/MicrosoftDocs/edge-developer/issues/807

**Comment by gebansal** [comment]
@cuiliang and @ejurinsky thank you for pointing out the error in the documentation. We are working on improving the documentation and we'll incorporate the above pointed out error at the same time. 
"extension://[Microsoft-Catalog-extensionID]" should be changed to "chrome-extension://[Microsoft-Catalog-extensionID]"
