### ISSUE TITLE
PWA on Edge (Chromium)

### ISSUE THREAD

**Issue by jamejone** [MicrosoftDocs/edge-developer#813]
Is there any way to list a PWA in the Microsoft Store and have it run on Chromium-Edge? I ask because my PWA ([nesteggly.com](https://www.nesteggly.com)) doesn't run on EdgeHTML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3263f88a-8279-75bc-1985-355339ae540f
* Version Independent ID: 5cf75ba7-6666-181f-ec00-dd4968a629ef
* Content: [Progressive Web Apps on Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by JudahGabriel** [comment]
Hi @jamejone,

Short answer: it's not currently possible, but will be soon.

Longer answer: The Edge team, Store team, and my team at pwabuilder.com have been working together to make PWAs in the Microsoft Store be based on the new Chromium-based Edge.

We've got a [Github issue opened here](https://github.com/pwa-builder/PWABuilder/issues/787) to track the work. The engineering work is partially done and still in progress. We expect the work to be done this year in the coming months.

Hope this helps.

**Comment by jamejone** [comment]
Thanks for sharing the status of that work. Good to know I'll probably need to repackage my app again once chromium-Edge arrives. Thanks again for the update. 👍
