### ISSUE TITLE
pwa apps in edge (Chromium)

### ISSUE THREAD

**Issue by behroozbc** [MicrosoftDocs/edge-developer#814]
hi 
i want know in new edge or edge (Chromium) this feature is active and i can submit my pwa apps to Microsoft store ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba583c8-c78b-49de-a68a-4fbc7a2bb568
* Version Independent ID: e71db58c-e513-eefd-3f4d-2644b88f405d
* Content: [Progressive Web Apps in the Microsoft Store - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-edgehtml/microsoft-store)
* Content Source: [microsoft-edge/progressive-web-apps-edgehtml/microsoft-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-edgehtml/microsoft-store.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@behroozbc thanks for reaching out. 
Short answer: it's not currently possible. For a more detailed response, please see:
https://github.com/MicrosoftDocs/edge-developer/issues/813
Thanks.
