### ISSUE TITLE
Clarify what the new runtime installer means?

### ISSUE THREAD

**Issue by Ciantic** [MicrosoftDocs/edge-developer#821]
May I ask what does this means specifically:

> Instead, it targets another set of binaries, branded Evergreen WebView2 Runtime, that you may chain-install through an installer the WebView team is currently developing. For more information, see App-Distribution.

Does it mean we need to package all webview2 programs with an installer? You may answer here: https://github.com/MicrosoftEdge/WebViewFeedback/issues/341 I have started a thread for it in there already.

I don't like the idea that all simple executables require installer, it makes the whole webview2 a bit cumbersome, it would be better if the runtime was shipped with the Edge instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af2b9c25-cf58-71cb-9046-acd2cdfd84d4
* Version Independent ID: 8515f71e-5ca1-530a-7c63-9de565eb368d
* Content: [Release Notes for Microsoft Edge WebView2 for Win32, WPF, and WinForms - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes)
* Content Source: [microsoft-edge/webview2/releasenotes.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/releasenotes.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@Ciantic I'll go ahead and close this issue since you've already opened up an issue in the WebView feedback repo. The WebView engineering team replies there. Thanks.
