### ISSUE TITLE
Typo on devtools workspaces page

### ISSUE THREAD

**Issue by champnic** [MicrosoftDocs/edge-developer#823]
"Devtools simply does support all the variations." should be "Devtools simply does **not** support all the variations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6fb311-8bae-b4cb-e395-8e4e084a32ef
* Version Independent ID: ecf93d87-c4c4-0678-a09c-6d920021a090
* Content: [Edit Files With Workspaces - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/workspaces/)
* Content Source: [microsoft-edge/devtools-guide-chromium/workspaces/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/workspaces/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jm-trd-ms** [comment]
@champnic  
Thank you for bringing this to our attention.  
For updates, please follow PR #848.
