### ISSUE TITLE
Nice, Clear Article, but it doesn't work

### ISSUE THREAD

**Issue by TyrantFox** [MicrosoftDocs/edge-developer#829]
This is a great article with detailed images and straightforward steps. However when I follow them verbatim, many times over, they simply don't work.

I'm using Microsoft Visual Studio Community 2019 Version 16.6.4.

I have tried both paths described, WPF App (.NET Framework) with .NET Framework 4.7.2, and also tried WPF App (.NET Core).

I add the NuGET package Microsoft.Web.WebView2, Version "Latest stable 0.9.579", which adds successfully.

I run the empty project, and as expected it gives me an empty window. I close that window and move on the the next step, editing MainWindow.xaml.

I add the line with the wv2 namespace: `xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"`

And this is where it all stops working. I get an error

> XLS0418 Assembly 'Microsoft.Web.WebView2.Wpf' was not found. Verify that you are not missing an assembly reference. Also, verify that your project and all referenced assemblies have been built.

And no combination of doing anything at all can make the Microsoft.Web namespace available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9dc9d2-795c-9612-3585-408b4621c080
* Version Independent ID: f73fc16d-d842-4507-9fdb-b42856720355
* Content: [Microsoft Edge WebView 2 for WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf)
* Content Source: [microsoft-edge/webview2/gettingstarted/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by mikemeinz** [comment]
You have to use the prerelease version of the NGet package. Only the prerelease versions contain .NET assemblies.

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.
