### ISSUE TITLE
[VS2017] 'Start page' entry doesn't exist in Package.appxmanifet

### ISSUE THREAD

**Issue by sprout2000** [MicrosoftDocs/edge-developer#837]
Package.appxmanifet made by 'C# Windows Application Packaging Project' template does not have 'Start Page'.

on the document:
![vs-manifest-application](https://user-images.githubusercontent.com/52094761/88500968-0d03fb00-d005-11ea-9ddd-06617c3a3b8a.png)

what actually happens:
<img width="418" alt="2020-07-27_12h22_31" src="https://user-images.githubusercontent.com/52094761/88500995-20af6180-d005-11ea-8a41-2b8b70fec710.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c306f3b9-d287-beba-eb3b-513e58df2440
* Version Independent ID: 787855c5-24d2-b772-e4c3-ce43118e5adb
* Content: [Tailor your PWA (EdgeHTML) for Windows - Microsoft Edge Development](https://docs.microsoft.com/en-US/microsoft-edge/progressive-web-apps-edgehtml/windows-features)
* Content Source: [microsoft-edge/progressive-web-apps-edgehtml/windows-features.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps-edgehtml/windows-features.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by JudahGabriel** [comment]
@sprout2000 the issue was that the article had the incorrect template name. You should instead use the Javascript `Progressive Web App (Universal Windows)` template. I've submitted a PR to fix the article. 👍

@Reezaali can you close this issue when the PR has been merged?

**Comment by Reezaali** [comment]
@sprout2000 - Thanks for opening the issue. We've updated the doc.
