### ISSUE TITLE
API Sample link 404

### ISSUE THREAD

**Issue by darianmiller** [MicrosoftDocs/edge-developer#839]
This page includes a link to API samples which currently results in 404/not found:

https://github.com/MicrosoftEdge/WebView2Samples/tree/master/WebView2APISample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c3ae57-a8c8-4615-7dcf-855e006a4043
* Version Independent ID: 39480ab3-700f-9151-cd72-a12aba59c63d
* Content: [Getting started with WebView2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32)
* Content Source: [microsoft-edge/webview2/gettingstarted/win32.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/win32.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jm-trd-ms** [comment]
@darianmiller 
Thank you for bringing this to out attention.  
For updates, please follow PR #846.
