### ISSUE TITLE
[VS2019] Build issue during PWA UWP

### ISSUE THREAD

**Issue by wunnle** [MicrosoftDocs/edge-developer#842]
Hello,

I'm following instructions [here](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-edgehtml/windows-features) to wrap my PWA with UWP. However on step 8, while building the app, I'm getting the following error: 

> **Error** Project must have a reference to an application. Please add a reference under the 'Applications' node in the Solution Explorer.	

I'm using **Windows Application Packaging Project** as instructed. Only other difference between the documentation and my screens is I have an "Entry point" field instead of "Start page". Not sure if that's related though.

**Comment by Reezaali** [comment]
Hi @wunnle - sorry to hear that you are having an issue. We updated our instructions on the topic to clarify that you should use VS2017 and provided a link to download previous versions as needed until we are able to publish a VS2019 workaround. We are also looking into a related issue here
https://github.com/MicrosoftDocs/edge-developer/issues/837

When I hear back from engineering I'll publish some guidance on how to solve the issue.

**Comment by wunnle** [comment]
Thanks, I'll download VS2017 and try again.

**Comment by Reezaali** [comment]
I'll go ahead and close this issue for now. Thanks.
