### ISSUE TITLE
Edge (chromium) Add-ons site statistics - Installs, uninstalls, store page views, etc.

### ISSUE THREAD

**Issue by WesselKroos** [MicrosoftDocs/edge-developer#847]
As an extension/add-on publisher, is there a way to view basic statistics like the amount of installs, uninstalls, store page views?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b21f817-68f4-27c7-f76e-650ecfbaca97
* Version Independent ID: 87572517-2c3c-7fd2-7dce-8233abecf420
* Content: [Manage Account Settings - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/manage-settings)
* Content Source: [microsoft-edge/extensions-chromium/publish/manage-settings.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/publish/manage-settings.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
@WesselKroos Thank you for reaching out. Our team is actively working on surfacing the basic telemetry around extensions to the extension developers. It's a part of our planned roadmap and should be able to ship out the changes soon. 
If you have any questions around the same, please feel free to write at ext_dev_support@microsoft.com.
