### ISSUE TITLE
This does not reflect the current Windows 10 theme. If Windows 10 theme is set to Dark it should be also set to Dark in Edge, so when a websites implements Auto Theme feature it reflects the current Windows 10 theme. This works fine in Google Chrome, but not in Edge

### ISSUE THREAD

**Issue by abbasaleid** [MicrosoftDocs/edge-developer#850]
Edit: This post was labelled "needs more info" so I made a short GIF to showcase what I mean, please have a look at it:
![InstantGif_2020 08 04-09 16](https://user-images.githubusercontent.com/40540480/89259831-cd0bcc00-d633-11ea-9aea-a5243fa9da99.gif)

You see, this is the chrome browser. When I change the system theme from dark to light or the opposite, the google chrome browser also changes its theme reflecting the system theme. In my blog, I implemented a feature called "Auto Theme" that reflects the system theme using CSS media query "prefers-color-scheme". This works fine in Chrome but not Edge. The browser Edge does not reflects the system theme whenever it changes like Chrome does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc385dd2-fb44-9553-7350-9813d104b3dc
* Version Independent ID: a3db4e1e-87ce-d35c-435a-8ff4a59d4dd3
* Content: [Force Microsoft Edge DevTools Into Color Scheme Preview Mode (CSS Prefers Color Scheme) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/accessibility/preferred-color-scheme-simulation)
* Content Source: [microsoft-edge/devtools-guide-chromium/accessibility/preferred-color-scheme-simulation.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/accessibility/preferred-color-scheme-simulation.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by abbasaleid** [comment]
Any updates on this?

**Comment by kypflug** [comment]
Hi @abbasaleid - This should work as expected in current versions of Microsoft Edge. Can you confirm that the "Default Theme" is set to "System Default" in Microsoft Edge (Settings -> Appearance)? Note that you may need to reload the page to see the dark theme take effect.

If this still doesn't work as expected, can you file a browser bug via the "Send Feedback" menu item in Microsoft Edge (preferably on the site where the issue reproduces)? That will help our platform team investigate further.

Thanks!

**Comment by abbasaleid** [comment]
> Hi @abbasaleid - This should work as expected in current versions of Microsoft Edge. Can you confirm that the "Default Theme" is set to "System Default" in Microsoft Edge (Settings -> Appearance)? Note that you may need to reload the page to see the dark theme take effect.

This does work! I think Edge should be set to "System Default" from install. Anyway, thank you @kypflug.
