### ISSUE TITLE
Need to Chromium Edge using Java

### ISSUE THREAD

**Issue by sowndarya2701** [MicrosoftDocs/edge-developer#851]
This page shows C# snippet to "UseChromium". 
Can you give me how to use this functionality in Java code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107ce527-7b9c-ff4e-e524-a8ebbc1a6714
* Version Independent ID: 6c8de68a-01bf-3426-8427-6daa5dca5f03
* Content: [WebDriver (Chromium) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium?tabs=c-sharp#driving-microsoft-edge-chromium)
* Content Source: [microsoft-edge/webdriver-chromium.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by sowndarya2701** [comment]
I am using selenium4.0.0-alpha6

**Comment by sowndarya2701** [comment]
Any updates here?

**Comment by zoherghadyali** [comment]
We've added Java code samples to https://docs.microsoft.com/microsoft-edge/webdriver-chromium/?tabs=java so I'm closing this issue. Thanks for giving us feedback!
