### ISSUE TITLE
MS Edge Developer tools

### ISSUE THREAD

**Issue by AlkisPis** [MicrosoftDocs/edge-developer#853]
The Developer tools screenshot for MS Edge you present at https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/debugger is totally different than mine (See below). And most basically, there's no Debugger anywhare in my Developer tools. (Use MS Edge v84+)

Your Developer tools:
![image](https://user-images.githubusercontent.com/17760857/89382514-aae17f00-d703-11ea-882d-9c4d4ac1dab9.png)

My  Developer tools:
![image](https://user-images.githubusercontent.com/17760857/89382209-2262de80-d703-11ea-9bfe-308d1d8a7238.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f29973-8033-43ba-8ce1-523437abdfb3
* Version Independent ID: c25d42ba-3548-9da1-84e2-9caaf3a317a9
* Content: [Debugger - DevTools (EdgeHTML) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/debugger#feedback)
* Content Source: [microsoft-edge/devtools-guide/debugger.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/debugger.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @AlkisPis, I've heard back from the engineering team. This document should help: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources
There was a name change from Debugger to Sources in the new version of Edge.
