### ISSUE TITLE
排版错误

### ISSUE THREAD

**Issue by huhubun** [MicrosoftDocs/edge-developer#859]
- 大部分图片无法显示
- `隐藏 "概述" 窗格` 后的内容错误

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 42ed05ac-9e2a-0809-47fb-75919b50d4ba
* Version Independent ID: 00e0f6cf-74f8-29fa-3ac0-78291fd5f428
* Content: [网络分析参考 - Microsoft Edge Development](https://docs.microsoft.com/zh-cn/microsoft-edge/devtools-guide-chromium/network/reference)
* Content Source: [microsoft-edge/devtools-guide-chromium/network/reference.md](https://github.com/MicrosoftDocs/edge-developer.zh-cn/blob/master/microsoft-edge/devtools-guide-chromium/network/reference.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by OfficeGlobal** [comment]
Hello @huhubun  , the article was updated. Images are displayed properly now

**Comment by huhubun** [comment]
@OfficeGlobal Thank you for the information, I will close this issue.
