### ISSUE TITLE
I followed the example and I am getting an error.

### ISSUE THREAD

**Issue by kaki104** [MicrosoftDocs/edge-developer#862]
[Enter feedback here]
Hi

I followed the example and I am getting an error.

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void System.Runtime.InteropServices.ComWrappers.RegisterForTrackerSupport(System.Runtime.InteropServices.ComWrappers)'.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ComWrappersSupport.set_ComWrappers(ComWrappers value)
   at WinRT.ComWrappersSupport.InitializeComWrappers(ComWrappers wrappers)
   at WebView2Desktop.Program.Main(String[] args) in C:\Users\kaki1\source\repos\WebView2Uwp\WebView2Desktop\WebView2Desktop\obj\x86\Debug\net5.0\win-x86\App.g.i.cs:line 25

Environment
Windows 10 version 2004
Installed Microsoft Edge (Chromium) Canary channel - In WPF project you can use WebView2.
Visual Studio 2019, version 16.7.0 Preview 4.0
Installed .NET 5 preview and reboot
- dotnet-sdk-5.0.100-preview.4.20268.1-win-x64.exe
- dotnet-sdk-5.0.100-preview.4.20268.1-win-x86.exe
WinUI 3 Project Templateds version 3.0.0.2007130
Enabled Developer Mode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87f61c26-2c48-2ec7-6e18-4aa181702b17
* Version Independent ID: ddd9e9ec-0143-b45b-6e72-225f73d89212
* Content: [Microsoft Edge WebView2 for WinUI apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui)
* Content Source: [microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winui.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @kaki104, a bug has been filed on the Engineering team's backlog. You can look at the linked issue on the WebViewFeedback repo for any updated status from the engineering team. I'll go ahead and close this issue now. Thanks.
