### ISSUE TITLE
[DevTools Docs Feedback]

### ISSUE THREAD

**Issue by ConwayMagee** [MicrosoftDocs/edge-developer#866]
I need instructions to attach the DevTool Console to the Office Word Add-in Task Panel to observe JavaScript console.log output.

**Comment by Reezaali** [comment]
Hi @ConwayMagee, to get help with this issue, I suggest opening an issue on the Office add-ins repo: https://github.com/OfficeDev/office-js-docs-pr

I'll go ahead and close this issue now. Thanks.
