### ISSUE TITLE
Since contributors are listed.. Possible to get my name added?

### ISSUE THREAD

**Issue by psuser9988** [MicrosoftDocs/edge-developer#873]
I actually wrote this article working with the Edge Team (Balaje Krishnan, Kyle Pflug and others)
Thanks. If so, my github is https://github.com/pkellner and they all have my e mail.  (accidentally posted from a test repo I'm working on)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cfa1a9e-266d-b28c-aa71-e95bffe38d63
* Version Independent ID: 4bf3ef80-21f5-0012-b0e1-e06c6437bfb1
* Content: [Getting Started With Microsoft Edge (Chromium) Extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/)
* Content Source: [microsoft-edge/extensions-chromium/getting-started/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/getting-started/index.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Thanks for reaching out about your question. Please reach out to your contacts over email to make the formal request and they can help provide an answer. In the meantime, if you’d like to submit a PR with a change to the document, it’ll show up on your GitHub profile. I’ll go ahead and close this issue now. Thanks.
