### ISSUE TITLE
Webview2 with Excel-Dna gives System.NullReferenceException

### ISSUE THREAD

**Issue by cirrusone** [MicrosoftDocs/edge-developer#875]
Attempting to use Webview2 with an Excel-Dna addin gives the following error

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

StackTrace:
   at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.AssignParent(Control value)
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at ClassLibrary1.Form1.InitializeComponent()
```

It fails on line `this.Controls.Add(this.webView2);` in `Form1.Designer.cs`

Attached is sample project where bug occurs [Sample repo](https://www.dropbox.com/s/jca3zz4ir8iwy1v/ClassLibrary1.7z?dl=0)

There is no error if Webview2 is removed entirely. Also Webview2 appears to work okay in a 'pure' winform app without Excel-Dna.
```

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Excel-DNA" version="1.1.1" targetFramework="net472" />
  <package id="ExcelDna.AddIn" version="1.1.1" targetFramework="net472" developmentDependency="true" />
  <package id="ExcelDna.Integration" version="1.1.0" targetFramework="net472" />
  <package id="Microsoft.Web.WebView2" version="0.9.579-prerelease" targetFramework="net472" />
</packages>
```

**Comment by Reezaali** [comment]
Hi @cirrusone, this repo is intended for documentation and related issues. To get support from the Engineering team, can you open this issue on the WebView repo please? Here's the link: https://github.com/MicrosoftEdge/WebViewFeedback

I'll go ahead and close this issue now.
