### ISSUE TITLE
Copy/paste error: text has 'Chrome' instead of 'Edge'

### ISSUE THREAD

**Issue by JohnMFlowers** [MicrosoftDocs/edge-developer#881]
This line:
> HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.my_company.my_application,
should read "Microsoft\Edge" instead of 'Google\Chrome'.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6baf3ba3-2850-707d-fdfc-9b65f88655c7
* Version Independent ID: 661b537b-bba6-cb07-9979-cddcc35421e3
* Content: [Native Messaging - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/native-messaging.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
@JohnMFlowers Thank you for pointing out the error, we are working on improving our documentation and this will be taken up as part of the changes.
