### ISSUE TITLE
Non accurate documentation.

### ISSUE THREAD

**Issue by mguerrer** [MicrosoftDocs/edge-developer#884]
I am using Selenium 3.141.59 with Java and found that EdgeOptions class is not exposing UseChromium property.

var options = new EdgeOptions();
options.UseChromium = true;

Please provide better guidance on how to deal with older and newer Edge versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107ce527-7b9c-ff4e-e524-a8ebbc1a6714
* Version Independent ID: 6c8de68a-01bf-3426-8427-6daa5dca5f03
* Content: [WebDriver (Chromium) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by zoherghadyali** [comment]
Hi @mguerrer! Sorry for the delay, but I wanted to let you know that we recently released a [Java version of the Selenium Tools for Microsoft Edge](https://github.com/microsoft/edge-selenium-tools). You can download the package yourself [here](https://github.com/microsoft/edge-selenium-tools/releases) or just add this dependency:

```xml
<dependency>
    <groupId>com.microsoft.edge</groupId>
    <artifactId>msedge-selenium-tools-java</artifactId>
    <version>[3.141.0,)</version>
</dependency>
```
to your `pom.xml` file. You can find more info about using Selenium 3 in our docs [here](https://docs.microsoft.com/microsoft-edge/webdriver-chromium/?tabs=java#use-selenium-3). Adding the Selenium Tools should expose the `UseChromium` property. If you are still blocked, please send feedback to the Developer Tools team via the feedback icon or [@EdgeDevTools on Twitter](https://twitter.com/edgedevtools)
![image](https://user-images.githubusercontent.com/34316555/110543297-fc5d4c80-80de-11eb-9df8-97ce1d8b52ad.png)
