### ISSUE TITLE
Whuch DLL?

### ISSUE THREAD

**Issue by mikemeinz** [MicrosoftDocs/edge-developer#889]
In which DLL do I find GetAvailableCoreWebView2BrowserVersionString. In order to call 
GetAvailableCoreWebView2BrowserVersionString, I need to include the DLL in the declaration for GetAvailableCoreWebView2BrowserVersionString.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d63a4b5-745c-1503-8bc3-7dced5018ad7
* Version Independent ID: 248b741f-cf55-54e0-1c22-09833ec68d35
* Content: [Globals - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/webview2-idl#getavailablecorewebview2browserversionstring)
* Content Source: [microsoft-edge/webview2/reference/win32/0-9-538/webview2-idl.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/reference/win32/0-9-538/webview2-idl.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by cgeier** [comment]
@mikemeinz 

Add a reference to **Microsoft.Web.WebView2.Core.dll**. Below is the usage. 

### VB .NET:

`Imports Microsoft.Web.WebView2.Core`

```
Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    'System.Diagnostics.Debug.WriteLine("Version: " & Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString())

    System.Diagnostics.Debug.WriteLine("Version: " & CoreWebView2Environment.GetAvailableBrowserVersionString())

End Sub
```


### C#

`using Microsoft.Web.WebView2.Core;`

```
private void Form1_Load(object sender, EventArgs e)
{
    //System.Diagnostics.Debug.WriteLine("Version: " + Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString());

    System.Diagnostics.Debug.WriteLine("Version: " + CoreWebView2Environment.GetAvailableBrowserVersionString());
}
```

**Comment by mikemeinz** [comment]
Thanks
