### ISSUE TITLE
GitHub Actions: Automatically Publish Microsoft Edge Extension

### ISSUE THREAD

**Issue by olafwrieden** [MicrosoftDocs/edge-developer#900]
This request poses two questions:
1. How may developers publish updates to their Microsoft Edge (Chromium) Extension via a Web API/request? Is this documented?
2. Could we put together a simple GitHub Action to read a `*.zip` file from a given directory and automatically publish it via a request to a Web API?

**Description**
With the parity between Google Chrome and Microsoft Edge (Chromium) browsers, the opportunity to employ the use of GitHub Actions to automatically publish an extension update to the store has presented itself. This capability is already available for the Google Chrome Extensions Store via [these Actions](https://github.com/marketplace?type=actions&query=chrome+extension). However, no equivalent exists (that I know of) for publishing to Microsoft Edge.

**Benefit**
Developers looking to publish updates to their extensions can do so to multiple stores with one simple Action triggered upon tagging a fresh release - without manually uploading the archive to all stores.

I would love to hear your feedback.

**Comment by gebansal** [comment]
Hello @olafwrieden, thank you so much for your feedback. This definitely will be a helpful tool for the developers to submit updates to their extension on the store. We are looking at similar functionalities and have added your suggesting in our backlog. We hope to be able to pick it up soon and make it more convenient for extension developers to submit their extensions/updates to Microsoft Edge add-ons store.

**Comment by mantou132** [comment]
Edge addon cannot be automatically released, the review time is too long, and other reasons, the Edge Addon version often lags behind the Chrome Webstore and Firefox Addons.

**Comment by olafwrieden** [comment]
Thanks @mantou132 that's good to know.

At present, the approval process for my extension (with almost no external permissions) takes about 24 hours for Edge Addons (compared to a few minutes on the Chrome Web Store). Personally, I don't mind the wait and am simply looking for a way to way to automate uploading a new version without my manual intervention (zipping, uploading, publishing for review). The review process is obviously out of my control and takes as long as it takes.

I don't intend to publish on every commit, instead set up a GitHub Action to trigger the process when a release is created.

**Comment by gebansal** [comment]
We have prioritized publish APIs for the extensions in our roadmap and they should be released in the near future. Thank you @olafwrieden and @mantou132  for the feedback.

Regarding the review time, we have a process in place where the team reviews the extension around certain policies. We are working at optimizing our processes here and reduce the time it takes for an extension to be reviewed.

Do let us know if you have any more feedback for us, it helps us constantly work on improving the experience and the product. Additionally, you may reach out to the Microsoft Edge extensions team at ext_dev_support@microsoft.com for any further issues or feedback.

**Comment by blimmer** [comment]
Hi @gebansal - are these APIs available for use yet? If not, is there a place we can track the progress?

**Comment by blimmer** [comment]
I talked with @ashishnirvana1 via the ext_dev_support email handler from the message above. It sounds like this API is at least a quarter or so away. Is there a good way for us to subscribe to updates on the availability of this API? We're having our users install from the Google Chrome store until this API exists.

**Comment by gebansal** [comment]
Hey @blimmer, the API work is still under development. We do not have a release date yet. Once complete, we'll add to our API support documentation. Meanwhile, feel free to reach out to us at ext_dev_support email handler for any further suggestions.

**Comment by blimmer** [comment]
Thanks @gebansal - would it be possible to leave this issue open so we can subscribe to it and get a push notification when the API is available (vs. needing to occasionally poll the documentation)?

**Comment by RickyRomero** [comment]
I'm really hoping for a publish API for extensions soon.

I distribute [an extension](https://rickyromero.com/shutup/) which uses its own internal update mechanism for remote CSS code. [Google is now actively discouraging developers from using such mechanisms](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#remotely-hosted-code), so I'll need to start bundling those updates inside my extension. This necessitates more frequent extension updates, which I plan to handle via automation. I can continue to use my CSS update system in Edge, but would rather have code parity between all versions.

I've already written my own GitHub Actions for both [AMO](https://github.com/RickyRomero/shut-up-amo) and [CWS](https://github.com/RickyRomero/shut-up-cws), but can't yet do so for Partner Center due to the lack of API support.

**Comment by gebansal** [comment]
Hey @RickyRomero, we'd like to assure you that the changes are actively being worked on. We should be able to release the changes soon to production. 

@blimmer We will try to communicate the changes once the APIs are available.

**Comment by ashishnirvana1** [comment]
We listened to your feedback, and we are happy to announce that we are soon bringing REST API to help you automate the process of uploading and publishing Microsoft Edge Add-ons. 

[Using the Microsoft Edge Add-ons API](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api) and  [Microsoft Edge Add-ons API Reference](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference), provide an early preview of the proposed Microsoft Edge Add-ons API. 

Tell us if these API’s meet your requirements or if you would like additional features. Submit your feedback on GitHub by creating [Issue for the Add-ons API](https://github.com/MicrosoftDocs/edge-developer/issues/new?title=%5BAdd-ons%20API%5D). While sharing feedback, do remember to share real examples and use cases that you wish us to enable and the constraints that these API’s may pose in helping you achieve your goals. We would love to hear from you!

**Comment by Myzel394** [comment]
@ashishnirvana1 Nice, will you also add a Github Action? I think that would be the easiest way for us all to publish extensions.

**Comment by ashishnirvana1** [comment]
Yes, a GitHub action is on the backlog, no timelines yet. Likely something we will address post API's are live and stable.

**Comment by olafwrieden** [comment]
@ashishnirvana1 This is amazing news!! Congratulations to the team! I can't seem to find "Publish APIs' as described under the _Before you begin_ section. Would love to test it out and provide feedback.

**Comment by ashishnirvana1** [comment]
These API are not available for testing yet. It is still under development. We want your feedback on the proposal, so that we have time to address any feedback in the early stages of development.

**Comment by captainbrosset** [comment]
I believe this issue can now be closed. It was opened to ask for an API to automatically publish extensions, and the API is now being worked on and the proposal is documented here: https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api
If you believe there is a problem with this documentation (or any other Edge developer documentation), feel free to open a new issue.
