### ISSUE TITLE
Instructions for Location Override Don't work in Edge (they do work for Chrome, so MS broke something)

### ISSUE THREAD

**Issue by Scribliotech** [MicrosoftDocs/edge-developer#901]
May be a bug in Edge's implementation of Chromium. These instructions work for Chrome, but do NOT work in Edge.

On further checking, I see that this is fixed and working in the Dev build of Edge, but in checking the release build of Edge on two different computers, in accounts used by different users (so settings are completely different), changing the location through Dev Tools -> Sensors -> and selecting a different location, then visiting any of the various sites that report the latitude and longitude of the browser (e.g., https://my-location.org/) still show the existing location. Edge is ignoring the override. I haven't seen this reported as a bug in Edge, so concerned that the fact that it's working in the Dev build is just a lucky fluke. Please be sure this is fixed broadly and makes its way to the release build, or, minimally, update the instructions, because they don't apply to the release version of Edge.

Because this hasn't been listed as a bug that's been fixed recently, I'm also concerned that there may be something else overriding the override in the release build of Edge, which just doesn't apply to the other builds. If so, again, please update the instructions to include whatever adjustment is needed to ensure the Dev Tools override will work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8adbf0ab-a03d-f7ed-76a4-20ad3127ade9
* Version Independent ID: 79112442-6921-c286-8f39-c079fc2d526b
* Content: [Override geolocation with Microsoft Edge DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/geolocation)
* Content Source: [microsoft-edge/devtools-guide-chromium/device-mode/geolocation.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/device-mode/geolocation.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Scribliotech** [comment]
Update: this does not work in Dev build either. The issue is that it works ONCE. If you create a manual location and select that, the first time doing this, Edge then correctly reports that as the location for the override. However, if you then add another manual lat/long location, and select that, then Edge ignores the override setting altogether and shows the original location (before any override). Clearly this is a bug in Edge.

**Comment by captainbrosset** [comment]
I tested the instructions today and they worked fine for me on Microsoft Edge Canary (version 93), on Windows 10.
So this must have been fixed since you reported the issue.
I tested both switching between pre-defined locations as well as creating new custom locations. I tested with multiple locations and they all worked fine.

**Comment by Scribliotech** [comment]
I am only able to reproduce your experience on first launch of Canary. After closing and restarting, it behaves as I've described. I'm not sure what is different about first launch on this, but it did work and show the specified address in Sensors initially, but only once per install of the current Canary build (ver 93.0.946.0).

I am in NH. In Sensors I have specified a Latitude and Longitude for a different town in NH. Then (after the initial launch, where this works as expected) I go to https://my-location.org and it shows an address in Brooklyn, NY (where our ISP connects to the Internet). Further, this only happens if I hit Allow in the browser dialog to grant the site access my location, proving that it's not just the site doing a lookup based on my IP#. This is clearly a defect in Edge, unless the Sensors are only supposed to work once. If you are not able to reproduce, then there must be something else differentiating our systems, please advise what information you need from me to be able to reproduce.

**Comment by captainbrosset** [comment]
Thank you for testing again and sharing this information.

I want to make sure I'm understanding this correctly: you said you closed and restarted, do you mean just devtools, or also Edge?

Also, after you restarted, did you go to Sensors again and selected a new location, or just immediately go to the https://my-location.org/ site and tested again?

I tested the following:
- Go to https://my-location.org/
- Go to Sensors
- Click "Manage"
- Create a new location
- Go back to Sensors
- Select the new location
- Reload the page --> the overridden location gets displayed by the page properly
- Close and reopen devtools
- Reload the page --> the overridden location gets displayed by the page properly
- Go back to Sensors
- Remove the override
- Reload the page --> my normal location gets displayed.

I have a feeling that the way Edge stores the override could explain why you are seeing the bug, so if you could share your exacts steps, that would help me a lot. Then I can open an issue with the right team in Edge and get this investigated.

Thanks!

**Comment by captainbrosset** [comment]
Closing issue as this has gotten stale. If you do still experience the issue, I suggest sending a feedback through the Edge feedback mechanism (press alt+shift+I to open the feedback dialog).
