### ISSUE TITLE
Do you support 32 bit application on VS 2015 ?

### ISSUE THREAD

**Issue by orengav** [MicrosoftDocs/edge-developer#912]
[Enter feedback here]
I don't succeed to works with 32-bit application  and i see that this issue already fixed 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17f573c0-3c98-2744-e2df-5bf023ee13cb
* Version Independent ID: 9c27ea10-29c8-5310-aa89-c3287d779d50
* Content: [Getting started with WebView2 for Win32 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32)
* Content Source: [microsoft-edge/webview2/gettingstarted/win32.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/win32.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by champnic** [comment]
@orengav Could you add some more detail about what you're running into? If you can, please open an issue in our feedback repo, which asks extra questions and details that will help us to diagnose your problem. 
https://github.com/MicrosoftEdge/WebViewFeedback/issues/new?assignees=&labels=bug&template=bug_report.md&title=

Thanks!

**Comment by Reezaali** [comment]
I'll go ahead and close the issue now. Thanks.
