### ISSUE TITLE
Where are snippets saved?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/edge-developer#913]
Please provide documentation on where the snippets are saved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71876e38-721a-4384-4c79-ca3a196d1384
* Version Independent ID: 20e75670-1789-5f4e-c361-2d07dfdd68e0
* Content: [Sources Panel Overview - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources)
* Content Source: [microsoft-edge/devtools-guide-chromium/sources.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/sources.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Bartolomeus-649** [comment]
Also, documentation on how to setup/configure roaming (roaming settings) for all settings, including snippets, workspaces, console command history, local modifications/overrides and so on.

**Comment by captainbrosset** [comment]
As far as I know, snippets are not saved as files on the disk by DevTools. They are stored in a local storage area only accessible to DevTools, similar to where other DevTools settings are stored.
There is, however, a way to save a snippet as a file, by right-clicking on it and then selecting "save as". This, however, does not establish a mapping between the snippet and the file, meaning that if you edit the file on disk, the changes won't be reflected in the snippet inside DevTools.

I think it would be good to document the "save as" feature on https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/snippets
