### ISSUE TITLE
List of all Chromium Edge User agent strings

### ISSUE THREAD

**Issue by ahsteele** [MicrosoftDocs/edge-developer#916]
The information provided is great, but it would be helpful if there was an official enumeration of all Chromium Edge user agent strings.

**Comment by Reezaali** [comment]
Hi @ahsteele, thanks for opening this issue. Can you share which page you were referring to please? Thanks.

**Comment by ahsteele** [comment]
@Reezaali sorry didn't realize when I created the issue that it didn't link to the page I started from. Nevertheless the page I am referring to is here: https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string. Even if this page didn't enumerate all of the agent strings it should link to one that does.

**Comment by Reezaali** [comment]
Thanks for the response @ahsteele. I'll ask engineering to look into this suggestion.

**Comment by jennynotjen** [comment]
Hey @ahsteele, thanks for the feedback! Could you elaborate on what your use case is here?

**Comment by Reezaali** [comment]
I'll go ahead and close out this issue now. Thanks.
