### ISSUE TITLE
wpf don't work in latest prerelease 0.9.628

### ISSUE THREAD

**Issue by just1982** [MicrosoftDocs/edge-developer#920]
Hi

I have followed this wpf tutorial.
Using release prerelease 0.9.628
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf

but no page is loaded.

I used debug
```
        private void ButtonGo_Click(object sender, RoutedEventArgs e)
        {
            if (webView != null && webView.CoreWebView2 != null)
            {
                webView.CoreWebView2.Navigate(addressBar.Text);
            }
        }
```
and webView was always null. Whatever i tried to do.

Finally i gave up and tried prerelease 0.9.579.
And wupti it worked at once.

**Comment by champnic** [comment]
Hey @just1982, thanks for filing this. It's a known issue that we have a fix for which should be available in the next release. If you're interested in following the progress of the fix you can watch https://github.com/MicrosoftEdge/WebView2Feedback/issues/431. Thanks!

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.
