### ISSUE TITLE
Fails with WPF .NET Framework

### ISSUE THREAD

**Issue by ddclabs** [MicrosoftDocs/edge-developer#927]
These instructions work well with WPF .NET Core but fails with WPF .NET Framework template (VS2017 v15.9.27 or VS2019 v16.7.5 and WebView2 v0.9.628-prerelease)

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ba9dc9d2-795c-9612-3585-408b4621c080
* Version Independent ID: f73fc16d-d842-4507-9fdb-b42856720355
* Content: [Applications WebView 2 de Microsoft Edge 2 pour les applications WPF - Microsoft Edge Development](https://docs.microsoft.com/fr-fr/microsoft-edge/webview2/gettingstarted/wpf)
* Content Source: [microsoft-edge/webview2/gettingstarted/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by cgeier** [comment]
@ddclabs You are probably encountering the issue described in #920. 

The fix is described in [Microsoft Edge WebView2 Feedback issue 431](https://github.com/MicrosoftEdge/WebView2Feedback/issues/431).

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.
