### ISSUE TITLE
Order/Precedence of merged native messaging host access controls

### ISSUE THREAD

**Issue by GregDomjan** [MicrosoftDocs/edge-developer#947]
I previously raised #699 and at the time was unable to reconfirm the issue I was having with the listing of native messaging host access controls.
I've since retested and found that the issue persists, maybe I'm doing something wrong, but otherwise the doc appears to be incorrect and it's taking the Google Chrome access list for a native messaging host id and ignoring the MS Edge registry

@gebansal @Reezaali
Re investigated to see if we can remove the MS Store id hobnnehemnjllfddjaeiniapbfjfonog from the chrome version of access file, and still find it failing to read the Edge config while Chrome config is present.

Edge Version 84.0.522.63 (Official build) (64-bit)

Any other details needed?

Working inclusion of ms store id in google chrome file and in it's own file
Registry
```
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost]
@="C:\\Program Files\\NetIQ\\SecureLogin\\Win32\\com.netiq.slNativeHost.chrome.json"
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost]
@="C:\\Program Files\\NetIQ\\SecureLogin\\Win32\\com.netiq.slNativeHost.edge.json"
```

com.netiq.slNativeHost.chrome.json
```
{
  "name": "com.netiq.slchromehost",
  "description": "SecureLogin Chrome native messaging host",
  "path": "slNativeHost.exe",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://abjopieldicnknjgiplcjgepeijbealm/",
    "chrome-extension://jkhicjgpbeiijonckbnnljpdpceijbbi/",
    "chrome-extension://gfgmejjjdncfgdoldimlnpoioepkkafi/",
    "chrome-extension://hobnnehemnjllfddjaeiniapbfjfonog/",
    "chrome-extension://alfldkommhkckjgodadfeidkbgmccpod/"
  ]
}
```

com.netiq.slNativeHost.edge.json
```
{
  "name": "com.netiq.slchromehost",
  "description": "SecureLogin Edge native messaging host",
  "path": "slNativeHost.exe",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://hobnnehemnjllfddjaeiniapbfjfonog/",
    "chrome-extension://gfgmejjjdncfgdoldimlnpoioepkkafi/"
  ]
}
```

Failing - remove Edge store id from Google chrome file
Change only com.netiq.slNativeHost.chrome.json to remove ms store id hobnnehemnjllfddjaeiniapbfjfonog

```
{
  "name": "com.netiq.slchromehost",
  "description": "SecureLogin Chrome native messaging host",
  "path": "slNativeHost.exe",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://abjopieldicnknjgiplcjgepeijbealm/",
    "chrome-extension://jkhicjgpbeiijonckbnnljpdpceijbbi/",
    "chrome-extension://gfgmejjjdncfgdoldimlnpoioepkkafi/",
    "chrome-extension://alfldkommhkckjgodadfeidkbgmccpod/"
  ]
}
```
Edge is no longer able to interact with native messaging host

> chrome.runtime.lastError
> {}
> message: "Access to the specified native messaging host is forbidden."
> get message: ƒ ()
> proto: Object

Working - Hide chrome config so Edge can't find it
Registry
```
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost**-badid**]
@="C:\\Program Files\\NetIQ\\SecureLogin\\Win32\\com.netiq.slNativeHost.chrome.json"
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost]
@="C:\\Program Files\\NetIQ\\SecureLogin\\Win32\\com.netiq.slNativeHost.edge.json"
```
config com.netiq.slNativeHost.chrome.json still has hobnnehemnjllfddjaeiniapbfjfonog remove but no longer found by edge (or chrome) edge is able to interact properly with native messaging host

**Comment by GregDomjan** [comment]
Also tested and found same behaviour in 
Version 85.0.564.70 (Official build) (64-bit)
Version 86.0.622.38 (Official build) (64-bit)

**Comment by gebansal** [comment]
@GregDomjan can you shoot us a mail at ext_dev_support@microsoft.com and we'll try our best to resolve the issue from there.

**Comment by utkarshspat** [comment]
@GregDomjan The order of registry locations searched by Chromium for a native messaging host's manifest file is as follows:

1. HKEY_CURRENT_USER is searched first, followed by HKEY_LOCAL_MACHINE.
2. 32 bit registry is searched first, followed by 64 bit registry.
3. Chromium registry location is searched first, followed by Chrome registry location.

Microsoft Edge also follows a similar convention. So, the order of search for the registry locations is as follows:

1. HKEY_CURRENT_USER\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost
2. HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost
3. HKEY_CURRENT_USER\SOFTWARE\WOW6432Node\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost
4. HKEY_CURRENT_USER\SOFTWARE\WOW6432Node\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost
5. HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost
6. HKEY_LOCAL_MACHINE\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost
7. HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost
8. HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost

Please note that as soon as a native messaging host manifest file is found, the search stops. So, if a file was found for Google Chrome under HKEY_CURRENT_USER, the file for Microsoft Edge under HKEY_LOCAL_MACHINE will never be read.

**Comment by GregDomjan** [comment]
Thanks @utkarshspat 
I believe the order you outlined as the expectation is not the order that is happening.  The order you expect matches what I would expect.

Have no settings under `HKEY_CURRENT_USER`  to confuse things

Registry 
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost`
Is blocking 
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost`

I believe it is blocking as when Chrome config is hidden by renaming
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost_2`
Then Edge config works

Further testing the order provided 
If I remove
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost`
and add
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost`
Then chrome Registry 
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost`
Is not blocking and the extension works successfully

Also with 
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost`
and chrome Registry 
`HKEY_LOCAL_MACHINE\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost`
Is not blocking, but according to order provided should block

Also with 
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\com.netiq.slchromehost`
and chrome Registry 
`HKEY_LOCAL_MACHINE\SOFTWARE\Google\Chrome\NativeMessagingHosts\com.netiq.slchromehost`
Is not blocking

**Comment by utkarshspat** [comment]
Thanks @GregDomjan. I had mentioned that 32 bit registry is searched before 64 bit registry but wrote them wrongly when I wrote the complete order. I have corrected it above.

As you mentioned, it should be expected that all the Edge registry locations should be searched first but registry entries in HKEY_CURRENT_USER get precedence over entries in HKEY_LOCAL_MACHINE and 32 bit registry gets precedence over 64 bit registry. Hence, all HKEY_CURRENT_USER locations are searched before HKEY_LOCAL_MACHINE locations and all 32 bit locations are searched before 64 bit locations.

Also, if an app is writing the registry locations for both Edge and Chrome, it is expected that it will use both the registry locations in either HKCU or HKLM, and both will be in either the 32 bit registry or the 64 bit registry. That's why Chrome also must be using a similar order/precedence for Chrome and Chromium.

**Comment by GregDomjan** [comment]
I believe I can continue to resolve the issue at my end with the given information. 

It would be great to see additional detail in the reference doc.
In Particular expanding and bringing more attention on the 
* Content: [Native Messaging - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/native-messaging.md)
> Microsoft Edge queries the 32-bit registry first, and then the 64-bit registry to identify native messaging hosts. ...

I would place the expanded advice on how to select which registry to use before the section on how to add the registry
>To add a registry key to the directory with the manifest key.

**Comment by gebansal** [comment]
Thank you @GregDomjan for the recommendation. We'll improve our documentation based on the feedback. Closing this issue, for now, do reach out to us in case of any further queries.
