### ISSUE TITLE
Incorrect code samples

### ISSUE THREAD

**Issue by dend** [MicrosoftDocs/edge-developer#949]
Code samples pass the `EdgeOptions` objects directly to the `Edge` constructor. This errors out with:

```bash
TypeError: expected str, bytes or os.PathLike object, not Options
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107ce527-7b9c-ff4e-e524-a8ebbc1a6714
* Version Independent ID: 6c8de68a-01bf-3426-8427-6daa5dca5f03
* Content: [WebDriver (Chromium) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Thanks for reporting this issue @dend .

**Comment by dend** [comment]
@Reezaali - any planned changes to the samples? 😃

**Comment by zoherghadyali** [comment]
Hi @dend! Sorry for the delay here but can you share with us the version of Selenium that you're using? If you're using Selenium 3, you'll also need the [Selenium Tools for Microsoft Edge](https://github.com/microsoft/edge-selenium-tools) package. Steps for downloading the Selenium Tools for Microsoft Edge depending on your language and package manager are in our docs [here](https://docs.microsoft.com/microsoft-edge/webdriver-chromium/?tabs=c-sharp#use-selenium-3). 

If that doesn't solve your problem, can you share with us a couple lines from your test script that are creating and passing the `Options` object to the `Edge` constructor?

Thanks!

**Comment by dend** [comment]
Y'all actually fixed it here 8 days ago: https://github.com/MicrosoftDocs/edge-developer/commit/9f5c145d4cc87e00fa449d7a49dad6aa27785a7c#diff-158dcdab7b102fd5911fad371c64955d75639d54a5831ce9dea8c36e72ceef7a

@Reezaali @zoherghadyali - thank you!
