### ISSUE TITLE
The Sample link is not working. Returns 404

### ISSUE THREAD

**Issue by axelrv** [MicrosoftDocs/edge-developer#959]
[Enter feedback here]
Adding the Page we need to update with the correct link:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/howto/webdriver

> If you do not have an existing WebView2 project, download our [WebView2API Sample application](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/WebView2APISample#webview2-api-sample), a compreh

ensive sample of the latest WebView2 SDK. Please double check that you have satisfied these prerequisites.

The hyperlink shows to be: https://github.com/MicrosoftEdge/WebView2Samples/tree/master/WebView2APISample#webview2-api-sample 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3317fb4-5819-7961-ab43-3b0e9d744acf
* Version Independent ID: 0c23b8c3-a6b7-ac17-aad4-da5dd54c80e2
* Content: [Automating and Testing WebView2 with Microsoft Edge Driver - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/howto/webdriver)
* Content Source: [microsoft-edge/webview2/howto/webdriver.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/howto/webdriver.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jm-trd-ms** [comment]
@axelrv  
Thank you for taking the time to contact us.  
Your feedback resulted in an update to the documentation.  
Please follow PR #1000 for future updates.
