### ISSUE TITLE
Confusing sentence

### ISSUE THREAD

**Issue by Konokai** [MicrosoftDocs/edge-developer#966]
Hi, this sentence is confusing, consider rewording it.

"When writing a WebView2 app using a particular SDK version, the users fo you app may run your it with various compatible versions of the WebView2 Runtime."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e7761f-33b7-cdd5-2a03-dbe3ad9fab20
* Version Independent ID: 9ba37c84-78c0-5fb6-5f6a-22d6286add19
* Content: [Versioning of Microsoft Edge WebView2 - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning?view=webview2-0.9.622)
* Content Source: [microsoft-edge/webview2/concepts/versioning.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/concepts/versioning.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Thanks for the feedback. We've update the document this week. I'll go ahead and close out this issue now.
