### ISSUE TITLE
Don't see the link to inspect the background page

### ISSUE THREAD

**Issue by jesaremi** [MicrosoftDocs/edge-developer#97]
I don't have that link when I nagivate to my extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b754b2f-8fdb-611a-fd7e-b9b8503db79a
* Version Independent ID: 9f673ab0-9bd6-3780-43b8-b36c5d4876af
* Content: [Extensions - Debugging extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/debugging-extensions)
* Content Source: [microsoft-edge/extensions/guides/debugging-extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/debugging-extensions.md)
* Service: **unspecified**
* Product: **microsoft-edge**
* GitHub Login: @abbycar
* Microsoft Alias: **abigailc**

**Comment by libbymc** [comment]
Hi @jesaremi - While this isn't an issue with the doc, make sure you have a background script and have it included in your manifest file. 

The section on [Adding content and background scripts](https://docs.microsoft.com/microsoft-edge/extensions/guides/creating-an-extension#adding-content-and-background-scripts) in the [Creating a Microsoft Edge extension](https://docs.microsoft.com/microsoft-edge/extensions/guides/creating-an-extension) guide might help!
