### ISSUE TITLE
The tag 'WebView2' does not exist in XML namespace 'clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf'.

### ISSUE THREAD

**Issue by CoenraadS** [MicrosoftDocs/edge-developer#970]
Following the release of WebView2, I wanted to try and make a demo WPF app.

I made a .Net 4.7.2 WPF app, and installed WebView2 1.0.622.22 (I guess the prerelease hint on the website is out of date)
Restored packages etc

Added this line to the xaml:
`xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"`

But get the following errors:
`Assembly 'Microsoft.Web.WebView2.Wpf' was not found. Verify that you are not missing an assembly reference. Also, verify that your project and all referenced assemblies have been built.
`
`
The tag 'WebView2' does not exist in XML namespace 'clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf'.`

Here is my entire xaml:
```
<Window x:Class="UI.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        xmlns:local="clr-namespace:UI"
        mc:Ignorable="d"
        Title="Omni" Height="450" Width="800">
    <DockPanel>
        <wv2:WebView2 Name="webView"
                  Source="https://www.microsoft.com"
    />
    </DockPanel>

</Window>
```

I installed the bootstrapper from: https://developer.microsoft.com/en-us/microsoft-edge/webview2/

But it didn't seem to help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9dc9d2-795c-9612-3585-408b4621c080
* Version Independent ID: f73fc16d-d842-4507-9fdb-b42856720355
* Content: [Getting started with WebView2 for WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf)
* Content Source: [microsoft-edge/webview2/gettingstarted/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Robson-Rocha** [comment]
I've ran into the same issue, but I had missed the "Ensure you check Include prerelease, select a prerelease package in Version, and then choose Install.". Only prerelease versions have the WPF components.

Maybe the documentation should be updated to reflect this.

**Comment by Symbai** [comment]
You need to install the `1.0.674-prerelease` nuget version. Robson-Rocha is right, make sure you have opt-in into "include preleases" in VS.

**Comment by bstordrup** [comment]
Any clue on when the WPF components will be available in non-prerelease package?

**Comment by Reezaali** [comment]
Closing this issue because there's an open issue on the engineering feedback repo. Thanks.
