### ISSUE TITLE
You Left A Step Out

### ISSUE THREAD

**Issue by protegesolutions** [MicrosoftDocs/edge-developer#971]
Once NuGet installs WebView2, you show a form but there is no description of how you get the control to show in Toolbox - it doesn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Getting started with WebView2 for WinForms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by champnic** [comment]
@protegesolutions Can you verify that "Automatically Populate Toolbox" is set to "true"?
![image](https://user-images.githubusercontent.com/45700886/96821998-e6741700-13dd-11eb-88e5-a47f806d2169.png)

**Comment by protegesolutions** [comment]
Yes, it's set to true:

![image](https://user-images.githubusercontent.com/5343907/96822377-85553f00-13ef-11eb-846a-3ba82e4efb18.png)

**Comment by champnic** [comment]
Ok, I'll open a bug on our backlog to investigate Thanks for reporting!

**Comment by Reezaali** [comment]
I'll go ahead and close out this issue now. Thanks.
