### ISSUE TITLE
WOW6432Node is only available on 64-bit Windows

### ISSUE THREAD

**Issue by siewers** [MicrosoftDocs/edge-developer#974]
Under the `Online-only deployment` and `Offline deployment` sections, the registry key to inspect is only valid for 64-bit Windows versions.
The key `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}` doesn't exist on 32-bit versions of Windows, but will instead be `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}` (notice the missing `WOW6432Node` part of the key).
On 64-bit Windows, the 32-bit node for HKLM\Software is redirected to `WOW6432Node`, but that is not the case on 32-bit.

Please make sure the registry key is universal or at least update the documentation to reflect the differences between the two architectures.

The documentation also says "_Inspect if the `pv (REG_SZ)` regkey [...]_", however, `pv` is not a registry key, it's the value name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a805f15-55ba-4ef4-aeda-22188a040c66
* Version Independent ID: 88de0955-526f-a4c9-efcc-d952281850e1
* Content: [Distribution of Microsoft Edge WebView2 apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#deploying-the-evergreen-webview2-runtime)
* Content Source: [microsoft-edge/webview2/concepts/distribution.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/concepts/distribution.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by siewers** [comment]
A couple of other questions:
- will the x64 version of the Runtime _always_ use the `WOW6432Node`?
- is it considered stable to use `{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}` as part of the key?
- can we distribute an application based on detection logic using this key?

**Comment by liminzhu** [comment]
@siewers sorry for not relying earlier, and thanks for pointing this out! We will update our docs. To your questions, 

> will the x64 version of the Runtime always use the WOW6432Node?

On x64 Windows, both x86 and x64 installers will use WOW6432Node, and arm64 also uses it. 32-bit Windows doesn't have `WOW6432Node`. 

> is it considered stable to use {F3017226-FE2A-4295-8BDF-00C3A9A7E4C5} as part of the key?

Yes the key is stable.

> can we distribute an application based on detection logic using this key?

Yes you can use the key to detect whether the runtime is installed or not.

**Comment by haiduong87** [comment]
Hi @liminzhu 
I see the 32bit key isn't updated.

I can't find this on windows 7 32bit
'HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}'

**Comment by liminzhu** [comment]
Oh it should be `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}` on 32bit. Sorry about the doc error, I will update it.

**Comment by Reezaali** [comment]
Closing this issue now as the documentation has been updated. Thanks.
