### ISSUE TITLE
Can't choose custom log levels for Dev Tools

### ISSUE THREAD

**Issue by iquitwow** [MicrosoftDocs/edge-developer#976]
In Chrome, you can select what level or individual (warnings, errors, etc.).  Custom Levels is disabled in Edge.  Is there a workaround for this?

![image](https://user-images.githubusercontent.com/6944956/97489648-313de380-1936-11eb-8235-ad9b22a85a29.png)

**Comment by captainbrosset** [comment]
You can select custom levels in Microsoft Edge too. For this to work, you first need to close the console left sidebar. Indeed, there are 2 ways to filter logs:

- Either you open the left sidebar, and then choose one of the categories.
- Or you close the left sidebar, and then use the toolbar dropdown.

Only one of these filtering mechanisms can be used at a time. This works the same in Chrome by the way.

**Comment by py130** [comment]
thanks
