### ISSUE TITLE
Where to find the latest runtime?

### ISSUE THREAD

**Issue by alexchx** [MicrosoftDocs/edge-developer#980]
Hi team,

I want to use this package `1.0.674-prerelease` in my project, however, the latest runtime on this [page](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) is `87.0.664.8`, where could I get the latest version `88.0.674.0`?

Thank you.

**Comment by Reezaali** [comment]
Hi @alexchx, it looks like the page has been updated with the latest version. I'll go ahead and close this issue now. Thanks.
