### ISSUE TITLE
WebView2 in WPF. WebView2 is in prerelease state. When can get it released?

### ISSUE THREAD

**Issue by halimote** [MicrosoftDocs/edge-developer#981]

**Comment by pagoe-msft** [comment]
@halimote

We will release WPF WebView2 when we hit GA for .NET. That is tentatively scheduled for the next SDK release! Stay tuned!

**Comment by peiche-jessica** [comment]
https://github.com/MicrosoftEdge/WebView2Announcements/issues/10
Microsoft Edge WebView2 is generally available for production .NET Framework, .NET Core, and .NET 5 applications. Please use the [WebView2Feedback repo](https://github.com/MicrosoftEdge/WebView2Feedback) to report any bugs or issues you find. Thanks!
