### ISSUE TITLE
Confusing information

### ISSUE THREAD

**Issue by davidsanda** [MicrosoftDocs/edge-developer#989]
Webauthn option in chrome dev tools in edge is missing from vrsion 86.0.622.63. The document should really explain what version of Edge contains these webauthn features.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c40654f-15fb-71ff-fb2c-24f0ea0cd7bb
* Version Independent ID: d4ab57a2-ee0b-efd6-2a8d-69399d3c59bf
* Content: [Emulate authenticators and debug WebAuthn in Microsoft Edge DevTools - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/webauthn/)
* Content Source: [microsoft-edge/devtools-guide-chromium/webauthn/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/webauthn/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
The Webauthn panel does exist in DevTools. I tested today with Microsoft Edge 91 (which is the current stable release) and the tool is available under the "More tools" menu as explained in the docs.

**Comment by captainbrosset** [comment]
Closed based on my last comment.
