### ISSUE TITLE
Update on reload

### ISSUE THREAD

**Issue by DaveEveritt** [MicrosoftDocs/edge-developer#992]
Service workers need to have an "Update on reload" toggle for debugging. Clearing out just the cache in one go could also be part of this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1893a18e-5062-4cde-67dc-798fa3bfe89b
* Version Independent ID: 2ccb6560-245a-9747-c92d-c7965fac13b0
* Content: [DevTools - Debugger - Service Workers - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/service-workers)
* Content Source: [microsoft-edge/devtools-guide/service-workers.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide/service-workers.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
@DaveEveritt - here's an updated topic for you to review: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/service-workers/

If you would like to submit a new feature request, you can do that using the Send Feedback option from within Microsoft Edge. I'll go ahead and close out this issue now. Thanks.
